import { z } from 'zod';

/**
 * Runtime validation for card data (handoff C.5). The hand-written `CardDef`
 * type in `@game/core` is the canonical compile-time shape; this schema guards
 * the *data* at load and is kept in lockstep with it.
 */
export const TribeSchema = z.enum(['beast', 'undead', 'mech', 'dragon', 'demon', 'neutral']);

export const KeywordSchema = z.enum(['T', 'DS', 'V', 'W', 'R', 'C', 'M', 'SC', 'CN', 'FD', 'IMM', 'ST', 'RL', 'SL', 'EG']);

export const GameEventSchema = z.enum([
  'onPlay',
  'onSummon',
  'onDeath',
  'onAttack',
  'onGainAttack',
  'onDamaged',
  'onLoseDivineShield',
  'onConsume',
  'onKill',
  'startOfCombat',
  'avenge',
  'onBuy',
  'endOfTurn',
  'battlecryTriggered',
  'cast',
  'spellCast',
  'summonOverflow',
  'goldSpent',
  'onSell',
]);

export const EffectFactoryIdSchema = z.enum([
  'deathrattleSummon',
  'deathrattleSummonOverflowBuff',
  'buffOnSummon',
  'deathrattleBuffTribe',
  'reAttackOnKill',
  'onKillBuffSelf',
  'onKillBuffSpellPower',
  'onKillGrantFreeRolls',
  'onKillGrantAttachmentRefreshes',
  'onKillGrantGold',
  'onKillCastSpell',
  'rallyCastRandomStatSpell',
  'avengeCastRandomStatSpell',
  'deathrattleDamageAll',
  'deathrattleDestroyKiller',
  'deathrattleBuffTribeByTally',
  'scDamage',
  'scSplitDamage',
  'scAoePerTribe',
  'scEngraveNeighbor',
  'deathrattleBuffRandom',
  'deathrattleBuffAllRandomStat',
  'onFriendDeathBuffRandom',
  'rallyBuff',
  'rallyProcDeathrattle',
  'deathrattleGrantSpell',
  'deathrattleGrantMagnetic',
  'deathrattleBuffSpellPower',
  'deathrattleBuffCardTypeRunWide',
  'buffFodderEverywhere',
  'deathrattleFillTribe',
  'avengeBuff',
  'scGrantShieldTribe',
  'scGrantReborn',
  'deathrattleGrantShield',
  'onShieldBreakGrantShield',
  'onShieldBreakDamage',
  'onShieldBreakBuffAll',
  'onFriendDeathSummon',
  'scDestroyHighestAttack',
  'scGrantEnemyTaunt',
  'scSummonCopy',
  'scTribeBuffPerSpell',
  'scTribeBuffPerPlayed',
  'scTribeBuffImproving',
  'battlecryBuffTribe',
  'battlecrySummon',
  'buffOnBuy',
  'battlecryGrantKeyword',
  'battlecryGainRandomMinion',
  'battlecryDiscoverSpell',
  'onBattlecryBuffTribe',
  'onBattlecryBuffFodder',
  'battlecryBuffFodder',
  'battlecryBuffSpellPower',
  'endOfTurnBuff',
  'endOfTurnMagnetizeMechs',
  'addTavernFodder',
  'addFodderNextShops',
  'deathrattleAddFodder',
  'deathrattleBuffFodder',
  'rallyBuffFodderHalf',
  'rallyBuffFodder',
  'avengeAddFodder',
  'avengeGrantSpellPower',
  'avengeImproveSummon',
  'avengeMaxGold',
  'avengeGrantSpell',
  'deathrattleGrantReborn',
  'deathrattleBuffAll',
  'battlecryTriggeredOwnDeathrattle',
  'onConsumeBuffSelf',
  'onConsumeGrantSelfKeyword',
  'onConsumeShieldNextCombat',
  'spellBuffTarget',
  'spellBuffTargetPerGold',
  'spellBuffAll',
  'spellDevour',
  'castSpell',
  'endOfTurnGetRandomSpells',
  'gainEmbers',
  'spellCastBuffOthers',
  'overflowBuffRandom',
  'spellCastTransform',
  'spellCastBuffSelf',
  'summonBuffSelfTribe',
  'spellBuffShop',
  'gainMaxMana',
  'grantFreeRolls',
  'spellGainOfTargetTribe',
  'spellGainRandomMinion',
  'spellGildTarget',
  'spellBuffTargetEscalating',
  'spellGrantTribeAttack',
  'healHero',
  'conjureTribeArmy',
  'stealTavernMinion',
  'endOfTurnGrantTribe',
  'avengeGiveAttack',
  'onFriendlyAttackBuffTribe',
  'battlecryDiscoverMinion',
  'spellSetStats',
  'onAllyAttackBuffAll',
  'onGainAttackBuffAll',
  'spellBuffTavern',
  'spellBuffNextShop',
  'spellPendingSCBuff',
  'onAllyAttackCastGrowth',
  'spellDemonConsumeFodder',
  'deathrattleGrantRandomSpell',
  'onDamagedGrantRefresh',
  'summonBuffTribeImprove',
  'deathrattleGiveHealth',
  'scGainFodderStats',
  'onSummonSelfBuff',
  'onSummonOverflowBuffTribe',
  'deathrattleBuffAllHealth',
  'onGainAttackImproveHpGrant',
  'spellCastBuffUndeadAttack',
  'deathrattleGrantCardToHand',
  'battlecryBuffUndeadAttack',
  'battlecryBuffBeastAttack',
  'battlecryScoutSpread',
  'battlecryBuffMagnetics',
  'battlecryBuffImps',
  'goldSpentBuffFodder',
  'goldSpentMagnetize',
  'onKillBuffUndeadAttack',
  'onKillBuffFodderImps',
  'onDamagedGainAttack',
  'rallyGrantMagnetic',
  'deathrattleBuffImps',
  'avengeBuffImps',
  'battlecryBonusGoldNextTurn',
  'deathrattleReplayAdjacentBattlecry',
  'spellBuffByTier',
  'spellSellToDemon',
  'spellSellToBeast',
  'spellReplayBattlecry',
  'spellExtraEndOfTurn',
  'spellGildRandomTavern',
  'spellDisplace',
  'spellCopyRecent',
  'spellRefreshToSpells',
  'battlecryTargetConsumeFodder',
  // Slaughter (on-kill) + random-spell batch
  'avengeGrantRandomSpell',
  'rallyGrantRandomSpell',
  'onKillGrantRandomSpell',
  'onKillBuffFodder',
  // 2026-07-05 content batch
  'avengeSummonAttack',
  'spellAttackFirst',
  // 2026-07-06 content batch
  'scBeastAura',
  'rallyTribeAura',
  'rallyTribeAuraGrowing',
  'rallyGiveDemonAttack',
  'rallyDamageRandomEnemy',
  'rallyImproveSummonAura',
  'avengeShieldAttack',
  'endOfTurnGrantSpellChoice',
  'spellRallyDoubleNext',
  'rallyCastTribeAttack',
  'battlecryDoubleNextSpell',
  'battlecryGrantSpell',
  'endOfTurnCastSpellEscalating',
  'endOfTurnAdjacentConsumeFodder',
  'endOfTurnFeastConsume',
  'endOfTurnBuffPerTribePlayed',
  'endOfTurnBuffWeakestDragon',
  'onSellGainGold',
  'battlecryDestroyForSpell',
  'avengeBonusGold',
  'deathrattleMaxGold',
  'getEchoAndTrigger',
  'spellTriggerEcho',
  'battlecryCopyEcho',
  'rallyGrantSpell',
  'rallyBuffAttachments',
  'onKillGrantMagnetic',
  'endOfTurnBonusGold',
  'scConsumeWeakestBuffDemons',
  'battlecryAllDemonsConsume',
  'spellBuffImpsPerDemon',
  'scEngraveAll',
  'rallyGiveHealthToDragons',
  'spellBloodlust',
  'copyLeftmostEcho',
  'spellAddTribe',
  'spellAddAllTribes',
  'castSpellById',
  'buffAllByImpAura',
  'deathrattleBuffAllByImpAura',
  'buffFodderImpsImproving',
  'scGrantRightTaunt',
  'onAttackStripKeywords',
]);

export const EffectDefSchema = z.object({
  on: GameEventSchema,
  do: EffectFactoryIdSchema,
  params: z.record(z.unknown()).optional(),
}).strict();

// `.strict()`: a typo'd optional key (`goldentext`, `targetTribes`) would otherwise validate silently and
// the card would ship without the feature. Every legit field is declared below, so this only rejects typos.
export const CardDefSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  tribe: TribeSchema,
  tribe2: TribeSchema.optional(),
  tier: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6),
  ]),
  attack: z.number().int().nonnegative(),
  health: z.number().int().positive(),
  keywords: z.array(KeywordSchema),
  effects: z.array(EffectDefSchema),
  // Body text is mechanical-only and may be empty for keyword-only cards
  // (the keyword badge + hover tooltip carry the meaning).
  text: z.string(),
  goldenText: z.string().optional(),
  universalTribe: z.boolean().optional(),
  imp: z.boolean().optional(),
  token: z.boolean().optional(),
  ascendAt: z.number().int().positive().optional(),
  attackImmuneTurns: z.number().int().positive().optional(),
  ascendInto: z.string().optional(),
  attackOnSummon: z.boolean().optional(),
  spell: z.boolean().optional(),
  singleCast: z.boolean().optional(),
  cost: z.number().int().nonnegative().optional(),
  target: z.enum(['friendly', 'any']).optional(),
  targetTribe: TribeSchema.optional(),
  targetMaxTier: z.number().int().positive().optional(),
  targetNoGolden: z.boolean().optional(),
  fodderMult: z.number().int().positive().optional(),
  manaPerTurn: z.number().int().positive().optional(),
  rallyMechAtk: z.number().int().positive().optional(),
  spellAura: z.number().int().positive().optional(),
  fodderAura: z.object({ attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict().optional(),
  chooseOne: z
    .array(z.object({ text: z.string(), goldenText: z.string().optional(), effects: z.array(EffectDefSchema), target: z.enum(['friendly', 'any']).optional() }).strict())
    .min(2)
    .optional(),
  primer: z.boolean().optional(),
  combo: z.object({ effects: z.array(EffectDefSchema).optional(), chooseBoth: z.boolean().optional() }).strict().optional(),
  discoverOnPlay: z
    .object({
      exactTier: z.number().int().positive().optional(),
      exactCurrentTier: z.boolean().optional(),
      tierOffset: z.number().int().optional(),
      filter: z.enum(['battlecry', 'deathrattle']).optional(),
      tribe: z.union([TribeSchema, z.literal('dominant')]).optional(),
      topTierFirst: z.boolean().optional(),
    })
    .strict()
    .optional(),
}).strict();

// ── Quests ───────────────────────────────────────────────────────────────────────────────────────────────
// Kept in lockstep with the `QuestDef` type in @game/core (same as CardDefSchema). `.strict()` rejects typo'd
// keys so a malformed test quest surfaces in `npm test`, not at runtime.
export const QuestTierSchema = z.enum(['lesser', 'greater', 'capstone']);
export const QuestObjectiveEventSchema = z.enum([
  'buy', 'play', 'sell', 'roll', 'summon', 'shout',
  'attack', 'summonCombat', 'slaughter', 'slaughterKeyword', 'deathrattle',
  'spendGold', 'endOfTurn', 'tribeStats', 'friendlyDeath',
  'rally', 'playAttachment',
  'consumeFodder', 'consumeStats', 'summonImp',
  'winRound', 'castSpell', 'authorsHand',
  'compound',
]);
export const QuestCombatFlagSchema = z.enum(['bloodTrail', 'echoingCoop', 'lawOfTeeth', 'oldHunt', 'sharedCircuit', 'deepHunger', 'contractRewrite', 'pitWithoutEnd', 'doubleLeftmostAttack', 'feedingLine', 'umbralEnergy', 'emptyGraves', 'assemblyLine', 'runeWarding', 'runeFury', 'runeSlaying', 'runeForthcoming', 'runeRallying', 'runeRisingGraves', 'runeBroodpit', 'runeSpearline', 'runeAppraisal', 'runeSoulTaxes', 'runeFirstClaws', 'runePackcraft', 'runeInheritance', 'runeSalvage', 'runeTwilight', 'runeWarden']);

// The reward palette — a discriminated union kept in lockstep with the `QuestReward` type in @game/core.
export const QuestRewardSchema: z.ZodType = z.lazy(() => z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('buffBoard'), attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict(),
  z.object({
    kind: z.literal('grant'),
    randomTribe: TribeSchema.optional(),
    randomCount: z.number().int().positive().optional(),
    randomSpell: z.number().int().positive().optional(),
    randomFilter: z.enum(['shout', 'endOfTurn', 'echo', 'rally', 'attachment']).optional(),
    randomFilterCount: z.number().int().positive().optional(),
    randomFilterExactTier: z.boolean().optional(),
    randomTier: z.number().int().min(1).max(6).optional(),
    cards: z.array(z.string().min(1)).optional(),
    grantGolden: z.array(z.string().min(1)).optional(),
    grantKeywords: z.array(KeywordSchema).optional(),
    repeatInTurns: z.number().int().positive().optional(),
  }).strict(),
  z.object({ kind: z.literal('shoutDouble'), count: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('tribeAura'), tribe: TribeSchema, attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict(),
  z.object({
    kind: z.literal('scalingTribeAura'),
    tribe: TribeSchema,
    attack: z.number().int().nonnegative(),
    health: z.number().int().nonnegative(),
    per: z.number().int().positive(),
    event: QuestObjectiveEventSchema,
    stepAttack: z.number().int().nonnegative(),
    stepHealth: z.number().int().nonnegative(),
  }).strict(),
  z.object({ kind: z.literal('recurringGrant'), cards: z.array(z.string().min(1)).min(1) }).strict(),
  z.object({ kind: z.literal('impAura'), attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict(),
  z.object({ kind: z.literal('combatFlag'), flag: QuestCombatFlagSchema, amount: z.number().int().nonnegative().optional() }).strict(),
  z.object({ kind: z.literal('shoutRepeat'), scope: z.enum(['always', 'firstEachRound']) }).strict(),
  z.object({ kind: z.literal('endOfTurnRepeat') }).strict(),
  z.object({ kind: z.literal('recurringEndOfTurn'), effect: z.enum(['triggerLeftmostShout', 'grantRandomShout', 'grantRandomAttachments', 'buffMechsPerAttachment', 'runeSpending', 'runeAction', 'triggerLeftmostEcho', 'weldMoneyBotsEdgeMechs']) }).strict(),
  z.object({ kind: z.literal('gainGold'), amount: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('echoRepeat'), scope: z.enum(['always', 'firstEachCombat']) }).strict(),
  z.object({ kind: z.literal('boneThrone'), every: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('rallyRepeat'), scope: z.enum(['always', 'firstEachCombat']) }).strict(),
  z.object({ kind: z.literal('fodderReward'), fodder: z.number().int().nonnegative().optional(), attack: z.number().int().nonnegative().optional(), health: z.number().int().nonnegative().optional() }).strict(),
  z.object({ kind: z.literal('gainMaxGold'), amount: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('discover'), tier: z.number().int().min(1).max(6).optional() }).strict(),
  z.object({ kind: z.literal('discoverGreaterQuest') }).strict(),
  z.object({ kind: z.literal('dupeFirstBuy') }).strict(),
  z.object({ kind: z.literal('spellRepeat'), scope: z.enum(['always', 'firstEachTurn']) }).strict(),
  z.object({ kind: z.literal('minionCost'), cost: z.number().int().nonnegative() }).strict(),
  z.object({ kind: z.literal('slaughterRepeat'), scope: z.enum(['firstEachCombat']) }).strict(),
  z.object({ kind: z.literal('shoutEdgeBuff'), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('goldFodder'), per: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('attachmentDeal'), cost: z.number().int().nonnegative() }).strict(),
  z.object({ kind: z.literal('friedCircuits'), step: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('undeadSpellAura'), attack: z.number().int().positive() }).strict(),
  // Runeforge rune rewards.
  z.object({ kind: z.literal('runeSpellDrip'), per: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeStructure') }).strict(),
  z.object({ kind: z.literal('runeConsume'), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('goldPouchValue'), value: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeSummoning') }).strict(),
  z.object({ kind: z.literal('runeKindling') }).strict(),
  z.object({ kind: z.literal('runeScales') }).strict(),
  z.object({ kind: z.literal('runeBartering') }).strict(),
  z.object({ kind: z.literal('runeTwinGilding') }).strict(),
  z.object({ kind: z.literal('runeDenMother') }).strict(),
  z.object({ kind: z.literal('runeScale'), count: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('runeCopies') }).strict(),
  z.object({ kind: z.literal('runeEmpowerment') }).strict(),
  z.object({ kind: z.literal('openEpicRuneforge') }).strict(),
  z.object({ kind: z.literal('scheduleRuneforge'), forge: z.enum(['basic', 'epic']), onWave: z.number().int().positive().optional(), gold: z.number().int().nonnegative().optional() }).strict(),
  z.object({ kind: z.literal('multi'), rewards: z.array(QuestRewardSchema).min(1) }).strict(),
]));

/** Rune definition schema — same reward palette as quests, plus a Gold cost + display text. `epic` /
 *  `requiresDoublePower` mark Epic-forge runes and their hero-power eligibility gate. */
export const RuneDefSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  cost: z.number().int().positive(),
  text: z.string().min(1),
  reward: QuestRewardSchema,
  epic: z.boolean().optional(),
  requiresDoublePower: z.boolean().optional(),
}).strict();

export const QuestDefSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  tribe: TribeSchema,
  tier: QuestTierSchema,
  objective: z.object({
    event: QuestObjectiveEventSchema,
    count: z.number().int().positive(),
    tribe: TribeSchema.optional(),
    filter: z.literal('shout').optional(),
    parts: z.array(z.object({
      event: QuestObjectiveEventSchema,
      count: z.number().int().positive(),
      tribe: TribeSchema.optional(),
    }).strict()).min(2).optional(),
  }).strict(),
  reward: QuestRewardSchema,
  repeatable: z.boolean().optional(),
}).strict();
