import { z } from 'zod';

/**
 * Runtime validation for card data (handoff C.5). The hand-written `CardDef`
 * type in `@game/core` is the canonical compile-time shape; this schema guards
 * the *data* at load and is kept in lockstep with it.
 */
export const TribeSchema = z.enum(['beast', 'undead', 'mech', 'dragon', 'demon', 'neutral', 'kobold', 'dwarf', 'celestial']);

export const KeywordSchema = z.enum(['T', 'DS', 'V', 'W', 'R', 'C', 'M', 'SC', 'CN', 'FD', 'IMM', 'ST', 'RL', 'SL', 'CR', 'EG']);

export const GameEventSchema = z.enum([
  'onPlay',
  'onSummon',
  'onDeath',
  'onAttack',
  'onGainAttack',
  'onDamaged',
  'friendlyDemonDealtDamage',
  'onLoseDivineShield',
  'onConsume',
  'onKill',
  'startOfCombat',
  'avenge',
  'onBuy',
  'endOfTurn',
  'battlecryTriggered',
  'cast',
  'spellCast',
  'summonOverflow',
  'goldSpent',
  'cardsBought',
  'cardsPlayed',
  'onSell',
  'startOfTurn',
  'equip', // grants this minion's Equipment (on play, and on every Start of Turn rebuild)
  'onGainCard',
  'onRubyPlayed',
  'rubyPlayedAnywhere',
  'minionSold',
  'spellCastOnThis',
  'onGetRuby',
  'rubyCast',
  'passive', // never dispatched — a marker another system reads (Deepdelve Paragon)
  'spellBought',
  'shopRefreshed',
  'orbit', // Celestial ORBIT — a card was played from hand adjacent to this minion
  'orbitFired', // Celestial — a board-wide watcher: ANY Orbit on your board resolved
]);

export const EffectFactoryIdSchema = z.enum([
  'buffOnePerTribe',
  'giftShoutExtraTurn',
  'giftRoyalAllowance',
  'giftShopBuffGame',
  'giftIroncladFavor',
  'giftUnbridledMight',
  'giftRegalia',
  'giftGrandLarceny',
  'giftSpellDiscountTurn',
  'giftMinionDiscountTurn',
  'giftUpgradeDiscount',
  'giftTierAboveMinion',
  'giftSecondCalling',
  'giftPartingGifts',
  'deathrattleSummon',
  'deathrattleSummonOverflowBuff',
  'buffOnSummon',
  'deathrattleBuffTribe',
  'reAttackOnKill',
  'onKillBuffSelf',
  'onKillBuffSpellPower',
  'onKillGrantFreeRolls',
  'onKillGrantAttachmentRefreshes',
  'onKillGrantGold',
  'onKillCastSpell',
  'rallyCastSpell',
  'rallyCastRandomStatSpell',
  'avengeCastRandomStatSpell',
  'deathrattleDamageAll',
  'deathrattleDestroyKiller',
  'deathrattleBuffTribeByTally',
  'scDamage',
  'scSplitDamage',
  'scAoePerTribe',
  'scArmBleed',
  'scEngraveNeighbor',
  'deathrattleBuffRandom',
  'deathrattleBuffAllRandomStat',
  'onFriendDeathBuffRandom',
  'rallyBuff',
  'rallyProcDeathrattle',
  'deathrattleGrantSpell',
  'battlecryBuffTribeImproving',
  'onBattlecryImproveSelf',
  'deathrattleQueueNextSpellCopy',
  'battlecryArmGrimoire',
  'onBattlecryRearmGrimoire',
  'onMinionSoldCopyFirstOfTribe',
  'minionSoldGrantSpell',
  'endOfTurnTriggerAdjacentShouts',
  'onRallyPlayRubiesTribe',
  'onRallyBuffOnePerTribe',
  'onSpellCastOnThisRecast',
  'onSpellCastOnThisSpreadAdjacent',
  'onSpellCastOnThisSpreadRandom',
  'onRubyPlayedSpreadAdjacent',
  'onRubyPlayedSpreadRandom',
  'scTriggerTribeShouts',
  'rallyTriggerLeftmostTribeShout',
  'onSpellCastBuffRandomTribe',
  'summonBuffTribeAsym',
  'onSpellCastImproveSummon',
  'battlecryCastTaughtSpell',
  'grantMagePupTaught',
  'battlecryGrantBeastHunt',
  'battlecryGrantBeastRitual',
  'rallySpreadTribeBuff',
  'scSummonOnlyTribeAura',
  'rallyProcLeftmostEcho',
  'deathrattleSummonRandomTribe',
  'deathrattleSummonRandomTribeSetStats',
  'onSummonTribeBuffFlat',
  'avengeSummonImps',
  'avengeSummon',
  'deathrattleBuffNextSummon',
  'deathrattleBuffRightmostSlot',
  'goldSpentBuffRightmostSlot',
  'battlecryGrantSpellPowerRun',
  'endOfTurnCopyNeighbour',
  'deathrattleSummonRandomTier',
  'summonImps',
  'rallySummonImpBuffImps',
  'deathrattleSummonRandomHandMinion',
  'rallyImpsAttackNow',
  'onTribePlayedConsumeShop',
  'avengeImproveSummonBuff',
  'onImpDeathSummonImp',
  'onImpAttackSummonCopy',
  'endOfTurnEndDemonsConsumeSides',
  'onShopRefreshConsume',
  'onSummonImpBuff',
  'scFillWithImpsAndBuff',
  'onImpAttackBuffImps',
  'battlecryConsumeShopRandom',
  'consumeShopRightmost',
  'battlecryTargetConsumesShop',
  'buffShopPermanent',
  'buffRightmostSlotPermanent',
  'endOfTurnGainRightmostShopStats',
  'onShopRefreshGainRightmostShopStats', // Hellrider (2026-08-14): every N refreshes, copy the right-most offer's stats
  'avengeGrantRandomTribeMinion',        // Grobbus (2026-08-14): Avenge (X) — get a random Demon
  'scBuffTribe',                         // Transcendant (2026-08-17): SoC buff your Dragons (Engrave is a live aura)
  'scBuffRandomTribePerAle',             // Drunken Oaf (2026-08-14): SoC buff a random Dwarf, once per Ale + 1
  'spellCopyTargetExact',
  'endOfTurnBuffSpellsAndImps',
  'onConsumeGoldFlat',
  'onOtherDemonConsumeEcho',
  'endOfTurnNeighboursConsumeShop',
  'onBattlecryBuffTribeAdjacentMore',
  'onSummonTribeBuffThenDouble',
  'onSummonTribeBuffImproveSelf',
  'deathrattleImpsOverflowGrant',
  'scGrantRightmostEcho',
  'endOfTurnSelfAndNeighboursConsume',
  'rallyBuffShopPermanent',
  'deathrattleBuffShopPermanent',
  'rallyBuffSelf',
  'rallyCastNamedSpell',
  'onTribeAttackCastNamedSpell',
  'rallyGrantRandomShoutMinion',
  'rallyTriggerTribeShouts',
  'spellBuffRandomPerTribe',
  'spellBuffHealthGrantFlurryDragon',
  'onRallyProcLeftmostEcho',
  'scTriggerLeftmostEchoes',
  'spellCastBuffImps',
  'rallyGrantSpellPower',
  'onBattlecryBuffSelf',
  'spellCastDemonConsumesShop', // Baal — every N spells, a friendly Demon eats a Shop minion
  'orbitBuffArriver',
  'orbitBuffRandomFriend',
  'orbitSellValue',
  'orbitBuffAlignedCelestials',
  'orbitBuffLowest',
  'orbitGrantSpellPower',
  'orbitCastSpell',
  'orbitCopyFirstSpell',
  'onOrbitBuffShopRightmost',
  'onOrbitBuffAll',
  'onOrbitBuffShop',
  'scGainKeyword',
  'orbitGainArriverBonus', // Celestial Orbit — buff the arriving minion
  'triggerAdjacentOrbits', // Celestial — trigger the Orbits either side of this minion
  'orbitBuffCelestialsPerBuffStack', // Celestial Orbit — scale off the arriver's Shop-buff stacks
  'orbitDevourArriver', // Celestial Orbit — destroy the arriver and hand on its bonus stats
  'orbitBuffSelf', //    Celestial Orbit — buff this minion
  'scBuffSelf', //       Celestial — SC self-gain (align-gated halves)
  'rallyBuffCelestials', //     Celestial — Rally: buff your Celestials
  'deathrattleBuffCelestials', // Celestial — Echo: buff your Celestials
  'battlecryGetRubies',
  'battlecryPlayRubiesAll',
  'spellCastBuffAll',
  'battlecryGrantShoutDragon',
  'onTribeAttackBuffAttacker',
  'onFriendlyDemonDamageBuffSelf',
  'scPlayRubiesSelfAndAdjacentTribe',
  'rallyPlayRubiesSelf',
  'rallyPlayRubiesAll',
  'onSellGetRubies',
  'startOfTurnGetSpellImproveRubies',
  'goldSpentBuffRandomTribe',
  'onGainCardBuffTribe',
  'minionSoldConsumeRightmost',
  'onConsumeBuffShop',
  'deathrattleDamageAllExceptTribe',
  'deathrattleGrantWardRandom',
  'onConsumeSelfGrantSpell',
  'spellPlayRubiesAll',
  'spellGainSpellPower',
  'spellDecoyNextCombat',
  'spellStealShop',
  'spellTargetConsumesShop',
  'deathrattleSummonGolemsWithRuby',
  'rallyCastShopBuffSpell',
  'spellWeakenNextCombat',
  'rallyBuffSelfPerTribe',
  'avengeCopyLeftmostHandSpell',
  'avengeBuffSpellPower',
  'onSpellCastFirstBuffSelf',
  'onSpellCastSecondCopyFirst',
  'endOfTurnRecastFirstSpell',
  'battlecryGrantShoutExtra',
  'battlecryGrantFirstSpellMult',
  'battlecryGrantTribeAndSpell',
  'battlecryGrantRandomSpell',
  'battlecryCopyCastSpell',
  'endOfTurnCopyCastSpell',
  'battlecryBuffOtherTribe',
  'deathrattleGrantMagnetic',
  'deathrattleBuffSpellPower',
  'deathrattleBuffCardTypeRunWide',
  'buffFodderEverywhere',
  'deathrattleFillTribe',
  'avengeBuff',
  'scTribeBuffPerAle',
  'scCastLeftmostHandSpell',
  'deathrattleCastLastSpell',
  'rallyCastRandomTargetedSpell',
  'deathrattleTriggerAdjacentRally',
  'rubyBounceExtra',
  'avengeCastRandomHandSpell',
  'scGrantSpellCastExtra',
  'scGrantShieldTribe',
  'scGrantReborn',
  'grantEquipment', // the `equip` factory: hands the player the Equipment named by `params.equipmentId`
  'equipmentBuffTarget', // Bloodpot: one Equipment TRIGGER — +atk/+hp onto the chosen friendly minion
  'equipmentCastSpell', // an EQUIPMENT SPELL: casts its named Shop spell through the real cast pipeline
  'deathrattleGrantShield',
  'onShieldBreakGrantShield',
  'onShieldBreakDamage',
  'onShieldBreakBuffAll',
  'onFriendDeathSummon',
  'scDestroyHighestAttack',
  'scGrantEnemyTaunt',
  'scSummonCopy',
  'scTribeBuffPerSpell',
  'scTribeBuffPerProgress',
  'scTribeBuffPerSpellImproving',
  'scTribeBuffPerPlayed',
  'scTribeBuffImproving',
  'battlecryBuffTribe',
  'battlecrySummon',
  'buffOnBuy',
  'buffBoardOnBuy',
  'battlecryGrantKeyword',
  'battlecryBuffTarget',
  'battlecryGainRandomMinion',
  'battlecryDiscoverSpell',
  'onBattlecryBuffTribe',
  'onBattlecryBuffFodder',
  'battlecryBuffFodder',
  'battlecryBuffSpellPower',
  'endOfTurnBuff',
  'endOfTurnMagnetizeMechs',
  'addTavernFodder',
  'addFodderNextShops',
  'deathrattleAddFodder',
  'deathrattleBuffFodder',
  'rallyBuffFodderHalf',
  'rallyBuffFodder',
  'avengeAddFodder',
  'avengeGrantSpellPower',
  'avengeImproveSummon',
  'avengeMaxGold',
  'avengeGrantSpell',
  'deathrattleGrantReborn',
  'deathrattleBuffAll',
  'battlecryTriggeredOwnDeathrattle',
  'onConsumeBuffSelf',
  'onConsumeGrantSelfKeyword',
  'onConsumeShieldNextCombat',
  'spellBuffTarget',
  'spellBuffTargetAndNeighbours', // Beefy: the target AND its neighbours
  'spellMarkPartingCry',
  'spellMarkClosedCasket',
  'spellSolidGround',
  'spellContainFirstEnemySummon',
  'spellStolenInitiative',
  'spellGambleTierPull',          // Gamble: roll a die, get a minion/spell of that tier
  'spellBuffTargetPerGold',
  'spellBuffAll',
  'spellDevour',
  'spellPowerShift',
  'castSpell',
  'endOfTurnGetRandomSpells',
  'gainEmbers',
  'spellCastBuffOthers',
  'overflowBuffRandom',
  'spellCastTransform',
  'spellCastImproveSelf',
  'spellCastBuffSelf',
  'summonBuffSelfTribe',
  'spellBuffShop',
  'gainMaxMana',
  'grantFreeRolls',
  'spellGainOfTargetTribe',
  'spellGainRandomMinion',
  'spellGildTarget',
  'spellBuffTargetEscalating',
  'spellGrantTribeAttack',
  'healHero',
  'conjureTribeArmy',
  'stealTavernMinion',
  'endOfTurnGrantTribe',
  'endOfTurnGrantRandomTierCard',
  'avengeGiveAttack',
  'onFriendlyAttackBuffTribe',
  'battlecryDiscoverMinion',
  'spellSetStats',
  'spellStealAdjacentRubies', // Ruby Transfer — steal adjacent Ruby buffs
  'spellAverageStats',
  'spellSwapStats',
  'spellGoldIfLostLast',
  'onAllyAttackBuffAll',
  'onGainAttackBuffAll',
  'onGainAttackBuffImproving',
  'spellBuffTavern',
  'spellBuffNextShop',
  'spellPendingSCBuff',
  'spellGrantKeywordNextCombat',
  'spellTauntNextSummons',
  'spellNextSellBonus',
  'spellRefreshToTribe',
  'spellRefreshTierUp',
  'spellLayaway',
  'spellReturnToHand',
  'spellTransformSameTier',
  'spellMarkEnemyTaunt',
  'spellSummonImpsNextCombat',
  'spellBuffShopByRuby',
  'spellBuffPerDragonPlayed',
  'spellDiscoverFromLastOpponent',
  'spellScoutNextOpponent',
  'onAllyAttackCastGrowth',
  'spellDemonConsumeFodder',
  'deathrattleGrantRandomSpell',
  'onDamagedGrantRefresh',
  'summonBuffTribeImprove',
  'countTribeSummon',
  'deathrattleGiveHealth',
  'scGainFodderStats',
  'onSummonSelfBuff',
  'onSummonOverflowBuffTribe',
  'deathrattleBuffAllHealth',
  'onGainAttackImproveHpGrant',
  'spellCastBuffUndeadAttack',
  'deathrattleGrantCardToHand',
  'battlecryBuffUndeadAttack',
  'battlecryBuffBeastAttack',
  'battlecryScoutSpread',
  'battlecryConductorAdjacent',
  'battlecryBuffMagnetics',
  'battlecryBuffImps',
  'goldSpentBuffFodder',
  'goldSpentMagnetize',
  'onKillBuffUndeadAttack',
  'onKillBuffFodderImps',
  'onDamagedGainAttack',
  'rallyGrantMagnetic',
  'deathrattleBuffImps',
  'avengeBuffImps',
  'battlecryBonusGoldNextTurn',
  'deathrattleReplayAdjacentBattlecry',
  'spellBuffByTier',
  'spellSellToDemon',
  'spellSellToBeast',
  'spellReplayBattlecry',
  'spellExtraEndOfTurn',
  'spellGildRandomTavern',
  'spellBuffLeftmost',
  'spellBuffRandomFriendlies',
  'spellGrantTopTypeMinion',
  'spellDisplace',
  'spellCopyRecent',
  'spellRefreshToSpells',
  'battlecryTargetConsumeFodder',
  // Slaughter (on-kill) + random-spell batch
  'avengeGrantRandomSpell',
  'rallyGrantRandomSpell',
  'onKillGrantRandomSpell',
  'onKillBuffFodder',
  // 2026-07-05 content batch
  'avengeSummonAttack',
  'spellAttackFirst',
  // 2026-07-06 content batch
  'scBeastAura',
  'rallyTribeAura',
  'rallyTribeAuraGrowing',
  'rallyGiveDemonAttack',
  'rallyDamageRandomEnemy',
  'avengeShieldAttack',
  'endOfTurnGrantSpellChoice',
  'spellRallyDoubleNext',
  'rallyCastTribeAttack',
  'battlecryDoubleNextSpell',
  'battlecryGrantSpell',
  'battlecryGrantMinion',
  'endOfTurnCastSpellEscalating',
  'endOfTurnCastSpellOnSelf',
  'endOfTurnAdjacentConsumeFodder',
  'endOfTurnFeastConsume',
  'endOfTurnBuffPerTribePlayed',
  'endOfTurnBuffWeakestDragon',
  'onSellGainGold',
  'battlecryDestroyForSpell',
  'avengeBonusGold',
  'deathrattleMaxGold',
  'getEchoAndTrigger',
  'spellTriggerEcho',
  'battlecryCopyEcho',
  'rallyGrantSpell',
  'rallyBuffAttachments',
  'onKillGrantMagnetic',
  'endOfTurnBonusGold',
  'scConsumeWeakestBuffDemons',
  'scBuffAlliesPctSelf',
  'rallyGrantSelfCopy',
  'battlecryAllDemonsConsume',
  'spellBuffImpsPerDemon',
  'scEngraveAll',
  'rallyGiveHealthToDragons',
  'spellBloodlust',
  'copyLeftmostEcho',
  'spellAddTribe',
  'spellAddAllTribes',
  'deathrattleBuffAllByImpAura',
  'buffFodderImpsImproving',
  'onAttackStripKeywords',
  // Tier 7 (Summit)
  'onAllyTribeAttackBuffSelf',
  'deathrattleGrantRebornAll',
  'deathrattleCastTribeAttack',
  'onSellDiscover',
  'deathrattleGainRandomMinion',
  // Set 2 — Kobolds / Rubies
  'getRubies',        // Shout/Rally: mint N Rubies into hand (base 1/1 + rubyBonus)
  'endOfTurnGetRubies', // Wardstone Jeweler: End of Turn, mint Rubies (Warding Ruby)
  'rubyStatGain',     // "Your Rubies gain +X/+Y" — raises rubyBonus + grows held Rubies
  'scPlayRubies',     // Start of Combat: play N Rubies on your [tribe] minions (permanent carry-back)
  'avengePlayRubies', // Avenge (X): play N Rubies on your [tribe] minions
  'cardsBoughtGetRubies',
  'goldSpentGetRubiesPlayOnTribe', // Mountainbond (2026-08-14)
  'grantRandomAle', 'battlecryBuffTribeOthersAttack', 'battlecryGainKeyword', 'goldSpentBuffTribeAttack', 'battlecryBuffTargetPerGoldSpent', 'endOfTurnBuffEndsTribePerCard', 'cardsBoughtGrantRandomSpell', 'battlecryGildTarget', 'goldSpentGrantTribeMinion',
  'combatGrantAle', 'rallyGiveAttackToOthers', 'echoSummonCopyNoEcho', 'echoSummonInheritAttackAndCharge',
  'impInheritOnDeath', 'impInheritOnSummon', 'echoCastRememberedSpells', 'echoResummonDeadBeasts',
  'setArmor',
  'battlecryGainGoldNextTurn', 'cardsPlayedPlayRubies', 'onTribeSummonedBuffTribe', 'onSpellCastBuffOnePerTribe', 'spellCastTriggerAdjacentShouts', // Hoardmaster Krik: every N cards bought, mint Rubies to hand
  'rallyGetRubies',   // Rally: get N Rubies (carried back to hand after combat)
  'avengeRubyStatGain', // Avenge (X): buff your Rubies +X/+Y (carried back to rubyBonus)
  'scPlayRubiesPerBuy', // Frenzied Excavator: SoC play N Rubies per M cards bought this turn
  'avengeGetRubies', // Gemline Martyr: Avenge (X) get N Rubies
  'avengePlayRubiesLeftmost', // Gemline Martyr: Avenge (X) play N Rubies on your left-most minion
  'rubyPlayedBounce', // Resonance Idol: a Ruby played on this bounces to both adjacent minions
  'rubyPlayedGold',   // Ruby Broker: a Ruby played on this gives Gold (capped per turn)
  'rubyGainedCast',   // Candle Conduit: getting a Ruby casts one on a random friendly Kobold
  'damagedGainRubyBonus', // Faultline Scrapper: on-damage, buff your Rubies +X/+Y
  'damagedGetRubies', // Candleback Bulwark: on-damage, get N Rubies (capped per fight)
  'rallyRubyStatGain', // Crownvein: Rally buff your Rubies +X/+Y
  'rallyPlayRubiesTargets', // Crownvein: Rally play N Rubies each on the first M friends of a tribe
  'deathrattleRubyStatGain', // Alchemist Brisbane (Echo): on death, buff your Rubies +X/+Y
  'deathrattlePlayRubiesAdjacent', // Geode Guardian (Echo): on death, play N Rubies on each neighbour
  'deathrattlePlayRubiesTribe', // Kobebes (Echo): on death, play N Rubies on each friendly tribe minion
  'onTribePlayedBuffSelfPerSpell', // Herzog: +N/+N when you play a tribe; N scales with Shop Spells cast
  'endOfTurnPlayRuby', // Alchemist Brisbane (EoT): play N Rubies on a random friendly Kobold
  'deathrattleSummonRubyStats', // Gemheart Carver: Echo summon a token with stats = its Rubies
  'rubyStatMultiplier', // Deepdelve Paragon: Rubies applied IN COMBAT are worth 2x (3x Gilded)
  'rubyCastConsumeShop', // Gemgorge Fiend: every N Rubies cast, Consume a Shop minion
  // --- RUNE-ONLY minion batch (2026-08-20) ---
  'onGetRubyDuplicate',           // Gem Sage
  'goldSpentScaleSelf',           // Ancient Wanderer
  'buffShopOffersThisTurn',       // Night Market Horror
  'onSellDiscoverSingleton',      // Traveling Salesman
  'onGainAleBuffSelf',            // Kegheart Dwarf
  'onBuyGrantSpellSameTier',      // Ninefold Broker
  'endOfTurnCopyLeftmostHandCard',// Stonehorn Archivist
  'endOfTurnTransformLeftTierUp', // Skybound Ascendant
  'minionSoldDemonGainStats',     // Arcane Behemoth
  'onFriendDeathGainEcho',        // Echo Mimic
  'avengeSummonAttackImproving',  // Muster General
  'rallyDoubleSelf',              // Evolving Abomination
]);

export const EffectDefSchema = z.object({
  on: GameEventSchema,
  do: EffectFactoryIdSchema,
  params: z.record(z.unknown()).optional(),
  // CELESTIAL alignment gate — this half only fires while its owner is Dawn / Dusk (Eclipse fires both).
  align: z.enum(['dawn', 'dusk']).optional(),
  // COMBAT-ONLY gate (Sunmane Herald, owner ruling 2026-08-20): the shop dispatchers skip this effect
  // entirely — see `EffectDef.combatOnly` in @game/core.
  combatOnly: z.boolean().optional(),
}).strict();

// `.strict()`: a typo'd optional key (`goldentext`, `targetTribes`) would otherwise validate silently and
// the card would ship without the feature. Every legit field is declared below, so this only rejects typos.
export const CardDefSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  tribe: TribeSchema,
  tribe2: TribeSchema.optional(),
  tier: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6),
    z.literal(7), // Tier 7 — reachable only under the Summit rift (see maxTierFor)
  ]),
  attack: z.number().int().nonnegative(),
  health: z.number().int().positive(),
  keywords: z.array(KeywordSchema),
  effects: z.array(EffectDefSchema),
  // Body text is mechanical-only and may be empty for keyword-only cards
  // (the keyword badge + hover tooltip carry the meaning).
  text: z.string(),
  goldenText: z.string().optional(),
  universalTribe: z.boolean().optional(),
  attackImmuneAlways: z.boolean().optional(),
  splashAdjacent: z.boolean().optional(),
  // TWO SHAPES, and the card's printed wording says which (owner vocabulary rule 2026-08-28):
  // "trigger twice" → `factor` (a multiplier; copies of one card do not stack, different cards multiply),
  // "trigger 1 additional time" → `extra` (additive; everything stacks). Exactly one of the two.
  triggerMultiplier: z.union([
    z.object({
      families: z.array(z.enum(['battlecry', 'deathrattle', 'rally', 'slaughter', 'endOfTurn', 'startOfCombat'])),
      extra: z.number().int().positive(),
      stacks: z.boolean().optional(),
    }).strict(),
    z.object({
      families: z.array(z.enum(['battlecry', 'deathrattle', 'rally', 'slaughter', 'endOfTurn', 'startOfCombat'])),
      factor: z.number().int().min(2),
    }).strict(),
  ]).optional(),
  imp: z.boolean().optional(),
  token: z.boolean().optional(),
  celestial: z.boolean().optional(), // alignment-bearing (Dawn/Dusk/Eclipse) — drives the alignment HUD
  henchman: z.boolean().optional(), // hero-bound recruit — never shop-offered (see cards/henchmen.ts)
  noTriple: z.boolean().optional(),
  rewardSpell: z.boolean().optional(),
  ascendAt: z.number().int().positive().optional(),
  attackImmuneTurns: z.number().int().positive().optional(),
  ascendInto: z.string().optional(),
  attackOnSummon: z.boolean().optional(),
  spell: z.boolean().optional(),
  gift: z.boolean().optional(),
  ruby: z.boolean().optional(),
  rubyGrantKeyword: KeywordSchema.optional(),
  singleCast: z.boolean().optional(),
  cost: z.number().int().nonnegative().optional(),
  target: z.enum(['friendly', 'any']).optional(),
  targetTribe: TribeSchema.optional(),
  orbitExtraAdjacent: z.boolean().optional(),
  orbitExtraBoard: z.boolean().optional(),
  targetMaxTier: z.number().int().positive().optional(),
  targetNoGolden: z.boolean().optional(),
  targetNotSelf: z.boolean().optional(),
  fodderMult: z.number().int().positive().optional(),
  critChance: z.number().min(0).max(1).optional(), // Critical Strike probability per swing (Commander Impala = 0.5)
  manaPerTurn: z.number().int().positive().optional(),
  rallyMechAtk: z.number().int().positive().optional(),
  spellAura: z.number().int().positive().optional(),
  rubyExtraCast: z.number().int().positive().optional(),
  fodderAura: z.object({ attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict().optional(),
  chooseOne: z
    .array(z.object({ text: z.string(), goldenText: z.string().optional(), effects: z.array(EffectDefSchema), target: z.enum(['friendly', 'any']).optional() }).strict())
    .min(2)
    .optional(),
  chooseBothWhenGolden: z.boolean().optional(),
  discoverOnPlay: z
    .object({
      exactTier: z.number().int().positive().optional(),
      exactCurrentTier: z.boolean().optional(),
      tierOffset: z.number().int().optional(),
      filter: z.enum(['battlecry', 'deathrattle']).optional(),
      tribe: z.union([TribeSchema, z.literal('dominant')]).optional(),
      topTierFirst: z.boolean().optional(),
      spell: z.boolean().optional(),
      maxTier: z.number().int().positive().optional(),
      lockUntilNextTurn: z.boolean().optional(),
      borrowed: z.boolean().optional(),
      grantKeywords: z.array(KeywordSchema).optional(),
    })
    .strict()
    .optional(),
}).strict();

// ── Quests ───────────────────────────────────────────────────────────────────────────────────────────────
// Kept in lockstep with the `QuestDef` type in @game/core (same as CardDefSchema). `.strict()` rejects typo'd
// keys so a malformed test quest surfaces in `npm test`, not at runtime.
export const QuestTierSchema = z.enum(['lesser', 'greater', 'capstone']);
export const QuestObjectiveEventSchema = z.enum([
  'buy', 'play', 'sell', 'roll', 'summon', 'shout',
  'attack', 'summonCombat', 'slaughter', 'slaughterKeyword', 'deathrattle',
  'spendGold', 'endOfTurn', 'tribeStats', 'friendlyDeath',
  'rally', 'playAttachment',
  'consumeFodder', 'consumeStats', 'summonImp',
  'winRound', 'castSpell', 'authorsHand',
  'castRuby',
  'shopStats',
  'consumeShopMinion',
  'compound',
  'journey', // hero quests (Fi/Coran): the shared "steps down the road" counter
]);
export const QuestCombatFlagSchema = z.enum(['bloodTrail', 'echoingCoop', 'lawOfTeeth', 'oldHunt', 'sharedCircuit', 'deepHunger', 'contractRewrite', 'pitWithoutEnd', 'doubleLeftmostAttack', 'feedingLine', 'umbralEnergy', 'emptyGraves', 'assemblyLine', 'crateringMissive', 'passingSpears', 'runeWarding', 'runeFury', 'runeSlaying', 'runeForthcoming', 'runeRallying', 'runeRisingGraves', 'runeBroodpit', 'runeSpearline', 'runeAppraisal', 'runeSoulTaxes', 'runeFirstClaws', 'runePackcraft', 'runeInheritance', 'runeSalvage', 'runeTwilight', 'runeWarden', 'runeRebirth', 'runeAftershocks', 'runeEngraving', 'runeUnderdog', 'runeGemGolem', 'runeChef', 'runeCarrionCoin', 'runeFiveBanners', 'runeCenterline', 'runeSecondLitter', 'runeDragonscale', 'runeTemperedTime', 'runeSavagery', 'runeCrucible', 'runeHerald', 'runeUndertow', 'runeMirrorMarch', 'runeTrophy', 'avengeFirstDouble', 'candlelightToll', 'gemheartCharge', 'burningLegion', 'runeVanguard', 'runeFinality', 'runeHatchery', 'runeLastCall', 'runeCinderLedger', 'runeProcession', 'runeGemstorm', 'runeBloodAndCoin', 'runeWildHunt', 'runeLivingTreasure', 'runeRemains', 'runeReinvestment', 'runeHuntingBell', 'runeBrood', 'runeLivingEchoes', 'runeWarChorus', 'runeFoodChain', 'runeAttackingGems', 'runeOverflow', 'runeCounterpoint', 'runeMammoth', 'runeWarpath', 'runeEmberline', 'runeAshenPayroll', 'runeBackbeat', 'runeSpareChair', 'runeAncestralRoar', 'runeRubyShrapnel', 'runeSharedScripture', 'runeMoonhowl', 'runeFloodedVault', 'runeBattleRefraction', 'runeWrangler', 'runeLivingGeode', 'runeDawnclaw', 'runeSylus', 'oldPack', 'runeJungle', 'runeBurrow', 'runeBeastialSwarm', 'runeZoo', 'runeRuins', 'runeGolems', 'runeEngravingGems', 'runeHerdingHorn', 'runeDeathtouchedApple', 'runeStokedMenagerie',
  // 2026-08-20 rune batch
  'runeReturningPack', 'runeGraveRefreshment', 'runeShiftingFacets', 'runeDeepeningVein']);

// The reward palette — a discriminated union kept in lockstep with the `QuestReward` type in @game/core.
export const QuestRewardSchema: z.ZodType = z.lazy(() => z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('buffBoard'), attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict(),
  z.object({
    kind: z.literal('grant'),
    randomTribe: TribeSchema.optional(),
    randomCount: z.number().int().positive().optional(),
    randomSpell: z.number().int().positive().optional(),
    randomAle: z.number().int().positive().optional(),
    randomRuby: z.number().int().positive().optional(),
    randomFilter: z.enum(['shout', 'endOfTurn', 'echo', 'rally', 'attachment']).optional(),
    randomFilterCount: z.number().int().positive().optional(),
    randomFilterExactTier: z.boolean().optional(),
    randomTier: z.number().int().min(1).max(6).optional(),
    cards: z.array(z.string().min(1)).optional(),
    grantGolden: z.array(z.string().min(1)).optional(),
    grantKeywords: z.array(KeywordSchema).optional(),
    repeatInTurns: z.number().int().positive().optional(),
  }).strict(),
  z.object({ kind: z.literal('shoutDouble'), count: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('tribeAura'), tribe: TribeSchema, attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict(),
  z.object({
    kind: z.literal('scalingTribeAura'),
    tribe: TribeSchema,
    attack: z.number().int().nonnegative(),
    health: z.number().int().nonnegative(),
    per: z.number().int().positive(),
    event: QuestObjectiveEventSchema,
    stepAttack: z.number().int().nonnegative(),
    stepHealth: z.number().int().nonnegative(),
  }).strict(),
  z.object({ kind: z.literal('recurringGrant'), cards: z.array(z.string().min(1)).min(1), everyTurns: z.number().int().positive().optional() }).strict(),
  // Hero quest rewards (Fi / Coran, 2026-08-21).
  z.object({ kind: z.literal('grantRune'), rarity: z.enum(['basic', 'epic']) }).strict(),
  z.object({ kind: z.literal('freeFirstBuy') }).strict(),
  z.object({ kind: z.literal('tier7Access') }).strict(),
  z.object({ kind: z.literal('gildCopies'), copies: z.number().int().min(2).max(3) }).strict(),
  z.object({ kind: z.literal('upgradeShopTier'), by: z.number().int().positive() }).strict(),
  // 2026-08-19 owner rune batch.
  z.object({ kind: z.literal('runeTribeDrip'), tribe: TribeSchema, count: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeSpellDouble'), spellId: z.string().min(1) }).strict(),
  z.object({ kind: z.literal('runeGlider'), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('runePendant'), maxTier: z.number().int().min(1).max(7) }).strict(),
  z.object({ kind: z.literal('runeWarDrum'), extra: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeBaller'), step: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeEmbers') }).strict(),
  z.object({ kind: z.literal('runeRefreshments') }).strict(),
  z.object({ kind: z.literal('runeWishbone') }).strict(),
  z.object({ kind: z.literal('runeMight') }).strict(),
  z.object({ kind: z.literal('runeHeldStrength') }).strict(),
  z.object({ kind: z.literal('runeChipperSticker') }).strict(),
  // 2026-08-20 owner rune batch.
  z.object({ kind: z.literal('runeSpellEcho'), uses: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeDraconicCuriosity') }).strict(),
  z.object({ kind: z.literal('runeSeasonedLedger'), attack: z.number().int().nonnegative(), health: z.number().int().nonnegative(), per: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeEchoedArrival'), per: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeSharedSpoils') }).strict(),
  z.object({ kind: z.literal('runeHeavyPayroll'), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('impAura'), attack: z.number().int().nonnegative(), health: z.number().int().nonnegative() }).strict(),
  z.object({ kind: z.literal('beastPlayBuff'), attack: z.number().int().positive(), health: z.number().int().positive(), step: z.number().int().nonnegative(), per: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('combatFlag'), flag: QuestCombatFlagSchema, amount: z.number().int().nonnegative().optional() }).strict(),
z.object({ kind: z.literal('tribeRallySlaughterExtra'), tribe: TribeSchema }).strict(),
z.object({ kind: z.literal('aleExtraCasts'), amount: z.number().int().positive().optional() }).strict(),
z.object({ kind: z.literal('questGoldTribeBuff'), tribe: TribeSchema, per: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('rubyStatGain'), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('rubyExtraCasts'), amount: z.number().int().positive(), scope: z.enum(['always', 'firstEachTurn']), firstN: z.number().int().positive().optional() }).strict(),
z.object({ kind: z.literal('shopBuff'), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('shopBuffPerShouts'), per: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('shopBuffOnRefresh'), attack: z.number().int(), health: z.number().int(), step: z.number().int(), per: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('shopAuraGrowing'), attack: z.number().int(), health: z.number().int(), step: z.number().int(), per: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('spellCost'), cost: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeCoffers') }).strict(),
z.object({ kind: z.literal('runeEnchantment') }).strict(),
z.object({ kind: z.literal('runeCrown'), per: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('runeLapidary') }).strict(),
z.object({ kind: z.literal('runeLastingCadence') }).strict(),
z.object({ kind: z.literal('runeCombatProwess') }).strict(),
z.object({ kind: z.literal('runeDeep'), tier: z.number().int().min(1).max(7) }).strict(),
z.object({ kind: z.literal('runeGuidingCandle'), count: z.number().int().positive(), tier: z.number().int().min(1).max(7) }).strict(),
z.object({ kind: z.literal('runeMuster') }).strict(),
z.object({ kind: z.literal('runeFoundry'), per: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeCorruptedTome') }).strict(),
z.object({ kind: z.literal('runeGroveweaver') }).strict(),
z.object({ kind: z.literal('runeSharedPour') }).strict(),
z.object({ kind: z.literal('runeAftermarket') }).strict(),
  z.object({ kind: z.literal('runeSpellhide') }).strict(),
  z.object({ kind: z.literal('runeSpellmarket') }).strict(),
  z.object({ kind: z.literal('runeLastWord') }).strict(),
  z.object({ kind: z.literal('runeRunicHoard') }).strict(),
  z.object({ kind: z.literal('runeBanquetHall') }).strict(),
  z.object({ kind: z.literal('runeCrucibleChoir') }).strict(),
  z.object({ kind: z.literal('runeFullMeasure') }).strict(),
  z.object({ kind: z.literal('runeMountainTrade') }).strict(),
  z.object({ kind: z.literal('runeOpenAppetite') }).strict(),
  z.object({ kind: z.literal('runeBroodmaster') }).strict(),
  z.object({ kind: z.literal('runeSecondLife') }).strict(),
  z.object({ kind: z.literal('runeSharedReflection') }).strict(),
  z.object({ kind: z.literal('runeUnbrokenVein') }).strict(),
  z.object({ kind: z.literal('runeLivingGrowth') }).strict(),
z.object({ kind: z.literal('runeHoardcalling') }).strict(),
z.object({ kind: z.literal('runeConduit') }).strict(),
z.object({ kind: z.literal('runeVault') }).strict(),
z.object({ kind: z.literal('runeAltar'), goldPer: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeLorekeeping') }).strict(),
z.object({ kind: z.literal('runeThrift') }).strict(),
z.object({ kind: z.literal('runeFlagship') }).strict(),
z.object({ kind: z.literal('runeBrew') }).strict(),
z.object({ kind: z.literal('runeEvolution'), tier: z.number().int().min(1).max(7) }).strict(),
z.object({ kind: z.literal('runeTranscription'), count: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeTreasureMap'), turns: z.number().int().positive(), gold: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeGoldenSplinter'), at: z.number().int().positive(), tier: z.number().int().min(1).max(7) }).strict(),
z.object({ kind: z.literal('endlessVerse'), per: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeThreshold'), meter: z.enum(['gold', 'spellCast', 'spellCastNonAle', 'castRuby', 'cardsBought', 'cardsPlayed', 'playDragon', 'shout', 'consume']), per: z.number().int().positive(),
  grantSpell: z.number().int().positive().optional(), grantAle: z.number().int().positive().optional(), grantRuby: z.number().int().positive().optional(),
  grantCards: z.array(z.string().min(1)).min(1).optional(),
  castStatSpell: z.number().int().positive().optional(),
  buff: z.object({ target: z.enum(['imps', 'shop', 'shopRightmost', 'shopTurn', 'spells', 'tribe']), tribe: TribeSchema.optional(), attack: z.number().int(), health: z.number().int(), step: z.object({ attack: z.number().int(), health: z.number().int() }).strict().optional() }).strict().optional(),
  rubyAll: z.boolean().optional(),
  grantGoldNextTurn: z.number().int().positive().optional(),
  resetEachTurn: z.boolean().optional(),
  oncePerTurn: z.boolean().optional(), once: z.boolean().optional() }).strict(),
z.object({ kind: z.literal('runeBrokerage') }).strict(),
z.object({ kind: z.literal('runeSharedTable'), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('runeRedirection') }).strict(),
z.object({ kind: z.literal('runeDistillation') }).strict(),
z.object({ kind: z.literal('runeLiquidation') }).strict(),
z.object({ kind: z.literal('runeFacetwright') }).strict(),
z.object({ kind: z.literal('runeDuplication') }).strict(),
z.object({ kind: z.literal('runeProfitSharing'), tribe: TribeSchema, attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('runeWhiteWolf') }).strict(),
z.object({ kind: z.literal('runeSpellstone') }).strict(),
z.object({ kind: z.literal('runeSellRubies'), count: z.number().int().positive() }).strict(),
z.object({ kind: z.literal('runeOpenMarket'), attack: z.number().int(), health: z.number().int() }).strict(),
z.object({ kind: z.literal('motherlode'), count: z.number().int().positive(), tribe: TribeSchema.optional() }).strict(),
z.object({ kind: z.literal('consumeDoubleFirstEachTurn') }).strict(),
  z.object({ kind: z.literal('shoutRepeat'), scope: z.enum(['always', 'firstEachRound']) }).strict(),
  z.object({ kind: z.literal('endOfTurnRepeat') }).strict(),
  z.object({ kind: z.literal('recurringEndOfTurn'), turns: z.number().int().positive().optional(), effect: z.enum(['triggerLeftmostShout', 'grantRandomShout', 'grantRandomAttachments', 'buffMechsPerAttachment', 'runeSpending', 'runeAction', 'triggerLeftmostEcho', 'weldMoneyBotsEdgeMechs', 'undeadPlayedAtk', 'attachClingDrones', 'recastFirstSpell', 'grantAles', 'grantAles3', 'quickStudy', 'copyFirstSpell', 'grantRuby', 'grantRuby2', 'demonEatsRightmostShop', 'grantFacetwright', 'lassoing']) }).strict(),
  z.object({ kind: z.literal('gainGold'), amount: z.number().int().positive(), immediate: z.boolean().optional() }).strict(),
  z.object({ kind: z.literal('echoRepeat'), scope: z.enum(['always', 'firstEachCombat']) }).strict(),
  z.object({ kind: z.literal('boneThrone'), every: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('rallyRepeat'), scope: z.enum(['always', 'firstEachCombat']) }).strict(),
  z.object({ kind: z.literal('fodderReward'), fodder: z.number().int().nonnegative().optional(), attack: z.number().int().nonnegative().optional(), health: z.number().int().nonnegative().optional() }).strict(),
  z.object({ kind: z.literal('gainMaxGold'), amount: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('discover'), tier: z.number().int().min(1).max(7).optional(), filter: z.enum(['battlecry', 'deathrattle']).optional(), grantKeywords: z.array(KeywordSchema).optional() }).strict(),
  z.object({ kind: z.literal('discoverGreaterQuest') }).strict(),
  z.object({ kind: z.literal('dupeFirstBuy') }).strict(),
  z.object({ kind: z.literal('spellRepeat'), scope: z.enum(['always', 'firstEachTurn']) }).strict(),
  z.object({ kind: z.literal('minionCost'), cost: z.number().int().nonnegative() }).strict(),
  z.object({ kind: z.literal('slaughterRepeat'), scope: z.enum(['firstEachCombat']) }).strict(),
  z.object({ kind: z.literal('shoutEdgeBuff'), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('goldFodder'), per: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('attachmentDeal'), cost: z.number().int().nonnegative() }).strict(),
  z.object({ kind: z.literal('friedCircuits'), stepAttack: z.number().int().positive(), stepHealth: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('undeadSpellAura'), attack: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('baneDemonAura'), attack: z.number().int().positive(), health: z.number().int().positive() }).strict(),
  // Runeforge rune rewards.
  z.object({ kind: z.literal('runeSpellDrip'), per: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeStructure') }).strict(),
  z.object({ kind: z.literal('runeConsume'), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('goldPouchValue'), value: z.number().int().positive() }).strict(),
  z.object({ kind: z.literal('runeSummoning') }).strict(),
  z.object({ kind: z.literal('runeKindling') }).strict(),
  z.object({ kind: z.literal('runeScales') }).strict(),
  z.object({ kind: z.literal('runeLongShift') }).strict(),
  z.object({ kind: z.literal('runeHappyBirthday') }).strict(),
  z.object({ kind: z.literal('runeMerryChristmas') }).strict(),
  z.object({ kind: z.literal('runeBartering') }).strict(),
  z.object({ kind: z.literal('runeTwinGilding') }).strict(),
  z.object({ kind: z.literal('runeDenMother') }).strict(),
  z.object({ kind: z.literal('runeDisplayCase') }).strict(),
  z.object({ kind: z.literal('runeBlart') }).strict(),
  z.object({ kind: z.literal('runeVaultkeeper') }).strict(),
  z.object({ kind: z.literal('runeSellersMarket') }).strict(),
  z.object({ kind: z.literal('runeFreshPages') }).strict(),
  z.object({ kind: z.literal('runeStrangeCaravan') }).strict(),
  z.object({ kind: z.literal('runeWindowShopping') }).strict(),
  z.object({ kind: z.literal('runeOpenEnrollment') }).strict(),
  z.object({ kind: z.literal('runeShopkeep') }).strict(),
  z.object({ kind: z.literal('runeTradeIn') }).strict(),
  z.object({ kind: z.literal('runeRestocking') }).strict(),
  z.object({ kind: z.literal('runeCollector') }).strict(),
  z.object({ kind: z.literal('runeBargainBin') }).strict(),
  z.object({ kind: z.literal('runeScale'), count: z.number().int().positive(), attack: z.number().int(), health: z.number().int(), per: z.number().int().positive().optional() }).strict(),
  z.object({ kind: z.literal('runeCopies') }).strict(),
  z.object({ kind: z.literal('runeTempering') }).strict(),
  z.object({ kind: z.literal('runeReplication') }).strict(),
  z.object({ kind: z.literal('runeRefrain') }).strict(),
  z.object({ kind: z.literal('runeTransfusion') }).strict(),
  z.object({ kind: z.literal('runeEndlessAppetite') }).strict(),
  z.object({ kind: z.literal('runeConductor') }).strict(),
  z.object({ kind: z.literal('runeMatriarch') }).strict(),
  z.object({ kind: z.literal('runeContraband') }).strict(),
  z.object({ kind: z.literal('runeCadence') }).strict(),
  z.object({ kind: z.literal('runeGemscript') }).strict(),
  z.object({ kind: z.literal('mintRubies'), count: z.number().int().positive(), attack: z.number().int(), health: z.number().int() }).strict(),
  z.object({ kind: z.literal('runeSecondPath') }).strict(),
  z.object({ kind: z.literal('runeChampion') }).strict(),
  z.object({ kind: z.literal('runeSummit') }).strict(),
  z.object({ kind: z.literal('runeMastery') }).strict(),
  z.object({ kind: z.literal('runeEmpowerment') }).strict(),
  z.object({ kind: z.literal('openEpicRuneforge') }).strict(),
  z.object({ kind: z.literal('scheduleRuneforge'), forge: z.enum(['basic', 'epic']), onWave: z.number().int().positive().optional(), gold: z.number().int().nonnegative().optional() }).strict(),
  z.object({ kind: z.literal('multi'), rewards: z.array(QuestRewardSchema).min(1) }).strict(),
]));

/** Rune definition schema — same reward palette as quests, plus a Gold cost + display text. `epic` /
 *  `requiresDoublePower` mark Epic-forge runes and their hero-power eligibility gate. */
export const RuneDefSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  // Non-negative, not positive: a FREE rune is a real design point (Rune of the Tip Jar, 2026-08-19 — 0 Gold
  // for 4 Gold and +4 max). The Runeforge already handles a 0 cost; only this bound said otherwise.
  cost: z.number().int().nonnegative(),
  text: z.string().min(1),
  reward: QuestRewardSchema,
  epic: z.boolean().optional(),
  sets: z.array(z.enum(['set1', 'set2'])).readonly().optional(),
  requiresDoublePower: z.boolean().optional(),
  previewCards: z.array(z.string().min(1)).optional(),
}).strict();

export const QuestDefSchema = z.object({
  sets: z.array(z.enum(['set1', 'set2'])).readonly().optional(),
  id: z.string().min(1),
  name: z.string().min(1),
  tribe: TribeSchema,
  tier: QuestTierSchema,
  objective: z.object({
    event: QuestObjectiveEventSchema,
    count: z.number().int().positive(),
    tribe: TribeSchema.optional(),
    filter: z.literal('shout').optional(),
    parts: z.array(z.object({
      event: QuestObjectiveEventSchema,
      count: z.number().int().positive(),
      tribe: TribeSchema.optional(),
    }).strict()).min(2).optional(),
  }).strict(),
  reward: QuestRewardSchema,
  wave: z.union([z.literal(5), z.literal(11)]).optional(),
  repeatable: z.boolean().optional(),
  heroQuest: z.string().min(1).optional(),
  variantGroup: z.string().min(1).optional(),
}).strict();
