/**
 * BEAT SYSTEM — the presentation-policy registry (PR 1). GENERATED 2026-08-12 from the live content surface,
 * then hand-adjusted; regenerate deliberately, never blindly (hand adjustments live here).
 *
 * Every automatic effect in the game is classified here — 654 entries. `flagged: true` marks entries
 * where the heuristic default deserves an owner look (the PR-1 review workflow). The coverage tripwire lives
 * content-side (`presentationPolicies.test.ts`): an unclassified new effect FAILS CI, a silent entry without
 * a reason fails, and a registry key no live content produces fails (no ghosts).
 */
import type { PresentationPolicy, PresentationPolicyEntry } from './types';

export const PRESENTATION_POLICIES: Record<string, PresentationPolicyEntry> = {
  // ── CARD EFFECTS — factory × trigger (heuristic default by trigger; flagged = owner review) ──
  'factory:addFodderNextShops:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:addTavernFodder:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:avengeAddFodder:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeBonusGold:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeBuffImps:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeCopyLeftmostHandSpell:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeGiveAttack:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeGrantRandomSpell:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeGrantSpell:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeGrantSpellPower:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeImproveSummon:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeImproveSummonBuff:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeMaxGold:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengePlayRubies:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeShieldAttack:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeSummon:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeSummonAttack:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:avengeGrantRandomTribeMinion:avenge': { policy: 'ownBeat', family: 'avenge' }, // Grobbus
  'factory:avengeSummonImps:avenge': { policy: 'ownBeat', family: 'avenge' },
  'factory:battlecryAllDemonsConsume:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryArmGrimoire:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBonusGoldNextTurn:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:battlecryBonusGoldNextTurn:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffFodder:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:battlecryBuffFodder:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffImps:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffMagnetics:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffSpellPower:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:battlecryBuffSpellPower:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffTarget:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffTargetPerGoldSpent:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffTribe:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffTribeOthersAttack:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryBuffUndeadAttack:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryCastTaughtSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryConsumeShopRandom:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryCopyCastSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryCopyEcho:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryDestroyForSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryDiscoverMinion:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryDiscoverSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryDoubleNextSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGainGoldNextTurn:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGainKeyword:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGainRandomMinion:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGainRandomMinion:onSell': { policy: 'ownBeat', family: 'economy' },
  'factory:battlecryGetRubies:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGildTarget:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantBeastHunt:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantBeastRitual:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantFirstSpellMult:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantKeyword:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantMinion:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantRandomSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantRandomSpell:onSell': { policy: 'ownBeat', family: 'economy' }, // River Drake: sell → a random Spell
  'factory:battlecryGrantShoutExtra:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantSpell:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryGrantSpell:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' }, // Gemline Martyr -> Veinstorm
  'factory:endOfTurnCastSpellOnSelf:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' }, // Arnold -> Beefy
  'factory:battlecryGrantSpell:startOfTurn': { policy: 'ownBeat', family: 'economy' }, // Fel Conjurer: turn opens with a Quick Study
  'factory:battlecryGrantSpellPowerRun:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryPlayRubiesAll:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryScoutSpread:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryConductorAdjacent:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecrySummon:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryTargetConsumesShop:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:battlecryTriggeredOwnDeathrattle:battlecryTriggered': { policy: 'foldedCue', family: 'shoutReact' },
  'factory:buffBoardOnBuy:onBuy': { policy: 'foldedCue', family: 'economyReact' },
  'factory:buffFodderImpsImproving:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:buffRightmostSlotPermanent:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:buffShopPermanent:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:buffShopPermanent:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:buffShopPermanent:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:cardsBoughtGrantRandomSpell:cardsBought': { policy: 'ownBeat', family: 'economy' },
  'factory:castSpell:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:combatGrantAle:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:combatGrantAle:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:conjureTribeArmy:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:copyLeftmostEcho:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:copyLeftmostEcho:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:countTribeSummon:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:damagedGetRubies:onDamaged': { policy: 'foldedCue', family: 'react' },
  'factory:deathrattleBuffAll:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffAllByImpAura:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffAllHealth:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffCardTypeRunWide:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffShopPermanent:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffCelestials:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffImps:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffNextSummon:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffRightmostSlot:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleBuffTribe:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleCastLastSpell:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleCastTribeAttack:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleDamageAll:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleDestroyKiller:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGainRandomMinion:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGiveHealth:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantCardToHand:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantMagnetic:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantReborn:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantRebornAll:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantShield:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantSpell:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleGrantWardRandom:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleMaxGold:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattlePlayRubiesTribe:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleReplayAdjacentBattlecry:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleRubyStatGain:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleSummon:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleSummonGolemsWithRuby:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleSummonOverflowBuff:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleSummonRandomTribe:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleSummonRandomTribeSetStats:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleSummonRubyStats:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:deathrattleTriggerAdjacentRally:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:echoCastRememberedSpells:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:echoResummonDeadBeasts:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:echoSummonCopyNoEcho:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:echoSummonInheritAttackAndCharge:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:endOfTurnAdjacentConsumeFodder:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnBonusGold:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnBuffEndsTribePerCard:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnBuffSpellsAndImps:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnBuffWeakestDragon:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnCopyCastSpell:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnCopyNeighbour:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnFeastConsume:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:consumeShopRightmost:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' }, // Bob Blart (2026-08-14)
  'factory:endOfTurnGetRandomSpells:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnGetRubies:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnGrantRandomTierCard:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnGrantSpellChoice:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnGrantTribe:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnMagnetizeMechs:battlecryTriggered': { policy: 'ownBeat', family: 'shoutPayoff', reason: 'attaches Attachments in response to a Shout; discrete payoff' },
  'factory:endOfTurnMagnetizeMechs:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnPlayRuby:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnRecastFirstSpell:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:endOfTurnTriggerAdjacentShouts:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:gainEmbers:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:gainMaxMana:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:getEchoAndTrigger:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:getRubies:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:getRubies:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:goldSpentBuffFodder:cardsBought': { policy: 'foldedCue', family: 'economyReact' },
  'factory:goldSpentGetRubiesPlayOnTribe:goldSpent': { policy: 'ownBeat', family: 'economy' }, // Mountainbond (2026-08-14)
  'factory:goldSpentBuffRightmostSlot:goldSpent': { policy: 'foldedCue', family: 'economyReact' },
  'factory:goldSpentBuffTribeAttack:goldSpent': { policy: 'foldedCue', family: 'economyReact' },
  'factory:goldSpentGrantTribeMinion:goldSpent': { policy: 'ownBeat', family: 'economy' },
  'factory:goldSpentMagnetize:cardsBought': { policy: 'foldedCue', family: 'economyReact' },
  'factory:grantFreeRolls:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:grantMagePupTaught:spellBought': { policy: 'ownBeat', family: 'economy' },
  'factory:grantRandomAle:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:grantRandomAle:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:grantRandomAle:goldSpent': { policy: 'ownBeat', family: 'economy' },
  'factory:grantRandomAle:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:impInheritOnDeath:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:impInheritOnSummon:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:minionSoldGrantSpell:minionSold': { policy: 'ownBeat', family: 'economy' },
  'factory:onAllyAttackBuffAll:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onAllyAttackCastGrowth:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onAllyTribeAttackBuffSelf:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onAttackStripKeywords:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onBattlecryBuffFodder:battlecryTriggered': { policy: 'foldedCue', family: 'shoutReact' },
  'factory:onBattlecryBuffSelf:battlecryTriggered': { policy: 'foldedCue', family: 'shoutReact' },
  'factory:onBattlecryBuffSelf:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:onBattlecryBuffTribe:battlecryTriggered': { policy: 'foldedCue', family: 'shoutReact' },
  'factory:onBattlecryRearmGrimoire:battlecryTriggered': { policy: 'ownBeat', family: 'shoutPayoff', reason: 'triggers nested Shouts to reset; discrete payoff' },
  'factory:onDamagedGainAttack:onDamaged': { policy: 'foldedCue', family: 'react' },
  'factory:onDamagedGrantRefresh:onDamaged': { policy: 'foldedCue', family: 'react' },
  'factory:onFriendDeathSummon:onDeath': { policy: 'ownBeat', family: 'echo' },
  'factory:onFriendlyAttackBuffTribe:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onGainAttackBuffImproving:onGainAttack': { policy: 'foldedCue', family: 'react' },
  'factory:onGainAttackImproveHpGrant:onGainAttack': { policy: 'foldedCue', family: 'react' },
  'factory:onImpAttackBuffImps:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onKillBuffFodder:onKill': { policy: 'ownBeat', family: 'slaughter' },
  'factory:onKillBuffSpellPower:onKill': { policy: 'ownBeat', family: 'slaughter' },
  'factory:onKillBuffUndeadAttack:onKill': { policy: 'ownBeat', family: 'slaughter' },
  'factory:onKillGrantAttachmentRefreshes:onKill': { policy: 'ownBeat', family: 'slaughter' },
  'factory:onKillGrantGold:onKill': { policy: 'ownBeat', family: 'slaughter' },
  'factory:onMinionSoldCopyFirstOfTribe:minionSold': { policy: 'ownBeat', family: 'economy' },
  'factory:onOrbitBuffAll:orbitFired': { policy: 'foldedCue', family: 'orbitReact' },
  'factory:onOrbitBuffShop:orbitFired': { policy: 'foldedCue', family: 'orbitReact' },
  'factory:onOrbitBuffShopRightmost:orbitFired': { policy: 'foldedCue', family: 'orbitReact' },
  'factory:onOtherDemonConsumeEcho:onConsume': { policy: 'foldedCue', family: 'react' },
  // ── Set 2 batch B (2026-08-18): new primitives ──
  'factory:onFriendlyDemonDamageBuffSelf:friendlyDemonDealtDamage': { policy: 'foldedCue', family: 'react' }, // Impossible Todd / Leech / Axeman
  'factory:scPlayRubiesSelfAndAdjacentTribe:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' }, // Kobe
  'factory:rallyPlayRubiesSelf:onAttack': { policy: 'ownBeat', family: 'rally' }, // Boulderdash
  'factory:rallyPlayRubiesAll:onAttack': { policy: 'ownBeat', family: 'rally' }, // Blazer
  'factory:onSellGetRubies:onSell': { policy: 'ownBeat', family: 'economy' }, // Beggy
  'factory:goldSpentBuffRandomTribe:goldSpent': { policy: 'foldedCue', family: 'economyReact' }, // Billings
  'factory:onGainCardBuffTribe:onGainCard': { policy: 'foldedCue', family: 'economyReact' }, // Gangplank
  'factory:minionSoldConsumeRightmost:minionSold': { policy: 'ownBeat', family: 'economy' }, // Grevlin & Co.
  'factory:onConsumeBuffShop:onConsume': { policy: 'foldedCue', family: 'react' }, // Enigma
  'factory:deathrattleDamageAllExceptTribe:onDeath': { policy: 'ownBeat', family: 'echo' }, // Fel Spikes
  'factory:avengeRubyStatGain:avenge': { policy: 'ownBeat', family: 'avenge' }, // Gem Portsmith (first live user)
  'factory:onRallyBuffOnePerTribe:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onRallyPlayRubiesTribe:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onRallyProcLeftmostEcho:onAttack': { policy: 'ownBeat', family: 'rally' }, // Hawkus
  'factory:onSellDiscover:onSell': { policy: 'ownBeat', family: 'economy' },
  'factory:onSellGainGold:onSell': { policy: 'foldedCue', family: 'economyReact' },
  'factory:onShopRefreshGainRightmostShopStats:shopRefreshed': { policy: 'ownBeat', family: 'economy' }, // Hellrider (2026-08-14)
  'factory:onSpellCastBuffOnePerTribe:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:onSpellCastBuffRandomTribe:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:onSpellCastFirstBuffSelf:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:onSpellCastImproveSummon:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:onSpellCastOnThisRecast:spellCastOnThis': { policy: 'ownBeat', family: 'economy' },
  // Reflector (Yirin's token) — same shape as the recast above: a second cast the player should SEE land.
  'factory:onSpellCastOnThisSpreadRandom:spellCastOnThis': { policy: 'ownBeat', family: 'economy' },
  // Reflector also bounces a played Ruby to a random friendly (owner balance 2026-08-18) — same beat as the spell spread.
  'factory:onRubyPlayedSpreadRandom:onRubyPlayed': { policy: 'ownBeat', family: 'economy' },
  'factory:onSpellCastSecondCopyFirst:spellCast': { policy: 'ownBeat', family: 'castPayoff', reason: 'discrete payoff fired immediately after the cast; near-zero windup' },
  'factory:onSummonImpBuff:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:onSummonOverflowBuffTribe:summonOverflow': { policy: 'foldedCue', family: 'react' },
  'factory:onSummonSelfBuff:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:onSummonTribeBuffFlat:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:onSummonTribeBuffThenDouble:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:onTribeAttackBuffAttacker:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onTribePlayedBuffSelfPerSpell:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:onTribePlayedConsumeShop:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:onTribeSummonedBuffTribe:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:orbitBuffAlignedCelestials:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitBuffArriver:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitBuffCelestialsPerBuffStack:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitBuffLowest:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitBuffRandomFriend:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitBuffSelf:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitCastSpell:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitDevourArriver:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitGainArriverBonus:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitGrantSpellPower:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:orbitSellValue:orbit': { policy: 'ownBeat', family: 'orbit' },
  'factory:overflowBuffRandom:summonOverflow': { policy: 'foldedCue', family: 'react' },
  'factory:rallyBuff:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyBuffAttachments:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyBuffCelestials:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyBuffSelf:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyBuffSelfPerTribe:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyBuffShopPermanent:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyCastNamedSpell:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyCastShopBuffSpell:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyCastSpell:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGrantRandomShoutMinion:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyTriggerTribeShouts:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:onTribeAttackCastNamedSpell:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyCastTribeAttack:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyDamageRandomEnemy:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGetRubies:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGiveAttackToOthers:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGiveHealthToDragons:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGrantMagnetic:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGrantSelfCopy:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGrantSpell:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyGrantSpellPower:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyProcDeathrattle:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyProcLeftmostEcho:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyRubyStatGain:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallySpreadTribeBuff:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallySummonImpBuffImps:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rallyTribeAuraGrowing:onAttack': { policy: 'ownBeat', family: 'rally' },
  'factory:rubyCastConsumeShop:rubyCast': { policy: 'ownBeat', family: 'economy' },
  'factory:rubyGainedCast:onGetRuby': { policy: 'foldedCue', family: 'economyReact' },
  'factory:rubyPlayedBounce:onRubyPlayed': { policy: 'foldedCue', family: 'economyReact' },
  'factory:rubyPlayedGold:onRubyPlayed': { policy: 'foldedCue', family: 'economyReact' },
  'factory:rubyStatGain:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:rubyStatGain:onPlay': { policy: 'ownBeat', family: 'shout' },
  'factory:rubyStatMultiplier:passive': { policy: 'passive', family: 'passive' },
  'factory:scArmBleed:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scBeastAura:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scBuffAlliesPctSelf:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scBuffSelf:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scCastLeftmostHandSpell:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scDamage:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scEngraveAll:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scTriggerLeftmostEchoes:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' }, // Spots
  'factory:scEngraveNeighbor:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scGainFodderStats:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scGainKeyword:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scGrantEnemyTaunt:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scGrantReborn:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scGrantSpellCastExtra:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scSummonCopy:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scTribeBuffImproving:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scBuffRandomTribePerAle:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' }, // Drunken Oaf
  'factory:scTribeBuffPerAle:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:scTribeBuffPerSpellImproving:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:setArmor:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellAddAllTribes:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellAttackFirst:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellAverageStats:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBloodlust:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffAll:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffByTier:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffImpsPerDemon:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffLeftmost:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffPerDragonPlayed:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffRandomFriendlies:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffRandomPerTribe:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffHealthGrantFlurryDragon:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffShop:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffShopByRuby:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffTarget:cast': { policy: 'ownBeat', family: 'spellCast' },
  // GREAT POT + the GIFTS (owner batch 2026-08-26) — each casts from hand, so each owns its beat.
  'factory:buffOnePerTribe:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftGrandLarceny:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftIroncladFavor:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftMinionDiscountTurn:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftPartingGifts:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftRegalia:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftRoyalAllowance:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftSecondCalling:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftShopBuffGame:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftShoutExtraTurn:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftSpellDiscountTurn:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftTierAboveMinion:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftUnbridledMight:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:giftUpgradeDiscount:cast': { policy: 'ownBeat', family: 'spellCast' },
  // Owner spell batch 2026-08-15 — both are ordinary shop casts: they resolve immediately and their result is
  // the display (stats landing on bodies / a card arriving in hand), so they share the spellCast family.
  'factory:spellBuffTargetAndNeighbours:cast': { policy: 'ownBeat', family: 'spellCast' },
  // Owner combat-spell batch 2026-08-15 — each ARMS a next-combat effect; the cast itself is the beat.
  'factory:spellMarkPartingCry:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellMarkClosedCasket:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellSolidGround:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellContainFirstEnemySummon:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellStolenInitiative:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGambleTierPull:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffTargetEscalating:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffTargetPerGold:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellBuffTavern:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellCastBuffAll:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:spellCastBuffOthers:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:spellCastBuffUndeadAttack:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:spellCastDemonConsumesShop:spellCast': { policy: 'ownBeat', family: 'castPayoff', reason: 'discrete payoff fired immediately after the cast; near-zero windup' },
  'factory:spellCastImproveSelf:spellCast': { policy: 'foldedCue', family: 'castReact' },
  'factory:spellCastTransform:spellCast': { policy: 'ownBeat', family: 'castPayoff', reason: 'discrete payoff fired immediately after the cast; near-zero windup' },
  'factory:spellCastTriggerAdjacentShouts:spellCast': { policy: 'ownBeat', family: 'castPayoff', reason: 'triggers a nested Shout right after the cast; near-zero windup' },
  'factory:spellCopyRecent:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:spellCopyTargetExact:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellDecoyNextCombat:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellDemonConsumeFodder:cast': { policy: 'ownBeat', family: 'spellCast' },
  // Power Shifter: the Discover it opens IS the beat — the player acts inside it.
  'factory:spellPowerShift:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellDevour:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellDiscoverFromLastOpponent:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellDisplace:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellExtraEndOfTurn:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGainOfTargetTribe:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGainRandomMinion:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGainSpellPower:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGildRandomTavern:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGildTarget:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGoldIfLostLast:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGrantKeywordNextCombat:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellTauntNextSummons:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGrantTopTypeMinion:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellGrantTribeAttack:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellLayaway:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellMarkEnemyTaunt:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellNextSellBonus:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellPendingSCBuff:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellPlayRubiesAll:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellRallyDoubleNext:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellRefreshTierUp:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellRefreshToSpells:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellRefreshToTribe:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellReplayBattlecry:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellReturnToHand:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellScoutNextOpponent:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellSellToBeast:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellSellToDemon:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellSetStats:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellStealAdjacentRubies:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellStealShop:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellSummonImpsNextCombat:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellSwapStats:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellTargetConsumesShop:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellTransformSameTier:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellTriggerEcho:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:spellWeakenNextCombat:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:stealTavernMinion:cast': { policy: 'ownBeat', family: 'spellCast' },
  'factory:summonBuffSelfTribe:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:summonBuffTribeAsym:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:summonBuffTribeImprove:onSummon': { policy: 'foldedCue', family: 'summonReact' },
  'factory:summonImps:startOfCombat': { policy: 'ownBeat', family: 'startOfCombat' },
  'factory:triggerAdjacentOrbits:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'factory:triggerAdjacentOrbits:onPlay': { policy: 'ownBeat', family: 'shout' },

  // ── RUNES — bucketed by reward mechanics ──
  'rune:rune_abomination:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_action:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_adventuring:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_aftermarket:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_aftershocks:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_altar:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_ancestral_roar:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_ancient_den:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_ancient_expenditure:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_appraisal:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_armory:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_ascension:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_ashen_heir:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_ashen_payroll:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_assembly:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_attacking_gems:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_baal:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_backbeat:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_banking:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_banquet_hall:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_bargain_bin:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_bartering:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_beastial_swarm:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_blart:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_blood_and_coin:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_borrowed_echoes:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_bottomless_cask:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_bottomless_portrait:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_brew:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_brisbane:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_brood:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_broodpit:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_bucky:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_burrow:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_cadence:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_carrion_coin:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_centerline:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_champion:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_chef:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_chimerus:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_choir:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  // 2026-08-19 owner rune batch.
  'rune:rune_chipper_sticker:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_clockwork_promotion:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_compounding_wages:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_deathtouched_apple:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_deep_feast:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_deepening_vein:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_delayed_duplication:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_draconic_curiosity:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_dragons_pantry:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_echoed_arrival:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_gem_sage:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_gilded_ledger:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_grave_refreshment:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_heavy_payroll:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_held_strength:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_kegheart:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_living_magic:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_might:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_muckbroker:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_muster_general:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_night_market:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_ninefold_commerce:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_perfect_recall:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_rare_goods:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_returning_pack:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_rising_echoes:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_baller:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_bubble_crown:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_herding_horn:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_seasoned_ledger:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_shared_spoils:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_shifting_facets:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_war_drum:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_wishbone:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_basic_beast:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_basic_demon:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_basic_dragon:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_basic_dwarf:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_basic_kobold:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_blasting_voices:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_catacomb:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_dragon_breath:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_drake_skull:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_epic_beast:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_epic_demon:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_epic_dragon:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_epic_dwarf:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_epic_kobold:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_glider:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_hoardflame:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_ornate_clock:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_pendant:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_engraving_gems:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_ruins:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_refraction:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_ruby_resonance:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_chorus:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_cinder_ledger:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_cindergem:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_coffers:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_collector:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_conductor:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_conduit:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_consumption:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_contraband:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_copies:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_copycat:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_corrupted_tome:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_counterpoint:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_crown:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_crucible:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_crucible_choir:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_dawnclaw:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_deep:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_den_mother:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_display_case:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_distillation:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_double_fisting:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_dragonscale:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_duplication:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_emberline:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_empty_plate:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_enchantment:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_endless_appetite:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_engraving:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_epic_forge:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_evolution:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_exgalloper:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_facetwright:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_feast:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_finality:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_first_claws:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_first_round:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_five_banners:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_flagship:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  // rune_flooded_vault archived 2026-08-18 (ARCHIVED_RUNES) — entry removed so the registry carries no ghost.
  'rune:rune_food_chain:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_forthcoming:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_foundry:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_fresh_pages:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_frontline_glory:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_full_measure:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_fury:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_gem_dividend:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_gem_golem:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_gemcutting:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_gemscript:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_gemspam:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_gemstorm:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_gilded_spark:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_golden_splinter:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_guiding_candle:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_hatchery:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_herald:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_herzog:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_high_king:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_hoardcalling:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_hunger:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_hunting_bell:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_infernal_ink:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_inheritance:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_investment:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_jungle:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_kindling:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_kobold_bebes:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_lapidary:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  // Rune of Lasting Cadence: ONE BEAT PER RALLY (see `runeLastingCadenceBeats`) — each rally is a real
  // trigger sourced on the minion whose Rally fires, so it must own its window rather than fold into a cue.
  'rune:rune_lasting_cadence:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  // Rune of Combat Prowess: ONE BEAT PER Start-of-Combat effect (see `runeCombatProwessBeats`) — each fire
  // is a real trigger sourced on the acting minion, so it owns its window rather than fold into a cue.
  'rune:rune_combat_prowess:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_lassoing:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_last_call:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_last_word:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_lazarus:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_liquidation:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_living_echoes:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_living_geode:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_living_growth:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_living_treasure:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_long_shift:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_happy_birthday:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_merry_christmas:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_lorekeeping:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_mastery:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_menagerie:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_menagerie_set2:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_merchants_chorus:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_mirror_march:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_moonhowl:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_motherlode:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_mountain_trade:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_muster:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_old_pack:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_open_appetite:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_open_enrollment:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_open_market:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_overflow:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_overtime:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_packcraft:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_pair:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_pillaging:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_procession:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_profit_sharing:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_quick_study:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_rallying:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_rebirth:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_recollection:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_reconfiguration:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_recurrence:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_redirection:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_refrain:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_reinvestment:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_reliquary:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_replication:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_resonance:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_restocking:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_rising_graves:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_ruby_shrapnel:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_runic_exchange:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_runic_hoard:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_salvage:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_savagery:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_scale:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_scales:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_scout:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_second_litter:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_second_path:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_sellers_market:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_shared_pour:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_shared_reflection:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_shared_scripture:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_shared_table:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_shopkeep:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_showcase:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_slaying:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_small_fortune:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_soul_taxes:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_spare_chair:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_spare_parts:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_spearline:combat': { policy: 'ownBeat', family: 'avenge' },
  'rune:rune_spellmarket:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_spellslinging:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_spellstone:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_spending:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'rune:rune_stampede:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_stormcalling:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_strange_caravan:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_structure:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_summit:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_summoning:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_sylus:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_taurus:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_tempered_time:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_tempering:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_thrift:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_tip_jar:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_top_hat:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_trade_in:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_transcription:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_transfusion:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_treasure_map:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_trophy:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_twilight:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_twin_gilding:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_unbroken_vein:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_underdog:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_stoked_menagerie:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_embers:recruit': { policy: 'foldedCue', family: 'shopEconomy' },
  'rune:rune_refreshments:recruit': { policy: 'foldedCue', family: 'shopEconomy' },
  'rune:rune_undertow:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_vanguard:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_vault:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_voidmother:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_war_chorus:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_warden:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_warding:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_warpath:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_wheel:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_white_wolf:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_wild_hunt:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'rune:rune_window_shopping:recruit': { policy: 'ownBeat', family: 'runeMechanic' },
  'rune:rune_yazzus:onAcquire': { policy: 'ownBeat', family: 'rewardGrant' },
  'rune:rune_zoo:combat': { policy: 'foldedCue', family: 'combatModifier' },

  // ── QUESTS — bucketed by reward mechanics ──
  'quest:q_ancient_runes:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_anomalous_reactor:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_apex_hunt:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_assembly_line:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_attachment_issues:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_banes_existence:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_banes_presence:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_barroom_bounty:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_blood_trail:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_blueprint_cache:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'quest:q_bone_ledger:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_bottomless_banquet:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_bottomless_cellar:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_burning_legion:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_candlelight_toll:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_chimerus:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_clinging_on:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'quest:q_coin_hoard:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_company_recruitment:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_company_store:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_contract_rewrite:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_cratering_missive:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_dark_bargain:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_death_writes_twice:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_deep_hunger:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_den_marker:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_dupes:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_echo_chamber:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_echoing_coop:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_echoing_roar:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'quest:q_empty_graves:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_endless_inventory:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_endless_verse:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_epic_commission:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_faultline_coronation:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_feed_the_alpha:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_feeding_line:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_first_blood:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_first_strike:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_food_for_gold:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_foragers_trail:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_forest_grove:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_forsaken_speed:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'quest:q_forsaken_will:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_fried_circuits:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_funeral_engine:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_gem_circuit:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_gilded_chance:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_golden_ledger:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_grave_contract:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_grave_robber:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_heart_of_the_mountain:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_hoard_spark:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_hoardwake_ritual:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_imp_census:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_implosion:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_impossible_shop:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_infinite_assembly:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_key_findings:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_kingdom_of_bones:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_law_of_teeth:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_leader_of_the_pack:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_machine_chorus:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_market_feast:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_maw_of_the_run:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_merchants_mark:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_motherlode:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_odd_jobs:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_open_tab:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'quest:q_open_the_vein:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_ossuary_rite:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_overclocked_core:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_pack_mentality:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_parliament_of_flame:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_passing_spears:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_perfect_machine:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_pit_without_end:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_pivot_door:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_rulebreakers_crown:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_runic_apprenticeship:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_runic_refrain:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },
  'quest:q_scrap_contract:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_sealed_vault:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_shared_circuit:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_shop_license:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_skybound_pact:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_small_offering:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_spark_permit:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_spell_thesis:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_stock_the_shelves:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_taragosas_inheritance:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_teleport_summit:onComplete': { policy: 'ownBeat', family: 'questReward' },
  // HERO QUESTS (Fi / Coran, 2026-08-21) — one payout each, at the end of a whole run's travelling.
  // `ownBeat` like every other quest completion: the reward lands on its own beat, not folded into the
  // action that happened to take the last step.
  'quest:hq_spare_forge:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_opening_act_shout:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_opening_act_echo:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_opening_act_rally:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_gilded_favor:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_first_pick:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_open_road:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_runic_passage:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_resonant_path_shout:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_resonant_path_echo:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_resonant_path_rally:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_gilded_shortcut:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_merchants_road:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:hq_summit_passage:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_the_bone_throne:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_the_old_hunt:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_the_red_trail:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_the_runeforge:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_trophy_den:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_true_contract:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_twin_sun_oath:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_umbral_energy:combat': { policy: 'foldedCue', family: 'combatModifier' },
  'quest:q_unstable_riches:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_war_council:onComplete': { policy: 'ownBeat', family: 'questReward' },
  'quest:q_warm_embers:onComplete': { policy: 'ownBeat', family: 'questReward' },
  // ── HERO POWERS (CHOREOGRAPHER PR 9). Heroes live in `@game/sim`, which the content-side surface cannot
  // import (content is a DEPENDENCY of sim, not the reverse) — so hero coverage is enforced sim-side by
  // `heroBeats.test.ts` instead, and the content ghost-check skips `hero:*`. Classified here so the key,
  // family and policy stay in ONE registry with everything else.
  'hero:repete:secondHand': { policy: 'ownBeat', family: 'heroPower' },

  // ── DERIVED / SYSTEM moments (CHOREOGRAPHER PR 7). Engine-derived payouts with no EffectDef of their own;
  // see `SYSTEM_SURFACE` in content. Each is an own beat because it is a visible thing happening TO the
  // board at the start of a fight, and the owner's report was precisely that it happened invisibly.
  'system:startOfCombat:fleetingVigor': { policy: 'ownBeat', family: 'startOfCombat' },
  'system:startOfCombat:pendingKeywords': { policy: 'ownBeat', family: 'startOfCombat' },
  'system:startOfCombat:pendingImps': { policy: 'ownBeat', family: 'startOfCombat' },
  // An End-of-Turn Discover that AUTO-resolves (Moira re-firing Black Belt Brian) grants a card at the combat
  // hand-off. Its own beat so the granted card coalesces into the hand DURING the End-of-Turn playback (like a
  // shop conjure) instead of snapping in at commit (owner report 2026-08-14).
  'system:eotDiscover:grant': { policy: 'ownBeat', family: 'grant' },
  // ── HEROES — hero:<id>:<power.kind> (DoD item 1b; heuristic classification, all flagged for owner review) ──
  // PR 22: Bag It is an ACTIVATED payout (click → Gold now, climbing each turn) — `passive` was
  // factually wrong; the reducer has an activation branch for it. Still flagged for the owner pass.
  // Rascal (id `baggerben`) moved from `scalingGold` to his own `allIn` on 2026-08-16. The old key is DELETED
  // rather than kept: policies are looked up by the LIVE hero's kind, so with no hero on `scalingGold` the key
  // is unreachable — which is exactly what the no-ghosts tripwire in heroPolicies.test.ts exists to catch.
  'hero:baggerben:allIn': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  // Yirin (id `rohan`) moved off `spellAmplify` on 2026-08-16; the old key is deleted for the same reason.
  'hero:rohan:startingReflector': { policy: 'passive', family: 'passive', flagged: true },
  // Cassen moved off `collision` on 2026-08-16; the old key is deleted for the same no-ghosts reason.
  'hero:cassen:commission': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  // Heroes batch 2026-08-17 (heuristic classification, flagged for owner review).
  'hero:devourer:devour': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:membrance:memory': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:flash:firstOrLast': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:juggler:baldgecoin': { policy: 'passive', family: 'passive', flagged: true },
  'hero:midas:midasTouch': { policy: 'passive', family: 'passive', flagged: true },
  'hero:brackus:summitLock': { policy: 'passive', family: 'passive', flagged: true },
  'hero:chaos:chaos': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:chronoshero:questChronos': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  // Fi & Coran's turn-1 quest Discover. `ownBeat` — it opens a modal the player acts in, which is a beat of
  // its own by definition. Replaced `hero:fi:lesserQuest` / `hero:coran:pathfinder` (2026-08-21).
  // 2026-08-22 hero batch. Rayse is a pure combat-side passive (the summon buff presents inside the replay);
  // Mimic and Void resolve through the power-Discover modal, a beat of its own by definition.
  'hero:rayse:empoweringVines': { policy: 'passive', family: 'passive', flagged: true },
  'hero:mimic:mimic': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:voidhero:voidTwin': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  // 2026-08-23 hero batch. Gorun and Cindara are combat-side passives that present INSIDE the replay (a buff
  // on the attacker, a summon + strike), so they ride the passive policy like Rayse. Aevor is the odd one:
  // it fires in the recruit phase's End-of-Turn engine and grants permanent stats between fights, so it gets
  // its own beat the way the other End-of-Turn payouts do — otherwise the board silently grows at turn end.
  'hero:aevor:tempest': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:gorun:bladeMastery': { policy: 'passive', family: 'passive', flagged: true },
  'hero:cindara:hoard': { policy: 'passive', family: 'passive', flagged: true },
  'hero:coran:heroQuest': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:fi:heroQuest': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:darah:displace': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:discodan:discoLock': { policy: 'passive', family: 'passive', flagged: true },
  'hero:djinn:replayAllEndOfTurn': { policy: 'ownBeat', family: 'heroReplay', flagged: true },
  'hero:drakko:quest': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:gildmaster:gildcrafter': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:gorr:fourPeat': { policy: 'foldedCue', family: 'heroReplay', flagged: true },
  'hero:hermithank:cheapMinions': { policy: 'passive', family: 'passive', flagged: true },
  'hero:indy:gild': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:jenkins:dynamiteDig': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:myra:replayBattlecry': { policy: 'foldedCue', family: 'heroReplay', flagged: true },
  'hero:nadja:gainMaxMana': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:fibbsy:rubyWealth': { policy: 'ownBeat', family: 'heroPower', flagged: true }, // Fibbsy: 1 Gold -> 2 Rubies, twice a turn
  'hero:risen:grantReborn': { policy: 'foldedCue', family: 'heroPayout', flagged: true },
  'hero:robin:sellGold': { policy: 'foldedCue', family: 'heroPayout', flagged: true },
  'hero:runeguard:epicRuneforge': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:runesmith:runeforge': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:soren:resummon': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  // PR 22: Dragon Tamer is an ACTIVATED Discover (click → pay shrinking cost → Discover a Dragon) —
  // `passive` was factually wrong. Still flagged for the owner pass.
  'hero:tiff:dragonTamer': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:warden:grantWard': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  // Heroes batch 2026-08-14 (heuristic classification, flagged for owner review).
  'hero:kindness:greatPresence': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:merrin:pocketMagic': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:gambler:dice': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:xerox:copyMachine': { policy: 'ownBeat', family: 'heroReplay', flagged: true },
  'hero:frank:clearance': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:pete:contraband': { policy: 'passive', family: 'passive', flagged: true },
  'hero:flint:companyRate': { policy: 'passive', family: 'passive', flagged: true },
  'hero:vale:unitedFront': { policy: 'passive', family: 'passive', flagged: true },
  'hero:quillen:archive': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:hunch:roundedSpellbook': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  // Heroes batch 2026-08-16 (heuristic classification, flagged for owner review).
  'hero:emeraldwarden:vanguard': { policy: 'passive', family: 'passive', flagged: true },
  'hero:underdweller:soulkeeper': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:albus:empowerment': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  // Heroes batch 2026-08-16b (heuristic classification, flagged for owner review).
  'hero:bram:investment': { policy: 'ownBeat', family: 'heroPayout', flagged: true },
  'hero:cia:luckySeat': { policy: 'passive', family: 'passive', flagged: true },
  'hero:odelle:exhibition': { policy: 'passive', family: 'passive', flagged: true },
  'hero:harlan:buyout': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:sable:soulbind': { policy: 'ownBeat', family: 'heroPower', flagged: true },
  'hero:keshi:crownTally': { policy: 'passive', family: 'passive' },
  // Aster the Guide (tutorial-only): an active, targeted +1/+1 — the same shape as Warden's grantWard.
  'hero:aster:preparation': { policy: 'ownBeat', family: 'heroPower' },

  // ── RUNE-ONLY MINION BATCH (2026-08-20). Each entry copies the bucket its closest sibling already sits in. ──
  'factory:onGetRubyDuplicate:onGetRuby': { policy: 'foldedCue', family: 'economyReact' },        // Gem Sage — cf. rubyGainedCast
  'factory:goldSpentScaleSelf:passive': { policy: 'passive', family: 'passive' },                 // Ancient Wanderer — a synced stat, never a beat
  'factory:buffShopOffersThisTurn:onBuy': { policy: 'foldedCue', family: 'economyReact' },        // Night Market Horror — cf. buffBoardOnBuy
  'factory:buffShopOffersThisTurn:spellBought': { policy: 'foldedCue', family: 'economyReact' },  // …its "a spell is a card too" half
  'factory:onSellDiscoverSingleton:onSell': { policy: 'ownBeat', family: 'economy' },             // Traveling Salesman — cf. onSellDiscover
  'factory:onGainAleBuffSelf:onGainCard': { policy: 'foldedCue', family: 'economyReact' },        // Kegheart Dwarf — cf. onGainCardBuffTribe
  'factory:onBuyGrantSpellSameTier:onBuy': { policy: 'ownBeat', family: 'economy' },              // Ninefold Broker — a card arrives, like onSellDiscover
  'factory:endOfTurnCopyLeftmostHandCard:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },  // Stonehorn Archivist — cf. endOfTurnCopyNeighbour
  'factory:endOfTurnTransformLeftTierUp:endOfTurn': { policy: 'ownBeat', family: 'endOfTurn' },   // Skybound Ascendant
  'factory:minionSoldDemonGainStats:minionSold': { policy: 'ownBeat', family: 'economy' }, // Arcane Behemoth — cf. minionSoldConsumeRightmost
  'factory:onFriendDeathGainEcho:onDeath': { policy: 'ownBeat', family: 'echo' },                 // Echo Mimic — cf. onFriendDeathSummon
  'factory:avengeSummonAttackImproving:avenge': { policy: 'ownBeat', family: 'avenge' },          // Muster General — cf. avengeSummonAttack
  'factory:rallyDoubleSelf:onAttack': { policy: 'ownBeat', family: 'rally' },                     // Evolving Abomination — cf. rallyBuffSelf
  // The WELDED rally payout (Better Bot's Mech Attack / Perfect Core's spell conjure) firing inside a SHOP
  // rally (Rune of Lasting Cadence's End-of-Turn dispatch). A reaction inside the rally's own beat — the
  // weld claims credit for its buffs/conjure without adding a pause, like combat folds it into the swing.
  'system:shopRally:weld': { policy: 'foldedCue', family: 'rally' },
};

/** Look up a key; undefined = unclassified (the tripwire's failure condition). */
export const presentationPolicyFor = (key: string): PresentationPolicyEntry | undefined => PRESENTATION_POLICIES[key];

/**
 * CHOREOGRAPHER (§7.1, and the "deriving families from source card ID" trap in §25): the ONE way an emitter
 * turns a registry key into the identity fields it stamps on its event. Emitters call this at the site where
 * the factory/rune/quest identity is still known, so `policyKey` + `family` + `policy` always agree with the
 * registry and presentation never has to reconstruct them from a display id.
 *
 * An unclassified key still yields a usable spread (the key is carried, `family` is absent) — the normalizer
 * then reports "missing family" as a diagnostic instead of the beat silently inheriting the wrong template.
 */
export function beatIdentity(policyKey: string, fallback: PresentationPolicy = 'ownBeat'): {
  policyKey: string;
  family?: string;
  policy: PresentationPolicy;
} {
  const entry = PRESENTATION_POLICIES[policyKey];
  return { policyKey, ...(entry ? { family: entry.family } : {}), policy: entry?.policy ?? fallback };
}
