import type { CardDef } from '@game/core';

/**
 * Set 2's DEMON tribe (owner roster 2026-07-25). The tribe's identity is **Consume from the Shop** — eight cards
 * eat a tavern minion for its stats — braided with an **Imp** swarm line. Set 1's Demons consume FODDER; these
 * eat any Shop minion, which is what `consumeShopMinion` adds.
 *
 * A recurring Gilded rider, "and gain double its stats", is the shared primitive's `times` multiplier rather than
 * a separate effect — so the golden text is a number change, not a second code path.
 */
export const SET2_DEMONS: CardDef[] = [
  {
    // The tribe's Tier-1 statement of intent: a 1/1 that turns a tavern minion into stats.
    id: 'dm_clerk',
    name: 'Cinder Clerk',
    tribe: 'demon',
    tier: 1,
    attack: 1,
    health: 1,
    keywords: [],
    effects: [{ on: 'onPlay', do: 'battlecryConsumeShopRandom', params: { times: 1 } }],
    text: '**Shout:** Consume a minion in the Shop.',
    goldenText: '**Shout:** Consume a minion in the Shop and gain **double** its stats.',
  },
  {
    id: 'dm_wrangler',
    name: 'Imp Wrangler',
    tribe: 'demon',
    tier: 1,
    attack: 2,
    health: 1,
    keywords: [],
    effects: [{ on: 'startOfCombat', do: 'summonImps', params: { count: 1 } }],
    text: '**Start of Combat:** summon an **Imp**.',
    goldenText: '**Start of Combat:** summon **2 Imps**.',
  },
  {
    id: 'dm_butcher',
    name: 'Contract Butcher',
    tribe: 'demon',
    tier: 2,
    attack: 2,
    health: 3,
    keywords: [],
    effects: [{ on: 'onPlay', do: 'buffShopOffers', params: { attack: 1, health: 1 } }],
    text: '**Shout:** give minions in the Shop **+1/+1**.',
    goldenText: '**Shout:** give minions in the Shop **+2/+2**.',
  },
  {
    // Flurry doubles the Rally, so this makes two Imps a turn on its own.
    id: 'dm_errand',
    name: 'Errand Fiend',
    tribe: 'demon',
    tier: 2,
    attack: 1,
    health: 3,
    keywords: ['W', 'RL'],
    effects: [{ on: 'onAttack', do: 'summonImps', params: { count: 1 } }],
    text: '**Flurry. Rally:** summon an **Imp**.',
    goldenText: '**Flurry. Rally:** summon **2 Imps**.',
  },
  {
    // The eater is the TARGET, not this card — so it can feed whichever body you want to grow.
    id: 'dm_agent',
    name: 'Appetite Agent',
    tribe: 'demon',
    tier: 3,
    attack: 3,
    health: 2,
    keywords: [],
    target: 'friendly',
    effects: [{ on: 'onPlay', do: 'battlecryTargetConsumesShop', params: { count: 1 } }],
    text: '**Shout:** target a minion. It Consumes a minion in the Shop.',
    goldenText: '**Shout:** target a minion. It Consumes **2** minions in the Shop.',
  },
  {
    id: 'dm_hungerling',
    name: 'Hungerling',
    tribe: 'demon',
    tier: 3,
    attack: 3,
    health: 3,
    keywords: [],
    effects: [{ on: 'endOfTurn', do: 'consumeShopRightmost', params: { times: 1 } }],
    text: '**End of Turn:** Consume the **right-most** Shop minion.',
    goldenText: '**End of Turn:** Consume the **right-most** Shop minion and gain **double** its stats.',
  },
  {
    // PERMANENT, so it goes through the run-wide per-card channel rather than the per-offer one — the buff
    // follows that card for the rest of the run instead of dying on the next refresh.
    id: 'dm_tormentor',
    name: 'Market Tormentor',
    tribe: 'demon',
    tier: 3,
    attack: 3,
    health: 4,
    keywords: [],
    effects: [{ on: 'onPlay', do: 'battlecryBuffRightmostShopPermanent', params: { attack: 4, health: 4 } }],
    text: '**Shout:** give the **right-most** minion in the Shop **+4/+4** permanently.',
    goldenText: '**Shout:** give the **right-most** minion in the Shop **+8/+8** permanently.',
  },
  {
    id: 'dm_drillmaster',
    name: 'Pit Drillmaster',
    tribe: 'demon',
    tier: 3,
    attack: 4,
    health: 4,
    keywords: [],
    effects: [{ on: 'onPlay', do: 'battlecryBuffImps', params: { attack: 2, health: 0 } }],
    text: '**Shout:** give your **Imps +2 Attack** wherever they are.',
    goldenText: '**Shout:** give your **Imps +4 Attack** wherever they are.',
  },
  {
    id: 'dm_riotcaller',
    name: 'Riot Caller',
    tribe: 'demon',
    tier: 3,
    attack: 2,
    health: 5,
    keywords: ['RL'],
    effects: [{ on: 'onAttack', do: 'rallyImpsAttackNow', params: { count: 1 } }],
    text: '**Rally:** your **left-most Imp** attacks immediately.',
    goldenText: '**Rally:** your **2 left-most Imps** attack immediately.',
  },
  {
    // An escalating shop buff: the longer it lives, the bigger every offer gets.
    id: 'dm_curator',
    name: 'Display Curator',
    tribe: 'demon',
    tier: 4,
    attack: 5,
    health: 3,
    keywords: [],
    effects: [{ on: 'endOfTurn', do: 'buffShopOffers', params: { attack: 1, health: 1, improve: 1 } }],
    text: '**End of Turn:** give minions in the Shop **+1/+1**. Improves by **+1/+1** each time this triggers.',
    goldenText: '**End of Turn:** give minions in the Shop **+2/+2**. Improves by **+2/+2** each time this triggers.',
  },
  {
    // A Demon eats every time you play a Demon — the tribe's engine card.
    id: 'dm_glutton',
    name: 'Selective Glutton',
    tribe: 'demon',
    tier: 4,
    attack: 4,
    health: 4,
    keywords: [],
    effects: [{ on: 'onSummon', do: 'onTribePlayedConsumeShop', params: { tribe: 'demon', times: 1 } }],
    text: 'Whenever you play a **Demon**, a friendly Demon Consumes a minion in the Shop.',
    goldenText: 'Whenever you play a **Demon**, a friendly Demon Consumes a minion in the Shop and gains **double** its stats.',
  },
  {
    id: 'dm_broodwright',
    name: 'Broodwright',
    tribe: 'demon',
    tier: 4,
    attack: 3,
    health: 6,
    keywords: [],
    effects: [
      { on: 'onSummon', do: 'onSummonImpBuff', params: { attack: 2, health: 2 } },
      { on: 'avenge', do: 'avengeImproveSummonBuff', params: { count: 3, step: 1 } },
    ],
    text: 'Whenever you summon an **Imp**, give it **+2/+2**. **Avenge (3):** improve this by **+1/+1**.',
    goldenText: 'Whenever you summon an **Imp**, give it **+4/+4**. **Avenge (3):** improve this by **+2/+2**.',
  },
  {
    id: 'dm_captain',
    name: 'Cinderwall Captain',
    tribe: 'demon',
    tier: 4,
    attack: 5,
    health: 2,
    keywords: [],
    effects: [{ on: 'onSummon', do: 'onSummonImpWard', params: { count: 2 } }],
    text: '**Start of Combat:** the first **2 Imps** you summon gain **Ward**.',
    goldenText: '**Start of Combat:** the first **4 Imps** you summon gain **Ward**.',
  },
  {
    // Takes the stats WITHOUT eating — the offer stays buyable, which is the difference from Hungerling.
    id: 'dm_gourmand',
    name: 'Grand Gourmand',
    tribe: 'demon',
    tier: 5,
    attack: 5,
    health: 5,
    keywords: [],
    effects: [{ on: 'endOfTurn', do: 'endOfTurnGainRightmostShopStats', params: { times: 1 } }],
    text: "**End of Turn:** gain the **right-most** Shop minion's stats.",
    goldenText: "**End of Turn:** gain the **right-most** Shop minion's stats **twice**.",
  },
  {
    id: 'dm_velvet',
    name: 'Velvet Rope Fiend',
    tribe: 'demon',
    tier: 5,
    attack: 5,
    health: 2,
    keywords: [],
    effects: [{ on: 'onDeath', do: 'deathrattleGrantSpell', params: { spellId: 'staffofguel', count: 1 } }],
    text: '**Echo:** get a **Staff of Guel**.',
    goldenText: '**Echo:** get **2 Staves of Guel**.',
  },
  {
    // The pay-off scales with the room you LEFT — a lone Shepherd fills six slots and buffs six times.
    id: 'dm_shepherd',
    name: 'Legion Shepherd',
    tribe: 'demon',
    tier: 5,
    attack: 3,
    health: 3,
    keywords: [],
    effects: [{ on: 'startOfCombat', do: 'scFillWithImpsAndBuff', params: { attack: 1, health: 1 } }],
    text: '**Start of Combat:** fill your warband with **Imps**. Give your Imps **+1/+1** for each one summoned.',
    goldenText: '**Start of Combat:** fill your warband with **Imps**. Give your Imps **+2/+2** for each one summoned.',
  },
  {
    id: 'dm_tallymonger',
    name: 'Tallymonger',
    tribe: 'demon',
    tier: 5,
    attack: 6,
    health: 6,
    keywords: [],
    effects: [{ on: 'endOfTurn', do: 'endOfTurnBuffSpellsAndImps', params: { attack: 1, health: 1 } }],
    text: '**End of Turn:** give your **spells** and **Imps +1/+1**.',
    goldenText: '**End of Turn:** give your **spells** and **Imps +2/+2**.',
  },
  {
    id: 'dm_avarice',
    name: 'Avarice Incarnate',
    tribe: 'demon',
    tier: 6,
    attack: 6,
    health: 7,
    keywords: [],
    effects: [{ on: 'onConsume', do: 'onConsumeGoldByTier', params: { cap: 1 } }],
    text: 'The **first time** you Consume a Shop minion each turn, gain **Gold equal to its Tier**.',
    goldenText: 'The **first 2 times** you Consume a Shop minion each turn, gain **Gold equal to its Tier**.',
  },
  {
    // Its NEIGHBOURS eat, so the stats land on them — seating is the card.
    id: 'dm_vhal',
    name: 'Feastmaster Vhal',
    tribe: 'demon',
    tier: 6,
    attack: 6,
    health: 8,
    keywords: [],
    effects: [{ on: 'endOfTurn', do: 'endOfTurnNeighboursConsumeShop', params: { count: 1 } }],
    text: '**End of Turn:** adjacent minions each Consume a random Shop minion.',
    goldenText: '**End of Turn:** adjacent minions each Consume **2** random Shop minions.',
  },
  {
    id: 'dm_chancellor',
    name: 'Cinder Chancellor',
    tribe: 'demon',
    tier: 6,
    attack: 4,
    health: 12,
    keywords: [],
    effects: [{ on: 'onAttack', do: 'onImpAttackBuffImps', params: { attack: 3, improve: 1, improveEvery: 3 } }],
    text: 'Whenever an **Imp** attacks, give your Imps **+3/+3** this combat. Improves by **+1/+1** every **3** Imp attacks.',
    goldenText: 'Whenever an **Imp** attacks, give your Imps **+6/+6** this combat. Improves by **+2/+2** every **3** Imp attacks.',
  },
];
