import type { CardDef } from '@game/core';

/**
 * Tavern spells (handoff: one spell is always offered, on the right of the shop).
 * Unlike minions (flat `CONFIG.minionCost`), each spell sets its own `cost`. A spell
 * is bought into the hand, then cast — it never takes a board slot. `target: 'friendly'`
 * spells make the player pick a friendly minion when cast.
 */
export const SPELLS: CardDef[] = [
  {
    id: 'spiritfire',
    name: 'Spirit Fire',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1, // unused for a spell; kept positive so the shared schema validates
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 2, health: 3 } }],
    text: 'Give a minion **+2/+3**.',
  },
  {
    id: 'emberpouch',
    name: 'Gold Pouch',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'gainEmbers', params: { amount: 1 } }],
    text: 'Gain **1 Gold**.',
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 0, health: 1, keyword: 'T' } }],
    text: 'Give a minion **+0/+1** and **Taunt**.',
  },
  {
    // Untargeted board-wide buff. Scales with spell power like every stat spell (spellStatBonus).
    id: 'growth',
    name: 'Growth',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffAll', params: { attack: 1, health: 1 } }],
    text: 'Give your minions **+1/+1**.',
  },
  {
    // Targeted sacrifice: the picked minion is devoured (removed) and a RANDOM other friend inherits its
    // stats. `singleCast` keeps spell-quantity multipliers from devouring twice. No spell-power scaling
    // (it transfers existing stats, not a flat grant).
    id: 'devour',
    name: 'Channeling the Devourer',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellDevour' }],
    text: 'Devour a friendly minion and spit its stats onto a random other friend.',
  },
  {
    // Targeted +2/+4 (scales with spell power) plus a Taunt toggle: gives Taunt if the target lacks it,
    // strips it if it already has it. The toggle rides on spellBuffTarget's `toggleKeyword` param.
    id: 'shatter',
    name: 'Shatter',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 2, health: 4, toggleKeyword: 'T' } }],
    text: 'Give a minion **+2/+4** and **Taunt**. If it already has Taunt, remove it instead.',
  },
  {
    // Conjure a random minion of the *target's* tribe, up to your tavern tier, into the hand.
    id: 'tribeschoice',
    name: 'Tribes Choice',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellGainOfTargetTribe' }],
    text: "Get a random minion of the targeted minion's type (up to your tavern tier).",
  },
  {
    // Bank two free rerolls (spent before Mana on a roll).
    id: 'refreshtexts',
    name: 'Refreshing Texts',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'grantFreeRolls', params: { count: 2 } }],
    text: 'Gain **2 free rerolls**.',
  },
  {
    // Gild a Tier-4-or-lower minion (like Oner's hero power). `targetMaxTier` gates the pick.
    id: 'aresmar',
    name: 'Eyes of Aresmar',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 5,
    target: 'friendly',
    targetMaxTier: 4,
    effects: [{ on: 'cast', do: 'spellGildTarget' }],
    text: 'Make a **Tier 4 or lower** minion **Golden**.',
  },
  {
    // Permanently raise max Gold by 1 (and refill 1 now). (id stays `manafont` — the art file matches it.)
    id: 'manafont',
    name: 'Gold Font',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'gainMaxMana', params: { amount: 1 } }],
    text: 'Gain **+1 max Gold** permanently.',
  },
  {
    // Discover a Tier 1 minion (fixed-tier Discover via the reducer's play path).
    id: 'sprout',
    name: 'Sprout',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    discoverOnPlay: { exactTier: 1 },
    text: '**Discover** a Tier 1 minion.',
  },
  {
    // Permanent run-wide buff: every minion you buy from the tavern (not Discovered) gets +2/+2.
    id: 'staffofguel',
    name: 'Staff of Guel',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffShop', params: { attack: 2, health: 2 } }],
    text: 'Every minion you **buy** gets **+2/+2** for the rest of the game.',
  },
  {
    // Conjure a random buyable Tier 1 minion (active tribes + neutral) into the hand.
    id: 'summonstone',
    name: 'Summon Stone',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGainRandomMinion', params: { tier: 1 } }],
    text: 'Get a random **Tier 1** minion.',
  },
  {
    // Escalation: +2/+2, improving by +2/+2 every OTHER cast this run (owner 2026-07-13; plus spell power).
    id: 'fronttoback',
    name: 'Front to Back',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTargetEscalating' }],
    text: 'Give a minion **+2/+2**. Improve this by **+2/+2** every other cast.',
  },
  {
    // Discover a Battlecry minion (filtered Discover via the reducer's play path).
    id: 'helpwanted',
    name: 'Help Wanted',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    discoverOnPlay: { filter: 'battlecry' },
    text: '**Discover** a Battlecry minion.',
  },
  {
    // Permanent run-wide buff: your Undead get +3 Attack everywhere — on the board in the shop AND in
    // combat — with spell power folding +X/+X onto both stats on top (so +1/+1 spells make it +4/+1).
    id: 'lanternofsouls',
    name: 'Lantern of Souls',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGrantTribeAttack', params: { tribe: 'undead', amount: 3 } }],
    text: 'Your **Undead** get **+3 Attack** everywhere — even in the shop — for the rest of the game.',
  },
  {
    // Heal your hero (capped at the hero's max Resolve — no overheal). Untargeted.
    id: 'mend',
    name: 'Mend',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [{ on: 'cast', do: 'healHero', params: { amount: 5 } }],
    text: "Heal your hero **5** Health (can't overheal).",
  },
  {
    // Conjure two copies of a random buyable Undead (active tribes), into the hand.
    id: 'undeadarmy',
    name: 'Undead Army',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [{ on: 'cast', do: 'conjureTribeArmy', params: { tribe: 'undead', count: 2 } }],
    text: 'Get **2 copies** of a random **Undead**.',
  },
  {
    // Steal a random minion offer out of the tavern, into the hand (free).
    id: 'lasso',
    name: 'Lasso',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'stealTavernMinion' }],
    text: 'Steal a random minion from the tavern.',
  },

  // --- New spells (2026-06-24 content batch, part 1). Tribe Portal + Corpse Board are reducer-driven
  //     Discover spells (like Sprout / Help Wanted — empty effects); Perfect Vision uses a new cast factory. ---
  {
    // Discover a minion of your most common board tribe (neutral isn't a type → never offered). Reducer
    // resolves the dominant tribe at play time (empty effects, like Sprout / Help Wanted).
    id: 'tribeportal',
    name: 'Tribe Portal',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [],
    discoverOnPlay: { tribe: 'dominant' },
    text: '**Discover** a minion from your most common type.',
  },
  {
    // Discover a Deathrattle minion (up to your tavern tier). Reducer-driven filtered Discover.
    id: 'corpseboard',
    name: 'Corpse Board',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    discoverOnPlay: { filter: 'deathrattle' },
    text: '**Discover** a **Deathrattle** minion.',
  },
  {
    // Set a friendly minion's stats to 20/20 — an absolute SET (not a grant), so it does NOT scale with
    // spell power. Targets a friend; the player won't aim it at a bigger minion (a literal set can lower).
    id: 'perfectvision',
    name: 'Perfect Vision',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellSetStats', params: { attack: 20, health: 20 } }],
    text: "Set a minion's stats to **20/20**.",
  },
  {
    // Bank a one-shot Start-of-Combat buff: your minions enter the NEXT combat at +2/+1 (+ spell power on
    // both stats), spent after that fight (win or lose). Applied to the combat board in `faceOmen`.
    id: 'fleetingvigor',
    name: 'Fleeting Vigor',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'spellPendingSCBuff', params: { attack: 2, health: 1 } }],
    text: '**Start of combat:** give your minions **+2/+1** (next combat only).',
  },
  {
    // Choose One: buff THIS tavern's offers by +1/+3 (rides on each offer, so a buy bakes it in — lost on
    // refresh, kept if frozen), OR bank +2/+4 onto the NEXT tavern roll. Flat — no spell-power scaling.
    id: 'apples',
    name: 'Apples',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [],
    chooseOne: [
      { text: 'Give the shop **+1/+3**.', effects: [{ on: 'cast', do: 'spellBuffTavern', params: { attack: 1, health: 3 } }] },
      { text: 'Give the next shop **+2/+4**.', effects: [{ on: 'cast', do: 'spellBuffNextShop', params: { attack: 2, health: 4 } }] },
    ],
    text: '**Choose One:** Give the shop **+1/+3**, or the next shop **+2/+4**.',
  },
  {
    // Tier-scaled buff: +Tavern Tier / +Tavern Tier, plus the run's spell power on top of both stats
    // (so at T4 with +1/+0 spell power it gives +5/+4).
    id: 'lanternlight',
    name: 'Lantern Light',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffByTier' }],
    text: 'Give a minion **+1/+1** for each **Tavern Tier**.',
  },
  {
    // Sell the target + spit its (current) stats onto your left-most Demon, firing that Demon's on-consume
    // payoffs. singleCast: a Yazzus shouldn't try to re-sell the already-gone target. No Demon → stats wasted.
    id: 'foddertreatment',
    name: 'Fodder Treatment',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellSellToDemon' }],
    text: 'Sell a friendly minion and give its stats to your left-most **Demon**.',
  },
  {
    // Quest reward (Feed the Alpha) — the Beast sibling of Fodder Treatment: sell a friendly minion, funnel its
    // stats into your right-most Beast. Granted once per turn by the quest (recurringGrant); reward-exclusive.
    id: 'feedalpha',
    name: 'Feed the Alpha',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    token: true, // reward-exclusive (the Feed the Alpha quest) — never rolls in the shop / spell Discover / random-spell grants
    singleCast: true,
    cost: 0,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellSellToBeast' }],
    text: 'Sell a friendly minion and give its stats to your right-most **Beast**.',
  },
  {
    // Re-trigger the target's Battlecry (reducer guards it to Battlecry minions). Yazzus multiplies it.
    id: 'resonance',
    name: 'Resonance',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellReplayBattlecry' }],
    text: "Trigger a friendly **Battlecry** minion's Battlecry.",
  },
  {
    // One-shot: this turn's End-of-Turn effects fire one extra time (stacks with Chronos, not itself).
    id: 'chronostaff',
    name: 'Chrono Staff',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellExtraEndOfTurn' }],
    text: 'Your **End of Turn** effects trigger **1 more** time this turn.',
  },
  {
    // Targeted Demon consumes ONE random tavern minion (the Consume pipeline). Not singleCast → Yazzus
    // multiplies it (a golden Yazzus → 3 random minions consumed).
    id: 'consume',
    name: 'Consume',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellDemonConsumeFodder', params: { count: 1 } }],
    text: 'Choose a **Demon** — it consumes a **Fodder**.',
  },
  {
    // Make a random tavern minion Golden — an offer-level golden flag the buy bakes in (goldens store base
    // stats, ×2 at combat, like Indy's gild). Untargeted → the game picks the minion.
    id: 'goldentouch',
    name: 'Golden Touch',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 5,
    effects: [{ on: 'cast', do: 'spellGildRandomTavern' }],
    text: 'Make a random minion in the tavern **Golden**.',
  },
  {
    // Swap the target friendly minion with a random tavern minion (shares Darah's Displace mechanic). The
    // tavern minion arrives fresh on the board; the target goes back to the tavern as a fresh re-buyable
    // offer. singleCast — a Yazzus can't re-swap the already-displaced target.
    id: 'displacement',
    name: 'Displacement',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 2,
    target: 'friendly',
    targetNoGolden: true, // can't trade away a golden (triple) — mirrors Darah's Displace power
    effects: [{ on: 'cast', do: 'spellDisplace' }],
    text: 'Swap a friendly minion with a random minion in the tavern.',
  },
  {
    // Refresh the tavern full of spells — the minion offers become random eligible spells. Untargeted; the
    // next normal roll/turn restocks minions (one-shot).
    id: 'spellcart',
    name: 'Spell Cart',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellRefreshToSpells' }],
    text: 'Refresh the tavern — fill it with **spells** instead of minions.',
  },
  {
    // Combat initiative: your board attacks first in the next fight, overriding the more-minions rule
    // (ties included). One fight only — the flag clears when the combat settles. T4 (owner dial 2026-07-05).
    id: 'preemptive',
    name: 'Pre-emptive Assault',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellAttackFirst' }],
    text: 'You attack **first** next fight.',
  },
  {
    // Anomaly Reactor: target a friendly minion, then CHOOSE an extra type to bolt on — it now counts as that
    // type in addition to its own for every synergy (auras, Rally-of-a-type, tribe quests, Magnetic hosts, …)
    // for the rest of the run. The drag picks the target; the Choose One picks the type.
    id: 'anomalyreactor',
    name: 'Anomaly Reactor',
    tribe: 'mech',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    token: true, // reward-exclusive (the Anomalous Reactor quest) — never rolls in the shop / spell Discover / random-spell grants
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellAddAllTribes' }],
    text: 'Give a friendly minion **All** types — it counts as every tribe and gets all of their buffs.',
  },
  {
    // Bloodlust: mark a friendly minion — it takes an immediate immune swing at the start of the next combat.
    id: 'bloodlust',
    name: 'Bloodlust',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    token: true, // reward-exclusive (the Red Trail quest) — never rolls in the shop / spell Discover / random-spell grants
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBloodlust' }],
    text: "Choose a friendly minion. It attacks immediately at the start of next combat (can't die from that attack) and gains **Rally: give a friendly minion this minion's Attack** for that combat.",
  },
  {
    // Banked economy: +2 Gold at the start of next turn (the Hoarder channel — bonusEmbersNextTurn).
    id: 'depositbox',
    name: 'Safety Deposit Box',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'battlecryBonusGoldNextTurn', params: { gold: 2 } }],
    text: 'Gain **2 Gold** next turn.',
  },
  {
    // Rally payoff (2026-07-06): every Rally on your board triggers twice in the NEXT combat (Deathsayer
    // procs its Deathrattle twice per swing, a rally-buffer buffs twice, etc.). One fight; does not stack
    // with itself (a bool flag). Resolved via `spellRallyDoubleNext` → simulate() re-runs each Rally.
    id: 'rallyoffensive',
    name: 'Rallying Offensive',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellRallyDoubleNext' }],
    text: 'Your **Rally** effects trigger **twice** next combat.',
  },
  {
    // Gold-sink payoff: a small +1/+1 base plus +2/+2 for every 6 Gold spent this recruit turn (buys, rerolls,
    // tier-ups). Scales with spell power per chunk, like any stat spell. Fetched by Field Mechanic. Reworked
    // from "per attachment" (2026-07-07) since welded magnetics leave no clean attachment count; base and step
    // split apart in the 2026-07-21 balance pass so an unspent turn pays much less.
    id: 'patchjob',
    name: 'Patch Job',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTargetPerGold', params: { gold: 6, attack: 2, health: 2, baseAttack: 1, baseHealth: 1 } }],
    text: 'Give a minion **+1/+1**, plus **+2/+2** for every **6 Gold** spent this turn.',
  },
  {
    // Spark Capacitor's Avenge payoff (also a T6 Tavern spell): buff your entire board +5/+5, twice — two
    // spellBuffAll casts, so each picks up spell power. A board-wide finisher.
    id: 'sparkplug',
    name: 'Spark Plug',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [
      { on: 'cast', do: 'spellBuffAll', params: { attack: 5, health: 5 } },
      { on: 'cast', do: 'spellBuffAll', params: { attack: 5, health: 5 } },
    ],
    text: 'Give your entire board **+5/+5** twice.',
  },
  {
    // Ossuary Rite reward (also a repeatable quest payoff). Reward-only spell (token: true). Cast: trigger a
    // targeted friendly minion's Echo out of combat, WITHOUT destroying it — its summons/buffs bake in, doubled
    // by Sylus + the run's echo doublers, and it ticks the run's Deathrattle tally like any Echo.
    id: 'ossuaryrite',
    name: 'Ossuary Rite',
    tribe: 'undead',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellTriggerEcho' }],
    text: "Trigger a friendly minion's **Echo** (Deathrattle).",
    token: true,
  },
  {
    // Implosion reward (recurring from the Implosion quest). Reward-only spell (token: true). Buffs your Imps
    // and recasts once per Demon you control (min 1); each cast folds in spell power.
    id: 'implosion',
    name: 'Implosion',
    tribe: 'demon',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffImpsPerDemon', params: { attack: 2, health: 2 } }],
    text: 'Give your **Imps** **+2/+2**, recast for every Demon you control.',
    token: true,
  },
  {
    // Gilded Chance / Rulebreaker's Crown reward (owner: it's a spell that golds the target). Reward-only.
    // Makes a friendly minion golden (gild). No tier cap (targetMaxTier defaults to the max tavern tier).
    id: 'goldcrafter',
    name: 'Goldcrafter',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellGildTarget' }],
    text: 'Make a friendly minion **golden**.',
    token: true,
  },
  {
    // Key Findings reward (owner spec: "Get 2 Key Findings"). Reward-only spell (token: true). On play it opens a
    // Discover for a minion of your CURRENT tavern tier ONLY (`exactCurrentTier` — not the up-to-tier default).
    id: 'keyfindings',
    name: 'Key Findings',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [],
    discoverOnPlay: { exactCurrentTier: true },
    text: 'Discover a minion from your tier.',
    token: true,
  },

  // --- New spells (2026-07-23 batch, tranche A — set-agnostic; carried into Set 2 via SET1_SPELLS_IN_SET2). ---
  {
    // Choose One flat stat grant. `flat: true` opts the buffs OUT of spell power, so the printed "+4" is always
    // exact — Choose-One option text isn't greened by spellDisplayText. `any` → a warband minion OR a tavern offer.
    id: 'crestclimb',
    name: 'Crest of the Climb',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [],
    chooseOne: [
      { text: 'Give **+4 Attack**.', effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 4, health: 0, flat: true } }] },
      { text: 'Give **+4 Health**.', effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 0, health: 4, flat: true } }] },
    ],
    text: '**Choose One:** give a minion **+4 Attack**, or **+4 Health**.',
  },
  {
    // Swap the target's Attack and Health (spellSwapStats). No spell-power scaling — it moves existing stats,
    // it doesn't grant them. `any` → warband minion or tavern offer.
    id: 'turnabout',
    name: 'Turnabout',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellSwapStats' }],
    text: "Swap a minion's **Attack and Health**.",
  },
  {
    // Comeback economy: +5 Gold, but ONLY if you lost your last combat (a draw doesn't count). Untargeted;
    // no last combat yet (turn 1) → no payout.
    id: 'insurancepolicy',
    name: 'Insurance Policy',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGoldIfLostLast', params: { gold: 5 } }],
    text: 'If you **lost** your last combat, gain **5 Gold**.',
  },
  {
    // Discover a SHOP SPELL (discoverOnPlay.spell) — reducer-driven, like Sprout (empty effects).
    id: 'riftsunkcodex',
    name: 'Rift-Sunk Codex',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [],
    discoverOnPlay: { spell: true },
    text: '**Discover** a Shop spell.',
  },
  {
    // Discover a minion ONE tier higher: `topTierFirst` fills from the offer tier (current + 1) DOWN, so you
    // get that higher tier when it can supply the offer. `maxTier: 7` lets it reach Tier 7 even without the
    // Summit rift (which otherwise caps Discover at 6).
    id: 'beyondsummit',
    name: 'Beyond the Summit',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [],
    discoverOnPlay: { tierOffset: 1, maxTier: 7, topTierFirst: true },
    text: '**Discover** a minion from **one tier higher** (up to Tier 7).',
  },
  {
    // Discover a fixed Tier 6 minion — `exactTier` bypasses the tavern-tier gate (buyable at any tier).
    id: 'invitationabove',
    name: 'Invitation Above',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 5,
    effects: [],
    discoverOnPlay: { exactTier: 6 },
    text: '**Discover** a **Tier 6** minion.',
  },

  // --- New spells (2026-07-23 batch, tranche B1 — "next-combat keyword" grants; set-agnostic). All target a
  //     FRIENDLY minion: the grant only lands on the board it fights with (a tavern offer never enters combat). ---
  {
    // Choose One: bank Ward (Divine Shield) or Flurry (Windfury) onto the target for the next combat only.
    id: 'fieldmaneuvers',
    name: 'Field Maneuvers',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [],
    chooseOne: [
      { text: 'Give **Ward**.', effects: [{ on: 'cast', do: 'spellGrantKeywordNextCombat', params: { keyword: 'DS' } }] },
      { text: 'Give **Flurry**.', effects: [{ on: 'cast', do: 'spellGrantKeywordNextCombat', params: { keyword: 'W' } }] },
    ],
    text: '**Choose One:** give a minion **Ward** or **Flurry** for the next combat.',
  },
  {
    // Rise (Reborn) for one fight — the minion resummons once when it dies this combat.
    id: 'laststand',
    name: 'Last Stand',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellGrantKeywordNextCombat', params: { keyword: 'R' } }],
    text: 'Give a minion **Rise** for the next combat.',
  },
  {
    // Critical Strike (50%, matching Commander Impala's convention) for one fight — `critChance` seeds the
    // per-swing double-damage roll onto the combat instance.
    id: 'executionersedge',
    name: "Executioner's Edge",
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellGrantKeywordNextCombat', params: { keyword: 'CR', critChance: 0.5 } }],
    text: 'Give a minion **Critical Strike (50%)** for the next combat.',
  },

  // --- New spells (2026-07-23 batch, tranche B2 — shop / economy; set-agnostic). ---
  {
    // The next minion sold this turn is worth +2 Gold. Untargeted; one-shot, expires unused at turn end.
    id: 'quicksale',
    name: 'Quick Sale',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'spellNextSellBonus', params: { gold: 2 } }],
    text: 'The next minion you **sell** this turn sells for **2** additional Gold.',
  },
  {
    // Choose a friendly minion; refresh the tavern's minions with random minions of ITS type (up to your tier).
    id: 'sigilkinship',
    name: 'Sigil of Kinship',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellRefreshToTribe' }],
    text: "Choose a minion. Refresh the Shop with minions of its **type**.",
  },
  {
    // Replace the tavern's minions with random minions ONE tier higher (capped at Tier 7). Untargeted.
    id: 'elevationritual',
    name: 'Elevation Ritual',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellRefreshTierUp' }],
    text: 'Upgrade each minion in the Shop to a random minion **one tier higher**.',
  },

  // --- New spells (2026-07-23 batch, tranche B3 — offer / minion manipulation; set-agnostic). ---
  {
    // Cast on a SHOP offer: it survives rerolls (kept) and costs 1 less. `target: 'any'` for the drag, but it
    // fizzles on a board minion (the reducer guards it) since only an offer can be kept.
    id: 'layaway',
    name: 'Layaway',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellLayaway', params: { reduce: 1 } }],
    text: 'Choose a minion in the Shop. **Keep it** through refreshes and reduce its cost by **1**.',
  },
  {
    // Return a friendly non-Gilded minion to hand INTACT (keeps its buffs) — replay it for its Battlecry, or
    // just reposition. `targetNoGolden` makes a golden (triple) target fizzle.
    id: 'seconddraft',
    name: 'Second Draft',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    target: 'friendly',
    targetNoGolden: true,
    effects: [{ on: 'cast', do: 'spellReturnToHand' }],
    text: 'Return a friendly **non-Gilded** minion to your hand.',
  },

  // --- New spells (2026-07-23 batch, tranche B4 — transform / combat-pending; set-agnostic). ---
  {
    // Transform a friendly minion into a random OTHER minion of the same tier, keeping its bonus stats
    // (its gains above base re-based onto the new form). singleCast so a Yazzus can't re-roll the new form.
    id: 'strangerevision',
    name: 'Strange Revision',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellTransformSameTier' }],
    text: 'Transform a friendly minion into a random minion of the **same tier**. It keeps its **bonus stats**.',
  },
  {
    // At the start of next combat, the enemy's right-most minion gains Taunt (funnels your attacks into it).
    id: 'markedtarget',
    name: 'Marked Target',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellMarkEnemyTaunt' }],
    text: "At the start of next combat, give the enemy's **right-most** minion **Taunt**.",
  },
  {
    // Re-trigger a friendly minion's Shout (Battlecry) and Echo (Deathrattle, without destroying it). Rally is
    // combat-only, so it's a no-op out of combat. singleCast — a Yazzus can't multiply the re-trigger.
    id: 'encore',
    name: 'Encore',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 4,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellEncore' }],
    text: 'Choose a friendly minion. Trigger its **Shout**, **Rally** or **Echo**.',
  },
  {
    // +4/+4, plus +1/+1 for each Dragon you PLAYED this turn (flat — no spell power, so the printed value stays
    // exact; spellDisplayText greens the +4/+4 to its live total). `any` → warband minion or tavern offer.
    id: 'hoardflame',
    name: 'Hoardflame',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffPerDragonPlayed', params: { attack: 4, health: 4, per: 1 } }],
    text: 'Give a minion **+4/+4**, plus **+1/+1** for each **Dragon** you played this turn.',
  },

  // --- New spells (2026-07-23 batch, tranche C — Discover-based; set-agnostic). ---
  {
    // Discover a minion from your CURRENT tavern tier, locked in hand until next turn (Hourglass Reserve).
    id: 'hourglassreserve',
    name: 'Hourglass Reserve',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [],
    discoverOnPlay: { exactCurrentTier: true, lockUntilNextTurn: true },
    text: '**Discover** a minion from your tier. You **cannot play it until next turn**.',
  },
  {
    // Discover an Echo (Deathrattle) minion, BORROWED — playing it triggers its Echo and destroys it (never
    // boards). An unplayed borrowed card is returned at turn end.
    id: 'funeralonloan',
    name: 'Funeral on Loan',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [],
    discoverOnPlay: { filter: 'deathrattle', borrowed: true },
    text: '**Discover** an **Echo** minion. If you play it this turn, **destroy it and trigger its effect**.',
  },
  {
    // Discover a plain copy of a minion from your LAST opponent's warband.
    id: 'rivalsreflection',
    name: "Rival's Reflection",
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'spellDiscoverFromLastOpponent' }],
    text: "**Discover** a plain copy of a minion from your **last opponent's** warband.",
  },
];
