import type { CardDef } from '@game/core';

/**
 * Tavern spells (handoff: one spell is always offered, on the right of the shop).
 * Unlike minions (flat `CONFIG.minionCost`), each spell sets its own `cost`. A spell
 * is bought into the hand, then cast — it never takes a board slot. `target: 'friendly'`
 * spells make the player pick a friendly minion when cast.
 */
export const SPELLS: CardDef[] = [
  {
    id: 'spiritfire',
    name: 'Spirit Fire',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1, // unused for a spell; kept positive so the shared schema validates
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 4, health: 4 } }],
    text: 'Give a friendly minion **+4/+4**.',
  },
  {
    id: 'emberpouch',
    name: 'Mana Pouch',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'gainEmbers', params: { amount: 1 } }],
    text: 'Gain **1 Mana**.',
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 0, health: 1, keyword: 'T' } }],
    text: 'Give a friendly minion **+0/+1** and **Taunt**.',
  },
  {
    // Untargeted board-wide buff. Scales with spell power like every stat spell (spellStatBonus).
    id: 'growth',
    name: 'Growth',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffAll', params: { attack: 3, health: 4 } }],
    text: 'Give your minions **+3/+4**.',
  },
  {
    // Targeted sacrifice: the picked minion is devoured (removed) and a RANDOM other friend inherits its
    // stats. `singleCast` keeps spell-quantity multipliers from devouring twice. No spell-power scaling
    // (it transfers existing stats, not a flat grant).
    id: 'devour',
    name: 'Channeling the Devourer',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellDevour' }],
    text: 'Devour a friendly minion and spit its stats onto a random other friend.',
  },
  {
    // Targeted +2/+4 (scales with spell power) plus a Taunt toggle: gives Taunt if the target lacks it,
    // strips it if it already has it. The toggle rides on spellBuffTarget's `toggleKeyword` param.
    id: 'shatter',
    name: 'Shatter',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 2, health: 4, toggleKeyword: 'T' } }],
    text: 'Give a minion **+2/+4** and **Taunt**. If it already has Taunt, remove it instead.',
  },
  {
    // Conjure a random minion of the *target's* tribe, up to your tavern tier, into the hand.
    id: 'tribeschoice',
    name: 'Tribes Choice',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellGainOfTargetTribe' }],
    text: "Get a random minion of the targeted minion's type (up to your tavern tier).",
  },
  {
    // Bank two free rerolls (spent before Mana on a roll).
    id: 'refreshtexts',
    name: 'Refreshing Texts',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'grantFreeRolls', params: { count: 2 } }],
    text: 'Gain **2 free rerolls**.',
  },
  {
    // Gild a Tier-4-or-lower minion (like Oner's hero power). `targetMaxTier` gates the pick.
    id: 'aresmar',
    name: 'Eyes of Aresmar',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 5,
    target: 'friendly',
    targetMaxTier: 4,
    effects: [{ on: 'cast', do: 'spellGildTarget' }],
    text: 'Make a **Tier 4 or lower** minion **Golden**.',
  },
  {
    // Permanently raise max Mana by 1 (and refill 1 now).
    id: 'manafont',
    name: 'Mana Font',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'gainMaxMana', params: { amount: 1 } }],
    text: 'Gain **+1 max Mana** permanently.',
  },
  {
    // Discover a Tier 1 minion (fixed-tier Discover via the reducer's play path).
    id: 'sprout',
    name: 'Sprout',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    text: '**Discover** a Tier 1 minion.',
  },
  {
    // Permanent run-wide buff: every minion you buy from the tavern (not Discovered) gets +2/+2.
    id: 'staffofguel',
    name: 'Staff of Guel',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffShop', params: { attack: 2, health: 2 } }],
    text: 'Every minion you **buy** gets **+2/+2** for the rest of the game.',
  },
  {
    // Conjure a random buyable Tier 1 minion (active tribes + neutral) into the hand.
    id: 'summonstone',
    name: 'Summon Stone',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGainRandomMinion', params: { tier: 1 } }],
    text: 'Get a random **Tier 1** minion.',
  },
  {
    // Linear escalation: +2/+2, then +2/+2 more for every Front to Back cast this run (plus spell power).
    id: 'fronttoback',
    name: 'Front to Back',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTargetEscalating' }],
    text: 'Give a minion **+2/+2**.',
  },
  {
    // Discover a Battlecry minion (filtered Discover via the reducer's play path).
    id: 'helpwanted',
    name: 'Help Wanted',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    text: '**Discover** a Battlecry minion.',
  },
  {
    // Permanent run-wide buff: your Undead get +3 Attack everywhere — on the board in the shop AND in
    // combat — with spell power folding +X/+X onto both stats on top (so +1/+1 spells make it +4/+1).
    id: 'lanternofsouls',
    name: 'Lantern of Souls',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGrantTribeAttack', params: { tribe: 'undead', amount: 3 } }],
    text: 'Your **Undead** get **+3 Attack** everywhere — even in the shop — for the rest of the game.',
  },
  {
    // Heal your hero (capped at the hero's max Resolve — no overheal). Untargeted.
    id: 'mend',
    name: 'Mend',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [{ on: 'cast', do: 'healHero', params: { amount: 5 } }],
    text: "Heal your hero **5** Health (can't overheal).",
  },
  {
    // Conjure two copies of a random buyable Undead (active tribes), into the hand.
    id: 'undeadarmy',
    name: 'Undead Army',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [{ on: 'cast', do: 'conjureTribeArmy', params: { tribe: 'undead', count: 2 } }],
    text: 'Get **2 copies** of a random **Undead**.',
  },
  {
    // Steal a random minion offer out of the tavern, into the hand (free).
    id: 'lasso',
    name: 'Lasso',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'stealTavernMinion' }],
    text: 'Steal a random minion from the tavern.',
  },
];
