import type { CardDef } from '@game/core';

/**
 * Tavern spells (handoff: one spell is always offered, on the right of the shop).
 * Unlike minions (flat `CONFIG.minionCost`), each spell sets its own `cost`. A spell
 * is bought into the hand, then cast — it never takes a board slot. `target: 'friendly'`
 * spells make the player pick a friendly minion when cast.
 */
export const SPELLS: CardDef[] = [
  {
    id: 'spiritfire',
    name: 'Spirit Fire',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1, // unused for a spell; kept positive so the shared schema validates
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 4, health: 4 } }],
    text: 'Give a friendly minion **+4/+4**.',
  },
  {
    id: 'emberpouch',
    name: 'Gold Pouch',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'gainEmbers', params: { amount: 1 } }],
    text: 'Gain **1 Gold**.',
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 0, health: 1, keyword: 'T' } }],
    text: 'Give a friendly minion **+0/+1** and **Taunt**.',
  },
  {
    // Untargeted board-wide buff. Scales with spell power like every stat spell (spellStatBonus).
    id: 'growth',
    name: 'Growth',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffAll', params: { attack: 3, health: 4 } }],
    text: 'Give your minions **+3/+4**.',
  },
  {
    // Targeted sacrifice: the picked minion is devoured (removed) and a RANDOM other friend inherits its
    // stats. `singleCast` keeps spell-quantity multipliers from devouring twice. No spell-power scaling
    // (it transfers existing stats, not a flat grant).
    id: 'devour',
    name: 'Channeling the Devourer',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellDevour' }],
    text: 'Devour a friendly minion and spit its stats onto a random other friend.',
  },
  {
    // Targeted +2/+4 (scales with spell power) plus a Taunt toggle: gives Taunt if the target lacks it,
    // strips it if it already has it. The toggle rides on spellBuffTarget's `toggleKeyword` param.
    id: 'shatter',
    name: 'Shatter',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTarget', params: { attack: 2, health: 4, toggleKeyword: 'T' } }],
    text: 'Give a minion **+2/+4** and **Taunt**. If it already has Taunt, remove it instead.',
  },
  {
    // Conjure a random minion of the *target's* tribe, up to your tavern tier, into the hand.
    id: 'tribeschoice',
    name: 'Tribes Choice',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellGainOfTargetTribe' }],
    text: "Get a random minion of the targeted minion's type (up to your tavern tier).",
  },
  {
    // Bank two free rerolls (spent before Mana on a roll).
    id: 'refreshtexts',
    name: 'Refreshing Texts',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'grantFreeRolls', params: { count: 2 } }],
    text: 'Gain **2 free rerolls**.',
  },
  {
    // Gild a Tier-4-or-lower minion (like Oner's hero power). `targetMaxTier` gates the pick.
    id: 'aresmar',
    name: 'Eyes of Aresmar',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 5,
    target: 'friendly',
    targetMaxTier: 4,
    effects: [{ on: 'cast', do: 'spellGildTarget' }],
    text: 'Make a **Tier 4 or lower** minion **Golden**.',
  },
  {
    // Permanently raise max Gold by 1 (and refill 1 now). (id stays `manafont` — the art file matches it.)
    id: 'manafont',
    name: 'Gold Font',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'gainMaxMana', params: { amount: 1 } }],
    text: 'Gain **+1 max Gold** permanently.',
  },
  {
    // Discover a Tier 1 minion (fixed-tier Discover via the reducer's play path).
    id: 'sprout',
    name: 'Sprout',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    discoverOnPlay: { exactTier: 1 },
    text: '**Discover** a Tier 1 minion.',
  },
  {
    // Permanent run-wide buff: every minion you buy from the tavern (not Discovered) gets +2/+2.
    id: 'staffofguel',
    name: 'Staff of Guel',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellBuffShop', params: { attack: 2, health: 2 } }],
    text: 'Every minion you **buy** gets **+2/+2** for the rest of the game.',
  },
  {
    // Conjure a random buyable Tier 1 minion (active tribes + neutral) into the hand.
    id: 'summonstone',
    name: 'Summon Stone',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGainRandomMinion', params: { tier: 1 } }],
    text: 'Get a random **Tier 1** minion.',
  },
  {
    // Linear escalation: +2/+2, then +2/+2 more for every Front to Back cast this run (plus spell power).
    id: 'fronttoback',
    name: 'Front to Back',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'any',
    effects: [{ on: 'cast', do: 'spellBuffTargetEscalating' }],
    text: 'Give a minion **+2/+2**. Improve this by **+2/+2**.',
  },
  {
    // Discover a Battlecry minion (filtered Discover via the reducer's play path).
    id: 'helpwanted',
    name: 'Help Wanted',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    discoverOnPlay: { filter: 'battlecry' },
    text: '**Discover** a Battlecry minion.',
  },
  {
    // Permanent run-wide buff: your Undead get +3 Attack everywhere — on the board in the shop AND in
    // combat — with spell power folding +X/+X onto both stats on top (so +1/+1 spells make it +4/+1).
    id: 'lanternofsouls',
    name: 'Lantern of Souls',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellGrantTribeAttack', params: { tribe: 'undead', amount: 3 } }],
    text: 'Your **Undead** get **+3 Attack** everywhere — even in the shop — for the rest of the game.',
  },
  {
    // Heal your hero (capped at the hero's max Resolve — no overheal). Untargeted.
    id: 'mend',
    name: 'Mend',
    tribe: 'neutral',
    tier: 2,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [{ on: 'cast', do: 'healHero', params: { amount: 5 } }],
    text: "Heal your hero **5** Health (can't overheal).",
  },
  {
    // Conjure two copies of a random buyable Undead (active tribes), into the hand.
    id: 'undeadarmy',
    name: 'Undead Army',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [{ on: 'cast', do: 'conjureTribeArmy', params: { tribe: 'undead', count: 2 } }],
    text: 'Get **2 copies** of a random **Undead**.',
  },
  {
    // Steal a random minion offer out of the tavern, into the hand (free).
    id: 'lasso',
    name: 'Lasso',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'stealTavernMinion' }],
    text: 'Steal a random minion from the tavern.',
  },

  // --- New spells (2026-06-24 content batch, part 1). Tribe Portal + Corpse Board are reducer-driven
  //     Discover spells (like Sprout / Help Wanted — empty effects); Perfect Vision uses a new cast factory. ---
  {
    // Discover a minion of your most common board tribe (neutral isn't a type → never offered). Reducer
    // resolves the dominant tribe at play time (empty effects, like Sprout / Help Wanted).
    id: 'tribeportal',
    name: 'Tribe Portal',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 4,
    effects: [],
    discoverOnPlay: { tribe: 'dominant' },
    text: '**Discover** a minion from your most common type.',
  },
  {
    // Discover a Deathrattle minion (up to your tavern tier). Reducer-driven filtered Discover.
    id: 'corpseboard',
    name: 'Corpse Board',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [],
    discoverOnPlay: { filter: 'deathrattle' },
    text: '**Discover** a **Deathrattle** minion.',
  },
  {
    // Set a friendly minion's stats to 20/20 — an absolute SET (not a grant), so it does NOT scale with
    // spell power. Targets a friend; the player won't aim it at a bigger minion (a literal set can lower).
    id: 'perfectvision',
    name: 'Perfect Vision',
    tribe: 'neutral',
    tier: 6,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellSetStats', params: { attack: 20, health: 20 } }],
    text: "Set a friendly minion's stats to **20/20**.",
  },
  {
    // Bank a one-shot Start-of-Combat buff: your minions enter the NEXT combat at +2/+1 (+ spell power on
    // both stats), spent after that fight (win or lose). Applied to the combat board in `faceOmen`.
    id: 'fleetingvigor',
    name: 'Fleeting Vigor',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'spellPendingSCBuff', params: { attack: 2, health: 1 } }],
    text: '**Start of combat:** give your minions **+2/+1** (next combat only).',
  },
  {
    // Choose One: buff THIS tavern's offers by +1/+3 (rides on each offer, so a buy bakes it in — lost on
    // refresh, kept if frozen), OR bank +2/+4 onto the NEXT tavern roll. Flat — no spell-power scaling.
    id: 'apples',
    name: 'Apples',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [],
    chooseOne: [
      { text: 'Give the shop **+1/+3**.', effects: [{ on: 'cast', do: 'spellBuffTavern', params: { attack: 1, health: 3 } }] },
      { text: 'Give the next shop **+2/+4**.', effects: [{ on: 'cast', do: 'spellBuffNextShop', params: { attack: 2, health: 4 } }] },
    ],
    text: '**Choose One:** Give the shop **+1/+3**, or the next shop **+2/+4**.',
  },
  {
    // Tier-scaled buff: +Tavern Tier / +Tavern Tier, plus the run's spell power on top of both stats
    // (so at T4 with +1/+0 spell power it gives +5/+4).
    id: 'lanternlight',
    name: 'Lantern Light',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBuffByTier' }],
    text: 'Give a friendly minion **+1/+1** for each **Tavern Tier**.',
  },
  {
    // Sell the target + spit its (current) stats onto your left-most Demon, firing that Demon's on-consume
    // payoffs. singleCast: a Yazzus shouldn't try to re-sell the already-gone target. No Demon → stats wasted.
    id: 'foddertreatment',
    name: 'Fodder Treatment',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellSellToDemon' }],
    text: 'Sell a friendly minion and give its stats to your left-most **Demon**.',
  },
  {
    // Re-trigger the target's Battlecry (reducer guards it to Battlecry minions). Yazzus multiplies it.
    id: 'resonance',
    name: 'Resonance',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellReplayBattlecry' }],
    text: "Trigger a friendly **Battlecry** minion's Battlecry.",
  },
  {
    // One-shot: this turn's End-of-Turn effects fire one extra time (stacks with Chronos, not itself).
    id: 'chronostaff',
    name: 'Chrono Staff',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellExtraEndOfTurn' }],
    text: 'Your **End of Turn** effects trigger **1 more** time this turn.',
  },
  {
    // Targeted Demon consumes ONE random tavern minion (the Consume pipeline). Not singleCast → Yazzus
    // multiplies it (a golden Yazzus → 3 random minions consumed).
    id: 'consume',
    name: 'Consume',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellDemonConsumeFodder', params: { count: 1 } }],
    text: 'Choose a **Demon** — it consumes a **Fodder**.',
  },
  {
    // Make a random tavern minion Golden — an offer-level golden flag the buy bakes in (goldens store base
    // stats, ×2 at combat, like Indy's gild). Untargeted → the game picks the minion.
    id: 'goldentouch',
    name: 'Golden Touch',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 5,
    effects: [{ on: 'cast', do: 'spellGildRandomTavern' }],
    text: 'Make a random minion in the tavern **Golden**.',
  },
  {
    // Swap the target friendly minion with a random tavern minion (shares Darah's Displace mechanic). The
    // tavern minion arrives fresh on the board; the target goes back to the tavern as a fresh re-buyable
    // offer. singleCast — a Yazzus can't re-swap the already-displaced target.
    id: 'displacement',
    name: 'Displacement',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    singleCast: true,
    cost: 2,
    target: 'friendly',
    targetNoGolden: true, // can't trade away a golden (triple) — mirrors Darah's Displace power
    effects: [{ on: 'cast', do: 'spellDisplace' }],
    text: 'Swap a friendly minion with a random minion in the tavern.',
  },
  {
    // Refresh the tavern full of spells — the minion offers become random eligible spells. Untargeted; the
    // next normal roll/turn restocks minions (one-shot).
    id: 'spellcart',
    name: 'Spell Cart',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    effects: [{ on: 'cast', do: 'spellRefreshToSpells' }],
    text: 'Refresh the tavern — fill it with **spells** instead of minions.',
  },
  {
    // Combat initiative: your board attacks first in the next fight, overriding the more-minions rule
    // (ties included). One fight only — the flag clears when the combat settles. T4 (owner dial 2026-07-05).
    id: 'preemptive',
    name: 'Pre-emptive Assault',
    tribe: 'neutral',
    tier: 4,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellAttackFirst' }],
    text: 'You attack **first** next fight.',
  },
  {
    // Banked economy: +2 Gold at the start of next turn (the Hoarder channel — bonusEmbersNextTurn).
    id: 'depositbox',
    name: 'Safety Deposit Box',
    tribe: 'neutral',
    tier: 1,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 1,
    effects: [{ on: 'cast', do: 'battlecryBonusGoldNextTurn', params: { gold: 2 } }],
    text: 'Gain **2 Gold** next turn.',
  },
  {
    // Rally payoff (2026-07-06): every Rally on your board triggers twice in the NEXT combat (Deathsayer
    // procs its Deathrattle twice per swing, a rally-buffer buffs twice, etc.). One fight; does not stack
    // with itself (a bool flag). Resolved via `spellRallyDoubleNext` → simulate() re-runs each Rally.
    id: 'rallyoffensive',
    name: 'Rallying Offensive',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [{ on: 'cast', do: 'spellRallyDoubleNext' }],
    text: 'Your **Rally** effects trigger **twice** next combat.',
  },
  {
    // Gold-sink payoff: buffs the target +3/+3 for every 7 Gold spent this recruit turn (buys, rerolls,
    // tier-ups). Scales with spell power per step, like any stat spell. Fetched by Field Mechanic. Reworked
    // from "per attachment" (2026-07-07) since welded magnetics leave no clean attachment count.
    id: 'patchjob',
    name: 'Patch Job',
    tribe: 'neutral',
    tier: 3,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 2,
    target: 'friendly',
    effects: [{ on: 'cast', do: 'spellBuffTargetPerGold', params: { gold: 7, attack: 3, health: 3 } }],
    text: 'Give a minion **+3/+3** for every **7 Gold** spent this turn.',
  },
  {
    // Spark Capacitor's Avenge payoff (also a T5 Tavern spell): buff your entire board +5/+5, twice — two
    // spellBuffAll casts, so each picks up spell power. A board-wide finisher.
    id: 'sparkplug',
    name: 'Spark Plug',
    tribe: 'neutral',
    tier: 5,
    attack: 0,
    health: 1,
    keywords: [],
    spell: true,
    cost: 3,
    effects: [
      { on: 'cast', do: 'spellBuffAll', params: { attack: 5, health: 5 } },
      { on: 'cast', do: 'spellBuffAll', params: { attack: 5, health: 5 } },
    ],
    text: 'Give your entire board **+5/+5** twice.',
  },
];
