/**
 * GENERATED by `npm run contracts:extract` — do not hand-edit. 63 convention questions
 * for the owner's Sitting 1 (Doc Bot 2.0 WP B; owner-review-pipeline.md §3/§5): one card per FAMILY —
 * presentation timing families, keyword contracts, hero-power activation families, quest reward shapes,
 * and the global conventions owner specs established but no R- rule yet pins. Every card is self-contained
 * (verbatim exemplar text, one concrete example, explicit ✓/✎/✕ click semantics, the member list) and
 * decided through the SAME board + decisions.json as every other pending rule. Decisions survive
 * regeneration; rejects tombstone into retired.generated.ts via the shared seed-hygiene pass.
 */
import type { GameRule } from '../schema';

export const CONVENTION_PENDING: GameRule[] = [
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-avenge",
    "title": "'avenge' family · 21 cards",
    "statement": "All 21 'avenge' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "19 effect factories across 21 cards dispatch through the 'avenge' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Dunkey: \"Avenge (4): summon an Armadiyo.\" · Members: Dunkey · Solaris · Bone Taxer · Brood Matron · Water Dragon · Broodwright · Grobbus · Endless Overseer · Gemstorm Instigator · Gem Portsmith · Kennelmaster · Muster General · … and 9 more",
    "example": "Dunkey follows the 'avenge' convention — its trigger fires on avenge, its numbers double when gilded.",
    "contentIds": [
      "b2_dunkey",
      "b2_solaris",
      "bonetaxer",
      "brood",
      "d2_curator",
      "dm_broodwright",
      "dm_grobbus",
      "dm_overseer",
      "k_gemstorm",
      "k_portsmith",
      "kennel",
      "n2_muster",
      "pitsupplier",
      "profgreg",
      "solaris",
      "soulsman",
      "sparkcapacitor",
      "spellappraiser",
      "steadfast",
      "stuntdrake",
      "weaver"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-castPayoff",
    "title": "'castPayoff' family · 4 cards",
    "statement": "All 4 'castPayoff' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "4 effect factories across 4 cards dispatch through the 'castPayoff' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Spell Warden: \"After you cast your second Shop spell each turn, get a copy of the first.\" · Members: Spell Warden · Baal · High King Mykel · Spirit Pup",
    "example": "Spell Warden follows the 'castPayoff' convention — its trigger fires on spellCast, its numbers double when gilded.",
    "contentIds": [
      "d2_spellkeeper",
      "dw_baal",
      "dw_brisbane",
      "spiritpup"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-castReact",
    "title": "'castReact' family · 9 cards",
    "statement": "All 9 'castReact' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "8 effect factories across 9 cards dispatch through the 'castReact' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Groveweaver: \"When you summon a Beast, give it +3/+3. Improve this by +2/+2 when you cast a Shop spell.\" · Members: Groveweaver · Ashscribe · Earthbreaker · Thunderous Sovereign · Runekeg · Forsaken Mage · Archmagus Guel · Fatecarver · Runescale Drake",
    "example": "Groveweaver follows the 'castReact' convention — its trigger fires on spellCast, its numbers double when gilded.",
    "contentIds": [
      "b2_groveweaver",
      "d2_ashscribe",
      "d2_scalechanter",
      "d2_sovereign",
      "dw_runekeg",
      "forsakenweaver",
      "guel",
      "n2_fatecarver",
      "runescale"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-echo",
    "title": "'echo' family · 61 cards",
    "statement": "All 61 'echo' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "43 effect factories across 61 cards dispatch through the 'echo' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Amun Rab: \"Deathrattle: Summon 7 Imps and give your Imps +5/+5.\" · Members: Amun Rab · Anubis · Ashen Heir · Armadiyo · Bullseye · Dawnclaw · Menagerie Mammoth · Scavvers · T-Rex · Voidmother · Wolvie · Blaster · … and 49 more",
    "example": "Amun Rab follows the 'echo' convention — its trigger fires on onDeath, its numbers double when gilded.",
    "contentIds": [
      "amunrab",
      "anubis",
      "ashen_heir",
      "b2_armadiyo",
      "b2_bullseye",
      "b2_dawnclaw",
      "b2_mammoth",
      "b2_scavenger",
      "b2_trex",
      "b2_voidmother",
      "b2_wolvie",
      "blaster",
      "bonetaxer",
      "brood",
      "broodmother",
      "burialimp",
      "c3_equinox",
      "chefraag",
      "d2_scalefeather",
      "deathlesshand",
      "dm_felspikes",
      "dm_hank",
      "dm_knocked",
      "dm_malphas",
      "dm_shepherd",
      "dm_velvet",
      "dw_anvilshade",
      "dw_bladethrower",
      "dw_brewer",
      "dw_chickenbrawl",
      "dw_exgalloper",
      "grim",
      "impking",
      "impoverseer",
      "jenkins",
      "junk",
      "k_alchemist",
      "k_faultline",
      "k_gemheart",
      "k_geode",
      "k_kobabyboldies",
      "knit",
      "labexperiment",
      "manasaber",
      "mossmemory_colossus",
      "mumi",
      "n2_echomimic",
      "n2_lastlight",
      "nanon",
      "pack",
      "pillager",
      "runesnout_archivist",
      "ryme",
      "scrapvendor",
      "selfless",
      "sergeant",
      "spore",
      "sporebat",
      "trickster",
      "twilightwhelp",
      "wolvesden"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-economy",
    "title": "'economy' family · 36 cards",
    "statement": "All 36 'economy' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "21 effect factories across 36 cards dispatch through the 'economy' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Moonhowl Mentor: \"Once per turn, when you buy a Shop spell, get a Mage-Pup that has learned it.\" · Members: Moonhowl Mentor · Buddy Buddy · Horizon Courier · Runic Archivist · Scalefeather · Fel Conjurer · Flutterdrake · Mirrorwing · River Drake · Mushy · Voicekeeper · Arcane Behemoth · … and 24 more",
    "example": "Moonhowl Mentor follows the 'economy' convention — its trigger fires on cardsBought, its numbers double when gilded.",
    "contentIds": [
      "b2_moonhowl",
      "buddy",
      "c3_courier",
      "d2_archivist",
      "d2_chronicler",
      "d2_felconjurer",
      "d2_flutterdrake",
      "d2_mirrorwing",
      "d2_riverdrake",
      "d2_scalefeather",
      "d2_voicekeeper",
      "dm_behemoth",
      "dm_grevlin",
      "dm_maw",
      "dw_brewer",
      "dw_brill",
      "dw_brunni",
      "dw_chirurgeon",
      "dw_mountainbond",
      "dw_sharpshooter",
      "dw_tapkeeper",
      "fieldmechanic",
      "havendrake",
      "k_beggy",
      "k_gemgorge",
      "k_gemline",
      "k_pouchpincher",
      "k_stormchaser",
      "labexperiment",
      "n2_deepchef",
      "n2_muckslinger",
      "n2_ninefold",
      "n2_reflector",
      "n2_salesman",
      "onthehouse",
      "salvatore"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-economyReact",
    "title": "'economyReact' family · 14 cards",
    "statement": "All 14 'economyReact' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "14 effect factories across 14 cards dispatch through the 'economyReact' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Korok, the Hungerer: \"When you buy 4 cards, give your Fodder +1/+1 and add 1 Fodder to your next tavern.\" · Members: Korok, the Hungerer · Banksly · Brightwing Broker · Night Market Horror · Feastmaster Vhal · Billings · Coinfire Forewoman · Gangplank · Kegheart Dwarf · Hoard Whelp · Candle Conduit · Gem Sage · … and 2 more",
    "example": "Korok, the Hungerer follows the 'economyReact' convention — its trigger fires on cardsBought, its numbers double when gilded.",
    "contentIds": [
      "acid",
      "banksly",
      "broker",
      "dm_nightmarket",
      "dm_vhal",
      "dw_billings",
      "dw_coinfire",
      "dw_gangplank",
      "dw_kegheart",
      "hoardwhelp",
      "k_candleconduit",
      "k_gemsage",
      "k_resonance",
      "k_rubybroker"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-endOfTurn",
    "title": "'endOfTurn' family · 45 cards",
    "statement": "All 45 'endOfTurn' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "31 effect factories across 45 cards dispatch through the 'endOfTurn' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Abyssal Feeder: \"End of Turn: adjacent minions each Consume a Fodder.\" · Members: Abyssal Feeder · Aeon Guard · Moira · Stonehorn Archivist · Starbroker Nym · Astral Relay · Starpath Vendor · Cinderwing Matron · Combinator · Crypt Scribe · Skybound Ascendant · Fel Conjurer · … and 33 more",
    "example": "Abyssal Feeder follows the 'endOfTurn' convention — its trigger fires on endOfTurn, its numbers double when gilded.",
    "contentIds": [
      "abyssalfeeder",
      "aeonguard",
      "b2_moira",
      "b2_stonehorn",
      "c3_nym",
      "c3_relay",
      "c3_vendor",
      "cinder",
      "combinator",
      "cryptscribe",
      "d2_ascendant",
      "d2_felconjurer",
      "d2_flutterdrake",
      "d2_runefire",
      "d2_scalefeather",
      "d2_spellvault",
      "dm_butcher",
      "dm_curator",
      "dm_gourmand",
      "dm_malphas",
      "dm_tallymonger",
      "dw_arnold",
      "dw_brewer",
      "dw_brunni",
      "dw_foreman",
      "dw_sharpshooter",
      "dw_tapkeeper",
      "feastingbogrot",
      "fieldmechanic",
      "frontdrake",
      "hoardwhelp",
      "k_alchemist",
      "k_gemline",
      "k_stormchaser",
      "k_wardstone",
      "maw",
      "moneymaker",
      "n2_bellringer",
      "onthehouse",
      "reconfiguredcombinator",
      "ritualist",
      "ropewrangler",
      "scrapvendor",
      "skybound",
      "stewardofspells"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-orbit",
    "title": "'orbit' family · 15 cards",
    "statement": "All 15 'orbit' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "12 effect factories across 15 cards dispatch through the 'orbit' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Constellation Broker: \"Orbit: destroy the played minion and give its bonus stats to another friendly Celestial.\" · Members: Constellation Broker · Star Cartographer · Equinox Channeler · Horizon Collector · Celestial Crucible · Orbiting Familiar · Worldseed Gardener · Twinlight Orbiter · Orrery, World Devourer · Starweft Familiar · Constellation Tender · Starpath Vendor · … and 3 more",
    "example": "Constellation Broker follows the 'orbit' convention — its trigger fires on orbit, its numbers double when gilded.",
    "contentIds": [
      "c3_broker",
      "c3_cartographer",
      "c3_channeler",
      "c3_collector",
      "c3_crucible",
      "c3_familiar",
      "c3_gardener",
      "c3_orbiter",
      "c3_orrery",
      "c3_starweft",
      "c3_tender",
      "c3_vendor",
      "dm_butcher",
      "dm_curator",
      "dm_malphas"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-orbitReact",
    "title": "'orbitReact' family · 3 cards",
    "statement": "All 3 'orbitReact' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "3 effect factories across 3 cards dispatch through the 'orbitReact' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Orrery, World Devourer: \"Whenever another Orbit triggers, give minions in the current Shop +1/+1. Orbit (3): destroy the played minion and split its bonus stats among your Celestials.\" · Members: Orrery, World Devourer · Astral Shopkeeper · Worldline Weaver",
    "example": "Orrery, World Devourer follows the 'orbitReact' convention — its trigger fires on orbitFired, its numbers double when gilded.",
    "contentIds": [
      "c3_orrery",
      "c3_shopkeeper",
      "c3_weaver"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-passive",
    "title": "'passive' family · 2 cards",
    "statement": "All 2 'passive' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch through the 'passive' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Deepdelve Paragon: \"Rubies applied in combat give 2× stats.\" · Members: Deepdelve Paragon · Ancient Wanderer",
    "example": "Deepdelve Paragon follows the 'passive' convention — its trigger fires on passive, its numbers double when gilded.",
    "contentIds": [
      "k_deepdelve",
      "n2_wanderer"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-rally",
    "title": "'rally' family · 45 cards",
    "statement": "All 45 'rally' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "41 effect factories across 45 cards dispatch through the 'rally' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Echohorn: \"Rally: trigger your left-most Echo.\" · Members: Echohorn · Hawkus · Packstrider · Sunmane Herald · Badgington · Equinox Duelist · Chimerus · Chorus Engine · Crypt Drake · Ashen Broodlord · Chorus Drake · Cinderchef · … and 33 more",
    "example": "Echohorn follows the 'rally' convention — its trigger fires on onAttack, its numbers double when gilded.",
    "contentIds": [
      "b2_echohorn",
      "b2_hawkus",
      "b2_packstrider",
      "b2_sunmane",
      "badgington",
      "c3_equinox",
      "chimerus",
      "chorusengine",
      "cryptdrake",
      "d2_broodlord",
      "d2_chorus",
      "d2_cinderchef",
      "d2_embercrest",
      "d2_flamebeat",
      "d2_roarcollector",
      "d2_skald",
      "d2_warflame",
      "deathsayer",
      "dm_chancellor",
      "dm_errand",
      "dm_hungerling",
      "dw_bladethrower",
      "dw_brewer",
      "dw_thane",
      "heraldapoc",
      "hoardbreaker",
      "jouster",
      "k_blazer",
      "k_boulderdash",
      "k_crownvein",
      "k_mineralmaster",
      "k_tunnelcharger",
      "n2_abomination",
      "n2_fatecarver",
      "n2_paragon",
      "n2_standardbearer",
      "perfectcore",
      "philippe",
      "raptor",
      "supporter",
      "taragosa",
      "tauntbreaker",
      "thundeer",
      "trophystalker",
      "watcher"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-react",
    "title": "'react' family · 12 cards",
    "statement": "All 12 'react' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "10 effect factories across 12 cards dispatch through the 'react' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Avarice Incarnate: \"The first time another friendly Demon Consumes a Shop minion each turn, this gains the same stats and grants 3 Gold.\" · Members: Avarice Incarnate · Axeman · Enigma · Leech · Impossible Todd · Gryphon · Hunter · Candleback Bulwark · Flowing Monk · Target Dummy · Sergeant · Cratering Hulk",
    "example": "Avarice Incarnate follows the 'react' convention — its trigger fires on friendlyDemonDealtDamage, its numbers double when gilded.",
    "contentIds": [
      "dm_avarice",
      "dm_chosenfiend",
      "dm_jumbo",
      "dm_leech",
      "dm_todd",
      "gryphon",
      "hunter",
      "k_candleback",
      "monk",
      "sandbag",
      "sergeant",
      "thunderingabomination"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-shout",
    "title": "'shout' family · 71 cards",
    "statement": "All 71 'shout' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "48 effect factories across 71 cards dispatch through the 'shout' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Aeon Guard: \"End of Turn: give your Shop spells +1/+1.\" · Members: Aeon Guard · Pennycat · Mage-Pup · Black Belt Brian · Buddy Buddy · Horizon Courier · Herald of the Divide · Astral Relay · Starpath Vendor · Cinderwing Matron · Hoard Cleric · Crypt Broker · … and 59 more",
    "example": "Aeon Guard follows the 'shout' convention — its trigger fires on onPlay, its numbers double when gilded.",
    "contentIds": [
      "aeonguard",
      "alley",
      "b2_magepup",
      "blackbelt",
      "buddy",
      "c3_courier",
      "c3_herald",
      "c3_relay",
      "c3_vendor",
      "cinder",
      "cleric",
      "cryptbroker",
      "d2_blazingkeeper",
      "d2_broodfire",
      "d2_broodwhelp",
      "d2_chronicler",
      "d2_embermouth",
      "d2_felconjurer",
      "d2_flutterdrake",
      "d2_grimoire",
      "d2_recaller",
      "d2_riverdrake",
      "d2_scalefeather",
      "deathswarmer",
      "depositbox",
      "dm_agent",
      "dm_butcher",
      "dm_clerk",
      "dm_curator",
      "dm_malphas",
      "dm_tormentor",
      "dw_brewer",
      "dw_brunni",
      "dw_dorrin",
      "dw_ironlung",
      "dw_orin",
      "dw_pimm",
      "dw_runemaster",
      "dw_sharpshooter",
      "dw_tapkeeper",
      "dw_wardkeeper",
      "emissary",
      "feed",
      "fieldmechanic",
      "graverobber",
      "gravetwin",
      "havendrake",
      "heraldapoc",
      "hoarder",
      "impoverseer",
      "joker",
      "k_alchemist",
      "k_chipwick",
      "k_deepvein",
      "k_frenzied",
      "k_gemline",
      "k_pouchpincher",
      "k_stormchaser",
      "labexperiment",
      "maw",
      "n2_clockwork",
      "n2_conductor",
      "n2_deepchef",
      "n2_muckslinger",
      "nimbus",
      "onthehouse",
      "rubyshipment",
      "scrapherald",
      "seaurchin",
      "squirlscout",
      "wayfinder"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-shoutPayoff",
    "title": "'shoutPayoff' family · 3 cards",
    "statement": "All 3 'shoutPayoff' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 3 cards dispatch through the 'shoutPayoff' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Combinator: \"End of Turn: magnetize a random Magnetic Mech onto 2 friendly Mechs.\" · Members: Combinator · Living Grimoire · Reconfigured Combinator",
    "example": "Combinator follows the 'shoutPayoff' convention — its trigger fires on battlecryTriggered, its numbers double when gilded.",
    "contentIds": [
      "combinator",
      "d2_grimoire",
      "reconfiguredcombinator"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-shoutReact",
    "title": "'shoutReact' family · 6 cards",
    "statement": "All 6 'shoutReact' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "4 effect factories across 6 cards dispatch through the 'shoutReact' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Bane: \"After you trigger a Shout, give your Imps +3/+3 this run.\" · Members: Bane · Herald of the Divide · Embermouth Whelp · Bathing Matriarch · Karwind · Sporeling",
    "example": "Bane follows the 'shoutReact' convention — its trigger fires on battlecryTriggered, its numbers double when gilded.",
    "contentIds": [
      "bane",
      "c3_herald",
      "d2_embermouth",
      "d2_matriarch",
      "karwind",
      "spore"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-slaughter",
    "title": "'slaughter' family · 5 cards",
    "statement": "All 5 'slaughter' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "5 effect factories across 5 cards dispatch through the 'slaughter' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Bounty Bot: \"Immune while attacking (first 2 attacks each combat). Slaughter: gain 2 Gold next shop.\" · Members: Bounty Bot · Gnasher, the Overrun · Karthus · Moe · Sword and Bored",
    "example": "Bounty Bot follows the 'slaughter' convention — its trigger fires on onKill, its numbers double when gilded.",
    "contentIds": [
      "bountybot",
      "gnash",
      "karthus",
      "moe",
      "swordbored"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-spellCast",
    "title": "'spellCast' family · 106 cards",
    "statement": "All 106 'spellCast' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "91 effect factories across 106 cards dispatch through the 'spellCast' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Anomaly Reactor: \"Give a friendly minion All types — it counts as every tribe and gets all of their buffs.\" · Members: Anomaly Reactor · Eyes of Aresmar · Bloodlust · Bulwark · Carnival Coin · Chrono Staff · Common Ground · Consume · Copycat · Cupcakes · Decoy Sigil · Deep Delve Writ · … and 94 more",
    "example": "Anomaly Reactor follows the 'spellCast' convention — its trigger fires on cast, its numbers double when gilded.",
    "contentIds": [
      "anomalyreactor",
      "aresmar",
      "bloodlust",
      "bulwark",
      "carnivalcoin",
      "chronostaff",
      "commonground",
      "consume",
      "copycat",
      "cupcakes",
      "decoysigil",
      "deepdelvewrit",
      "depositbox",
      "devour",
      "displacement",
      "dw_brewer",
      "dw_brunni",
      "dw_tapkeeper",
      "elevationritual",
      "emberpouch",
      "executionersedge",
      "farseersreport",
      "feedalpha",
      "fleetingvigor",
      "foddertreatment",
      "fronttoback",
      "gift_allowance",
      "gift_arcane_clearance",
      "gift_encore",
      "gift_fast_track",
      "gift_friends_family",
      "gift_ironclad",
      "gift_larceny",
      "gift_parting_gifts",
      "gift_premium_stock",
      "gift_regalia",
      "gift_second_calling",
      "gift_special_delivery",
      "gift_unbridled",
      "goldcrafter",
      "goldentouch",
      "greatpot",
      "growth",
      "hoarder",
      "hoardflame",
      "implosion",
      "insurancepolicy",
      "ironcladreq",
      "k_alchemist",
      "k_chipwick",
      "k_deepvein",
      "lanternlight",
      "lanternofsouls",
      "lasso",
      "laststand",
      "layaway",
      "manafont",
      "markedtarget",
      "mend",
      "mightofaeon",
      "onthehouse",
      "openthegates",
      "ossuaryrite",
      "patchjob",
      "perfectvision",
      "powershifter",
      "preemptive",
      "quicksale",
      "quickstudy",
      "rallyoffensive",
      "refreshtexts",
      "resonance",
      "rivalsreflection",
      "rubyexcavation",
      "rubyshipment",
      "rubytransfer",
      "seconddraft",
      "shatter",
      "sigilkinship",
      "sp_beefy",
      "sp_blessing",
      "sp_closedcasket",
      "sp_containmentrune",
      "sp_dragonflame",
      "sp_flutter",
      "sp_gamble",
      "sp_partingcry",
      "sp_solidground",
      "sp_stoleninitiative",
      "sparkplug",
      "spellcart",
      "spiritfire",
      "staffofguel",
      "strangerevision",
      "summoningbulwark",
      "summonstone",
      "tribeschoice",
      "turnabout",
      "undeadarmy",
      "veinstorm",
      "weaken",
      "wo_attack",
      "wo_champion",
      "wo_health",
      "wo_mine",
      "wo_reinforcement"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-startOfCombat",
    "title": "'startOfCombat' family · 23 cards",
    "statement": "All 23 'startOfCombat' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "22 effect factories across 23 cards dispatch through the 'startOfCombat' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Abhorrent Horror: \"Start of Combat: Gain +Attack/+Health equal to the Fodder consumed this turn.\" · Members: Abhorrent Horror · Arena Heckler · Quil · Runebloom Matriarch · Spots · Bloodbinder · Daybreak Acolyte · Horizon Sentinel · Twilight Sentinel · Thunderous Sovereign · Imp Wrangler · Bucky · … and 11 more",
    "example": "Abhorrent Horror follows the 'startOfCombat' convention — its trigger fires on startOfCombat, its numbers double when gilded.",
    "contentIds": [
      "abhorrenthorror",
      "arenaheckler",
      "b2_quil",
      "b2_runebloom",
      "b2_spots",
      "bloodbinder",
      "c3_acolyte",
      "c3_sentinel",
      "c3_twilight",
      "d2_sovereign",
      "dm_wrangler",
      "dw_bucky",
      "dw_oaf",
      "gravebody",
      "gravewarden",
      "k_kobe",
      "kennel",
      "mirrorrhino",
      "packleader",
      "runescale",
      "runmaw",
      "taurus",
      "taurustruth"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-summonReact",
    "title": "'summonReact' family · 13 cards",
    "statement": "All 13 'summonReact' cards trigger the same way, and gilding doubles their numbers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "13 effect factories across 13 cards dispatch through the 'summonReact' presentation family; the factoryPhase lane gates each (trigger, factory) pair.",
    "cardText": "Exemplar — Ashen Heir: \"Whenever an Imp dies, another friendly Imp gains its stats — or the next Imp you summon, if none are alive.\" · Members: Ashen Heir · Beardsley · Groveweaver · King Oona · Vaultkeeper · Broodwright · Chipper · Chef Gary Toast · Grave Body · Den Mother · Pack Leader · Spirit Worgen · … and 1 more",
    "example": "Ashen Heir follows the 'summonReact' convention — its trigger fires on onSummon, its numbers double when gilded.",
    "contentIds": [
      "ashen_heir",
      "b2_beardsley",
      "b2_groveweaver",
      "b2_oona",
      "d2_herzog",
      "dm_broodwright",
      "dm_glutton",
      "dw_chef",
      "gravebody",
      "mamabear",
      "packleader",
      "spiritworgen",
      "thunderingabomination"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts Keyword EG docblock"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-combat-gains",
    "title": "Combat-only stat gains",
    "statement": "Stats gained in combat vanish when the fight ends — unless Engraved or an explicit carry-back keeps them. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "persistence",
    "currentBehaviour": "simulate() returns combat stats separately; only EG minions and persist* channels write back into run state.",
    "cardText": "Exemplar — a minion buffed +4/+4 mid-fight returns to its shop stats at settle unless it carries Engraved.",
    "example": "the same +4/+4 on an Engraved minion IS on the run board next shop."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts CardDef.tribe2/universalTribe docblocks"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-dual-tribe",
    "title": "Dual & universal tribes · 21 carriers",
    "statement": "A dual-tribe minion counts as both tribes, everywhere. A universal minion counts as every tribe. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "isTribe/tribe predicates fold tribe2 and universalTribe; the tribePredicates lane sweeps raw comparisons.",
    "cardText": "Exemplar — Bane: \"After you trigger a Shout, give your Imps +3/+3 this run.\" · Carriers: Bane · Crypt Drake · Crypt Wolf · Ashen Broodlord · Fel Conjurer · Baal · High King Mykel · Mountainbond · Heckbinder · Gemgorge Fiend · Lab Experiment · Evolving Abomination · … and 9 more",
    "example": "Bane receives BOTH tribes' buffs and satisfies either tribe's quest counters.",
    "contentIds": [
      "bane",
      "cryptdrake",
      "cryptwolf",
      "d2_broodlord",
      "d2_felconjurer",
      "dw_baal",
      "dw_brisbane",
      "dw_mountainbond",
      "heckbinder",
      "k_gemgorge",
      "labexperiment",
      "n2_abomination",
      "n2_paragon",
      "n2_standardbearer",
      "perfectcore",
      "philippe",
      "solaris",
      "spiritpup",
      "spiritworgen",
      "symbioticattachment",
      "wolvesden"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts CardDef.gift docblock (owner design 2026-08-26)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-gift-casts",
    "title": "Gifts vs Shop spells",
    "statement": "A Gift counts as a spell cast, but is never a Shop spell — no shop offers, no copies, no cast multipliers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "gifts",
    "currentBehaviour": "The gift flag gates every Shop-spell surface (offers, copies, multipliers); cast bookkeeping treats gifts as real casts.",
    "cardText": "Exemplar — a Gift cast with a spell-copy engine on board: the tally advances, the copier stays silent.",
    "example": "casting a Gift beside a spell copier advances \"spells cast this game\" by 1 and mints no copy."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts CardDef.goldenText docblock"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-gild-default",
    "title": "Gilding default: ×2",
    "statement": "A gilded card doubles its printed numbers. If gilding changes more than the numbers, the card carries its own golden text. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "gilding",
    "currentBehaviour": "320 cards carry authored goldenText; every other card inherits the ×2 number-doubler.",
    "cardText": "Exemplar — Wolves Den: \"Deathrattle: Summon 3 Crypt Wolves.\" → gilded: \"Deathrattle: Summon 6 Crypt Wolves.\"",
    "example": "Wolves Den's gilded text is authored because the count changes shape, not just ×2 digits."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "owner-handoff",
        "ref": "HeroDef.henchman docblock (owner spec 2026-08-03)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-henchman-pricing",
    "title": "Henchman pricing",
    "statement": "Your Henchman is recruitable once per run. Its cost drops 3 after a win, 2 after a loss, never below 0. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "henchmanCostOf applies win −3 / loss −2 with a 0 floor; recruit is once per run. — PARKED BY ARCHIVE 2026-08-28 (owner: \"henchmen are not in the game and are extremely WIP / being removed for now\"). `henchmanOffer` is gated by HENCHMEN_ARCHIVED, so no henchman is offerable and the pricing decay this rule describes cannot be observed in play. The decay STATE still accrues and henchmen.test.ts still asserts it, so the rule remains checkable and un-archiving restores it exactly. The ruling stands — it is the content that is inactive, not the convention.",
    "cardText": "Exemplar — Warden's henchman (hm_test_squire, base 10 Gold): after a win and a loss it costs 10 − 3 − 2 = 5.",
    "example": "base cost 10, then W/L/W → 10 − 3 − 2 − 3 = 2 Gold."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts extraTriggerFires"
      },
      {
        "kind": "owner-handoff",
        "ref": "R-MULT-01 (registry/approved.ts)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-multiplier-gilded",
    "title": "Trigger multipliers · 5 carriers",
    "statement": "Gilded multipliers count double. Stacking copies add up; non-stackers use their best copy; the two pools add together. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "multipliers",
    "currentBehaviour": "extraTriggerFires: contribution = extra × (golden ? 2 : 1); stacking summed, non-stacking best, summed + best returned.",
    "cardText": "Carriers: Chronos · Drakko the Drummer · Sylus the Reaper · Uron, Oathbringer · Zyff, the Betrayer",
    "example": "a gilded Sylus (stacking, extra 1) beside a plain Uron (non-stacking) grants 2 + 1 = 3 extra fires for a shared family.",
    "contentIds": [
      "chronos",
      "drummer",
      "sylus",
      "uron",
      "zyff"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "owner-handoff",
        "ref": "R-AVWIN-04/-05 partial-progress rulings (registry/approved.ts)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-threshold-scope",
    "title": "Threshold counters · 21 Avenge carriers",
    "statement": "Combat counters (Avenge) reset when the fight ends. Shop counters last the whole run. Progress never crosses between them. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "persistence",
    "currentBehaviour": "Avenge progress lives in per-combat instance state; quest/cadence counters live in run state and persist.",
    "cardText": "Exemplar — Dunkey: \"Avenge (4): summon an Armadiyo.\" · Avenge carriers: Dunkey · Solaris · Bone Taxer · Brood Matron · Water Dragon · Broodwright · Grobbus · Endless Overseer · Gemstorm Instigator · Gem Portsmith · Kennelmaster · Muster General · … and 9 more",
    "example": "Dunkey at 2 of 3 deaths when combat ends starts the next combat at 0 — but a quest at 4 of 5 buys stays at 4 next turn.",
    "contentIds": [
      "b2_dunkey",
      "b2_solaris",
      "bonetaxer",
      "brood",
      "d2_curator",
      "dm_broodwright",
      "dm_grobbus",
      "dm_overseer",
      "k_gemstorm",
      "k_portsmith",
      "kennel",
      "n2_muster",
      "pitsupplier",
      "profgreg",
      "solaris",
      "soulsman",
      "sparkcapacitor",
      "spellappraiser",
      "steadfast",
      "stuntdrake",
      "weaver"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/content/src/index.ts ALL_CARDS doctrine comment"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-token-reachability",
    "title": "Never-drawable cards",
    "statement": "Tokens, Gifts, Henchmen and archived cards never appear in shops or random pools. Only a card that names them can create them. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "ALL_CARDS carries every class; poolFor() draws only from set manifests, which exclude all five by construction.",
    "cardText": "Exemplar — Imp (token): reachable only through the Demon cards that summon it; never offered in a shop.",
    "example": "a rune granting Pillager (an out-of-set Undead) still resolves — the grant reaches CARD_INDEX, the pool never offers it."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-c",
    "title": "Cleave [C] · 2 carriers",
    "statement": "Cleave means: its attack also hits both minions adjacent to the target, simultaneously — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Cleave for all 2 carriers.",
    "cardText": "Exemplar — Baby Cub: \"Cleave\" · Carriers: Baby Cub · Broad-Axe Brakka",
    "example": "Baby Cub carries Cleave — in play, its attack also hits both minions adjacent to the target, simultaneously.",
    "contentIds": [
      "babycub",
      "dw_brakka"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-cn",
    "title": "Consume [CN] · 0 carriers",
    "statement": "Consume means: eats another minion, absorbing per its printed rule; the eaten minion is gone — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Consume for all 0 carriers.",
    "cardText": "(no current carrier of Consume)",
    "example": "any future Consume card inherits this meaning."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-cr",
    "title": "Critical Strike [CR] · 5 carriers",
    "statement": "Critical Strike means: a per-card chance to deal double damage on attack — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Critical Strike for all 5 carriers.",
    "cardText": "Exemplar — Guardian Drake: \"(vanilla body with the keyword)\" · Carriers: Guardian Drake · Warflame · Axeman · Mountainbond · Commander Impala",
    "example": "Guardian Drake carries Critical Strike — in play, a per-card chance to deal double damage on attack.",
    "contentIds": [
      "bronzewarden",
      "d2_warflame",
      "dm_chosenfiend",
      "dw_mountainbond",
      "impala"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-ds",
    "title": "Ward [DS] · 16 carriers",
    "statement": "Ward means: negates the first damage this minion would take, then breaks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Ward for all 16 carriers.",
    "cardText": "Exemplar — Beardsley: \"Ward. Whenever you summon a Beast, give it +3/+3. Improves +3/+3 every 3 Beasts summoned.\" · Carriers: Beardsley · Guardian Drake · Transcendant · Hellrider · Impossible Todd · Warding Drone · Mountainbond · Commander Impala · Mechanical Jouster · Gem Portsmith · Resonance Idol · Karthus · … and 4 more",
    "example": "Beardsley carries Ward — in play, negates the first damage this minion would take, then breaks.",
    "contentIds": [
      "b2_beardsley",
      "bronzewarden",
      "d2_transcendence",
      "dm_maw",
      "dm_todd",
      "drone",
      "dw_mountainbond",
      "impala",
      "jouster",
      "k_portsmith",
      "k_resonance",
      "karthus",
      "karwind",
      "perfectcore",
      "tauntbreaker",
      "trainingdummy"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-eg",
    "title": "Engraved [EG] · 4 carriers",
    "statement": "Engraved means: stat gains during combat carry back to the run board permanently — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Engraved for all 4 carriers.",
    "cardText": "Exemplar — Tara: \"Engraved. Grant stats 15 times in combat to ascend.\" · Carriers: Tara · Taragosa · Taragosa's Heir · Thundeer",
    "example": "Tara carries Engraved — in play, stat gains during combat carry back to the run board permanently.",
    "contentIds": [
      "tara",
      "taragosa",
      "taragosaheir",
      "thundeer"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-fd",
    "title": "Fodder [FD] · 1 carriers",
    "statement": "Fodder means: a cheap body meant to be Consumed; Fodder-scaling effects count these — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Fodder for all 1 carriers.",
    "cardText": "Exemplar — Fred: \"A 1/1 Demon Fodder — your Demons devour it from the tavern.\" · Carriers: Fred",
    "example": "Fred carries Fodder — in play, a cheap body meant to be Consumed; Fodder-scaling effects count these.",
    "contentIds": [
      "fred"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-imm",
    "title": "Immune [IMM] · 0 carriers",
    "statement": "Immune means: takes no damage from any source while the keyword holds — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Immune for all 0 carriers.",
    "cardText": "(no current carrier of Immune)",
    "example": "any future Immune card inherits this meaning."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-m",
    "title": "Magnetic [M] · 7 carriers",
    "statement": "Magnetic means: an Attachment: can be played onto a compatible minion, merging stats and effects into it — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Magnetic for all 7 carriers.",
    "cardText": "Exemplar — Better Bot: \"Rally: give your other Mechs +5 Attack. Magnetic — welds onto a Mech, which then grants the buff (stacks).\" · Carriers: Better Bot · Cling Drone · Heckbinder · Money Bot · Perfect Core · Speedy · Chaos Attachment",
    "example": "Better Bot carries Magnetic — in play, an Attachment: can be played onto a compatible minion, merging stats and effects into it.",
    "contentIds": [
      "betterbot",
      "cling",
      "heckbinder",
      "moneybot",
      "perfectcore",
      "speedy",
      "symbioticattachment"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-r",
    "title": "Rise [R] · 3 carriers",
    "statement": "Rise means: the first time this dies, it returns with 1 Health (its Rise spent) — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Rise for all 3 carriers.",
    "cardText": "Exemplar — Anubis: \"Deathrattle: Give your minions Reborn. Cast Lantern of Souls.\" · Carriers: Anubis · Footman · Chaos Attachment",
    "example": "Anubis carries Rise — in play, the first time this dies, it returns with 1 Health (its Rise spent).",
    "contentIds": [
      "anubis",
      "footman",
      "symbioticattachment"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-rl",
    "title": "Rally [RL] · 34 carriers",
    "statement": "Rally means: triggers its effect each time this minion attacks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Rally for all 34 carriers.",
    "cardText": "Exemplar — Echohorn: \"Rally: trigger your left-most Echo.\" · Carriers: Echohorn · Packstrider · Sunmane Herald · Badgington · Better Bot · Equinox Duelist · Chimerus · Chorus Engine · Ashen Broodlord · Chorus Drake · Cinderchef · Embercrest · … and 22 more",
    "example": "Echohorn carries Rally — in play, triggers its effect each time this minion attacks.",
    "contentIds": [
      "b2_echohorn",
      "b2_packstrider",
      "b2_sunmane",
      "badgington",
      "betterbot",
      "c3_equinox",
      "chimerus",
      "chorusengine",
      "d2_broodlord",
      "d2_chorus",
      "d2_cinderchef",
      "d2_embercrest",
      "d2_flamebeat",
      "d2_roarcollector",
      "deathsayer",
      "dm_errand",
      "dm_hungerling",
      "dw_bladethrower",
      "dw_thane",
      "heraldapoc",
      "hoardbreaker",
      "jouster",
      "k_blazer",
      "k_boulderdash",
      "k_crownvein",
      "k_tunnelcharger",
      "n2_abomination",
      "n2_standardbearer",
      "perfectcore",
      "philippe",
      "supporter",
      "tauntbreaker",
      "trophystalker",
      "watcher"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-sc",
    "title": "Start of Combat [SC] · 12 carriers",
    "statement": "Start of Combat means: its effect fires once when combat begins, before any attacks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Start of Combat for all 12 carriers.",
    "cardText": "Exemplar — Abhorrent Horror: \"Start of Combat: Gain +Attack/+Health equal to the Fodder consumed this turn.\" · Carriers: Abhorrent Horror · Quil · Runebloom Matriarch · Spots · Thunderous Sovereign · Bucky · Drunken Oaf · Kobe · Kennelmaster · Speed Demon · Taurus · Taurus the Truth Bringer",
    "example": "Abhorrent Horror carries Start of Combat — in play, its effect fires once when combat begins, before any attacks.",
    "contentIds": [
      "abhorrenthorror",
      "b2_quil",
      "b2_runebloom",
      "b2_spots",
      "d2_sovereign",
      "dw_bucky",
      "dw_oaf",
      "k_kobe",
      "kennel",
      "runmaw",
      "taurus",
      "taurustruth"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-sl",
    "title": "Slaughter [SL] · 5 carriers",
    "statement": "Slaughter means: triggers its effect each time this minion kills an enemy minion — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Slaughter for all 5 carriers.",
    "cardText": "Exemplar — Bounty Bot: \"Immune while attacking (first 2 attacks each combat). Slaughter: gain 2 Gold next shop.\" · Carriers: Bounty Bot · Gnasher, the Overrun · Karthus · Moe · Sword and Bored",
    "example": "Bounty Bot carries Slaughter — in play, triggers its effect each time this minion kills an enemy minion.",
    "contentIds": [
      "bountybot",
      "gnash",
      "karthus",
      "moe",
      "swordbored"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-st",
    "title": "Stealth [ST] · 0 carriers",
    "statement": "Stealth means: cannot be targeted by attacks; lost the moment it attacks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Stealth for all 0 carriers.",
    "cardText": "(no current carrier of Stealth)",
    "example": "any future Stealth card inherits this meaning."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-t",
    "title": "Taunt [T] · 20 carriers",
    "statement": "Taunt means: enemies must attack your Taunt minions before anything else — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Taunt for all 20 carriers.",
    "cardText": "Exemplar — Armadiyo: \"Taunt. Echo: give your Beast Aura +2/+4.\" · Carriers: Armadiyo · Dawnclaw · Wolvie · Blaster · Fel Spikes · Chipper · Knocked · Big Huggies · Brunni · Twilight Emissary · Gryphon · Candleback Bulwark · … and 8 more",
    "example": "Armadiyo carries Taunt — in play, enemies must attack your Taunt minions before anything else.",
    "contentIds": [
      "b2_armadiyo",
      "b2_dawnclaw",
      "b2_wolvie",
      "blaster",
      "dm_felspikes",
      "dm_glutton",
      "dm_knocked",
      "dm_velvet",
      "dw_brunni",
      "emissary",
      "gryphon",
      "k_candleback",
      "k_geode",
      "k_kobe",
      "maw",
      "ryme",
      "sabercub",
      "sandbag",
      "sporebat",
      "trainingdummy"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-v",
    "title": "Venomous [V] · 2 carriers",
    "statement": "Venomous means: destroys whatever it damages; drops off after its first clash (a Cleave clash is simultaneous, so one venom can fell up to three bodies before dropping) — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Venomous for all 2 carriers.",
    "cardText": "Exemplar — Lab Experiment: \"Battlecry: get a Tier 6 minion. Deathrattle: get a Tier 5 minion.\" · Carriers: Lab Experiment · Venom",
    "example": "Lab Experiment carries Venomous — in play, destroys whatever it damages; drops off after its first clash (a Cleave clash is simultaneous, so one venom can fell up to three bodies before dropping).",
    "contentIds": [
      "labexperiment",
      "venom"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-w",
    "title": "Windfury [W] · 4 carriers",
    "statement": "Windfury means: attacks twice per attack turn — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Windfury for all 4 carriers.",
    "cardText": "Exemplar — Commander Impala: \"Flurry. Ward. Critical Strike (50%).\" · Carriers: Commander Impala · Blazer · Speedy · Tauntbreaker",
    "example": "Commander Impala carries Windfury — in play, attacks twice per attack turn.",
    "contentIds": [
      "impala",
      "k_blazer",
      "speedy",
      "tauntbreaker"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-active",
    "title": "'active' powers · 17 heroes",
    "statement": "These 17 powers all fires through the real hero-power action, with at most a board/shop target. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 17 powers as 'active'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Albus, Empowerment: \"Choose a Shop minion. Discover a minion from the tier above it for it to become.\" · Members: Albus — Empowerment [empowerment] · Rascal — All In [allIn] · Darah — Swap [displace] · Devourer — Devour [devour] · Djinni — Cadence [replayAllEndOfTurn] · Fibbsy — Ruby Wealth [rubyWealth] · Frantic Frank — Clearance [clearance] · Harlan — Buyout [buyout] · Jensen — Dynamite Dig [dynamiteDig] · Merrin — Pocket Magic [pocketMagic] · Auctioneer — Pulse [replayBattlecry] · Nadja — Goldspring [gainMaxMana] · Lord of the Risen — Undying [grantReborn] · Sable — Soulbind [soulbind] · Tiff — Dragon Tamer [dragonTamer] · Warden — Aegis [grantWard] · Xerox — Copy Machine [copyMachine]",
    "example": "Albus's Empowerment fires through the real hero-power action, with at most a board/shop target."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-active-conditional",
    "title": "'active-conditional' powers · 5 heroes",
    "statement": "These 5 powers all active, but only against a staged precondition (a pair to complete, a fight behind you, a spell cast). — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 5 powers as 'active-conditional'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Gildmaster, Gildcrafter: \"When you have 2 copies of a minion, this grants a third.\" · Members: Gildmaster — Gildcrafter [gildcrafter] · Hunch — Rounded Spellbook [roundedSpellbook] · Membrance — Memory [memory] · Quillen — Archive [archive] · Underdweller — Soulkeeper [soulkeeper]",
    "example": "Gildmaster's Gildcrafter active, but only against a staged precondition (a pair to complete, a fight behind you, a spell cast)."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-adopted-secondary",
    "title": "'adopted-secondary' powers · 2 heroes",
    "statement": "These 2 powers all adopts other heroes' powers through the pick ceremony. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'adopted-secondary'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Mimic, Mimicry: \"At the start of every turn, Discover a hero power to wield this turn.\" · Members: Mimic — Mimicry [mimic] · Void — Twin Voids [voidTwin]",
    "example": "Mimic's Mimicry adopts other heroes' powers through the pick ceremony."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-combat-trigger",
    "title": "'combat-trigger' powers · 5 heroes",
    "statement": "These 5 powers all the payoff happens inside or around combat. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 5 powers as 'combat-trigger'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Cindara, Hoard: \"Avenge (4): summon a 1/1 Whelp that attacks immediately. Improve your Whelps +2/+2.\" · Members: Cindara — Hoard [hoard] · Gorun — Blade Mastery [bladeMastery] · Rayse — Empowering Vines [empoweringVines] · Soren — Reclaim [resummon] · Emissary — United Front [unitedFront]",
    "example": "Cindara's Hoard the payoff happens inside or around combat."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-count-threshold",
    "title": "'count-threshold' powers · 10 heroes",
    "statement": "These 10 powers all a buy/sell/refresh/tally counter crossing a threshold. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 10 powers as 'count-threshold'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Aevor, Tempest: \"Unlocks after your minions kill 15 enemies. End of Turn: give your left and right-most minions +4/+4. Upgrades every 15 kills.\" · Members: Aevor — Tempest [tempest] · Braum — Investment [investment] · Chronos — Timelapse [questChronos] · Ayse — Lucky Seat [luckySeat] · Drakko — Drumline [quest] · Gorr — Four Peat [fourPeat] · Juggler — Carnival Coin [baldgecoin] · Keshi the Protector — Keshi’s Crown [crownTally] · Pete — Contrabanana [contraband] · Robin — Spoils [sellGold]",
    "example": "Aevor's Tempest a buy/sell/refresh/tally counter crossing a threshold."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-every-n-turns",
    "title": "'every-n-turns' powers · 3 heroes",
    "statement": "These 3 powers all a repeating schedule. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 3 powers as 'every-n-turns'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Chaos, Chaos Bond: \"Start with a Chaos Attachment. Get another every 5 turns.\" · Members: Chaos — Chaos Bond [chaos] · Kindness — Great Presence [greatPresence] · Re-Pete — Second Hand [secondHand]",
    "example": "Chaos's Chaos Bond a repeating schedule."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-modal-choice",
    "title": "'modal-choice' powers · 2 heroes",
    "statement": "These 2 powers all the activation carries a choice payload the player picks. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'modal-choice'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Cassen, Commission: \"Choose a commission — it pays out in a few turns.\" · Members: Cassen — Commission [commission] · Flash — First or Last [firstOrLast]",
    "example": "Cassen's Commission the activation carries a choice payload the player picks."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-passive-pricing",
    "title": "'passive-pricing' powers · 3 heroes",
    "statement": "These 3 powers all an always-on price/rule rewrite. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 3 powers as 'passive-pricing'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Foreman Flint, Company Rate: \"Dwarves cost 2 Gold.\" · Members: Foreman Flint — Company Rate [companyRate] · Tradesman — Frugal [cheapMinions] · Midas — Midas' Touch [midasTouch]",
    "example": "Foreman Flint's Company Rate an always-on price/rule rewrite."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-shop-action-trigger",
    "title": "'shop-action-trigger' powers · 2 heroes",
    "statement": "These 2 powers all rides one specific shop action (a tier-up, a play position). — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'shop-action-trigger'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Emerald Warden, Vanguard: \"When you tier up, get a random minion from the new tier.\" · Members: Emerald Warden — Vanguard [vanguard] · Odelle — Exhibition [exhibition]",
    "example": "Emerald Warden's Vanguard rides one specific shop action (a tier-up, a play position)."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-start-of-run",
    "title": "'start-of-run' powers · 5 heroes",
    "statement": "These 5 powers all the work happens at run creation (opening tokens, locked Discovers, the turn-1 quest offer). — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 5 powers as 'start-of-run'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Brackus, Summit: \"At the start of the game, Discover a Tier 7 minion. It is locked until you spend 70 Gold.\" · Members: Brackus — Summit [summitLock] · Coran — Pathfinder [heroQuest] · Disco Dan — Setlist [discoLock] · Fi — Errand [heroQuest] · Yirin — Reflector [startingReflector]",
    "example": "Brackus's Summit the work happens at run creation (opening tokens, locked Discovers, the turn-1 quest offer)."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-turn-number",
    "title": "'turn-number' powers · 2 heroes",
    "statement": "These 2 powers all opens/fires on one specific turn. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'turn-number'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Guardian, Runeguard: \"On turn 8, visit the Epic Runeforge.\" · Members: Guardian — Runeguard [epicRuneforge] · Runesmith — Forgemaster [runeforge]",
    "example": "Guardian's Runeguard opens/fires on one specific turn."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-unlock-recharge",
    "title": "'unlock-recharge' powers · 3 heroes",
    "statement": "These 3 powers all active, but gated by its own lock/recharge schedule. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 3 powers as 'unlock-recharge'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Aster, the Guide, Preparation: \"Give a friendly minion +1/+1. Recharges every other turn.\" · Members: Aster, the Guide — Preparation [preparation] · Gambler — Dice [dice] · Indy — Masterwork [gild]",
    "example": "Aster, the Guide's Preparation active, but gated by its own lock/recharge schedule."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-combatflag",
    "title": "'combatFlag' rewards · 14 quests",
    "statement": "These 14 quests pay the same 'combatFlag' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 14 through the same 'combatFlag' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Blood Trail (beast, lesser): objective buy × 5 → reward 'combatFlag' · Members: Blood Trail · Assembly Line · Umbral Energy · Deep Hunger · Contract Rewrite · Law of Teeth · The Old Hunt · Feeding Line · Empty Graves · Shared Circuit · Pit Without End · Echoing Coop · … and 2 more",
    "example": "completing Blood Trail pays its 'combatFlag' reward through the shared engine.",
    "contentIds": [
      "q_assembly_line",
      "q_blood_trail",
      "q_burning_legion",
      "q_candlelight_toll",
      "q_contract_rewrite",
      "q_deep_hunger",
      "q_echoing_coop",
      "q_empty_graves",
      "q_feeding_line",
      "q_law_of_teeth",
      "q_pit_without_end",
      "q_shared_circuit",
      "q_the_old_hunt",
      "q_umbral_energy"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-echorepeat",
    "title": "'echoRepeat' rewards · 3 quests",
    "statement": "These 3 quests pay the same 'echoRepeat' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 3 through the same 'echoRepeat' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Grave Contract (neutral, lesser): objective deathrattle × 7 → reward 'echoRepeat' · Members: Grave Contract · Opening Act · Resonant Path",
    "example": "completing Grave Contract pays its 'echoRepeat' reward through the shared engine.",
    "contentIds": [
      "hq_opening_act_echo",
      "hq_resonant_path_echo",
      "q_grave_contract"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-grant",
    "title": "'grant' rewards · 28 quests",
    "statement": "These 28 quests pay the same 'grant' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 28 through the same 'grant' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Forest Grove (beast, lesser): objective summon × 8 → reward 'grant' · Members: Forest Grove · Forager's Trail · Hoard Spark · Coin Hoard · Grave Robber · Scrap Contract · Gilded Chance · Key Findings · Apex Hunt · Trophy Den · Skybound Pact · Kingdom of Bones · … and 16 more",
    "example": "completing Forest Grove pays its 'grant' reward through the shared engine.",
    "contentIds": [
      "hq_gilded_favor",
      "q_apex_hunt",
      "q_barroom_bounty",
      "q_chimerus",
      "q_coin_hoard",
      "q_company_recruitment",
      "q_death_writes_twice",
      "q_echo_chamber",
      "q_first_blood",
      "q_first_strike",
      "q_foragers_trail",
      "q_forest_grove",
      "q_gilded_chance",
      "q_grave_robber",
      "q_hoard_spark",
      "q_impossible_shop",
      "q_key_findings",
      "q_kingdom_of_bones",
      "q_machine_chorus",
      "q_market_feast",
      "q_maw_of_the_run",
      "q_perfect_machine",
      "q_pivot_door",
      "q_scrap_contract",
      "q_skybound_pact",
      "q_taragosas_inheritance",
      "q_trophy_den",
      "q_true_contract"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-multi",
    "title": "'multi' rewards · 20 quests",
    "statement": "These 20 quests pay the same 'multi' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 20 through the same 'multi' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Imp Census (demon, lesser): objective summonImp × 4 → reward 'multi' · Members: Imp Census · Dark Bargain · The Epic Runeforge · Feed the Alpha · Hoardwake Ritual · Overclocked Core · Leader of the Pack · Anomalous Reactor · Parliament of Flame · Funeral Engine · Infinite Assembly · Rulebreaker's Crown · … and 8 more",
    "example": "completing Imp Census pays its 'multi' reward through the shared engine.",
    "contentIds": [
      "hq_summit_passage",
      "q_anomalous_reactor",
      "q_banes_existence",
      "q_company_store",
      "q_cratering_missive",
      "q_dark_bargain",
      "q_epic_commission",
      "q_feed_the_alpha",
      "q_funeral_engine",
      "q_heart_of_the_mountain",
      "q_hoardwake_ritual",
      "q_imp_census",
      "q_infinite_assembly",
      "q_leader_of_the_pack",
      "q_overclocked_core",
      "q_parliament_of_flame",
      "q_passing_spears",
      "q_rulebreakers_crown",
      "q_sealed_vault",
      "q_stock_the_shelves"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-rallyrepeat",
    "title": "'rallyRepeat' rewards · 3 quests",
    "statement": "These 3 quests pay the same 'rallyRepeat' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 3 through the same 'rallyRepeat' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Spark Permit (neutral, lesser): objective castSpell × 10 → reward 'rallyRepeat' · Members: Spark Permit · Opening Act · Resonant Path",
    "example": "completing Spark Permit pays its 'rallyRepeat' reward through the shared engine.",
    "contentIds": [
      "hq_opening_act_rally",
      "hq_resonant_path_rally",
      "q_spark_permit"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-recurringendofturn",
    "title": "'recurringEndOfTurn' rewards · 6 quests",
    "statement": "These 6 quests pay the same 'recurringEndOfTurn' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 6 through the same 'recurringEndOfTurn' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Echoing Roar (dragon, greater): objective shout × 7 → reward 'recurringEndOfTurn' · Members: Echoing Roar · Blueprint Cache · Forsaken Speed · Clinging On · Open Tab · Runic Refrain",
    "example": "completing Echoing Roar pays its 'recurringEndOfTurn' reward through the shared engine.",
    "contentIds": [
      "q_blueprint_cache",
      "q_clinging_on",
      "q_echoing_roar",
      "q_forsaken_speed",
      "q_open_tab",
      "q_runic_refrain"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-recurringgrant",
    "title": "'recurringGrant' rewards · 3 quests",
    "statement": "These 3 quests pay the same 'recurringGrant' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 3 through the same 'recurringGrant' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — The Red Trail (beast, greater): objective spendGold × 18 → reward 'recurringGrant' · Members: The Red Trail · Ossuary Rite · Implosion",
    "example": "completing The Red Trail pays its 'recurringGrant' reward through the shared engine.",
    "contentIds": [
      "q_implosion",
      "q_ossuary_rite",
      "q_the_red_trail"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-residual",
    "title": "Rarer reward kinds · 40 quests",
    "statement": "These rarer reward kinds all use the same shared engine — no special cases: 'shoutRepeat' ×3, 'spellRepeat' ×3, 'gainGold' ×2, 'grantRune' ×2, 'minionCost' ×2, 'rubyExtraCasts' ×2, 'rubyStatGain' ×2, 'aleExtraCasts' ×1, 'attachmentDeal' ×1, 'beastPlayBuff' ×1, 'boneThrone' ×1, 'consumeDoubleFirstEachTurn' ×1, 'discover' ×1, 'dupeFirstBuy' ×1, 'endlessVerse' ×1, 'fodderReward' ×1, 'freeFirstBuy' ×1, 'friedCircuits' ×1, 'gainMaxGold' ×1, 'gildCopies' ×1, 'goldFodder' ×1, 'motherlode' ×1, 'questGoldTribeBuff' ×1, 'scalingTribeAura' ×1, 'scheduleRuneforge' ×1, 'shopBuffOnRefresh' ×1, 'shopBuffPerShouts' ×1, 'shoutEdgeBuff' ×1, 'tier7Access' ×1, 'tribeRallySlaughterExtra' ×1, 'undeadSpellAura' ×1. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "Each kind is one applyQuestReward branch; no per-quest special cases. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "'shoutRepeat': Warm Embers · 'spellRepeat': Spell Thesis · 'gainGold': Bone Ledger · 'grantRune': Spare Forge · 'minionCost': Merchant's Mark · 'rubyExtraCasts': Gem Circuit · 'rubyStatGain': Open the Vein · 'aleExtraCasts': Bottomless Cellar · 'attachmentDeal': Attachment Issues · 'beastPlayBuff': Den Marker",
    "example": "Warm Embers pays its 'shoutRepeat' reward through the same engine as every other quest.",
    "contentIds": [
      "hq_first_pick",
      "hq_gilded_shortcut",
      "hq_merchants_road",
      "hq_open_road",
      "hq_opening_act_shout",
      "hq_resonant_path_shout",
      "hq_runic_passage",
      "hq_spare_forge",
      "q_ancient_runes",
      "q_attachment_issues",
      "q_banes_presence",
      "q_bone_ledger",
      "q_bottomless_banquet",
      "q_bottomless_cellar",
      "q_den_marker",
      "q_dupes",
      "q_endless_inventory",
      "q_endless_verse",
      "q_faultline_coronation",
      "q_food_for_gold",
      "q_forsaken_will",
      "q_fried_circuits",
      "q_gem_circuit",
      "q_golden_ledger",
      "q_merchants_mark",
      "q_motherlode",
      "q_odd_jobs",
      "q_open_the_vein",
      "q_pack_mentality",
      "q_runic_apprenticeship",
      "q_shop_license",
      "q_small_offering",
      "q_spell_thesis",
      "q_teleport_summit",
      "q_the_bone_throne",
      "q_the_runeforge",
      "q_twin_sun_oath",
      "q_unstable_riches",
      "q_war_council",
      "q_warm_embers"
    ]
  }
] as GameRule[];
