/**
 * GENERATED by `npm run docbot:text` — do not hand-edit. 10 wording questions for the
 * owner's Sitting 3 (Doc Bot 2.0 WP E; blueprint §11.3): one card per language-guide rule whose printed
 * usage is measured INCONSISTENT — both spellings live in the corpus, the owner picks the canon. Cards
 * are self-contained (verbatim exemplars from BOTH sides, one concrete example, ✓/✕/✎ click semantics)
 * and decided through the SAME board + decisions.json as every other pending rule. Decisions survive
 * regeneration; rejects tombstone; a pair whose text becomes consistent self-retires on the next run.
 */
import type { GameRule } from '../schema';

export const WORDING_PENDING: GameRule[] = [
  {
    "id": "q-word-lg-duration-01",
    "title": "Wording: run vs game · 10 vs 14",
    "statement": "Run-long effects say \"this run\" / \"for the rest of the run\" — never \"game\". — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"this run\" in 10 printed texts, \"this game\" in 14. Approving picks \"this run\"; the LG-DURATION-01 guide predicate then watches new text.",
    "cardText": "\"this run\" — Bane: \"After you trigger a Shout, give your Imps +3/+3 this run.\" · \"this game\" — Vaultkeeper: \"Gain +2/+2 whenever you play a Dragon. Improves +2/+2 for every 4 spells cast this game.\"",
    "example": "Vaultkeeper would be re-worded to the \"this run\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-DURATION-01 (corpus survey: 10 vs 14)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "d2_herzog",
      "dm_shepherd",
      "dm_todd",
      "gift_premium_stock",
      "impoverseer",
      "lanternofsouls",
      "staffofguel"
    ]
  },
  {
    "id": "q-word-lg-gild-01",
    "title": "Wording: Gilded vs Golden · 8 vs 7",
    "statement": "Upgraded cards are called \"Gilded\" in text; every \"Golden\"/\"golden\" is updated to match. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"Gilded\" in 8 printed texts, \"Golden\" in 7. Approving picks \"Gilded\"; the LG-GILD-01 guide predicate then watches new text.",
    "cardText": "\"Gilded\" — Dunkey: \"Avenge (4): summon a Gilded Armadiyo.\" · \"Golden\" — Eyes of Aresmar: \"Make a Tier 4 or lower minion Golden.\"",
    "example": "Eyes of Aresmar would be re-worded to the \"Gilded\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-GILD-01 (corpus survey: 8 vs 7)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "aresmar",
      "dw_chickenbrawl",
      "goldcrafter",
      "goldentouch",
      "rune_golden_splinter",
      "salvatore",
      "steadfast"
    ]
  },
  {
    "id": "q-word-lg-keyword-01",
    "title": "Wording: Ward vs Divine Shield · 43 vs 2",
    "statement": "The shield keyword prints \"Ward\" everywhere; the last \"Divine Shield\" texts are updated to match. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"Ward\" in 43 printed texts, \"Divine Shield\" in 2. Approving picks \"Ward\"; the LG-KEYWORD-01 guide predicate then watches new text.",
    "cardText": "\"Ward\" — Beardsley: \"Ward. Whenever you summon a Beast, give it +3/+3. Improves +3/+3 every 3 Beasts summoned.\" · \"Divine Shield\" — Selfless Sentinel: \"Deathrattle: give a friend a Divine Shield.\"",
    "example": "Selfless Sentinel would be re-worded to the \"Ward\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-KEYWORD-01 (corpus survey: 43 vs 2)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "selfless"
    ]
  },
  {
    "id": "q-word-lg-numeral-01",
    "title": "Wording: Gold vs g · 67 vs 2",
    "statement": "Money always prints as \"N Gold\" — never the \"Ng\" abbreviation. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"N Gold\" in 67 printed texts, \"Ng\" in 2. Approving picks \"N Gold\"; the LG-NUMERAL-01 guide predicate then watches new text.",
    "cardText": "\"N Gold\" — Bone Taxer: \"Avenge (4): get 2 Gold next shop. Deathrattle: raise your maximum Gold by 1.\" · \"Ng\" — Trail Forager: \"Sells for 3g, plus 1g for every Beast you play.\"",
    "example": "Trail Forager would be re-worded to the \"N Gold\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-NUMERAL-01 (corpus survey: 67 vs 2)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "trailforager"
    ]
  },
  {
    "id": "q-word-lg-position-01",
    "title": "Wording: left-most vs leftmost · 68 vs 3",
    "statement": "Positional words are hyphenated: \"left-most\" / \"right-most\", never \"leftmost\". — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"left-most\" in 68 printed texts, \"leftmost\" in 3. Approving picks \"left-most\"; the LG-POSITION-01 guide predicate then watches new text.",
    "cardText": "\"left-most\" — Echohorn: \"Rally: trigger your left-most Echo.\" · \"leftmost\" — Deathsayer: \"Rally: before this attacks, trigger your leftmost Deathrattle.\"",
    "example": "Deathsayer would be re-worded to the \"left-most\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-POSITION-01 (corpus survey: 68 vs 3)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "deathsayer",
      "gravebody"
    ]
  },
  {
    "id": "q-word-lg-trigger-01",
    "title": "Wording: Shout vs Battlecry · 110 vs 42",
    "statement": "On-play triggers print \"Shout\" everywhere; every \"Battlecry\" in card text is updated to match. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"Shout\" in 110 printed texts, \"Battlecry\" in 42. Approving picks \"Shout\"; the LG-TRIGGER-01 guide predicate then watches new text.",
    "cardText": "\"Shout\" — Dawnclaw: \"Taunt. Echo: trigger an adjacent minion's Shout.\" · \"Battlecry\" — Pennycat: \"Battlecry: summon a 1/1 Stray next to it.\"",
    "example": "Pennycat would be re-worded to the \"Shout\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-TRIGGER-01 (corpus survey: 110 vs 42)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "alley",
      "blackbelt",
      "cleric",
      "cryptbroker",
      "deathswarmer",
      "emissary",
      "fieldmechanic",
      "graverobber",
      "gravetwin",
      "havendrake",
      "helpwanted",
      "hoarder",
      "joker",
      "labexperiment",
      "nimbus",
      "resonance",
      "ryme",
      "scrapherald",
      "seaurchin",
      "spore",
      "squirlscout",
      "wayfinder",
      "zyff"
    ]
  },
  {
    "id": "q-word-lg-trigger-02",
    "title": "Wording: Echo vs Deathrattle · 98 vs 53",
    "statement": "On-death triggers print \"Echo\" everywhere; every \"Deathrattle\" in card text is updated to match. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"Echo\" in 98 printed texts, \"Deathrattle\" in 53. Approving picks \"Echo\"; the LG-TRIGGER-02 guide predicate then watches new text.",
    "cardText": "\"Echo\" — Armadiyo: \"Taunt. Echo: give your Beast Aura +2/+4.\" · \"Deathrattle\" — Amun Rab: \"Deathrattle: Summon 7 Imps and give your Imps +5/+5.\"",
    "example": "Amun Rab would be re-worded to the \"Echo\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-TRIGGER-02 (corpus survey: 98 vs 53)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "amunrab",
      "anubis",
      "bonetaxer",
      "broodmother",
      "corpseboard",
      "deathlesshand",
      "deathsayer",
      "graverobber",
      "gravetwin",
      "impking",
      "jenkins",
      "junk",
      "labexperiment",
      "manasaber",
      "mumi",
      "nanon",
      "ossuaryrite",
      "pack",
      "pillager",
      "ryme",
      "scrapvendor",
      "selfless",
      "sergeant",
      "spore",
      "trickster",
      "twilightwhelp",
      "wolvesden",
      "zyff"
    ]
  },
  {
    "id": "q-word-lg-verb-01",
    "title": "Wording: trigger vs fire/proc · 93 vs 2",
    "statement": "Effects \"trigger\" — never \"fire\" or \"proc\". The three straggler texts are updated to match. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"trigger\" in 93 printed texts, \"fire/proc\" in 2. Approving picks \"trigger\"; the LG-VERB-01 guide predicate then watches new text.",
    "cardText": "\"trigger\" — Dawnclaw: \"Taunt. Echo: trigger an adjacent minion's Shout.\" · \"fire/proc\" — Graverobber: \"Battlecry: Destroy a friendly minion (procs its Deathrattle), then add a random Shop spell of its tier to your hand.\"",
    "example": "Graverobber would be re-worded to the \"trigger\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-VERB-01 (corpus survey: 93 vs 2)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "graverobber"
    ]
  },
  {
    "id": "q-word-lg-verb-02",
    "title": "Wording: Consume vs devour · 23 vs 2",
    "statement": "The eat mechanic is the keyword \"Consume\" — flavor \"devour\" is reserved for non-mechanical prose. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"Consume\" in 23 printed texts, \"devour\" in 2. Approving picks \"Consume\"; the LG-VERB-02 guide predicate then watches new text.",
    "cardText": "\"Consume\" — Abyssal Feeder: \"End of Turn: adjacent minions each Consume a Fodder.\" · \"devour\" — Channeling the Devourer: \"Devour a friendly minion and spit its stats onto a random other friend.\"",
    "example": "Channeling the Devourer would be re-worded to the \"Consume\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-VERB-02 (corpus survey: 23 vs 2)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "devour",
      "fred"
    ]
  },
  {
    "id": "q-word-lg-zone-01",
    "title": "Wording: Shop vs tavern · 196 vs 9",
    "statement": "The buy row is always \"the Shop\" in text; every remaining \"tavern\" is updated to match. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "text",
    "status": "needs-ruling",
    "currentBehaviour": "Both spellings are live: \"Shop\" in 196 printed texts, \"tavern\" in 9. Approving picks \"Shop\"; the LG-ZONE-01 guide predicate then watches new text.",
    "cardText": "\"Shop\" — Aeon Guard: \"End of Turn: give your Shop spells +1/+1.\" · \"tavern\" — Korok, the Hungerer: \"When you buy 4 cards, give your Fodder +1/+1 and add 1 Fodder to your next tavern.\"",
    "example": "Korok, the Hungerer would be re-worded to the \"Shop\" form; mechanics untouched.",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "textParse.wording · LG-ZONE-01 (corpus survey: 196 vs 9)"
      }
    ],
    "sourceQueue": "textParse.wording",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "textParse"
      ]
    },
    "contentIds": [
      "acid",
      "displacement",
      "fred",
      "goldentouch",
      "lanternlight",
      "lasso",
      "spellcart",
      "tribeschoice"
    ]
  }
] as GameRule[];
