/**
 * GENERATED by `npm run contracts:extract` — do not hand-edit. 71 convention questions
 * for the owner's Sitting 1 (Doc Bot 2.0 WP B; owner-review-pipeline.md §3/§5): one card per FAMILY —
 * presentation timing families, keyword contracts, hero-power activation families, quest reward shapes,
 * and the global conventions owner specs established but no R- rule yet pins. Every card is self-contained
 * (verbatim exemplar text, one concrete example, explicit ✓/✎/✕ click semantics, the member list) and
 * decided through the SAME board + decisions.json as every other pending rule. Decisions survive
 * regeneration; rejects tombstone into retired.generated.ts via the shared seed-hygiene pass.
 */
import type { GameRule } from '../schema';

export const CONVENTION_PENDING: GameRule[] = [
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-avenge",
    "title": "'avenge' family · 18 cards",
    "statement": "All 18 'avenge' cards trigger the same way. Gilding doubles their output, except a few that summon a gilded token or add a proc. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "19 effect factories across 18 cards dispatch through the 'avenge' presentation family, all on the single trigger 'avenge' (combat); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline, with Dunkey/Muster General/Steadfast Sentinel summoning a GILDED token at the same count, and Gemstorm Instigator buying one extra proc (owner ruling 2026-08-28).",
    "cardText": "Exemplar — Dunkey: \"Avenge (4): summon an Armadiyo.\" · Members: Dunkey · Solaris · Bone Taxer · Brood Matron · Grobbus · Gemstorm Instigator · Gem Portsmith · Kennelmaster · Muster General · Pit Supplier · Professor Greg · Solaris Fang · … and 6 more",
    "example": "Dunkey follows the 'avenge' convention — its trigger fires on avenge. Gilded Dunkey summons ONE gilded Armadiyo, not two plain ones.",
    "contentIds": [
      "b2_dunkey",
      "b2_solaris",
      "bonetaxer",
      "brood",
      "dm_grobbus",
      "k_gemstorm",
      "k_portsmith",
      "kennel",
      "n2_muster",
      "pitsupplier",
      "profgreg",
      "solaris",
      "soulsman",
      "sparkcapacitor",
      "spellappraiser",
      "steadfast",
      "stuntdrake",
      "weaver"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-castPayoff",
    "title": "'castPayoff' family · 4 cards",
    "statement": "All 4 'castPayoff' cards trigger the same way. Gilding doubles their output, except High King Mykel, whose gild widens its targets instead. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "4 effect factories across 4 cards dispatch through the 'castPayoff' presentation family, all on the single trigger 'spellCast' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline (gilded Baal consumes 2 Shop minions), with High King Mykel reshaped instead — one adjacent Shout becomes BOTH adjacent (owner ruling 2026-08-28).",
    "cardText": "Exemplar — Spell Warden: \"After you cast your second Shop spell each turn, get a copy of the first.\" · Members: Spell Warden · Baal · High King Mykel · Spirit Pup",
    "example": "Spell Warden follows the 'castPayoff' convention — its trigger fires on spellCast. Gilded Baal doubles its consume quantity; gilded High King Mykel triggers both adjacent Shouts.",
    "contentIds": [
      "d2_spellkeeper",
      "dw_baal",
      "dw_brisbane",
      "spiritpup"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-castReact",
    "title": "'castReact' family · 5 cards",
    "statement": "All 5 'castReact' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "8 effect factories across 5 cards dispatch through the 'castReact' presentation family, all on the single trigger 'spellCast' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Earthbreaker: \"Whenever you cast a Shop spell, give your Dragons +2/+3.\" · Members: Earthbreaker · Forsaken Mage · Archmagus Guel · Fatecarver · Runescale Drake",
    "example": "Earthbreaker follows the 'castReact' convention — its trigger fires on spellCast. its printed numbers double when the card is gilded.",
    "contentIds": [
      "d2_scalechanter",
      "forsakenweaver",
      "guel",
      "n2_fatecarver",
      "runescale"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-echo",
    "title": "'echo' family · 57 cards",
    "statement": "All 57 'echo' cards trigger the same way. Gilding doubles their output; a few summon a gilded token instead. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "43 effect factories across 57 cards dispatch through the 'echo' presentation family, all on the single trigger 'onDeath' (both); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline is the safe reading, with Void Panther / T-Rex / Chicken Brawl gilding the token they summon instead of doubling the count (owner ruling 2026-08-28).",
    "cardText": "Exemplar — Amun Rab: \"Deathrattle: Summon 7 Imps and give your Imps +5/+5.\" · Members: Amun Rab · Anubis · Ashen Heir · Armadiyo · Bullseye · Dawnclaw · Menagerie Mammoth · T-Rex · Voidmother · Wolvie · Bone Taxer · Brood Matron · … and 45 more",
    "example": "Amun Rab follows the 'echo' convention — its trigger fires on onDeath. Gilded T-Rex summons one GILDED T-Rex Baby, while gilded Wolves Den summons 6 Crypt Wolves instead of 3.",
    "contentIds": [
      "amunrab",
      "anubis",
      "ashen_heir",
      "b2_armadiyo",
      "b2_bullseye",
      "b2_dawnclaw",
      "b2_mammoth",
      "b2_trex",
      "b2_voidmother",
      "b2_wolvie",
      "bonetaxer",
      "brood",
      "broodmother",
      "burialimp",
      "chefraag",
      "d2_scalefeather",
      "deathlesshand",
      "dm_felspikes",
      "dm_hank",
      "dm_knocked",
      "dm_malphas",
      "dm_shepherd",
      "dm_velvet",
      "dw_anvilshade",
      "dw_brewer",
      "dw_chickenbrawl",
      "dw_exgalloper",
      "grim",
      "impking",
      "impoverseer",
      "jenkins",
      "junk",
      "k3_veinchant",
      "k_alchemist",
      "k_faultline",
      "k_gemheart",
      "k_geode",
      "k_kobabyboldies",
      "knit",
      "labexperiment",
      "manasaber",
      "mossmemory_colossus",
      "mumi",
      "n2_echomimic",
      "n2_lastlight",
      "nanon",
      "pack",
      "pillager",
      "runesnout_archivist",
      "ryme",
      "scrapvendor",
      "selfless",
      "sergeant",
      "spore",
      "trickster",
      "twilightwhelp",
      "wolvesden"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-endOfTurn",
    "title": "'endOfTurn' family · 25 cards",
    "statement": "All 25 'endOfTurn' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "31 effect factories across 25 cards dispatch through the 'endOfTurn' presentation family, all on the single trigger 'endOfTurn' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Abyssal Feeder: \"End of Turn: adjacent minions each Consume a Fodder.\" · Members: Abyssal Feeder · Aeon Guard · Moira · Stonehorn Archivist · Combinator · Crypt Scribe · Skybound Ascendant · Soul Defiler · Bob Blart · Arnold · Brunni · Kringle · … and 13 more",
    "example": "Abyssal Feeder follows the 'endOfTurn' convention — its trigger fires on endOfTurn. its printed numbers double when the card is gilded.",
    "contentIds": [
      "abyssalfeeder",
      "aeonguard",
      "b2_moira",
      "b2_stonehorn",
      "combinator",
      "cryptscribe",
      "d2_ascendant",
      "dm_curator",
      "dm_gourmand",
      "dw_arnold",
      "dw_brunni",
      "dw_foreman",
      "feastingbogrot",
      "frontdrake",
      "hoardwhelp",
      "k_alchemist",
      "k_gemline",
      "maw",
      "moneymaker",
      "n2_bellringer",
      "ritualist",
      "ropewrangler",
      "scrapvendor",
      "skybound",
      "stewardofspells"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-grant",
    "title": "'grant' family · 3 cards",
    "statement": "All 3 'grant' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "1 effect factories across 3 cards dispatch through the 'grant' presentation family, all on the single trigger 'equip' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Alchemist Frank: \"Equip Bloodpot (1): Give a friendly minion +3/+3.\" · Members: Alchemist Frank · Titan Sculptor · Blast Surveyor",
    "example": "Alchemist Frank follows the 'grant' convention — its trigger fires on equip. its printed numbers double when the card is gilded.",
    "contentIds": [
      "e3_frank",
      "e3_sculptor",
      "k3_blastsurveyor"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-passive",
    "title": "'passive' family · 2 cards",
    "statement": "All 2 'passive' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch through the 'passive' presentation family, all on the single trigger 'passive' (both); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Deepdelve Paragon: \"Rubies applied in combat give 2× stats.\" · Members: Deepdelve Paragon · Ancient Wanderer",
    "example": "Deepdelve Paragon follows the 'passive' convention — its trigger fires on passive. its printed numbers double when the card is gilded.",
    "contentIds": [
      "k_deepdelve",
      "n2_wanderer"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-rally",
    "title": "'rally' family · 40 cards",
    "statement": "All 40 'rally' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "41 effect factories across 40 cards dispatch through the 'rally' presentation family, all on the single trigger 'onAttack' (both); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Echohorn: \"Rally: trigger your left-most Echo.\" · Members: Echohorn · Hawkus · Packstrider · Sunmane Herald · Chimerus · Chorus Engine · Crypt Drake · Chorus Drake · Cinderchef · Embercrest · Flamebeat Drake · Roarcollector · … and 28 more",
    "example": "Echohorn follows the 'rally' convention — its trigger fires on onAttack. its printed numbers double when the card is gilded.",
    "contentIds": [
      "b2_echohorn",
      "b2_hawkus",
      "b2_packstrider",
      "b2_sunmane",
      "chimerus",
      "chorusengine",
      "cryptdrake",
      "d2_chorus",
      "d2_cinderchef",
      "d2_embercrest",
      "d2_flamebeat",
      "d2_roarcollector",
      "d2_skald",
      "d2_warflame",
      "deathsayer",
      "dm_hungerling",
      "dw_bladethrower",
      "dw_thane",
      "heraldapoc",
      "hoardbreaker",
      "jouster",
      "k3_korn",
      "k_blazer",
      "k_boulderdash",
      "k_crownvein",
      "k_mineralmaster",
      "k_tunnelcharger",
      "n2_abomination",
      "n2_fatecarver",
      "n2_paragon",
      "n2_standardbearer",
      "perfectcore",
      "philippe",
      "raptor",
      "supporter",
      "taragosa",
      "tauntbreaker",
      "thundeer",
      "trophystalker",
      "watcher"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-shout",
    "title": "'shout' family · 53 cards",
    "statement": "All 53 'shout' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "48 effect factories across 53 cards dispatch through the 'shout' presentation family, all on the single trigger 'onPlay' (both); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Pennycat: \"Battlecry: summon a 1/1 Stray next to it.\" · Members: Pennycat · Mage-Pup · Black Belt Brian · Buddy Buddy · Cinderwing Matron · Hoard Cleric · Crypt Broker · Commander Warpath · Broodfire · Brood Whelp · Scalefeather · Flutterdrake · … and 41 more",
    "example": "Pennycat follows the 'shout' convention — its trigger fires on onPlay. its printed numbers double when the card is gilded.",
    "contentIds": [
      "alley",
      "b2_magepup",
      "blackbelt",
      "buddy",
      "cinder",
      "cleric",
      "cryptbroker",
      "d2_blazingkeeper",
      "d2_broodfire",
      "d2_broodwhelp",
      "d2_chronicler",
      "d2_flutterdrake",
      "d2_grimoire",
      "d2_recaller",
      "d2_scalefeather",
      "deathswarmer",
      "dm_agent",
      "dm_butcher",
      "dm_malphas",
      "dm_tormentor",
      "dw_brewer",
      "dw_dorrin",
      "dw_ironlung",
      "dw_orin",
      "dw_pimm",
      "dw_runemaster",
      "dw_sharpshooter",
      "dw_wardkeeper",
      "emissary",
      "feed",
      "fieldmechanic",
      "graverobber",
      "gravetwin",
      "havendrake",
      "heraldapoc",
      "hoarder",
      "impoverseer",
      "joker",
      "k_alchemist",
      "k_chipwick",
      "k_deepvein",
      "k_frenzied",
      "k_stormchaser",
      "labexperiment",
      "n2_clockwork",
      "n2_conductor",
      "n2_deepchef",
      "n2_muckslinger",
      "nimbus",
      "scrapherald",
      "seaurchin",
      "squirlscout",
      "wayfinder"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-shoutPayoff",
    "title": "'shoutPayoff' family · 2 cards",
    "statement": "All 2 'shoutPayoff' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch through the 'shoutPayoff' presentation family, all on the single trigger 'battlecryTriggered' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Living Grimoire: \"The first spell you cast each turn casts twice. Once used, trigger 3 Shouts to reset this.\" · Members: Living Grimoire · Reconfigured Combinator",
    "example": "Living Grimoire follows the 'shoutPayoff' convention — its trigger fires on battlecryTriggered. its printed numbers double when the card is gilded.",
    "contentIds": [
      "d2_grimoire",
      "reconfiguredcombinator"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-shoutReact",
    "title": "'shoutReact' family · 4 cards",
    "statement": "All 4 'shoutReact' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "4 effect factories across 4 cards dispatch through the 'shoutReact' presentation family, all on the single trigger 'battlecryTriggered' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Bane: \"After you trigger a Shout, give your Imps +3/+3 this run.\" · Members: Bane · Embermouth Whelp · Karwind · Sporeling",
    "example": "Bane follows the 'shoutReact' convention — its trigger fires on battlecryTriggered. its printed numbers double when the card is gilded.",
    "contentIds": [
      "bane",
      "d2_embermouth",
      "karwind",
      "spore"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-slaughter",
    "title": "'slaughter' family · 5 cards",
    "statement": "All 5 'slaughter' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "5 effect factories across 5 cards dispatch through the 'slaughter' presentation family, all on the single trigger 'onKill' (combat); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Bounty Bot: \"Immune while attacking (first 2 attacks each combat). Slaughter: gain 2 Gold next shop.\" · Members: Bounty Bot · Gnasher, the Overrun · Karthus · Moe · Sword and Bored",
    "example": "Bounty Bot follows the 'slaughter' convention — its trigger fires on onKill. its printed numbers double when the card is gilded.",
    "contentIds": [
      "bountybot",
      "gnash",
      "karthus",
      "moe",
      "swordbored"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-spellCast",
    "title": "'spellCast' family · 99 cards",
    "statement": "All 99 'spellCast' cards trigger the same way. These are the spells themselves, and spells are never gilded. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "90 effect factories across 99 cards dispatch through the 'spellCast' presentation family, all on the single trigger 'cast' (recruit); the factoryPhase lane gates each (trigger, factory) pair. Gilding: INAPPLICABLE — checkTriples skips spells and Rubies, so no member of this family can ever BE gilded (R-GILD-02, owner ruling 2026-08-28).",
    "cardText": "Exemplar — Anomaly Reactor: \"Give a friendly minion All types — it counts as every tribe and gets all of their buffs.\" · Members: Anomaly Reactor · Eyes of Aresmar · Bloodlust · Bulwark · Carnival Coin · Chrono Staff · Common Ground · Consume · Copycat · Cupcakes · Decoy Sigil · Deep Delve Writ · … and 87 more",
    "example": "Anomaly Reactor follows the 'spellCast' convention — its trigger fires on cast. three copies of it never combine into a golden one, so it has no gilded form at all.",
    "contentIds": [
      "anomalyreactor",
      "aresmar",
      "bloodlust",
      "bulwark",
      "carnivalcoin",
      "chronostaff",
      "commonground",
      "consume",
      "copycat",
      "cupcakes",
      "decoysigil",
      "deepdelvewrit",
      "depositbox",
      "devour",
      "displacement",
      "elevationritual",
      "emberpouch",
      "executionersedge",
      "farseersreport",
      "feedalpha",
      "fleetingvigor",
      "foddertreatment",
      "fronttoback",
      "gift_allowance",
      "gift_arcane_clearance",
      "gift_encore",
      "gift_fast_track",
      "gift_friends_family",
      "gift_ironclad",
      "gift_larceny",
      "gift_parting_gifts",
      "gift_premium_stock",
      "gift_regalia",
      "gift_second_calling",
      "gift_special_delivery",
      "gift_unbridled",
      "goldcrafter",
      "goldentouch",
      "greatpot",
      "growth",
      "hoardflame",
      "implosion",
      "insurancepolicy",
      "ironcladreq",
      "lanternlight",
      "lanternofsouls",
      "lasso",
      "laststand",
      "layaway",
      "manafont",
      "markedtarget",
      "mend",
      "mightofaeon",
      "onthehouse",
      "openthegates",
      "ossuaryrite",
      "patchjob",
      "perfectvision",
      "powershifter",
      "preemptive",
      "quicksale",
      "quickstudy",
      "rallyoffensive",
      "refreshtexts",
      "resonance",
      "rivalsreflection",
      "rubyexcavation",
      "rubyshipment",
      "rubytransfer",
      "seconddraft",
      "shatter",
      "sigilkinship",
      "sp_beefy",
      "sp_blessing",
      "sp_closedcasket",
      "sp_containmentrune",
      "sp_dragonflame",
      "sp_flutter",
      "sp_gamble",
      "sp_partingcry",
      "sp_solidground",
      "sp_stoleninitiative",
      "sparkplug",
      "spellcart",
      "spiritfire",
      "staffofguel",
      "strangerevision",
      "summoningbulwark",
      "summonstone",
      "tribeschoice",
      "turnabout",
      "undeadarmy",
      "veinstorm",
      "weaken",
      "wo_attack",
      "wo_champion",
      "wo_health",
      "wo_mine",
      "wo_reinforcement"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-startOfCombat",
    "title": "'startOfCombat' family · 16 cards",
    "statement": "All 16 'startOfCombat' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "22 effect factories across 16 cards dispatch through the 'startOfCombat' presentation family, all on the single trigger 'startOfCombat' (both); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Abhorrent Horror: \"Start of Combat: Gain +Attack/+Health equal to the Fodder consumed this turn.\" · Members: Abhorrent Horror · Arena Heckler · Quil · Spots · Bloodbinder · Bucky · Grave Body · Gravewarden · Kobe · Kennelmaster · Mirrorhide Rhino · Pack Leader · … and 4 more",
    "example": "Abhorrent Horror follows the 'startOfCombat' convention — its trigger fires on startOfCombat. its printed numbers double when the card is gilded.",
    "contentIds": [
      "abhorrenthorror",
      "arenaheckler",
      "b2_quil",
      "b2_spots",
      "bloodbinder",
      "dw_bucky",
      "gravebody",
      "gravewarden",
      "k_kobe",
      "kennel",
      "mirrorrhino",
      "packleader",
      "runescale",
      "runmaw",
      "taurus",
      "taurustruth"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-family-summonReact",
    "title": "'summonReact' family · 11 cards",
    "statement": "All 11 'summonReact' cards trigger the same way. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "13 effect factories across 11 cards dispatch through the 'summonReact' presentation family, all on the single trigger 'onSummon' (both); the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Ashen Heir: \"Whenever an Imp dies, another friendly Imp gains its stats — or the next Imp you summon, if none are alive.\" · Members: Ashen Heir · Beardsley · King Oona · Vaultkeeper · Chipper · Chef Gary Toast · Grave Body · Den Mother · Pack Leader · Spirit Worgen · Cratering Hulk",
    "example": "Ashen Heir follows the 'summonReact' convention — its trigger fires on onSummon. its printed numbers double when the card is gilded.",
    "contentIds": [
      "ashen_heir",
      "b2_beardsley",
      "b2_oona",
      "d2_herzog",
      "dm_glutton",
      "dw_chef",
      "gravebody",
      "mamabear",
      "packleader",
      "spiritworgen",
      "thunderingabomination"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts Keyword EG docblock"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-combat-gains",
    "title": "Combat-only stat gains",
    "statement": "Stats gained in combat vanish when the fight ends — unless Engraved or an explicit carry-back keeps them. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "persistence",
    "currentBehaviour": "simulate() returns combat stats separately; only EG minions and persist* channels write back into run state.",
    "cardText": "Exemplar — a minion buffed +4/+4 mid-fight returns to its shop stats at settle unless it carries Engraved.",
    "example": "the same +4/+4 on an Engraved minion IS on the run board next shop."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts CardDef.tribe2/universalTribe docblocks"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-dual-tribe",
    "title": "Dual & universal tribes · 20 carriers",
    "statement": "A dual-tribe minion counts as both tribes, everywhere. A universal minion counts as every tribe. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "isTribe/tribe predicates fold tribe2 and universalTribe; the tribePredicates lane sweeps raw comparisons.",
    "cardText": "Exemplar — Bane: \"After you trigger a Shout, give your Imps +3/+3 this run.\" · Carriers: Bane · Crypt Drake · Crypt Wolf · Fel Conjurer · Baal · High King Mykel · Mountainbond · Heckbinder · Gemgorge Fiend · Lab Experiment · Evolving Abomination · Paragon · … and 8 more",
    "example": "Bane receives BOTH tribes' buffs and satisfies either tribe's quest counters.",
    "contentIds": [
      "bane",
      "cryptdrake",
      "cryptwolf",
      "d2_felconjurer",
      "dw_baal",
      "dw_brisbane",
      "dw_mountainbond",
      "heckbinder",
      "k_gemgorge",
      "labexperiment",
      "n2_abomination",
      "n2_paragon",
      "n2_standardbearer",
      "perfectcore",
      "philippe",
      "solaris",
      "spiritpup",
      "spiritworgen",
      "symbioticattachment",
      "wolvesden"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts CardDef.gift docblock (owner design 2026-08-26)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-gift-casts",
    "title": "Gifts vs Shop spells",
    "statement": "A Gift counts as a spell cast, but is never a Shop spell — no shop offers, no copies, no cast multipliers. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "gifts",
    "currentBehaviour": "The gift flag gates every Shop-spell surface (offers, copies, multipliers); cast bookkeeping treats gifts as real casts.",
    "cardText": "Exemplar — a Gift cast with a spell-copy engine on board: the tally advances, the copier stays silent.",
    "example": "casting a Gift beside a spell copier advances \"spells cast this game\" by 1 and mints no copy."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts CardDef.goldenText docblock"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-gild-default",
    "title": "Gilding default: ×2",
    "statement": "A gilded card doubles its printed numbers. Outliers instead gild the summoned token, reshape the effect, or add a proc; spells never gild. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "gilding",
    "currentBehaviour": "277 cards carry authored goldenText; every other card inherits the ×2 number-doubler. The outlier shapes are the owner's 2026-08-28 rulings, now carried per card as the contract's gildedDelta kind (R-GILD-01); spells and Rubies are not-applicable (R-GILD-02).",
    "cardText": "Exemplar — Wolves Den: \"Deathrattle: Summon 3 Crypt Wolves.\" → gilded: \"Deathrattle: Summon 6 Crypt Wolves.\"",
    "example": "Wolves Den's gilded text just writes the ×2 out in full — while gilded Dunkey instead summons ONE gilded Armadiyo."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "owner-handoff",
        "ref": "HeroDef.henchman docblock (owner spec 2026-08-03)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-henchman-pricing",
    "title": "Henchman pricing",
    "statement": "Your Henchman is recruitable once per run. Its cost drops 3 after a win, 2 after a loss, never below 0. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "henchmanCostOf applies win −3 / loss −2 with a 0 floor; recruit is once per run. — PARKED BY ARCHIVE 2026-08-28 (owner: \"henchmen are not in the game and are extremely WIP / being removed for now\"). `henchmanOffer` is gated by HENCHMEN_ARCHIVED, so no henchman is offerable and the pricing decay this rule describes cannot be observed in play. The decay STATE still accrues and henchmen.test.ts still asserts it, so the rule remains checkable and un-archiving restores it exactly. The ruling stands — it is the content that is inactive, not the convention.",
    "cardText": "Exemplar — Warden's henchman (hm_test_squire, base 10 Gold): after a win and a loss it costs 10 − 3 − 2 = 5.",
    "example": "base cost 10, then W/L/W → 10 − 3 − 2 − 3 = 2 Gold."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/core/src/types.ts extraTriggerFires"
      },
      {
        "kind": "owner-handoff",
        "ref": "R-MULT-01 (registry/approved.ts)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-multiplier-gilded",
    "title": "Trigger multipliers · 5 carriers",
    "statement": "Gilded multipliers count double. Stacking copies add up; non-stackers use their best copy; the two pools add together. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "multipliers",
    "currentBehaviour": "extraTriggerFires: contribution = extra × (golden ? 2 : 1); stacking summed, non-stacking best, summed + best returned.",
    "cardText": "Carriers: Chronos · Drakko the Drummer · Sylus the Reaper · Uron, Oathbringer · Zyff, the Betrayer",
    "example": "a gilded Sylus (stacking, extra 1) beside a plain Uron (non-stacking) grants 2 + 1 = 3 extra fires for a shared family.",
    "contentIds": [
      "chronos",
      "drummer",
      "sylus",
      "uron",
      "zyff"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "owner-handoff",
        "ref": "R-AVWIN-04/-05 partial-progress rulings (registry/approved.ts)"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-threshold-scope",
    "title": "Threshold counters · 18 Avenge carriers",
    "statement": "Combat counters (Avenge) reset when the fight ends. Shop counters last the whole run. Progress never crosses between them. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "persistence",
    "currentBehaviour": "Avenge progress lives in per-combat instance state; quest/cadence counters live in run state and persist.",
    "cardText": "Exemplar — Dunkey: \"Avenge (4): summon an Armadiyo.\" · Avenge carriers: Dunkey · Solaris · Bone Taxer · Brood Matron · Grobbus · Gemstorm Instigator · Gem Portsmith · Kennelmaster · Muster General · Pit Supplier · Professor Greg · Solaris Fang · … and 6 more",
    "example": "Dunkey at 2 of 3 deaths when combat ends starts the next combat at 0 — but a quest at 4 of 5 buys stays at 4 next turn.",
    "contentIds": [
      "b2_dunkey",
      "b2_solaris",
      "bonetaxer",
      "brood",
      "dm_grobbus",
      "k_gemstorm",
      "k_portsmith",
      "kennel",
      "n2_muster",
      "pitsupplier",
      "profgreg",
      "solaris",
      "soulsman",
      "sparkcapacitor",
      "spellappraiser",
      "steadfast",
      "stuntdrake",
      "weaver"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "code",
        "ref": "packages/content/src/index.ts ALL_CARDS doctrine comment"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-global-token-reachability",
    "title": "Never-drawable cards",
    "statement": "Tokens, Gifts, Henchmen and archived cards never appear in shops or random pools. Only a card that names them can create them. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "ALL_CARDS carries every class; poolFor() draws only from set manifests, which exclude all five by construction.",
    "cardText": "Exemplar — Imp (token): reachable only through the Demon cards that summon it; never offered in a shop.",
    "example": "a rune granting Pillager (an out-of-set Undead) still resolves — the grant reaches CARD_INDEX, the pool never offers it."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-c",
    "title": "Cleave [C] · 2 carriers",
    "statement": "Cleave means: its attack also hits both minions adjacent to the target, simultaneously — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Cleave for all 2 carriers.",
    "cardText": "Exemplar — Baby Cub: \"Cleave\" · Carriers: Baby Cub · Broad-Axe Brakka",
    "example": "Baby Cub carries Cleave — in play, its attack also hits both minions adjacent to the target, simultaneously.",
    "contentIds": [
      "babycub",
      "dw_brakka"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-cn",
    "title": "Consume [CN] · 0 carriers",
    "statement": "Consume means: eats another minion, absorbing per its printed rule; the eaten minion is gone — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Consume for all 0 carriers.",
    "cardText": "(no current carrier of Consume)",
    "example": "any future Consume card inherits this meaning."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-cr",
    "title": "Critical Strike [CR] · 5 carriers",
    "statement": "Critical Strike means: a per-card chance to deal double damage on attack — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Critical Strike for all 5 carriers.",
    "cardText": "Exemplar — Guardian Drake: \"(vanilla body with the keyword)\" · Carriers: Guardian Drake · Warflame · Axeman · Mountainbond · Commander Impala",
    "example": "Guardian Drake carries Critical Strike — in play, a per-card chance to deal double damage on attack.",
    "contentIds": [
      "bronzewarden",
      "d2_warflame",
      "dm_chosenfiend",
      "dw_mountainbond",
      "impala"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-ds",
    "title": "Ward [DS] · 15 carriers",
    "statement": "Ward means: negates the first damage this minion would take, then breaks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Ward for all 15 carriers.",
    "cardText": "Exemplar — Beardsley: \"Ward. Whenever you summon a Beast, give it +3/+3. Improves +3/+3 every 3 Beasts summoned.\" · Carriers: Beardsley · Guardian Drake · Transcendant · Hellrider · Impossible Todd · Warding Drone · Mountainbond · Commander Impala · Mechanical Jouster · Gem Portsmith · Karthus · Karwind · … and 3 more",
    "example": "Beardsley carries Ward — in play, negates the first damage this minion would take, then breaks.",
    "contentIds": [
      "b2_beardsley",
      "bronzewarden",
      "d2_transcendence",
      "dm_maw",
      "dm_todd",
      "drone",
      "dw_mountainbond",
      "impala",
      "jouster",
      "k_portsmith",
      "karthus",
      "karwind",
      "perfectcore",
      "tauntbreaker",
      "trainingdummy"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-eg",
    "title": "Engraved [EG] · 4 carriers",
    "statement": "Engraved means: stat gains during combat carry back to the run board permanently — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Engraved for all 4 carriers.",
    "cardText": "Exemplar — Tara: \"Engraved. Grant stats 15 times in combat to ascend.\" · Carriers: Tara · Taragosa · Taragosa's Heir · Thundeer",
    "example": "Tara carries Engraved — in play, stat gains during combat carry back to the run board permanently.",
    "contentIds": [
      "tara",
      "taragosa",
      "taragosaheir",
      "thundeer"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-fd",
    "title": "Fodder [FD] · 1 carriers",
    "statement": "Fodder means: a cheap body meant to be Consumed; Fodder-scaling effects count these — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Fodder for all 1 carriers.",
    "cardText": "Exemplar — Fred: \"A 1/1 Demon Fodder — your Demons devour it from the tavern.\" · Carriers: Fred",
    "example": "Fred carries Fodder — in play, a cheap body meant to be Consumed; Fodder-scaling effects count these.",
    "contentIds": [
      "fred"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-imm",
    "title": "Immune [IMM] · 0 carriers",
    "statement": "Immune means: takes no damage from any source while the keyword holds — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Immune for all 0 carriers.",
    "cardText": "(no current carrier of Immune)",
    "example": "any future Immune card inherits this meaning."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-m",
    "title": "Magnetic [M] · 7 carriers",
    "statement": "Magnetic means: an Attachment: can be played onto a compatible minion, merging stats and effects into it — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Magnetic for all 7 carriers.",
    "cardText": "Exemplar — Better Bot: \"Rally: give your other Mechs +5 Attack. Magnetic — welds onto a Mech, which then grants the buff (stacks).\" · Carriers: Better Bot · Cling Drone · Heckbinder · Money Bot · Perfect Core · Speedy · Chaos Attachment",
    "example": "Better Bot carries Magnetic — in play, an Attachment: can be played onto a compatible minion, merging stats and effects into it.",
    "contentIds": [
      "betterbot",
      "cling",
      "heckbinder",
      "moneybot",
      "perfectcore",
      "speedy",
      "symbioticattachment"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-r",
    "title": "Rise [R] · 3 carriers",
    "statement": "Rise means: the first time this dies, it returns with 1 Health (its Rise spent) — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Rise for all 3 carriers.",
    "cardText": "Exemplar — Anubis: \"Deathrattle: Give your minions Reborn. Cast Lantern of Souls.\" · Carriers: Anubis · Footman · Chaos Attachment",
    "example": "Anubis carries Rise — in play, the first time this dies, it returns with 1 Health (its Rise spent).",
    "contentIds": [
      "anubis",
      "footman",
      "symbioticattachment"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-rl",
    "title": "Rally [RL] · 31 carriers",
    "statement": "Rally means: triggers its effect each time this minion attacks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Rally for all 31 carriers.",
    "cardText": "Exemplar — Echohorn: \"Rally: trigger your left-most Echo.\" · Carriers: Echohorn · Packstrider · Sunmane Herald · Better Bot · Chimerus · Chorus Engine · Chorus Drake · Cinderchef · Embercrest · Flamebeat Drake · Roarcollector · Deathsayer · … and 19 more",
    "example": "Echohorn carries Rally — in play, triggers its effect each time this minion attacks.",
    "contentIds": [
      "b2_echohorn",
      "b2_packstrider",
      "b2_sunmane",
      "betterbot",
      "chimerus",
      "chorusengine",
      "d2_chorus",
      "d2_cinderchef",
      "d2_embercrest",
      "d2_flamebeat",
      "d2_roarcollector",
      "deathsayer",
      "dm_hungerling",
      "dw_bladethrower",
      "dw_thane",
      "heraldapoc",
      "hoardbreaker",
      "jouster",
      "k3_korn",
      "k_blazer",
      "k_boulderdash",
      "k_crownvein",
      "k_tunnelcharger",
      "n2_abomination",
      "n2_standardbearer",
      "perfectcore",
      "philippe",
      "supporter",
      "tauntbreaker",
      "trophystalker",
      "watcher"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-sc",
    "title": "Start of Combat [SC] · 9 carriers",
    "statement": "Start of Combat means: its effect fires once when combat begins, before any attacks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Start of Combat for all 9 carriers.",
    "cardText": "Exemplar — Abhorrent Horror: \"Start of Combat: Gain +Attack/+Health equal to the Fodder consumed this turn.\" · Carriers: Abhorrent Horror · Quil · Spots · Bucky · Kobe · Kennelmaster · Speed Demon · Taurus · Taurus the Truth Bringer",
    "example": "Abhorrent Horror carries Start of Combat — in play, its effect fires once when combat begins, before any attacks.",
    "contentIds": [
      "abhorrenthorror",
      "b2_quil",
      "b2_spots",
      "dw_bucky",
      "k_kobe",
      "kennel",
      "runmaw",
      "taurus",
      "taurustruth"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-sl",
    "title": "Slaughter [SL] · 5 carriers",
    "statement": "Slaughter means: triggers its effect each time this minion kills an enemy minion — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Slaughter for all 5 carriers.",
    "cardText": "Exemplar — Bounty Bot: \"Immune while attacking (first 2 attacks each combat). Slaughter: gain 2 Gold next shop.\" · Carriers: Bounty Bot · Gnasher, the Overrun · Karthus · Moe · Sword and Bored",
    "example": "Bounty Bot carries Slaughter — in play, triggers its effect each time this minion kills an enemy minion.",
    "contentIds": [
      "bountybot",
      "gnash",
      "karthus",
      "moe",
      "swordbored"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-st",
    "title": "Stealth [ST] · 0 carriers",
    "statement": "Stealth means: cannot be targeted by attacks; lost the moment it attacks — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Stealth for all 0 carriers.",
    "cardText": "(no current carrier of Stealth)",
    "example": "any future Stealth card inherits this meaning."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-t",
    "title": "Taunt [T] · 17 carriers",
    "statement": "Taunt means: enemies must attack your Taunt minions before anything else — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Taunt for all 17 carriers.",
    "cardText": "Exemplar — Armadiyo: \"Taunt. Echo: give your Beast Aura +2/+4.\" · Carriers: Armadiyo · Dawnclaw · Wolvie · Fel Spikes · Chipper · Knocked · Big Huggies · Brunni · Twilight Emissary · Gryphon · Geode Guardian · Kobe · … and 5 more",
    "example": "Armadiyo carries Taunt — in play, enemies must attack your Taunt minions before anything else.",
    "contentIds": [
      "b2_armadiyo",
      "b2_dawnclaw",
      "b2_wolvie",
      "dm_felspikes",
      "dm_glutton",
      "dm_knocked",
      "dm_velvet",
      "dw_brunni",
      "emissary",
      "gryphon",
      "k_geode",
      "k_kobe",
      "maw",
      "ryme",
      "sabercub",
      "sandbag",
      "trainingdummy"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-v",
    "title": "Venomous [V] · 2 carriers",
    "statement": "Venomous means: destroys whatever it damages; drops off after its first clash (a Cleave clash is simultaneous, so one venom can fell up to three bodies before dropping) — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Venomous for all 2 carriers.",
    "cardText": "Exemplar — Lab Experiment: \"Battlecry: get a Tier 6 minion. Deathrattle: get a Tier 5 minion.\" · Carriers: Lab Experiment · Venom",
    "example": "Lab Experiment carries Venomous — in play, destroys whatever it damages; drops off after its first clash (a Cleave clash is simultaneous, so one venom can fell up to three bodies before dropping).",
    "contentIds": [
      "labexperiment",
      "venom"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-keyword-w",
    "title": "Windfury [W] · 4 carriers",
    "statement": "Windfury means: attacks twice per attack turn — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "keywords",
    "currentBehaviour": "One shared engine path implements Windfury for all 4 carriers.",
    "cardText": "Exemplar — Commander Impala: \"Flurry. Ward. Critical Strike (50%).\" · Carriers: Commander Impala · Blazer · Speedy · Tauntbreaker",
    "example": "Commander Impala carries Windfury — in play, attacks twice per attack turn.",
    "contentIds": [
      "impala",
      "k_blazer",
      "speedy",
      "tauntbreaker"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-active",
    "title": "'active' powers · 17 heroes",
    "statement": "These 17 powers all fires through the real hero-power action, with at most a board/shop target. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 17 powers as 'active'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Albus, Empowerment: \"Choose a Shop minion. Discover a minion from the tier above it for it to become.\" · Members: Albus — Empowerment [empowerment] · Rascal — All In [allIn] · Darah — Swap [displace] · Devourer — Devour [devour] · Djinni — Cadence [replayAllEndOfTurn] · Fibbsy — Ruby Wealth [rubyWealth] · Frantic Frank — Clearance [clearance] · Harlan — Buyout [buyout] · Jensen — Dynamite Dig [dynamiteDig] · Merrin — Pocket Magic [pocketMagic] · Auctioneer — Pulse [replayBattlecry] · Nadja — Goldspring [gainMaxMana] · Lord of the Risen — Undying [grantReborn] · Sable — Soulbind [soulbind] · Tiff — Dragon Tamer [dragonTamer] · Warden — Aegis [grantWard] · Xerox — Copy Machine [copyMachine]",
    "example": "Albus's Empowerment fires through the real hero-power action, with at most a board/shop target."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-active-conditional",
    "title": "'active-conditional' powers · 5 heroes",
    "statement": "These 5 powers all active, but only against a staged precondition (a pair to complete, a fight behind you, a spell cast). — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 5 powers as 'active-conditional'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Gildmaster, Gildcrafter: \"When you have 2 copies of a minion, this grants a third.\" · Members: Gildmaster — Gildcrafter [gildcrafter] · Hunch — Rounded Spellbook [roundedSpellbook] · Membrance — Memory [memory] · Quillen — Archive [archive] · Underdweller — Soulkeeper [soulkeeper]",
    "example": "Gildmaster's Gildcrafter active, but only against a staged precondition (a pair to complete, a fight behind you, a spell cast)."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-adopted-secondary",
    "title": "'adopted-secondary' powers · 2 heroes",
    "statement": "These 2 powers all adopts other heroes' powers through the pick ceremony. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'adopted-secondary'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Mimic, Mimicry: \"At the start of every turn, Discover a hero power to wield this turn.\" · Members: Mimic — Mimicry [mimic] · Void — Twin Voids [voidTwin]",
    "example": "Mimic's Mimicry adopts other heroes' powers through the pick ceremony."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-combat-trigger",
    "title": "'combat-trigger' powers · 5 heroes",
    "statement": "These 5 powers all the payoff happens inside or around combat. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 5 powers as 'combat-trigger'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Cindara, Hoard: \"Avenge (4): summon a 1/1 Whelp that attacks immediately. Improve your Whelps +2/+2.\" · Members: Cindara — Hoard [hoard] · Gorun — Blade Mastery [bladeMastery] · Rayse — Empowering Vines [empoweringVines] · Soren — Reclaim [resummon] · Emissary — United Front [unitedFront]",
    "example": "Cindara's Hoard the payoff happens inside or around combat."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-count-threshold",
    "title": "'count-threshold' powers · 10 heroes",
    "statement": "These 10 powers all a buy/sell/refresh/tally counter crossing a threshold. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 10 powers as 'count-threshold'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Aevor, Tempest: \"Unlocks after your minions kill 15 enemies. End of Turn: give your left and right-most minions +4/+4. Upgrades every 15 kills.\" · Members: Aevor — Tempest [tempest] · Braum — Investment [investment] · Chronos — Timelapse [questChronos] · Ayse — Lucky Seat [luckySeat] · Drakko — Drumline [quest] · Gorr — Four Peat [fourPeat] · Juggler — Carnival Coin [baldgecoin] · Keshi the Protector — Keshi’s Crown [crownTally] · Pete — Contrabanana [contraband] · Robin — Spoils [sellGold]",
    "example": "Aevor's Tempest a buy/sell/refresh/tally counter crossing a threshold."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-every-n-turns",
    "title": "'every-n-turns' powers · 3 heroes",
    "statement": "These 3 powers all a repeating schedule. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 3 powers as 'every-n-turns'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Chaos, Chaos Bond: \"Start with a Chaos Attachment. Get another every 5 turns.\" · Members: Chaos — Chaos Bond [chaos] · Kindness — Great Presence [greatPresence] · Re-Pete — Second Hand [secondHand]",
    "example": "Chaos's Chaos Bond a repeating schedule."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-modal-choice",
    "title": "'modal-choice' powers · 2 heroes",
    "statement": "These 2 powers all the activation carries a choice payload the player picks. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'modal-choice'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Cassen, Commission: \"Choose a commission — it pays out in a few turns.\" · Members: Cassen — Commission [commission] · Flash — First or Last [firstOrLast]",
    "example": "Cassen's Commission the activation carries a choice payload the player picks."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-passive-pricing",
    "title": "'passive-pricing' powers · 3 heroes",
    "statement": "These 3 powers all an always-on price/rule rewrite. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 3 powers as 'passive-pricing'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Foreman Flint, Company Rate: \"Dwarves cost 2 Gold.\" · Members: Foreman Flint — Company Rate [companyRate] · Tradesman — Frugal [cheapMinions] · Midas — Midas' Touch [midasTouch]",
    "example": "Foreman Flint's Company Rate an always-on price/rule rewrite."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-shop-action-trigger",
    "title": "'shop-action-trigger' powers · 2 heroes",
    "statement": "These 2 powers all rides one specific shop action (a tier-up, a play position). — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'shop-action-trigger'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Emerald Warden, Vanguard: \"When you tier up, get a random minion from the new tier.\" · Members: Emerald Warden — Vanguard [vanguard] · Odelle — Exhibition [exhibition]",
    "example": "Emerald Warden's Vanguard rides one specific shop action (a tier-up, a play position)."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-start-of-run",
    "title": "'start-of-run' powers · 5 heroes",
    "statement": "These 5 powers all the work happens at run creation (opening tokens, locked Discovers, the turn-1 quest offer). — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 5 powers as 'start-of-run'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Brackus, Summit: \"At the start of the game, Discover a Tier 7 minion. It is locked until you spend 70 Gold.\" · Members: Brackus — Summit [summitLock] · Coran — Pathfinder [heroQuest] · Disco Dan — Setlist [discoLock] · Fi — Errand [heroQuest] · Yirin — Reflector [startingReflector]",
    "example": "Brackus's Summit the work happens at run creation (opening tokens, locked Discovers, the turn-1 quest offer)."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-turn-number",
    "title": "'turn-number' powers · 2 heroes",
    "statement": "These 2 powers all opens/fires on one specific turn. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 2 powers as 'turn-number'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Guardian, Runeguard: \"On turn 8, visit the Epic Runeforge.\" · Members: Guardian — Runeguard [epicRuneforge] · Runesmith — Forgemaster [runeforge]",
    "example": "Guardian's Runeguard opens/fires on one specific turn."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-power-unlock-recharge",
    "title": "'unlock-recharge' powers · 3 heroes",
    "statement": "These 3 powers all active, but gated by its own lock/recharge schedule. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "heroes",
    "currentBehaviour": "heroPowerFamilies.ts classifies these 3 powers as 'unlock-recharge'; the heroPowerLane + stager suites verify each against that reading.",
    "cardText": "Exemplar — Aster, the Guide, Preparation: \"Give a friendly minion +1/+1. Recharges every other turn.\" · Members: Aster, the Guide — Preparation [preparation] · Gambler — Dice [dice] · Indy — Masterwork [gild]",
    "example": "Aster, the Guide's Preparation active, but gated by its own lock/recharge schedule."
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-combatflag",
    "title": "'combatFlag' rewards · 14 quests",
    "statement": "These 14 quests pay the same 'combatFlag' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 14 through the same 'combatFlag' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Blood Trail (beast, lesser): objective buy × 5 → reward 'combatFlag' · Members: Blood Trail · Assembly Line · Umbral Energy · Deep Hunger · Contract Rewrite · Law of Teeth · The Old Hunt · Feeding Line · Empty Graves · Shared Circuit · Pit Without End · Echoing Coop · … and 2 more",
    "example": "completing Blood Trail pays its 'combatFlag' reward through the shared engine.",
    "contentIds": [
      "q_assembly_line",
      "q_blood_trail",
      "q_burning_legion",
      "q_candlelight_toll",
      "q_contract_rewrite",
      "q_deep_hunger",
      "q_echoing_coop",
      "q_empty_graves",
      "q_feeding_line",
      "q_law_of_teeth",
      "q_pit_without_end",
      "q_shared_circuit",
      "q_the_old_hunt",
      "q_umbral_energy"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-echorepeat",
    "title": "'echoRepeat' rewards · 3 quests",
    "statement": "These 3 quests pay the same 'echoRepeat' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 3 through the same 'echoRepeat' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Grave Contract (neutral, lesser): objective deathrattle × 7 → reward 'echoRepeat' · Members: Grave Contract · Opening Act · Resonant Path",
    "example": "completing Grave Contract pays its 'echoRepeat' reward through the shared engine.",
    "contentIds": [
      "hq_opening_act_echo",
      "hq_resonant_path_echo",
      "q_grave_contract"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-grant",
    "title": "'grant' rewards · 28 quests",
    "statement": "These 28 quests pay the same 'grant' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 28 through the same 'grant' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Forest Grove (beast, lesser): objective summon × 8 → reward 'grant' · Members: Forest Grove · Forager's Trail · Hoard Spark · Coin Hoard · Grave Robber · Scrap Contract · Gilded Chance · Key Findings · Apex Hunt · Trophy Den · Skybound Pact · Kingdom of Bones · … and 16 more",
    "example": "completing Forest Grove pays its 'grant' reward through the shared engine.",
    "contentIds": [
      "hq_gilded_favor",
      "q_apex_hunt",
      "q_barroom_bounty",
      "q_chimerus",
      "q_coin_hoard",
      "q_company_recruitment",
      "q_death_writes_twice",
      "q_echo_chamber",
      "q_first_blood",
      "q_first_strike",
      "q_foragers_trail",
      "q_forest_grove",
      "q_gilded_chance",
      "q_grave_robber",
      "q_hoard_spark",
      "q_impossible_shop",
      "q_key_findings",
      "q_kingdom_of_bones",
      "q_machine_chorus",
      "q_market_feast",
      "q_maw_of_the_run",
      "q_perfect_machine",
      "q_pivot_door",
      "q_scrap_contract",
      "q_skybound_pact",
      "q_taragosas_inheritance",
      "q_trophy_den",
      "q_true_contract"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-multi",
    "title": "'multi' rewards · 20 quests",
    "statement": "These 20 quests pay the same 'multi' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 20 through the same 'multi' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Imp Census (demon, lesser): objective summonImp × 4 → reward 'multi' · Members: Imp Census · Dark Bargain · The Epic Runeforge · Feed the Alpha · Hoardwake Ritual · Overclocked Core · Leader of the Pack · Anomalous Reactor · Parliament of Flame · Funeral Engine · Infinite Assembly · Rulebreaker's Crown · … and 8 more",
    "example": "completing Imp Census pays its 'multi' reward through the shared engine.",
    "contentIds": [
      "hq_summit_passage",
      "q_anomalous_reactor",
      "q_banes_existence",
      "q_company_store",
      "q_cratering_missive",
      "q_dark_bargain",
      "q_epic_commission",
      "q_feed_the_alpha",
      "q_funeral_engine",
      "q_heart_of_the_mountain",
      "q_hoardwake_ritual",
      "q_imp_census",
      "q_infinite_assembly",
      "q_leader_of_the_pack",
      "q_overclocked_core",
      "q_parliament_of_flame",
      "q_passing_spears",
      "q_rulebreakers_crown",
      "q_sealed_vault",
      "q_stock_the_shelves"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-rallyrepeat",
    "title": "'rallyRepeat' rewards · 3 quests",
    "statement": "These 3 quests pay the same 'rallyRepeat' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 3 through the same 'rallyRepeat' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Spark Permit (neutral, lesser): objective castSpell × 10 → reward 'rallyRepeat' · Members: Spark Permit · Opening Act · Resonant Path",
    "example": "completing Spark Permit pays its 'rallyRepeat' reward through the shared engine.",
    "contentIds": [
      "hq_opening_act_rally",
      "hq_resonant_path_rally",
      "q_spark_permit"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-recurringendofturn",
    "title": "'recurringEndOfTurn' rewards · 6 quests",
    "statement": "These 6 quests pay the same 'recurringEndOfTurn' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 6 through the same 'recurringEndOfTurn' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — Echoing Roar (dragon, greater): objective shout × 7 → reward 'recurringEndOfTurn' · Members: Echoing Roar · Blueprint Cache · Forsaken Speed · Clinging On · Open Tab · Runic Refrain",
    "example": "completing Echoing Roar pays its 'recurringEndOfTurn' reward through the shared engine.",
    "contentIds": [
      "q_blueprint_cache",
      "q_clinging_on",
      "q_echoing_roar",
      "q_forsaken_speed",
      "q_open_tab",
      "q_runic_refrain"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-recurringgrant",
    "title": "'recurringGrant' rewards · 3 quests",
    "statement": "These 3 quests pay the same 'recurringGrant' reward through one shared engine — no special cases. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "applyQuestReward resolves all 3 through the same 'recurringGrant' branch. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "Exemplar — The Red Trail (beast, greater): objective spendGold × 18 → reward 'recurringGrant' · Members: The Red Trail · Ossuary Rite · Implosion",
    "example": "completing The Red Trail pays its 'recurringGrant' reward through the shared engine.",
    "contentIds": [
      "q_implosion",
      "q_ossuary_rite",
      "q_the_red_trail"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-quest-reward-residual",
    "title": "Rarer reward kinds · 40 quests",
    "statement": "These rarer reward kinds all use the same shared engine — no special cases: 'shoutRepeat' ×3, 'spellRepeat' ×3, 'gainGold' ×2, 'grantRune' ×2, 'minionCost' ×2, 'rubyExtraCasts' ×2, 'rubyStatGain' ×2, 'aleExtraCasts' ×1, 'attachmentDeal' ×1, 'beastPlayBuff' ×1, 'boneThrone' ×1, 'consumeDoubleFirstEachTurn' ×1, 'discover' ×1, 'dupeFirstBuy' ×1, 'endlessVerse' ×1, 'fodderReward' ×1, 'freeFirstBuy' ×1, 'friedCircuits' ×1, 'gainMaxGold' ×1, 'gildCopies' ×1, 'goldFodder' ×1, 'motherlode' ×1, 'questGoldTribeBuff' ×1, 'scalingTribeAura' ×1, 'scheduleRuneforge' ×1, 'shopBuffOnRefresh' ×1, 'shopBuffPerShouts' ×1, 'shoutEdgeBuff' ×1, 'tier7Access' ×1, 'tribeRallySlaughterExtra' ×1, 'undeadSpellAura' ×1. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "categories",
    "currentBehaviour": "Each kind is one applyQuestReward branch; no per-quest special cases. — PARKED BY ARCHIVE 2026-08-28: the quest system is archived (QUESTS_ARCHIVED), so no quest can be offered or completed in play. The reward engine is untouched and still swept: economyScan grants every quest via devGrant and asserts its payout, and every rune resolves through the same applyQuestReward.",
    "cardText": "'shoutRepeat': Warm Embers · 'spellRepeat': Spell Thesis · 'gainGold': Bone Ledger · 'grantRune': Spare Forge · 'minionCost': Merchant's Mark · 'rubyExtraCasts': Gem Circuit · 'rubyStatGain': Open the Vein · 'aleExtraCasts': Bottomless Cellar · 'attachmentDeal': Attachment Issues · 'beastPlayBuff': Den Marker",
    "example": "Warm Embers pays its 'shoutRepeat' reward through the same engine as every other quest.",
    "contentIds": [
      "hq_first_pick",
      "hq_gilded_shortcut",
      "hq_merchants_road",
      "hq_open_road",
      "hq_opening_act_shout",
      "hq_resonant_path_shout",
      "hq_runic_passage",
      "hq_spare_forge",
      "q_ancient_runes",
      "q_attachment_issues",
      "q_banes_presence",
      "q_bone_ledger",
      "q_bottomless_banquet",
      "q_bottomless_cellar",
      "q_den_marker",
      "q_dupes",
      "q_endless_inventory",
      "q_endless_verse",
      "q_faultline_coronation",
      "q_food_for_gold",
      "q_forsaken_will",
      "q_fried_circuits",
      "q_gem_circuit",
      "q_golden_ledger",
      "q_merchants_mark",
      "q_motherlode",
      "q_odd_jobs",
      "q_open_the_vein",
      "q_pack_mentality",
      "q_runic_apprenticeship",
      "q_shop_license",
      "q_small_offering",
      "q_spell_thesis",
      "q_teleport_summit",
      "q_the_bone_throne",
      "q_the_runeforge",
      "q_twin_sun_oath",
      "q_unstable_riches",
      "q_war_council",
      "q_warm_embers"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-buy",
    "title": "Trigger: you buy a card · 6 cards",
    "statement": "All 6 of these fire on one trigger: you buy a card. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "7 effect factories across 6 cards dispatch on 'cardsBought', 'onBuy', 'spellBought' (recruit) — re-clustered by TRIGGER out of the 'economy' + 'economyReact' presentation families on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Korok, the Hungerer: \"When you buy 4 cards, give your Fodder +1/+1 and add 1 Fodder to your next tavern.\" · Members: Korok, the Hungerer · Moonhowl Mentor · Banksly · Brightwing Broker · Night Market Horror · Ninefold Broker",
    "example": "Korok, the Hungerer fires when you buy a card, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "acid",
      "b2_moonhowl",
      "banksly",
      "broker",
      "dm_nightmarket",
      "n2_ninefold"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-consume",
    "title": "Trigger: this minion Consumes something · 1 card",
    "statement": "The 1 card here fires on one trigger: this minion Consumes something. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 1 card dispatch on 'onConsume' (recruit) — re-clustered by TRIGGER out of the 'react' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Enigma: \"When you consume a minion, give minions in the Shop +2/+1 permanently.\" · Members: Enigma",
    "example": "Enigma fires when this minion Consumes something, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "dm_jumbo"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-damaged",
    "title": "Trigger: a friendly minion takes or deals damage · 5 cards",
    "statement": "All 5 of these fire on one trigger: a friendly minion takes or deals damage. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "4 effect factories across 5 cards dispatch on 'friendlyDemonDealtDamage', 'onDamaged' (combat) — re-clustered by TRIGGER out of the 'react' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Axeman: \"Critical Strike (50%). When a friendly Demon deals damage, gain +3/+3 permanently.\" · Members: Axeman · Leech · Impossible Todd · Gryphon · Target Dummy",
    "example": "Axeman fires when a friendly minion takes or deals damage, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "dm_chosenfiend",
      "dm_leech",
      "dm_todd",
      "gryphon",
      "sandbag"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-gainAttack",
    "title": "Trigger: a friendly minion gains Attack · 2 cards",
    "statement": "All 2 of these fire on one trigger: a friendly minion gains Attack. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch on 'onGainAttack' (both) — re-clustered by TRIGGER out of the 'react' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Hunter: \"When this gains Attack, give your minions +1/+1. Improve this by +1/+1 every 5 times.\" · Members: Hunter · Sergeant",
    "example": "Hunter fires when a friendly minion gains Attack, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "hunter",
      "sergeant"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-gainCard",
    "title": "Trigger: a card is added to your hand · 2 cards",
    "statement": "All 2 of these fire on one trigger: a card is added to your hand. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch on 'onGainCard' (both) — re-clustered by TRIGGER out of the 'economyReact' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Gangplank: \"When a card is added to your hand, give a random friendly Dwarf +1/+2.\" · Members: Gangplank · Kegheart Dwarf",
    "example": "Gangplank fires when a card is added to your hand, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "dw_gangplank",
      "dw_kegheart"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-goldSpent",
    "title": "Trigger: you spend Gold this turn · 5 cards",
    "statement": "All 5 of these fire on one trigger: you spend Gold this turn. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "6 effect factories across 5 cards dispatch on 'goldSpent' (recruit) — re-clustered by TRIGGER out of the 'economy' + 'economyReact' presentation families on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Billings: \"When you spend 5 Gold, give 2 random friendly Dwarves +5/+5.\" · Members: Billings · Dwarf King, Brill · Coinfire Forewoman · Mountainbond · Tapkeeper",
    "example": "Billings fires when you spend Gold this turn, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "dw_billings",
      "dw_brill",
      "dw_coinfire",
      "dw_mountainbond",
      "dw_tapkeeper"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-overflow",
    "title": "Trigger: a summon overflows a full board · 2 cards",
    "statement": "All 2 of these fire on one trigger: a summon overflows a full board. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch on 'summonOverflow' (both) — re-clustered by TRIGGER out of the 'react' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Flowing Monk: \"When you summon a minion that doesn't fit, Engrave 2 friendly minions +2/+2. Improves by +2/+2 every 5 overflows.\" · Members: Flowing Monk · Cratering Hulk",
    "example": "Flowing Monk fires when a summon overflows a full board, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "monk",
      "thunderingabomination"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-ruby",
    "title": "Trigger: a Ruby is gained or cast · 3 cards",
    "statement": "All 3 of these fire on one trigger: a Ruby is gained or cast. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "6 effect factories across 3 cards dispatch on 'onGetRuby', 'onRubyPlayed', 'rubyCast' (both/recruit) — re-clustered by TRIGGER out of the 'economy' + 'economyReact' presentation families on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Gemgorge Fiend: \"When you cast 3 spells, Consume a minion in the Shop.\" · Members: Gemgorge Fiend · Gem Sage · Reflector",
    "example": "Gemgorge Fiend fires when a Ruby is gained or cast, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "k_gemgorge",
      "k_gemsage",
      "n2_reflector"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-sell",
    "title": "Trigger: you sell a card · 9 cards",
    "statement": "All 9 of these fire on one trigger: you sell a card. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "10 effect factories across 9 cards dispatch on 'minionSold', 'onSell' (recruit) — re-clustered by TRIGGER out of the 'economy' + 'economyReact' presentation families on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — River Drake: \"When you sell this, get a random Spell.\" · Members: River Drake · Voicekeeper · Arcane Behemoth · Grevlin & Co. · Hoard Whelp · Beggy · Cheap Date · Traveling Salesman · Salvatore McKlusky",
    "example": "River Drake fires when you sell a card, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "d2_riverdrake",
      "d2_voicekeeper",
      "dm_behemoth",
      "dm_grevlin",
      "hoardwhelp",
      "k_beggy",
      "k_pouchpincher",
      "n2_salesman",
      "salvatore"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-shopRefresh",
    "title": "Trigger: you refresh the Shop · 1 card",
    "statement": "The 1 card here fires on one trigger: you refresh the Shop. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "1 effect factories across 1 card dispatch on 'shopRefreshed' (recruit) — re-clustered by TRIGGER out of the 'economy' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Hellrider: \"Ward. Every 4 refreshes, gain the right-most Shop minion's stats.\" · Members: Hellrider",
    "example": "Hellrider fires when you refresh the Shop, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "dm_maw"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-spellTargeted",
    "title": "Trigger: a spell targets this minion · 2 cards",
    "statement": "All 2 of these fire on one trigger: a spell targets this minion. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "2 effect factories across 2 cards dispatch on 'spellCastOnThis' (recruit) — re-clustered by TRIGGER out of the 'economy' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Mirrorwing: \"The first Shop spell you cast on this each turn casts again.\" · Members: Mirrorwing · Reflector",
    "example": "Mirrorwing fires when a spell targets this minion, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "d2_mirrorwing",
      "n2_reflector"
    ]
  },
  {
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "contracts.conventions"
      }
    ],
    "sourceQueue": "contracts.conventions",
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "contractExtraction"
      ]
    },
    "id": "q-conv-trigger-startOfTurn",
    "title": "Trigger: the turn starts · 1 card",
    "statement": "The 1 card here fires on one trigger: the turn starts. Gilding doubles their output. — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "currentBehaviour": "1 effect factories across 1 card dispatch on 'startOfTurn' (recruit) — re-clustered by TRIGGER out of the 'economy' presentation family on the owner's 2026-08-28 ruling; the factoryPhase lane gates each (trigger, factory) pair. Gilding: the ×2 baseline; any member whose gild changes shape instead carries authored golden text (R-GILD-01).",
    "cardText": "Exemplar — Fel Conjurer: \"Start of Turn: get a Quick Study.\" · Members: Fel Conjurer",
    "example": "Fel Conjurer fires when the turn starts, like every other card here. its printed numbers double when the card is gilded.",
    "contentIds": [
      "d2_felconjurer"
    ]
  }
] as GameRule[];
