/**
 * GENERATED by `npm run docbot:interactions` — do not hand-edit. The owner's SITTING-2 deck (Doc Bot 2.0
 * WP F): one pending question card per surviving §9.7 anomaly (confidence-floored, fingerprint-deduped),
 * at the fly-through language bar — one short statement, one concrete example, the compact ✓/✕/✎ click
 * tail. Decided through the SAME board + decisions.json as every other pending rule; decisions survive
 * regeneration and rejects tombstone via the shared seed-hygiene pass. THE DECK SHIPS DORMANT — the main
 * session schedules the sitting.
 */
import type { GameRule } from '../schema';

export const INTERACTION_PENDING: GameRule[] = [
  {
    "id": "q-interact2-2ad14500",
    "title": "copy of kennel carries unstated instance state",
    "statement": "hero:xerox + Kennelmaster: a copy carries per-instance state the card's contract never states as riding — intended? — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "triggers",
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "docbot.interactions:copied-source-unexpected-state"
      }
    ],
    "currentBehaviour": "reducer: heroPower on a gilded Kennelmaster (summonBonus 2) — copy golden=true summonBonus=2; contract states 'exact'. The copy carries [gilding] which kennel's contract does not state as riding a copy.",
    "recommendation": "Reading A: the copy is over-carrying state (a copy-mode bug). Reading B: the behaviour is intended and the subject contract is incomplete — state the rides — approve endorses Reading A.",
    "cardText": "Kennelmaster: \"Start of Combat: give your Beasts +1 Attack wherever they are. Avenge (4): Improve this.\"",
    "example": "Measured: rides stated: [accrued-improve-counters (summonBonus)] where the structural expectation was copySubject.rides ⊇ [gilding].",
    "sourceQueue": "docbot.interactions",
    "contentIds": [
      "kennel"
    ],
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "interactionSweep"
      ]
    }
  },
  {
    "id": "q-interact2-32aa654f",
    "title": "uron multiplies [endOfTurn, startOfCombat] with no ruled composition law",
    "statement": "Uron, Oathbringer: no ruling states how its multiplier families compose (stacking, cross-card collapse, phase symmetry) — rule it like Battlecry/Echo/Rally? — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "multipliers",
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "docbot.interactions:unruled-multiplier-composition"
      }
    ],
    "currentBehaviour": "uron declares ×(1+1) on [endOfTurn, startOfCombat], but no owner ruling or pinned matrix row states how those families compose (cross-card collapse, phase symmetry, stacking) — the interactionFamilyMatrix Q1 class.",
    "recommendation": "Reading A: these families fold like the ruled ones: additive within a family, best-of across non-stacking cards. Reading B: each family needs its own ruling — the shop/combat phase split or the rune interplay may differ (socTwilightExtraFires stacked by owner REVERSAL, not by the default law) — approve endorses Reading A.",
    "cardText": "Uron, Oathbringer: \"Your Rallies, End of Turns and Start of Combats trigger an additional time.\"",
    "example": "Measured: no ruling; behaviour pinned only implicitly by shared fold helpers where the structural expectation was a ruled composition law for [endOfTurn, startOfCombat] (like battlecry/deathrattle/rally have).",
    "sourceQueue": "docbot.interactions",
    "contentIds": [
      "uron"
    ],
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "interactionSweep"
      ]
    }
  },
  {
    "id": "q-interact2-faeb3c44",
    "title": "chronos multiplies [endOfTurn] with no ruled composition law",
    "statement": "Chronos: no ruling states how its multiplier families compose (stacking, cross-card collapse, phase symmetry) — rule it like Battlecry/Echo/Rally? — ✓ yes · ✕ no (say why) · ✎ your wording",
    "domain": "multipliers",
    "status": "needs-ruling",
    "evidence": [
      {
        "kind": "docbot-scan",
        "ref": "docbot.interactions:unruled-multiplier-composition"
      }
    ],
    "currentBehaviour": "chronos declares ×(1+1) on [endOfTurn], but no owner ruling or pinned matrix row states how those families compose (cross-card collapse, phase symmetry, stacking) — the interactionFamilyMatrix Q1 class.",
    "recommendation": "Reading A: these families fold like the ruled ones: additive within a family, best-of across non-stacking cards. Reading B: each family needs its own ruling — the shop/combat phase split or the rune interplay may differ (socTwilightExtraFires stacked by owner REVERSAL, not by the default law) — approve endorses Reading A.",
    "cardText": "Chronos: \"Your End of Turn effects trigger 1 more time.\"",
    "example": "Measured: no ruling; behaviour pinned only implicitly by shared fold helpers where the structural expectation was a ruled composition law for [endOfTurn] (like battlecry/deathrattle/rally have).",
    "sourceQueue": "docbot.interactions",
    "contentIds": [
      "chronos"
    ],
    "enforcement": {
      "kind": "oracle",
      "refs": [
        "interactionSweep"
      ]
    }
  }
] as GameRule[];
