/**
 * GENERATED by `npm run docbot:interactions` — do not hand-edit. The owner's SITTING-2 deck (Doc Bot 2.0
 * WP F): one pending question card per surviving §9.7 anomaly (confidence-floored, fingerprint-deduped),
 * at the fly-through language bar — one short statement, one concrete example, the compact ✓/✕/✎ click
 * tail. Decided through the SAME board + decisions.json as every other pending rule; decisions survive
 * regeneration and rejects tombstone via the shared seed-hygiene pass. THE DECK SHIPS DORMANT — the main
 * session schedules the sitting.
 */
import type { GameRule } from '../schema';

export const INTERACTION_PENDING: GameRule[] = [] as GameRule[];
