/**
 * GENERATED by `npm run rules:seed` — do not hand-edit. AUTO-retired tombstones: pending questions that
 * left the board mechanically (owner REJECTED the recommendation, or the question's content ids vanished),
 * each with an audit record. Entries are append-only — the seeder merges, never drops. Ids here are never
 * recycled as new pending ids (tested in rules.test.ts).
 */
import type { RetiredRule } from './retired';

export const AUTO_RETIRED_RULES: RetiredRule[] = [
  {
    "id": "q-policy-rune-duplicates",
    "why": "AUTO-RETIRED by rules:seed (2026-08-27): the owner REJECTED this recommendation on 2026-08-26. A rejected question leaves the active pending set on reseed (§10.4); any follow-up work the rejection implies is roadmap material, not a standing board card. Question was: \"Rune duplicate policy: 80 runes whose second copy does nothing\"",
    "retiredAt": "2026-08-27"
  }
] as RetiredRule[];

export const AUTO_RETIRED_IDS: ReadonlySet<string> = new Set(AUTO_RETIRED_RULES.map((r) => r.id));
