import type { WikiEntry } from './types';

// Checked against Recruit.tsx (drag/drop zones), RefreshButton / FreezeButton / TavernUpButton / EndTurnButton,
// Game.tsx (Tab / Esc), Inspect.tsx and EscMenu.tsx on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  {
    id: 'buy-a-minion',
    topic: 'controls',
    q: 'How do I buy a minion?',
    a: "Drag it out of the shop and drop it anywhere down in your half of the screen. It goes to your **hand** first, not straight onto the board. Just clicking a shop card won't buy it.",
    aliases: ['purchase', 'recruit', 'get a minion', 'buy card'],
    seeAlso: ['play-from-hand', 'sell-a-minion'],
  },
  {
    id: 'play-from-hand',
    topic: 'controls',
    q: 'How do I put a minion from my hand onto the board?',
    a: "Drag it up out of your hand and let go over the board. The board opens a gap where you're hovering, so you pick exactly where it lands. If your board is already full (7 minions), it snaps back.",
    aliases: ['play a card', 'place minion', 'summon from hand', 'put down'],
    seeAlso: ['board-order', 'buy-a-minion'],
  },
  {
    id: 'sell-a-minion',
    topic: 'controls',
    q: 'How do I sell a minion?',
    a: "Drag it from your **board** up into the shop area. The whole top of the screen lights up as a sell zone, so let go anywhere in it and you'll see the Gold pop up. Minions still in your hand can't be sold, so play them first. And once your turn timer hits 0, selling is locked.",
    aliases: ['get rid of', 'remove a minion', 'discard', 'sell unit', 'dump'],
    seeAlso: ['buy-a-minion', 'timer-runs-out'],
  },
  {
    id: 'board-order',
    topic: 'controls',
    q: 'Can I rearrange my minions, and does the order matter?',
    a: "Yep, drag a minion sideways along your board and drop it in the gap. Order **really** matters: in combat your minions take turns attacking from **left to right**. You can still shuffle them around even after the timer runs out.",
    aliases: ['reorder', 'move minion', 'position', 'left to right', 'swap'],
    seeAlso: ['timer-runs-out'],
  },
  {
    id: 'refresh-and-freeze-buttons',
    topic: 'controls',
    q: 'How do I refresh or freeze the shop?',
    a: "**Refresh** is the crystal at the top middle of the screen. Its coin shows what a reroll costs (a green 0 means it's free). **Freeze** is the gem at the top-right of your board; click it again to unfreeze. Neither one has a keyboard shortcut.",
    aliases: ['reroll', 'roll', 'new shop', 'lock shop', 'hold shop'],
    seeAlso: ['timer-runs-out'],
  },
  {
    id: 'tavern-up-button',
    topic: 'controls',
    q: 'How do I upgrade my tavern tier?',
    a: "Click the stone **Tavern Up** button on the left side of your board. The coin on it shows the price, and the pips around the orb show your current tier. It greys out when you can't afford it or you're already maxed.",
    aliases: ['level up', 'tier up', 'upgrade shop', 'tavern tier'],
  },
  {
    id: 'end-turn',
    topic: 'controls',
    q: 'How do I end my turn?',
    a: "Click the big diamond gem on the right side of your board. It ignores clicks for the first couple of seconds of each shop turn, so a stray double-click can't skip your whole turn. After combat, the same gem takes you back to the shop.",
    aliases: ['start combat', 'fight', 'done', 'finish turn', 'go'],
    seeAlso: ['timer-runs-out'],
  },
  {
    id: 'timer-runs-out',
    topic: 'controls',
    q: 'What happens when my turn timer hits 0?',
    a: "Combat **doesn't** start by itself. Instead, buying, playing, selling, refreshing and Tavern Up all lock, and the End Turn gem starts glowing at you. You can still rearrange your board, freeze, and hit End Turn. The timer also pauses while you're making a pick (like a Discover).",
    aliases: ['turn timer', 'clock', 'out of time', 'countdown'],
    seeAlso: ['end-turn'],
  },
  {
    id: 'inspect-a-card',
    topic: 'controls',
    q: 'How do I look at a card up close?',
    a: "**Right-click** any card. You'll get a big version with every buff it has picked up and what its keywords mean. Hovering a card also shows the full card, plus any card it makes (like a token it summons). On a touchscreen, just tap it.",
    aliases: ['zoom', 'enlarge', 'card details', 'buffs', 'hover', 'right click'],
    seeAlso: ['open-compendium'],
  },
  {
    id: 'open-compendium',
    topic: 'controls',
    q: 'How do I open the Compendium (and this Rules page)?',
    a: "Press **Tab**, on the title screen or in the middle of a run. Press Tab or Esc again (or click outside it) to close it. In a run it only shows the cards you can actually find that game. The **Rules** button up top is where you are right now.",
    aliases: ['card list', 'book', 'codex', 'glossary', 'help', 'wiki'],
  },
  {
    id: 'combat-speed',
    topic: 'controls',
    q: 'Can I speed up or skip a fight?',
    a: "Yep. While a fight plays there's a **Skip** button just above the End Turn gem. To make every fight faster, open the menu with **Esc** and move the combat speed slider (anywhere from 0.5× to 5×).",
    aliases: ['fast forward', 'skip combat', 'speed', 'slow down'],
  },
];
