import type { WikiEntry } from './types';

// Checked against packages/core/src/effects/arena.ts + factories.ts, combat/simulate.ts (isTribeOf),
// packages/core/src/tribeGate.ts, packages/content/src/sets.ts, packages/sim/src/recruit.ts (playCard, fire
// 'onSummon', settleMinionSale, addTurnShopBuff), reducer.ts (sell, spendGold, combineIntoGolden, buy),
// packages/ui/src/Card.tsx (tribe plate) and the approved rules cited in `covers`, on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── Tribes ──────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'what-is-a-tribe',
    topic: 'glossary',
    q: 'What is a tribe?',
    a: "A tribe is a minion's **type**, printed on the card (Beast, Dragon, Demon and so on). Lots of cards only care about one tribe, like \"give your Beasts +1/+1\", so building around a tribe is how most boards get strong.",
    aliases: ['type', 'minion type', 'race', 'tribal', 'synergy', 'what type is this'],
    seeAlso: ['tribes-in-a-game', 'neutral-tribe-meaning', 'dual-tribe-minions', 'all-type-minions'],
  },
  {
    id: 'neutral-tribe-meaning',
    topic: 'glossary',
    q: 'What does "Neutral" mean on a minion?',
    a: "It has **no tribe**. A Neutral minion never counts for tribe effects (\"your Dragons\" skips it), but it also shows up in every game no matter which tribes are in play. Think of Neutrals as flexible glue that fits any board.",
    aliases: ['neutral', 'no tribe', 'untyped', 'tribeless', 'no type'],
    seeAlso: ['what-is-a-tribe', 'all-type-minions'],
  },
  {
    id: 'dual-tribe-minions',
    topic: 'glossary',
    q: 'Does a minion with two tribes count as both?',
    a: "Yep. A minion printed with two tribes (like **Dragon / Demon**) counts as **both, fully**. \"Give your Demons +2/+2\" buffs it, and so does \"give your Dragons +2/+2\". It also counts once for each of its tribes when something counts your minions of a type.",
    aliases: ['two tribes', 'double tribe', 'dual type', 'hybrid', 'both types', 'slash tribe'],
    seeAlso: ['what-is-a-tribe', 'all-type-minions'],
  },
  {
    id: 'all-type-minions',
    topic: 'glossary',
    q: 'What does "ALL" mean where the tribe should be?',
    a: "That minion counts as **every tribe at once**. Any tribe effect can hit it: your Beast buffs, your Demon buffs, your Kobold Ruby riders, all of them. It shows **ALL** instead of a tribe name so you know it isn't Neutral.",
    aliases: ['all', 'every type', 'all tribes', 'every tribe', 'all types', 'amalgam', 'counts as every type'],
    seeAlso: ['dual-tribe-minions', 'neutral-tribe-meaning'],
  },

  // ── Cards, minions, spells, tokens ─────────────────────────────────────────────────────────────────────
  {
    id: 'minion-vs-card',
    topic: 'glossary',
    q: 'What\'s the difference between a "card", a "minion" and a "unit"?',
    a: "**Card** means anything you can hold: minions and spells alike. A **minion** is a card with Attack and Health that goes on your board and fights. A few cards say **unit**; that just means minion.",
    aliases: ['unit', 'units', 'card', 'minion', 'creature', 'body', 'follower'],
    seeAlso: ['spell-vs-minion', 'what-is-a-token'],
  },
  {
    id: 'spell-vs-minion',
    topic: 'glossary',
    q: 'How are spells different from minions?',
    a: "A spell is played from your hand **for its effect** and then it's gone; it never takes a spot on your board. Some spells ask you to aim them at a friendly minion. Heads up: you **can't sell a spell**, only minions.",
    aliases: ['spell', 'spells', 'cast a spell', 'sell a spell', 'can i sell spells'],
    seeAlso: ['shop-spell-meaning', 'what-cast-means', 'minion-vs-card'],
    covers: [{ keyword: 'shopspell', fp: '29456d92' }],
  },
  {
    id: 'what-is-a-token',
    topic: 'glossary',
    q: 'What is a token?',
    a: "A token is a minion that **only exists because another card made it** (like the little guys an Echo summons). Tokens never show up in the Shop, so the only way to get one is through the card or effect that names it.",
    aliases: ['token', 'tokens', 'summoned minion', 'generated minion', 'not in shop', 'generated card', 'created card'],
    seeAlso: ['summon-vs-play', 'minion-vs-card'],
  },
  {
    id: 'what-are-stats',
    topic: 'glossary',
    q: 'What are "stats"?',
    a: "A minion's **stats** are its **Attack** (how much damage it deals when it hits) and its **Health** (how much damage it can take before it dies). They're the two numbers in the corners of the card. \"Gain stats\" or \"give stats\" means raising both.",
    aliases: ['stats', 'attack', 'health', 'atk', 'hp', 'power', 'numbers on the card'],
    seeAlso: ['plus-x-plus-y'],
  },
  {
    id: 'plus-x-plus-y',
    topic: 'glossary',
    q: 'What does "+2/+3" mean?',
    a: "It's **+Attack/+Health**, always in that order. So +2/+3 means **2 more Attack and 3 more Health**. A plain \"3/4\" (no plus signs) is a minion's full stats: 3 Attack, 4 Health.",
    aliases: ['+1/+1', '+x/+y', 'slash', 'attack health notation', 'buff numbers'],
    seeAlso: ['what-are-stats', 'set-stats-to'],
  },
  {
    id: 'set-stats-to',
    topic: 'glossary',
    q: 'What\'s the difference between "give +7/+7" and "set its stats to 7/7"?',
    a: "**Give +7/+7** adds on top of what it already has. **Set its stats to 7/7** replaces the numbers: the minion ends up exactly 7/7, whatever it was before.",
    aliases: ['set stats', 'set to', 'becomes', 'replace stats', 'change stats'],
    seeAlso: ['plus-x-plus-y', 'double-stats'],
  },
  {
    id: 'double-stats',
    topic: 'glossary',
    q: 'What does "double its stats" do?',
    a: "The minion gains a **second helping of whatever it has right now**, so a 5/4 becomes a 10/8. When a card says it gains \"double\" another minion's stats (like when it Consumes one), it gains twice that minion's Attack and Health.",
    aliases: ['double', 'doubles', 'twice the stats', '2x stats', 'multiply'],
    seeAlso: ['set-stats-to', 'plus-x-plus-y'],
  },
  {
    id: 'gain-vs-give',
    topic: 'glossary',
    q: 'What\'s the difference between "gain" and "give"?',
    a: "**Gain** means the card itself gets it (\"gain +3/+2\" grows this minion; \"gain 2 Gold\" is Gold for you). **Give** means it hands the bonus to other minions. When a card gives something to a whole group, like \"give your Dwarves +3/+3\", it's included too if it belongs to that group.",
    aliases: ['gain', 'gains', 'give', 'gives', 'self buff', 'does it buff itself'],
    seeAlso: ['friendly', 'what-are-stats'],
    covers: [{ rule: 'R-TARGET-03', fp: '214c61db' }],
  },

  // ── Playing, summoning, casting ────────────────────────────────────────────────────────────────────────
  {
    id: 'summon-vs-play',
    topic: 'glossary',
    q: 'What\'s the difference between "play" and "summon"?',
    a: "**Play** means you dragged the card out of your hand. **Summon** means a minion appeared on the board, however it got there. Playing a minion counts as summoning it too, but a minion that an effect summons was **not played**. So its **Shout doesn't go off**, and \"whenever you play a...\" cards don't notice it. \"Whenever you summon a...\" cards notice both.",
    aliases: ['summon', 'summoned', 'play', 'played', 'does summoning trigger battlecry', 'does a token trigger shout', 'enter the board'],
    seeAlso: ['what-counts-as-played', 'what-is-a-token', 'play-from-hand'],
    covers: [{ keyword: 'shout', fp: 'bbe6a0f3' }],
  },
  {
    id: 'what-counts-as-played',
    topic: 'glossary',
    q: 'What counts as "playing" a card?',
    a: "Only **you playing it from your hand**: minions, spells, Shop spells, Rubies, Ales and Gifts all count. Buying a card doesn't play it (it just goes to your hand). Getting, drawing or moving a card doesn't either, and a spell an effect casts by itself isn't \"played\".",
    aliases: ['played', 'play a card', 'cards played this turn', 'does buying count', 'play count'],
    seeAlso: ['summon-vs-play', 'what-cast-means', 'buy-play-get'],
    covers: [{ rule: 'R-PLAY-01', fp: '55820196' }],
  },
  {
    id: 'buy-play-get',
    topic: 'glossary',
    q: 'What do "buy", "get" and "Discover" each do with a card?',
    a: "**Buy** pays Gold for a Shop card and puts it in your hand. **Get** puts a card straight into your hand for free. **Discover** shows you three and puts the one you pick in your hand. None of these play the card: you still have to play it yourself.",
    aliases: ['get a card', 'add to hand', 'buy', 'receive', 'goes to hand', 'discover'],
    seeAlso: ['what-counts-as-played', 'discover', 'buy-a-minion'],
    covers: [{ rule: 'R-PLAY-01', fp: '55820196' }],
  },
  {
    id: 'summon-auras-before-shout',
    topic: 'glossary',
    q: 'When I play a minion, do my "whenever you summon" cards buff it before its Shout?',
    a: "Yes. The minion lands, your \"whenever you summon\" effects hit it first, and **then** its own Shout goes off. So if the Shout summons more minions, they see the already-improved bonus.",
    aliases: ['order', 'shout timing', 'summon buff order', 'battlecry order', 'before battlecry'],
    seeAlso: ['summon-vs-play'],
    covers: [{ rule: 'R-ORD-02', fp: 'f49cb500' }],
  },
  {
    id: 'what-cast-means',
    topic: 'glossary',
    q: 'If a minion casts a spell for me, does that count as me casting it?',
    a: "Yes. A spell a minion (or rune) casts **counts as a spell cast** everywhere: your \"whenever you cast a spell\" cards react, and it counts toward spell tallies, in the Shop, at End of Turn and in combat. It just **isn't a card played from hand**, so it doesn't count as \"played\".",
    aliases: ['cast', 'casts', 'minion casts a spell', 'does it count as a spell', 'spell cast by minion'],
    seeAlso: ['cast-multipliers-from-hand', 'what-counts-as-played'],
    covers: [{ rule: 'R-MINIONCAST-01', fp: '5e8a4848' }, { rule: 'R-PLAY-01', fp: '55820196' }],
  },
  {
    id: 'cast-multipliers-from-hand',
    topic: 'glossary',
    q: 'Do "your spells cast twice" effects work on spells a minion casts?',
    a: "No. Anything that makes a spell **cast more times** only works on spells **you cast from your hand**. A spell a minion, rune or Equipment casts goes off once, and it doesn't use up your one-shot \"next spell\" bonuses either; those wait for your next spell from hand.",
    aliases: ['spell twice', 'cast twice', 'extra cast', 'spell multiplier', 'next spell casts again'],
    seeAlso: ['what-cast-means'],
    covers: [{ rule: 'R-MULT-06', fp: 'af59f5c6' }],
  },
  {
    id: 'shop-spell-meaning',
    topic: 'glossary',
    q: 'What counts as a "Shop spell"?',
    a: "A spell that comes from the **Shop's spell pool**, and that includes **Dwarven Ales**. Rubies, Clues, Gifts and reward spells are **not** Shop spells, even though they're spells. Casting a Shop spell counts no matter who casts it (you, a minion or a rune).",
    aliases: ['shop spell', 'shop spells', 'is a ruby a shop spell', 'is an ale a shop spell', 'gift spell'],
    seeAlso: ['spell-vs-minion', 'what-cast-means'],
    covers: [{ keyword: 'shopspell', fp: '29456d92' }, { rule: 'R-SHOPSPELL-01', fp: 'fcac2a2e' }],
  },

  // ── Dying, destroying, selling ────────────────────────────────────────────────────────────────────────
  {
    id: 'destroy-vs-dies',
    topic: 'glossary',
    q: 'Is "destroy" different from a minion dying?',
    a: "**Destroy** kills a minion outright, no matter how much Health it has. It's still a real death: its **Echo goes off** and a **Rise** minion comes back, in the Shop just like in combat.",
    aliases: ['destroy', 'destroyed', 'kill', 'dies', 'death', 'sacrifice', 'destroy in shop'],
    seeAlso: ['selling-is-not-dying', 'rise-in-shop'],
    covers: [{ rule: 'R-RISE-02', fp: '0487dd36' }],
  },
  {
    id: 'selling-is-not-dying',
    topic: 'glossary',
    q: 'Does selling a minion count as it dying?',
    a: "No. Selling just removes it and pays you Gold. Its **Echo doesn't go off** and it won't Rise. Minions that care about being sold say **Sell:** instead.",
    aliases: ['sell echo', 'sell deathrattle', 'does selling kill', 'sold minion', 'sell vs die'],
    seeAlso: ['destroy-vs-dies', 'sell-trigger', 'sell-a-minion'],
  },
  {
    id: 'sell-this-vs-sell-another',
    topic: 'glossary',
    q: 'What\'s the difference between "Sell:" and "when you sell a minion"?',
    a: "**Sell:** only fires when **this** minion is sold. A card that says \"when you sell a Demon\" (or any minion) is watching you sell **other** minions while it stays on your board.",
    aliases: ['sell trigger', 'when you sell', 'on sell', 'sell another'],
    seeAlso: ['sell-trigger', 'rally-watchers'],
    covers: [{ keyword: 'sell', fp: '2b305b36' }, { rule: 'R-TEXT-09', fp: '522bf00e' }],
  },

  // ── Positions and targets ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'adjacent-meaning',
    topic: 'glossary',
    q: 'What does "adjacent" mean, and what if my minion is on the edge?',
    a: "Adjacent means the minions **directly to its left and right**. On the edge of the board there's only one neighbour, so it only affects that one (and a lone minion has none). In combat, when a neighbour dies the next living minion over becomes the new neighbour.",
    aliases: ['adjacent', 'neighbour', 'neighbor', 'next to', 'beside', 'edge', 'end of board', 'both sides'],
    seeAlso: ['left-most-right-most', 'board-order'],
    covers: [{ rule: 'R-TARGET-03', fp: '214c61db' }],
  },
  {
    id: 'left-most-right-most',
    topic: 'glossary',
    q: 'What do "left-most" and "right-most" mean?',
    a: "The one **furthest left** (or right) that matches the text, on your board, or in your hand or the Shop if the card says so. It's a position check, not a choice, so the card can count itself if it matches.",
    aliases: ['left-most', 'right-most', 'leftmost', 'rightmost', 'first', 'last', 'furthest left'],
    seeAlso: ['adjacent-meaning', 'board-order'],
    covers: [{ rule: 'R-TARGET-03', fp: '214c61db' }],
  },
  {
    id: 'random-meaning',
    topic: 'glossary',
    q: 'How does "random" pick?',
    a: "It picks at random from **everything that fits** the text right then. When a card picks a random friendly minion, it **never picks itself**. If an effect repeats, each repeat picks again, so the same minion can get hit more than once.",
    aliases: ['random', 'randomly', 'random target', 'rng', 'luck', 'who gets it'],
    seeAlso: ['friendly', 'another-vs-different', 'for-each-vs-repeat'],
    covers: [{ rule: 'R-TARGET-03', fp: '214c61db' }, { rule: 'R-REPEAT-01', fp: '88688c67' }],
  },
  {
    id: 'enemy-meaning',
    topic: 'glossary',
    q: 'What counts as an "enemy"?',
    a: "The minions on your **opponent's** side in a fight. Enemies only exist in **combat**; the Shop is just you and your board.",
    aliases: ['enemy', 'enemies', 'opponent minions', 'foe', 'their minions'],
    seeAlso: ['friendly', 'who-do-i-fight'],
  },
  {
    id: 'your-minions-vs-hand',
    topic: 'glossary',
    q: 'Does "your minions" include the cards in my hand?',
    a: "No, \"your minions\" means the ones **on your board**. Anything that touches your hand says **\"in your hand\"**. A nice bonus: a buff that lands on a card in your hand is **permanent**, even if it happens during a fight.",
    aliases: ['in your hand', 'hand buff', 'hand minions', 'does it buff my hand'],
    seeAlso: ['friendly', 'aura-meaning'],
    covers: [{ rule: 'R-HAND-02', fp: 'd7ad0466' }],
  },
  {
    id: 'locked-hand-card',
    topic: 'glossary',
    q: 'Why is a card in my hand locked?',
    a: "Some effects **lock** a hand card for a while. A locked card **can't reach the board by any route**: you can't play it, and \"summon from your hand\" effects skip it. It can still be buffed, and it still counts for cards that only look at your hand.",
    aliases: ['locked', 'lock', 'cant play card', 'greyed out', 'grayed out'],
    seeAlso: ['summon-from-hand-copy'],
    covers: [{ rule: 'R-HAND-03', fp: '790b0f80' }],
  },

  // ── Copies ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'plain-copy',
    topic: 'glossary',
    q: 'Does a "plain copy" keep the original\'s buffs?',
    a: "No. A **plain copy** is a **fresh card as printed**: no extra stats, no granted keywords, no progress, and not Gilded. It does still get any **Auras** you have, since those apply to every card that fits.",
    aliases: ['plain copy', 'copy', 'copies', 'duplicate', 'clone', 'does a copy keep buffs'],
    seeAlso: ['exact-copy', 'aura-meaning'],
    covers: [{ rule: 'R-COPY-01', fp: '31bb49a1' }, { rule: 'R-AVWIN-04', fp: 'b0ceb0fc' }],
  },
  {
    id: 'exact-copy',
    topic: 'glossary',
    q: 'What\'s an "exact copy"?',
    a: "A perfect clone of the minion **as it is right now**: all its buffs, keywords, attachments, improved numbers and counters. If the original already used a once-per-combat effect, the exact copy has used it too.",
    aliases: ['exact copy', 'perfect copy', 'clone', 'copy with buffs'],
    seeAlso: ['plain-copy', 'summon-from-hand-copy'],
    covers: [{ rule: 'R-COPY-02', fp: '099b2ddc' }, { rule: 'R-AVWIN-03', fp: '0ff2e888' }, { rule: 'R-AVWIN-08', fp: 'ddc7cca7' }],
  },
  {
    id: 'summon-from-hand-copy',
    topic: 'glossary',
    q: 'When a card "summons a minion from your hand", do I lose the card?',
    a: "No. It puts an **exact copy** of that hand card onto the board and the card **stays in your hand**. Each hand card can only be summoned this way **once per combat**. Buffs the hand card gets later don't reach the copy.",
    aliases: ['summon from hand', 'from your hand', 'hand summon', 'do i lose the card'],
    seeAlso: ['exact-copy', 'locked-hand-card'],
    covers: [{ keyword: 'summonfromhand', fp: 'ff0f6fc0' }, { rule: 'R-HAND-04', fp: '719345af' }],
  },

  // ── Gilded ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'gilded-text',
    topic: 'glossary',
    q: 'What does the Gilded version of a card do?',
    a: "Usually its effect is **doubled** (twice the stats, twice the summons, or it triggers twice). A few cards do something different when Gilded instead, and those say so in their Gilded text, so inspect the card to be sure. Its stats are the **two strongest copies added together**, with every copy's keywords.",
    aliases: ['gilded', 'golden', 'gold version', 'tripled', 'what does golden do'],
    seeAlso: ['triples', 'gilded-spells'],
    covers: [{ keyword: 'gilded', fp: '14fa614f' }, { rule: 'R-GILD-01', fp: 'd0abe88d' }],
  },
  {
    id: 'gilded-spells',
    topic: 'glossary',
    q: 'Can a spell be Gilded?',
    a: "No. Gilding is only for minions. There's no Gilded spell.",
    aliases: ['golden spell', 'gilded spell', 'triple spells', 'spell triple'],
    seeAlso: ['gilded-text', 'triples'],
    covers: [{ rule: 'R-GILD-02', fp: '4cf9aa2f' }],
  },

  // ── Timing words ───────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'this-turn-includes-combat',
    topic: 'glossary',
    q: 'Does "this turn" include the fight after the Shop?',
    a: "Yes. A turn is your Shop phase **plus the fight that ends it**. Something that lasts \"this turn\" (or counts \"this turn\") is still live in that combat, and it resets when your next Shop opens.",
    aliases: ['this turn', 'turn', 'until end of turn', 'when does it reset', 'per turn'],
    seeAlso: ['each-turn-vs-start-of-turn', 'combat-vs-permanent-wording'],
    covers: [{ rule: 'R-TURN-01', fp: '61026a27' }],
  },
  {
    id: 'each-turn-vs-start-of-turn',
    topic: 'glossary',
    q: 'What\'s the difference between "each turn", "Start of Turn" and "End of Turn"?',
    a: "**Start of Turn** fires when your Shop opens. **End of Turn** fires after you press End Turn, right before the fight. **Each turn** (or \"once per turn\") is a limit: you get it once per turn, and it's ready again when your next Shop opens.",
    aliases: ['each turn', 'once per turn', 'start of turn', 'end of turn', 'every turn', 'resets'],
    seeAlso: ['this-turn-includes-combat', 'end-turn'],
    covers: [{ keyword: 'startofturn', fp: '0f361616' }, { keyword: 'endofturn', fp: 'e71a0509' }],
  },
  {
    id: 'when-vs-whenever',
    topic: 'glossary',
    q: 'Is "when" different from "whenever"?',
    a: "No, both mean **every time** it happens, not just the first time. If a card only works once, it says so, like \"(Once per turn)\" or \"the first ... each turn\".",
    aliases: ['when', 'whenever', 'after', 'every time', 'only once', 'first time'],
    seeAlso: ['each-turn-vs-start-of-turn'],
  },
  {
    id: 'combat-vs-permanent-wording',
    topic: 'glossary',
    q: 'What\'s the difference between a buff "in combat", "permanently" and "this game"?',
    a: "A buff from a **combat** effect only lasts that fight. **Permanently** means that minion keeps it for the rest of the run. **This game** (or an **Aura**) goes further: it applies to **every** minion of that kind you have now **or get later**.",
    aliases: ['this game', 'this combat', 'for the rest of the game', 'temporary', 'run wide', 'forever'],
    seeAlso: ['permanent', 'combat-buffs-dont-stay', 'aura-meaning'],
    covers: [{ rule: 'R-REALTIME-04', fp: '928aa562' }],
  },
  {
    id: 'shop-buff-this-turn',
    topic: 'glossary',
    q: 'If Shop minions get a buff "this turn", do they keep it when I buy them?',
    a: "Yes. \"This turn\" is how long the **Shop** stays boosted (even after you refresh). Any minion you **buy** during that time is yours with the extra stats, for good.",
    aliases: ['shop buff', 'shop minions', 'buff the shop', 'tavern buff', 'keep shop buff'],
    seeAlso: ['this-turn-includes-combat', 'buy-a-minion'],
  },
  {
    id: 'realtime-triggers',
    topic: 'glossary',
    q: 'If a fight earns me something, do I get it right away or after the fight?',
    a: "**Right away**, at the moment it happens, unless the card says otherwise (\"next turn\", \"after combat\" and so on). A card earned mid-fight lands in your hand during the fight, and counters on cards tick up live.",
    aliases: ['when do i get it', 'after combat', 'during combat', 'delayed', 'timing'],
    seeAlso: ['this-turn-includes-combat'],
    covers: [{ rule: 'R-REALTIME-01', fp: 'c38cdde1' }],
  },

  // ── Triggers ───────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'trigger-meaning',
    topic: 'glossary',
    q: 'What does it mean to "trigger" an effect?',
    a: "To make it **go off right now**, as if its condition just happened. \"Trigger your left-most Echo\" fires that minion's Echo **without it dying**. A triggered Shout, Echo or Rally counts as a real one, so cards that react to those notice it.",
    aliases: ['trigger', 'retrigger', 're-trigger', 'fire', 'activate', 'proc', 'trigger an echo'],
    seeAlso: ['trigger-your-shouts', 'trigger-twice-stacking'],
    covers: [{ rule: 'R-RALLY-01', fp: '4f5d9f16' }],
  },
  {
    id: 'trigger-your-shouts',
    topic: 'glossary',
    q: 'What happens when a card says "trigger your Shout minions"?',
    a: "**Every** Shout minion on your board fires its Shout again, **left to right**, wherever it's standing. Each one counts as a Shout for anything that watches Shouts. It doesn't fire its own Shout, and a Shout minion that shows up partway through waits for next time.",
    aliases: ['trigger shouts', 'retrigger battlecry', 'refire shout', 'replay shouts', 'shout again'],
    seeAlso: ['trigger-meaning', 'shout-refire-target'],
    covers: [{ rule: 'R-SHOUT-02', fp: '1b547e9e' }],
  },
  {
    id: 'for-each-vs-repeat',
    topic: 'glossary',
    q: 'What\'s the difference between "+1/+1 for each" and "Repeat for every"?',
    a: "**For each** adds it all up into **one bigger buff**. **Repeat for every** does the base effect once, then **again** for each one counted, as separate hits (a random target re-rolls every time). With zero counted, both still give the base once.",
    aliases: ['for each', 'repeat', 'repeat for every', 'per', 'for every', 'stacks'],
    seeAlso: ['trigger-twice-stacking', 'random-meaning'],
    covers: [{ rule: 'R-REPEAT-01', fp: '88688c67' }],
  },

  // ── Numbers that grow ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'card-shows-current-value',
    topic: 'glossary',
    q: 'Are the numbers in card text the real ones?',
    a: "Yep. When a card's effect grows (improves, counts things, gets spell power), its text shows **what it will actually do right now**, everywhere you see it: the Shop, Discover, your hand, your board and in combat.",
    aliases: ['card text wrong', 'live numbers', 'current value', 'text updates', 'real number'],
    seeAlso: ['improve'],
    covers: [{ rule: 'R-TEXT-02', fp: 'f752fe61' }],
  },
  {
    id: 'aura-meaning',
    topic: 'glossary',
    q: 'What does "your Beast Aura" (or any Aura) mean?',
    a: "An **Aura** is a run-wide bonus for a whole group. Giving your Beast Aura +2/+4 buffs **every Beast you have**, on your board, in your hand and in the Shop, **plus every Beast you get later**. It never wears off, even if it happened in combat.",
    aliases: ['aura', 'beast aura', 'imp aura', 'undead aura', 'run wide', 'everywhere', 'wherever they are'],
    seeAlso: ['combat-vs-permanent-wording', 'plain-copy'],
    covers: [{ keyword: 'aura', fp: '602ebf18' }, { rule: 'R-AURA-02', fp: '5884cd85' }],
  },
  {
    id: 'card-tier-meaning',
    topic: 'glossary',
    q: 'What is a card\'s tier?',
    a: "Every card has a tier from 1 upward (stronger cards sit higher). The Shop only offers cards **at or below your Tavern Tier**, so tiering up is how you unlock better cards. Tier 6 is the normal top; Tier 7 cards only appear when something unlocks them.",
    aliases: ['tier', 'card tier', 'tavern tier', 'level', 'star', 'tier 7'],
    seeAlso: ['tavern-tier-cost', 'tavern-up-button'],
  },
];
