import type { WikiEntry } from './types';

// Checked against sim/reducer.ts (Magnetic weld, Ruby play, sell, triples), sim/recruit.ts (consumeShopOffer,
// consumeTavernFodder, aura grants, Clue), sim/equipment.ts, sim/starform.ts notes in docs/GAME-RULES.md,
// core/effects/factories.ts + combat/simulate.ts (summon from hand), content gifts/handSpells/tokens, and
// ui StatusBar.tsx / Recruit.tsx / dragDecision.ts / runBuffs.ts on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── Attachment ────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'attachment',
    topic: 'keywords',
    q: 'What does Attachment do?',
    a: "An Attachment is a minion you can **fuse into another friendly minion** that shares its type. The host gains the Attachment's stats and its keywords, and the Attachment doesn't take up a board slot (so it works even on a full board). You can also just play it as a normal minion if you want.",
    aliases: ['magnetic', 'magnetize', 'attach', 'weld', 'fuse'],
    seeAlso: ['attach-how-to', 'attachment-type-match'],
    covers: [{ keyword: 'attachment', fp: '168ceb1c' }],
  },
  {
    id: 'attach-how-to',
    topic: 'keywords',
    q: 'How do I attach an Attachment to a minion?',
    a: "**Drag it from your hand and drop it right on top of** a friendly minion that shares its type. The minion lights up when the drop will attach. Drop it in a gap between minions instead and it's played as its own minion.",
    aliases: ['magnetize onto', 'how to magnetic', 'drop attachment', 'attach to minion'],
    seeAlso: ['attachment', 'attachment-type-match'],
  },
  {
    id: 'attachment-type-match',
    topic: 'keywords',
    q: 'Which minions can an Attachment go on?',
    a: "Any friendly minion that **shares at least one type** with it. Dual-type minions count both types, so a Mech/Demon Attachment can go on a Mech or a Demon. An all-types Attachment goes on any minion that has a type.",
    aliases: ['magnetic target', 'what can i attach to', 'attach to demon', 'attach to mech', 'same tribe'],
    seeAlso: ['attachment', 'attach-how-to'],
  },
  {
    id: 'attachment-shout',
    topic: 'keywords',
    q: "Does an Attachment's Shout go off when I attach it?",
    a: "No. When it's attached, it just hands over its stats and keywords. Its Shout only happens if you play it as its own minion on the board. Effects that care about you **playing** a card or summoning still count it, though.",
    aliases: ['attachment battlecry', 'magnetic battlecry', 'attach shout'],
    seeAlso: ['attachment'],
  },
  {
    id: 'attachment-keyword-transfer',
    topic: 'keywords',
    q: 'Does the host minion become an Attachment too?',
    a: "No. The host picks up the Attachment's stats and its other keywords (like Ward or Rally), but not the Attachment keyword itself. So you can't later peel it off and attach the host somewhere else.",
    aliases: ['host becomes magnetic', 'magnetic keyword transfer', 'attachment keywords'],
    seeAlso: ['attachment'],
  },
  {
    id: 'attachment-sold',
    topic: 'keywords',
    q: 'What happens to my attachments if I sell the minion they are on?',
    a: "They're gone with it. Once attached, an Attachment is part of that minion, so selling the host sells everything that was fused into it. You don't get the Attachment back.",
    aliases: ['sell magnetic', 'sell host', 'lose attachments'],
    seeAlso: ['sell-a-minion', 'attachment'],
  },
  {
    id: 'attachment-gilded',
    topic: 'keywords',
    q: 'Do attachments carry over when the minion gets Gilded?',
    a: "Mostly, yes. The Gilded minion stacks your **two strongest copies** (attached stats included) and keeps every keyword any of the copies had. Heads up: the stats on the weakest copy aren't added, so if you care, attach to a copy you'll keep.",
    aliases: ['triple magnetic', 'golden attachments', 'gild attached minion'],
    seeAlso: ['triples', 'attachment'],
  },
  {
    id: 'attachment-aura',
    topic: 'keywords',
    q: "What's the Attachment Aura?",
    a: "A run-wide bonus for your Attachments. When it goes up, the Attachments on your board and in your hand get the stats right away, and every Attachment you get later arrives with it too. Attach one and those stats get fused into the host.",
    aliases: ['magnetic aura', 'attachment buff', 'scrap aura'],
    seeAlso: ['aura', 'attachment'],
  },

  // ── Consume ───────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'consume',
    topic: 'keywords',
    q: 'What does Consume do?',
    a: "Your minion **eats a minion from the Shop** and gains its stats. The eaten offer disappears from the Shop. It's mostly a Demon thing.",
    aliases: ['devour', 'eat', 'eats a minion', 'consumes'],
    seeAlso: ['consume-what-it-eats', 'fodder', 'consume-in-combat'],
    covers: [{ keyword: 'consume', fp: '557ac431' }],
  },
  {
    id: 'consume-what-it-eats',
    topic: 'keywords',
    q: 'What can a Consume eat?',
    a: "Only **minions in the Shop**. Spells and Rubies sitting in the Shop row are never eaten, and your own board minions are never on the menu. A card that says \"the right-most minion\" skips over spells to find the last minion, and one that just says \"a minion\" picks a random one.",
    aliases: ['consume target', 'eat spell', 'right-most minion', 'random shop minion'],
    seeAlso: ['consume', 'consume-gilded'],
    covers: [{ rule: 'R-ORD-03', fp: '47052a67' }, { rule: 'R-RAND-01', fp: '3d89d2c5' }],
  },
  {
    id: 'consume-gilded',
    topic: 'keywords',
    q: 'Can a Consume eat my Gilded minion?',
    a: "No. Consume only eats offers in the **Shop**, so nothing on your board (Gilded or not) is ever eaten. If a Shop offer happens to be Gilded, eating it gives its doubled stats.",
    aliases: ['consume golden', 'eat gilded', 'consume my minion'],
    seeAlso: ['consume-what-it-eats', 'triples'],
  },
  {
    id: 'consume-in-combat',
    topic: 'keywords',
    q: 'Can Consume happen during combat?',
    a: "No, Consume only happens in the Shop. If a Consume effect goes off mid-fight (say a Shout replayed in combat), it still counts as firing, but the actual eating waits until the next Shop opens.",
    aliases: ['combat consume', 'consume in fight', 'consume during battle'],
    seeAlso: ['consume'],
    covers: [{ rule: 'R-REALTIME-05', fp: 'ba2ada71' }],
  },

  // ── Fodder ────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'fodder',
    topic: 'keywords',
    q: 'What is Fodder?',
    a: "Fodder is a minion made to be eaten. When Fodder **shows up in the Shop** and you have a Demon, a random one of your Demons automatically Consumes it and gains its stats. Some Demons gain extra from Fodder.",
    aliases: ['fodder minion', 'demon food', 'imp food'],
    seeAlso: ['consume', 'fodder-no-demon', 'fodder-aura'],
    covers: [{ keyword: 'fodder', fp: 'cd91c783' }],
  },
  {
    id: 'fodder-no-demon',
    topic: 'keywords',
    q: "What happens to Fodder if I don't have a Demon?",
    a: "It just sits in the Shop like any other offer, and you can buy it if you want.",
    aliases: ['fodder not eaten', 'buy fodder', 'no demon'],
    seeAlso: ['fodder', 'fodder-already-in-shop'],
  },
  {
    id: 'fodder-already-in-shop',
    topic: 'keywords',
    q: 'If I play a Demon while Fodder is already in the Shop, does it eat it?',
    a: "No. The auto-eat only checks Fodder at the moment it **arrives** in the Shop. Fodder that was already sitting there stays put (a card that specifically Consumes can still eat it).",
    aliases: ['fodder late demon', 'fodder already there', 'demon next to fodder'],
    seeAlso: ['fodder'],
  },
  {
    id: 'fodder-aura',
    topic: 'keywords',
    q: "What's the Fodder Aura?",
    a: "A run-wide bonus on your Fodder. Every Fodder that shows up carries the extra stats, so your Demons gain more when they eat it. You can see it in your Buffs panel.",
    aliases: ['fodder buff', 'bigger fodder'],
    seeAlso: ['fodder', 'aura', 'check-my-auras'],
  },

  // ── Improve ───────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'improve',
    topic: 'keywords',
    q: 'What does Improve mean?',
    a: "Improve **raises the number an effect uses, for the rest of the run**. For example, \"give it +2/+2, and improve this by +2/+2\" gives +2/+2 now and +4/+4 next time.",
    aliases: ['improves', 'improving', 'scaling', 'grows', 'ramps up', 'improve', 'scales', 'escalate'],
    seeAlso: ['improve-current-value'],
    covers: [{ keyword: 'improve', fp: '0b5fe611' }],
  },
  {
    id: 'improve-current-value',
    topic: 'keywords',
    q: 'How do I know how big an improved effect is right now?',
    a: "Just read the card. It **always shows the current value**, not the starting one, and where it improves every few times it also shows how many to go.",
    aliases: ['current number', 'live value', 'card text updates', 'countdown'],
    seeAlso: ['improve', 'inspect-a-card'],
    covers: [{ keyword: 'improve', fp: '0b5fe611' }],
  },

  // ── Aura ──────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'aura',
    topic: 'keywords',
    q: 'What is an Aura?',
    a: "A **run-wide bonus** for every minion it suits, like your \"Beast Aura\" or \"Undead Aura\". It reaches the ones on your board and in your hand, and every matching minion you get later arrives with it too. It holds in both the Shop and combat.",
    aliases: ['auras', 'tribe aura', 'global buff', 'wherever they are', 'run buff'],
    seeAlso: ['aura-stacking', 'aura-after-source-leaves', 'check-my-auras'],
    covers: [{ keyword: 'aura', fp: '602ebf18' }, { rule: 'R-AURA-01', fp: '9edd5889' }],
  },
  {
    id: 'aura-stacking',
    topic: 'keywords',
    q: 'Do Auras stack?',
    a: "Yes. Every \"give your X Aura +N\" adds to that Aura's total, so two grants of +2/+2 make it +4/+4. A minion with two types gets both of its Auras.",
    aliases: ['aura stack', 'multiple auras', 'two auras'],
    seeAlso: ['aura'],
  },
  {
    id: 'aura-after-source-leaves',
    topic: 'keywords',
    q: 'Does an Aura bonus go away when the minion that gave it leaves?',
    a: "No. Once you've raised an Aura, it's **yours for the rest of the run**, even if you sell the card that did it or it dies.",
    aliases: ['aura sold', 'aura permanent', 'lose aura', 'aura minion died'],
    seeAlso: ['aura', 'aura-in-combat'],
  },
  {
    id: 'aura-in-combat',
    topic: 'keywords',
    q: 'If an Aura goes up during a fight, does it stay?',
    a: "Yep. An Aura raised in combat is permanent, exactly like one raised in the Shop. There's no \"just this fight\" Aura.",
    aliases: ['combat aura', 'aura permanent combat', 'lantern of souls'],
    seeAlso: ['aura', 'aura-after-source-leaves'],
    covers: [{ rule: 'R-AURA-02', fp: '5884cd85' }],
  },
  {
    id: 'check-my-auras',
    topic: 'keywords',
    q: 'Where can I see my Auras and other run bonuses?',
    a: "**Click your hero portrait** (bottom left). It opens your Buffs panel, listing your Auras plus things like Ruby power, Clue power and Spell power. The little arrow on the portrait only shows up once you have something to list.",
    aliases: ['buffs panel', 'run buffs', 'aura list', 'where are my buffs'],
    seeAlso: ['aura', 'ruby-power'],
  },

  // ── Summon from hand ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'summon-from-hand',
    topic: 'keywords',
    q: 'What does "summon from your hand" do?',
    a: "During combat it puts an **exact copy** of a minion from your hand onto the battlefield (with all its current stats). The card itself **stays in your hand**, so you don't lose it.",
    aliases: ['summon from hand', 'hand summon', 'spirit summon'],
    seeAlso: ['summon-from-hand-once'],
    covers: [{ keyword: 'summonfromhand', fp: 'ff0f6fc0' }],
  },
  {
    id: 'summon-from-hand-once',
    topic: 'keywords',
    q: 'Can the same hand card be summoned twice in one fight?',
    a: "No, each hand card can be summoned this way **once per combat**. If your board was full and the copy couldn't land, it doesn't count, so the card can still be summoned later that fight.",
    aliases: ['summon twice', 'once per combat', 'hand summon full board'],
    seeAlso: ['summon-from-hand'],
    covers: [{ keyword: 'summonfromhand', fp: 'ff0f6fc0' }],
  },

  // ── Equip / Equipment / Amplified ─────────────────────────────────────────────────────────────────────
  {
    id: 'equip',
    topic: 'keywords',
    q: 'What does "Equip" on a minion mean?',
    a: "Playing that minion gives you a piece of **Equipment**, a Shop ability you can trigger **once per turn** for the Gold cost in brackets. The text after the colon is what it does, like \"Equip Bloodpot (1): give a friendly minion +3/+3\".",
    aliases: ['equip minion', 'equipment minion', 'trinket'],
    seeAlso: ['equipment', 'use-equipment'],
    covers: [{ keyword: 'equip', fp: '373a24f6' }],
  },
  {
    id: 'equipment',
    topic: 'keywords',
    q: 'What is Equipment?',
    a: "An ability you get from an Equip minion. It sits in a **slot beside your hero power** and works in the Shop. You keep it as long as you keep the minion: every new turn your Equipment is rebuilt from the minions still on your board.",
    aliases: ['equipment slot', 'item', 'gear'],
    seeAlso: ['equip', 'use-equipment', 'equipment-sold-minion'],
    covers: [{ keyword: 'equipment', fp: '03ca7951' }],
  },
  {
    id: 'use-equipment',
    topic: 'keywords',
    q: 'How do I use my Equipment?',
    a: "**Click the Equipment slot** next to your hero power. If it needs a target, click the minion you want next. The Gold cost is on the little pill, and the number on the slot is how many uses you have left.",
    aliases: ['activate equipment', 'click equipment', 'equipment button'],
    seeAlso: ['equipment', 'equipment-charges'],
  },
  {
    id: 'equipment-charges',
    topic: 'keywords',
    q: 'How many times can I use Equipment each turn?',
    a: "Each piece of Equipment can be used **once per turn**, and it refreshes every turn. Some cards give bonus uses that any Equipment can spend: the number turns **green** while you have those, and they're used up first. Unused uses don't carry over.",
    aliases: ['equipment uses', 'equipment per turn', 'green number', 'bonus charge'],
    seeAlso: ['use-equipment', 'amplified'],
  },
  {
    id: 'equipment-sold-minion',
    topic: 'keywords',
    q: 'If I sell the Equip minion, do I lose the Equipment?',
    a: "Not right away. You keep it for the **rest of that turn**. At the start of your next turn it's gone unless you still have a minion that grants it.",
    aliases: ['sell equip minion', 'lose equipment', 'equipment gone'],
    seeAlso: ['equipment', 'sell-a-minion'],
  },
  {
    id: 'equipment-switch',
    topic: 'keywords',
    q: 'I have more than one Equipment. How do I switch between them?',
    a: "**Hover the Equipment slot** and a row of your Equipment slides out to the right. Click the one you want. Switching is free and doesn't use anything up.",
    aliases: ['change equipment', 'swap equipment', 'select equipment', 'multiple equipment'],
    seeAlso: ['use-equipment'],
  },
  {
    id: 'equipment-gilded-duplicates',
    topic: 'keywords',
    q: 'What if I have two of the same Equip minion, or a Gilded one?',
    a: "Copies of the same Equipment merge into one, so two of the same Equip minion still give you one Equipment. If any of them is **Gilded**, you get the upgraded Gilded version.",
    aliases: ['two equip minions', 'gilded equipment', 'duplicate equipment', 'golden equipment'],
    seeAlso: ['equipment', 'triples'],
  },
  {
    id: 'amplified',
    topic: 'keywords',
    q: 'What does Amplified mean?',
    a: "An Amplified Equipment **triggers its effect twice** the next time you use it, for **no extra Gold**. Its number turns **blue** while it's Amplified, and using it spends the Amplify.",
    aliases: ['amplify', 'amplifies', 'double equipment', 'blue number'],
    seeAlso: ['equipment', 'amplified-stacking'],
    covers: [{ keyword: 'amplified', fp: 'd5cbf937' }],
  },
  {
    id: 'amplified-stacking',
    topic: 'keywords',
    q: 'Does Amplified stack or carry over to next turn?',
    a: "It doesn't stack: an Equipment is either Amplified or not, so it fires twice at most. It **does** carry over to later turns as long as you still hold that Equipment, and it stays until you use it.",
    aliases: ['amplified twice', 'amplify carry over', 'amplify next turn'],
    seeAlso: ['amplified'],
  },

  // ── Ruby ──────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'ruby',
    topic: 'keywords',
    q: 'What is a Ruby?',
    a: "A little Kobold spell you get in your hand. **Drag it onto a minion** to give it the Ruby's stats **permanently**. Rubies are free to cast.",
    aliases: ['rubies', 'gem', 'kobold gem'],
    seeAlso: ['ruby-vs-shop-spell', 'ruby-power', 'ruby-types'],
    covers: [{ keyword: 'ruby', fp: '6a017aad' }],
  },
  {
    id: 'ruby-vs-shop-spell',
    topic: 'keywords',
    q: 'Is a Ruby a Shop spell?',
    a: "No. Rubies never count for \"Shop spell\" effects. They do count for effects that just say \"a spell\", and some cards count \"spells and Rubies\" together.",
    aliases: ['ruby shop spell', 'does ruby count as spell'],
    seeAlso: ['ruby', 'ale-shop-spell'],
    covers: [{ keyword: 'ruby', fp: '6a017aad' }, { rule: 'R-SHOPSPELL-01', fp: 'fcac2a2e' }],
  },
  {
    id: 'ruby-power',
    topic: 'keywords',
    q: 'What does "improve your Rubies" do?',
    a: "It raises your **Ruby power** for the rest of the run, so every Ruby gives more. Rubies already in your hand grow right away, and the card always shows what it'll give. Check the total in your Buffs panel (click your hero portrait).",
    aliases: ['ruby power', 'bigger rubies', 'ruby strength', 'rubies gain'],
    seeAlso: ['ruby', 'check-my-auras'],
  },
  {
    id: 'ruby-on-shop-minion',
    topic: 'keywords',
    q: 'Can I cast a Ruby on a minion in the Shop?',
    a: "A plain Ruby, yes: it says \"a minion\", so you can buff a Shop offer before you buy it. Some special Rubies need a friendly minion on your board instead, like the Warding Ruby.",
    aliases: ['ruby shop offer', 'ruby tavern', 'buff before buying'],
    seeAlso: ['ruby'],
  },
  {
    id: 'ruby-types',
    topic: 'keywords',
    q: 'What are the different kinds of Rubies?',
    a: "There are six: plain, Warding, Golden, Splintered, Ripple and Dark. They all give stats, and the special ones do something extra **if the target is a Kobold** (Ward, 2 Gold, a bounce, a second cast, or eating a Shop minion). \"Get a random Ruby\" picks any of the six evenly.",
    aliases: ['warding ruby', 'golden ruby', 'splintered ruby', 'ripple ruby', 'dark ruby', 'random ruby'],
    seeAlso: ['ruby'],
    covers: [{ rule: 'R-RAND-02', fp: '68b20e45' }],
  },
  {
    id: 'ruby-gilded',
    topic: 'keywords',
    q: 'Can three Rubies make a Gilded Ruby?',
    a: "No. Spells never get Gilded, and that includes Rubies, so extra copies just sit in your hand as normal Rubies.",
    aliases: ['triple rubies', 'golden ruby triple', 'gild a spell'],
    seeAlso: ['triples', 'ruby'],
    covers: [{ rule: 'R-GILD-02', fp: '4cf9aa2f' }],
  },

  // ── Dwarven Ale ───────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'ale',
    topic: 'keywords',
    q: 'What are Dwarven Ales?',
    a: "A family of cheap Dwarf spells with different perks: Gold, a minion of your most common type, or stat boosts. You can find them in the Shop, and Dwarf cards hand them out too.",
    aliases: ['ale', 'ales', 'dwarven ale', 'golden ale', 'bloody ale', 'defensive ale', "champion's ale", 'reinforcing ale'],
    seeAlso: ['ale-shop-spell'],
    covers: [{ keyword: 'ale', fp: 'f90de653' }],
  },
  {
    id: 'ale-shop-spell',
    topic: 'keywords',
    q: 'Do Ales count as Shop spells?',
    a: "Yes! Every Dwarven Ale counts as a Shop spell, no matter how you got it, so it triggers all your \"when you cast a Shop spell\" cards.",
    aliases: ['ale shop spell', 'ale counts as spell'],
    seeAlso: ['ale', 'ruby-vs-shop-spell'],
    covers: [{ keyword: 'ale', fp: 'f90de653' }, { rule: 'R-SHOPSPELL-01', fp: 'fcac2a2e' }],
  },

  // ── Gift ──────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'gift',
    topic: 'keywords',
    q: 'What is a Gift?',
    a: "A **free spell** that a rune, hero or card puts in your hand. You cast it like any other spell (it counts for anything that says \"a spell\"), but it's **never a Shop spell**: it never shows up in the Shop and never counts for \"Shop spell\" effects.",
    aliases: ['gifts', 'free spell', 'present', 'gift counts as spell', 'birthday', 'bonus spell'],
    seeAlso: ['gift-sell', 'gift-copy'],
    covers: [{ keyword: 'gift', fp: '08b705ba' }, { rule: 'R-SHOPSPELL-01', fp: 'fcac2a2e' }],
  },
  {
    id: 'gift-sell',
    topic: 'keywords',
    q: 'Can I sell a Gift?',
    a: "No. Only minions on your board can be sold, so Gifts (like every spell and Ruby in your hand) can only be cast.",
    aliases: ['sell gift', 'sell spell', 'sell from hand'],
    seeAlso: ['sell-a-minion', 'gift'],
  },
  {
    id: 'gift-copy',
    topic: 'keywords',
    q: 'Can a Gift be copied or Discovered?',
    a: "Effects that copy spells never copy a Gift, and effects that make spells cast extra times usually skip them too. Normal spell Discovers never offer one either. The only way to Discover a Gift is an effect that specifically says it Discovers a Gift.",
    aliases: ['copy gift', 'discover gift', 'duplicate gift'],
    seeAlso: ['gift', 'discover'],
  },

  // ── Clue ──────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'clue',
    topic: 'keywords',
    q: 'What is a Clue?',
    a: "A free spell for your hand. **Drag it onto a friendly minion** to give it +1/+1, and then every Clue after it gives +1/+1 more.",
    aliases: ['clues', 'magnifying glass'],
    seeAlso: ['clue-scaling'],
    covers: [{ keyword: 'clue', fp: '0897f360' }],
  },
  {
    id: 'clue-scaling',
    topic: 'keywords',
    q: 'How big do Clues get?',
    a: "Each Clue you cast makes **every later Clue +1/+1 bigger**, for the rest of the run. So your first gives +1/+1, the next +2/+2, then +3/+3. The Clue in your hand always shows what it gives right now, and Spell power doesn't change it.",
    aliases: ['clue power', 'clue value', 'clue growth'],
    seeAlso: ['clue', 'check-my-auras'],
    covers: [{ keyword: 'clue', fp: '0897f360' }],
  },

  // ── Starform / Collapse ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'starform',
    topic: 'keywords',
    q: 'What is a Starform?',
    a: "A Celestial token that **lives in the Shop**. Celestial cards create it and pump its stats. When you buy it, your **left-most Celestial** eats it and gains all its stats. You can only have one at a time.",
    aliases: ['starforms', 'star', 'celestial token'],
    seeAlso: ['starform-price', 'starform-stays', 'collapse'],
    covers: [{ keyword: 'starform', fp: '76e4f4bd' }],
  },
  {
    id: 'starform-price',
    topic: 'keywords',
    q: 'How much does a Starform cost?',
    a: "It starts at **6 Gold** and gets **1 Gold cheaper every refresh** (down to 0), and the discount carries over between turns. A brand new Starform starts at 6 again.",
    aliases: ['starform cost', 'starform gold', 'starform cheaper'],
    seeAlso: ['starform', 'starform-no-celestial'],
  },
  {
    id: 'starform-no-celestial',
    topic: 'keywords',
    q: 'What happens if I buy the Starform with no Celestial on my board?',
    a: "You still pay the Gold, but the Starform is just lost, since nobody's there to eat it. Get a Celestial on board first!",
    aliases: ['starform no celestial', 'buy starform wasted'],
    seeAlso: ['starform'],
  },
  {
    id: 'starform-stays',
    topic: 'keywords',
    q: 'Does the Starform disappear when I refresh the Shop?',
    a: "No. It stays through refreshes, Freeze, combat and new turns, and always goes back to the **right-most Shop slot**. It does take up a slot, so you see one fewer offer while it's there. It keeps every Shop buff it gets, even the ones that normally reset.",
    aliases: ['starform refresh', 'starform reroll', 'starform freeze'],
    seeAlso: ['starform', 'refresh-and-freeze-buttons'],
  },
  {
    id: 'collapse',
    topic: 'keywords',
    q: 'What does Collapse do?',
    a: "It **destroys your Starform** and gives **half its stats** (rounded up) to **3 different random** friendly Celestials. Fewer Celestials means fewer hits, and if you have none, the stats go nowhere.",
    aliases: ['collapses', 'starform collapse'],
    seeAlso: ['starform', 'collapse-vs-buy'],
    covers: [{ keyword: 'collapse', fp: '2d5f3369' }],
  },
  {
    id: 'collapse-vs-buy',
    topic: 'keywords',
    q: 'Should I buy my Starform or Collapse it?',
    a: "Buying gives **100%** of its stats to one Celestial (your left-most). Collapse gives **50%** to each of 3 Celestials, so with 3 or more Celestials it hands out more stats in total.",
    aliases: ['collapse or consume', 'starform buy vs collapse'],
    seeAlso: ['collapse', 'starform'],
  },
  {
    id: 'star-destroyer',
    topic: 'keywords',
    q: 'How do I get rid of a Starform I don\'t want?',
    a: "While you have a Starform you also hold the **Star Destroyer** Equipment. Using it costs 0 Gold and just removes the Starform from the Shop, with nothing else happening.",
    aliases: ['remove starform', 'star destroyer', 'delete starform'],
    seeAlso: ['starform', 'use-equipment'],
  },
  {
    id: 'starform-demon',
    topic: 'keywords',
    q: 'Can a Demon eat my Starform?',
    a: "Yep. For everything besides buying, the Starform counts as a regular Shop minion, so a Demon's Consume can eat it (stats and all).",
    aliases: ['consume starform', 'demon starform'],
    seeAlso: ['starform', 'consume'],
  },
];
