import type { WikiEntry } from './types';

// Checked against packages/core/src/combat/simulate.ts (performAttack, applyDamage, killOrReborn, placeSummon,
// the attack loop + outcome), packages/core/src/combat/minion.ts (instantiate), packages/sim/src/reducer.ts
// (settle carry-backs), packages/content/src (critChance values) and the approved rules R-EXECUTE-01,
// R-RISE-01/02/04/05, R-ORD-05, R-REALTIME-04 on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── Execute ────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'execute',
    topic: 'keywords',
    q: 'What does Execute do?',
    a: "Any damage an Execute minion deals to a minion **destroys it**, no matter how big it is. After it lands a hit, the minion loses Execute for the rest of that fight.",
    aliases: ['venomous', 'poisonous', 'poison', 'venom', 'destroy', 'instant kill'],
    seeAlso: ['execute-vs-ward', 'execute-comes-back', 'execute-on-defense'],
    covers: [{ keyword: 'execute', fp: '577f7ac7' }, { rule: 'R-EXECUTE-01', fp: 'd0e72582' }],
  },
  {
    id: 'execute-vs-ward',
    topic: 'keywords',
    q: 'What happens when Execute hits a Ward?',
    a: "The **Ward blocks it**. The Ward breaks, the minion lives, and your Execute is **not used up**, so it's still ready for the next hit.",
    aliases: ['venomous divine shield', 'poison vs shield', 'execute shield'],
    seeAlso: ['execute', 'ward', 'resilient-ward'],
    covers: [{ keyword: 'execute', fp: '577f7ac7' }, { keyword: 'ward', fp: '7855e365' }],
  },
  {
    id: 'execute-on-defense',
    topic: 'keywords',
    q: 'Does Execute work when my minion gets attacked?',
    a: "Yep. When something attacks your Execute minion, the hit it deals back counts too, so the attacker is **destroyed** (unless a Ward saves it). Attacking into Execute is a bad idea.",
    aliases: ['venomous retaliation', 'poison defending', 'counter attack execute'],
    seeAlso: ['execute', 'simultaneous-damage'],
    covers: [{ keyword: 'execute', fp: '577f7ac7' }],
  },
  {
    id: 'execute-comes-back',
    topic: 'keywords',
    q: 'Is Execute gone for good once it is used?',
    a: "Only for that fight. If the minion had Execute on your board, it has it again **next combat**. Execute given to it during a fight just lasts that fight.",
    aliases: ['venomous reset', 'lost after use', 'execute next combat'],
    seeAlso: ['execute', 'combat-buffs-dont-stay'],
    covers: [{ keyword: 'execute', fp: '577f7ac7' }],
  },
  {
    id: 'flurry-plus-execute',
    topic: 'keywords',
    q: 'If a minion has Flurry and Execute, do both attacks destroy?',
    a: "Only the first one that lands. The first hit uses up Execute, so the second attack does normal damage. Nice trick: if the first attack hits a **Ward**, Execute isn't spent and the second attack still destroys.",
    aliases: ['windfury venomous', 'double attack poison'],
    seeAlso: ['flurry', 'execute', 'execute-vs-ward'],
    covers: [{ keyword: 'flurry', fp: '2f6e1d15' }, { keyword: 'execute', fp: '577f7ac7' }],
  },
  {
    id: 'cleave-plus-execute',
    topic: 'keywords',
    q: 'Does Cleave with Execute destroy all three minions?',
    a: "Yes! The main target and both neighbours are hit in the **same swing**, so each one that takes damage is destroyed. Wards still block it for the minion they're on.",
    aliases: ['cleave venomous', 'cleave poison'],
    seeAlso: ['cleave', 'execute'],
    covers: [{ keyword: 'cleave', fp: '42ce6d41' }, { keyword: 'execute', fp: '577f7ac7' }],
  },
  {
    id: 'execute-zero-attack',
    topic: 'keywords',
    q: 'Does a 0-Attack Execute minion destroy things?',
    a: "No. A hit for 0 damage doesn't count as a hit at all, so Execute doesn't go off. It needs at least 1 Attack.",
    aliases: ['0 attack venomous', 'zero damage poison'],
    seeAlso: ['execute', 'zero-attack-minions'],
    covers: [{ keyword: 'execute', fp: '577f7ac7' }],
  },

  // ── Flurry ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'flurry',
    topic: 'keywords',
    q: 'What does Flurry do?',
    a: "When it's this minion's turn to attack, it **attacks twice** in a row. Each attack picks its own target.",
    aliases: ['windfury', 'attack twice', 'double attack', 'two attacks'],
    seeAlso: ['flurry-first-target-dies', 'flurry-plus-execute'],
    covers: [{ keyword: 'flurry', fp: '2f6e1d15' }],
  },
  {
    id: 'flurry-first-target-dies',
    topic: 'keywords',
    q: 'If Flurry kills its first target, what does the second attack hit?',
    a: "It picks a **new target** the normal way (random, Taunts first). If there's nothing left it can attack, the second attack just doesn't happen.",
    aliases: ['windfury second attack', 'flurry retarget'],
    seeAlso: ['flurry', 'attack-order'],
    covers: [{ keyword: 'flurry', fp: '2f6e1d15' }],
  },
  {
    id: 'flurry-dies-first-swing',
    topic: 'keywords',
    q: 'Does a Flurry minion still attack twice if it dies on the first attack?',
    a: "No. If it dies on the first attack, there's no second one. Even if it **Rises**, the returned minion's turn is over; it attacks again later like normal.",
    aliases: ['windfury dies', 'flurry reborn', 'flurry rise'],
    seeAlso: ['flurry', 'rise'],
    covers: [{ keyword: 'flurry', fp: '2f6e1d15' }, { keyword: 'rise', fp: '2187eacf' }],
  },
  {
    id: 'flurry-interrupted',
    topic: 'keywords',
    q: 'Can something cut in between the two Flurry attacks?',
    a: "Yes. If the first attack causes a minion to be summoned that **attacks immediately**, that minion strikes between the two attacks. Then the Flurry minion takes its second attack, if it's still alive.",
    aliases: ['windfury interrupt', 'attack immediately flurry'],
    seeAlso: ['flurry', 'attack-immediately'],
    covers: [{ keyword: 'flurry', fp: '2f6e1d15' }, { rule: 'R-ORD-05', fp: '657ce940' }],
  },

  // ── Critical Strike ────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'crit',
    topic: 'keywords',
    q: 'What does Critical Strike do?',
    a: "Each time the minion attacks, it has a chance to deal **double damage** with that attack. It's rolled fresh every attack.",
    aliases: ['crit', 'critical', 'critical hit', 'double damage'],
    seeAlso: ['crit-chance', 'crit-details'],
    covers: [{ keyword: 'crit', fp: '8e3d530f' }],
  },
  {
    id: 'crit-chance',
    topic: 'keywords',
    q: 'What is the exact chance to Crit?',
    a: "Every card that comes with Critical Strike right now has a **50%** chance per attack. So it's a coin flip each swing.",
    aliases: ['crit percent', 'crit odds', 'critical chance', 'how often crit'],
    seeAlso: ['crit'],
    covers: [{ keyword: 'crit', fp: '8e3d530f' }],
  },
  {
    id: 'crit-details',
    topic: 'keywords',
    q: 'Does a Crit double Cleave damage, or the damage it takes back?',
    a: "It doubles everything the attacker **deals** that swing, Cleave splash included. It does **not** double the damage the defender hits back with. With Flurry, each of the two attacks rolls its own Crit.",
    aliases: ['crit cleave', 'crit retaliation', 'crit flurry'],
    seeAlso: ['crit', 'cleave', 'flurry'],
    covers: [{ keyword: 'crit', fp: '8e3d530f' }],
  },

  // ── Rise / Rebirth ─────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'rise',
    topic: 'keywords',
    q: 'What does Rise do?',
    a: "Returns once when destroyed with 1 health. The first time the minion dies, it **comes back** as a fresh copy of the card with **1 Health**. Its buffs are gone.",
    aliases: ['reborn', 'revive', 'come back', 'resurrect', 'undying'],
    seeAlso: ['rise-stats', 'rise-vs-rebirth', 'echo-vs-rise'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }],
  },
  {
    id: 'rise-stats',
    topic: 'keywords',
    q: 'What stats does a minion come back with after Rise?',
    a: "Its **original Attack** and **1 Health** (Gilded doubles the Attack, still 1 Health). All its buffs, granted keywords and progress are gone. Auras you have (like a tribe aura) are then added on top, like for any fresh copy.",
    aliases: ['reborn stats', 'rise health', 'rise buffs lost', 'risen minion'],
    seeAlso: ['rise', 'rise-vs-rebirth'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }, { rule: 'R-RISE-01', fp: 'ec1bb994' }, { rule: 'R-RISE-04', fp: 'f85d8c6a' }],
  },
  {
    id: 'rise-full-board',
    topic: 'keywords',
    q: 'What if my board is full when a minion tries to Rise?',
    a: "It **stays dead**. If its Echo filled the board up to 7, there's no room to come back. That counts as an Overflow. If nothing got summoned into the gap, it fits right back in.",
    aliases: ['reborn full board', 'rise no room', 'rise overflow'],
    seeAlso: ['echo-vs-rise', 'full-board-summon'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }, { rule: 'R-RISE-05', fp: '08016ede' }],
  },
  {
    id: 'rise-counts-as-death',
    topic: 'keywords',
    q: 'Does a minion that Rises count as dying?',
    a: "Yes. It really dies first, so its Echo fires, Avenge counts it, and anything that cares about deaths sees it. Then it comes back.",
    aliases: ['reborn avenge', 'rise death count', 'does rise trigger avenge'],
    seeAlso: ['rise', 'echo-vs-rise'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }],
  },
  {
    id: 'rise-attacks-again',
    topic: 'keywords',
    q: 'If my minion dies while attacking and Rises, does it attack again?',
    a: "Yes, it's **next up** for your side when your turn comes back around, instead of waiting for the whole line to cycle.",
    aliases: ['reborn attack again', 'rise attack order'],
    seeAlso: ['rise', 'attack-order', 'flurry-dies-first-swing'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }],
  },
  {
    id: 'rise-in-shop',
    topic: 'keywords',
    q: 'Does Rise work in the shop too?',
    a: "Yep. If a Rise minion is destroyed during your shop turn, it comes back exactly like it would in a fight: a fresh copy with 1 Health.",
    aliases: ['reborn shop', 'rise outside combat'],
    seeAlso: ['rise', 'rise-stats'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }, { rule: 'R-RISE-02', fp: '0487dd36' }],
  },
  {
    id: 'rise-every-fight',
    topic: 'keywords',
    q: 'Does my minion get Rise back for the next fight?',
    a: "Yes. Rise only works once **per fight**, but your board minion keeps the keyword, so it's ready again next combat. Same goes for Ward and Stealth.",
    aliases: ['reborn reset', 'rise recharge', 'rise once'],
    seeAlso: ['rise', 'minions-dont-stay-dead'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }],
  },
  {
    id: 'rebirth',
    topic: 'keywords',
    q: 'What does Rebirth do?',
    a: "The first time the minion dies, it comes back **exactly as it was**: all its stats (Health refilled), buffs and keywords. Even a Ward it lost earlier in the fight comes back. It only happens once.",
    aliases: ['phoenix', 'full revive', 'come back whole'],
    seeAlso: ['rise-vs-rebirth', 'rise'],
    covers: [{ keyword: 'rebirth', fp: '2ef8b0b2' }],
  },
  {
    id: 'rise-vs-rebirth',
    topic: 'keywords',
    q: "What's the difference between Rise and Rebirth?",
    a: "**Rise** brings back a fresh copy of the card with 1 Health, losing its buffs. **Rebirth** brings back the whole minion with all its stats, buffs and keywords at full Health. Otherwise they work the same way (Echo first, needs room on the board).",
    aliases: ['reborn vs rebirth', 'rise or rebirth'],
    seeAlso: ['rise', 'rebirth', 'rise-stats'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }, { keyword: 'rebirth', fp: '2ef8b0b2' }],
  },
  {
    id: 'rise-and-rebirth-together',
    topic: 'keywords',
    q: 'What if a minion has both Rise and Rebirth?',
    a: "**Rebirth goes first**, so it comes back whole. It still has Rise after that, so the next time it dies, it Rises as a fresh copy with 1 Health.",
    aliases: ['rise plus rebirth', 'both revive'],
    seeAlso: ['rise-vs-rebirth'],
    covers: [{ keyword: 'rise', fp: '2187eacf' }, { keyword: 'rebirth', fp: '2ef8b0b2' }],
  },

  // ── Cleave ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'cleave',
    topic: 'keywords',
    q: 'What does Cleave do?',
    a: "When this minion attacks, it also hits the minions **on both sides** of its target for the same damage. If the target is on the end, it only hits the one neighbour.",
    aliases: ['splash', 'adjacent damage', 'hit neighbours', 'area damage'],
    seeAlso: ['cleave-and-ward', 'cleave-plus-execute'],
    covers: [{ keyword: 'cleave', fp: '42ce6d41' }],
  },
  {
    id: 'cleave-and-ward',
    topic: 'keywords',
    q: 'Does Cleave break Wards on the neighbours?',
    a: "Yes. Each minion Cleave hits is hit separately, so a neighbour's **Ward pops** (and blocks the damage) just like it would from a normal attack.",
    aliases: ['cleave divine shield', 'cleave shield'],
    seeAlso: ['cleave', 'ward'],
    covers: [{ keyword: 'cleave', fp: '42ce6d41' }, { keyword: 'ward', fp: '7855e365' }],
  },
  {
    id: 'cleave-neighbours',
    topic: 'keywords',
    q: 'Which minions count as "next to" the target for Cleave?',
    a: "The minions standing next to it **right now**. Dead minions have left the board, so Cleave hits the living minion beside the target even if something died in between.",
    aliases: ['cleave adjacent', 'cleave gap'],
    seeAlso: ['cleave'],
    covers: [{ keyword: 'cleave', fp: '42ce6d41' }],
  },
  {
    id: 'cleave-hit-back',
    topic: 'keywords',
    q: 'Do the neighbours hit back when Cleave hits them?',
    a: "No. Only the **main target** hits the attacker back. The minions caught in the splash just take the damage.",
    aliases: ['cleave retaliation', 'splash hit back'],
    seeAlso: ['cleave', 'simultaneous-damage'],
    covers: [{ keyword: 'cleave', fp: '42ce6d41' }],
  },

  // ── Immune ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'immune',
    topic: 'keywords',
    q: 'What does Immune do?',
    a: "An Immune minion **takes no damage** at all, from anything. Execute can't destroy it either, and its Ward won't pop because nothing reaches it.",
    aliases: ['invulnerable', 'no damage', 'cant be hurt'],
    seeAlso: ['immune-can-be-attacked', 'immune-while-attacking'],
    covers: [{ keyword: 'immune', fp: 'dac72317' }],
  },
  {
    id: 'immune-can-be-attacked',
    topic: 'keywords',
    q: 'Can enemies still attack an Immune minion?',
    a: "Yes, it can still be picked as a target. It just takes nothing, and it still hits the attacker back as usual.",
    aliases: ['attack immune', 'immune target'],
    seeAlso: ['immune'],
    covers: [{ keyword: 'immune', fp: 'dac72317' }],
  },
  {
    id: 'immune-while-attacking',
    topic: 'keywords',
    q: 'What does "Immune while attacking" mean?',
    a: "When that minion attacks, it takes **no damage back** from the minion it hits. It can still be hurt when enemies attack it. Some cards limit it to the first few attacks each combat (the card says how many).",
    aliases: ['immune attacking', 'no retaliation', 'takes no damage when attacking'],
    seeAlso: ['immune', 'simultaneous-damage'],
    covers: [{ keyword: 'immune', fp: 'dac72317' }],
  },

  // ── Engraved / Permanent ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'engraved',
    topic: 'keywords',
    q: 'What does Engraved do?',
    a: "Normally, stats a minion gains **during a fight** vanish when the fight ends. An Engraved minion **keeps them** for good. Win or lose, even if it died in that fight.",
    aliases: ['engrave', 'keep combat buffs', 'keep stats'],
    seeAlso: ['combat-buffs-dont-stay', 'permanent', 'engraved-damage'],
    covers: [{ keyword: 'engraved', fp: '5c0422d8' }],
  },
  {
    id: 'engraved-damage',
    topic: 'keywords',
    q: 'Does an Engraved minion keep the damage it took?',
    a: "No. Engraved only keeps stats it **gained**. Damage never carries over; it's back at full Health next fight.",
    aliases: ['engraved health', 'engraved lose health'],
    seeAlso: ['engraved', 'heal-between-fights'],
    covers: [{ keyword: 'engraved', fp: '5c0422d8' }],
  },
  {
    id: 'permanent',
    topic: 'keywords',
    q: 'What does "permanently" mean on a card?',
    a: "That buff **sticks for the rest of the run**, even if it happens in the middle of a fight. Buffs you give in the shop are already permanent; the word matters most for combat, where buffs normally wear off.",
    aliases: ['permanent', 'permanently', 'for the rest of the run', 'stays forever'],
    seeAlso: ['combat-buffs-dont-stay', 'engraved'],
    covers: [{ keyword: 'permanent', fp: '32993c18' }],
  },
  {
    id: 'combat-buffs-dont-stay',
    topic: 'combat',
    q: 'Do buffs my minions get during combat stay after the fight?',
    a: "No. Combat buffs only last **that fight**. The exceptions: the minion is **Engraved**, or the card says the buff is **permanent**. Buffs you give in the shop always stay.",
    aliases: ['combat buff', 'lose buffs', 'buffs reset', 'temporary buff', 'shout in combat'],
    seeAlso: ['engraved', 'permanent', 'heal-between-fights'],
    covers: [{ keyword: 'engraved', fp: '5c0422d8' }, { keyword: 'permanent', fp: '32993c18' }, { rule: 'R-REALTIME-04', fp: '928aa562' }],
  },

  // ── General combat ─────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'heal-between-fights',
    topic: 'combat',
    q: 'Do my minions heal between fights?',
    a: "Yep, fully. Every fight starts with your board **exactly as you left it in the shop**, full Health and all. Damage from the last fight never carries over.",
    aliases: ['heal', 'full health', 'damage carry over', 'stats reset', 'minion health after combat'],
    seeAlso: ['minions-dont-stay-dead', 'combat-buffs-dont-stay'],
  },
  {
    id: 'minions-dont-stay-dead',
    topic: 'combat',
    q: 'If my minions die in combat, do I lose them?',
    a: "No! Combat is played out with **copies** of your board. When you get back to the shop, every minion you had is still there, no matter what happened in the fight.",
    aliases: ['lose minions', 'minion died', 'dead minions', 'board after combat', 'do minions come back'],
    seeAlso: ['heal-between-fights', 'tokens-after-fight'],
  },
  {
    id: 'tokens-after-fight',
    topic: 'combat',
    q: 'What happens to minions summoned during a fight?',
    a: "They **disappear** when the fight ends. Only the minions you actually had on your board come back to the shop.",
    aliases: ['tokens', 'summoned minions', 'keep summons', 'combat summons'],
    seeAlso: ['minions-dont-stay-dead', 'summon-slot'],
  },
  {
    id: 'simultaneous-damage',
    topic: 'combat',
    q: 'When two minions fight, who deals damage first?',
    a: "Neither. It's **at the same time**: the attacker hits the target, and the target hits back with its own Attack. Both can die in the same trade. Any Echoes go off after all the damage has landed.",
    aliases: ['trade', 'retaliation', 'hit back', 'both die', 'counter attack', 'mutual kill'],
    seeAlso: ['attack-order', 'cleave-hit-back', 'immune-while-attacking'],
  },
  {
    id: 'overkill',
    topic: 'combat',
    q: 'Does extra damage carry over to other minions or my opponent?',
    a: "No. If you hit a 2-Health minion for 10, the extra 8 is simply wasted. Only effects like **Cleave** hit more than one minion.",
    aliases: ['overkill', 'excess damage', 'trample', 'spare damage'],
    seeAlso: ['cleave', 'how-much-damage'],
  },
  {
    id: 'zero-attack-minions',
    topic: 'combat',
    q: 'Do 0-Attack minions attack?',
    a: "No, they get **skipped** in the attack order. And if you attack one, it hits back for 0, so you take nothing and your Ward doesn't pop.",
    aliases: ['0 attack', 'zero attack', 'no attack', 'wall minion', 'skipped'],
    seeAlso: ['attack-order', 'nobody-can-attack'],
  },
  {
    id: 'nobody-can-attack',
    topic: 'combat',
    q: 'What if neither side can attack?',
    a: "If neither board has a minion with any Attack left, the fight ends right there as a **draw**. Nobody takes damage.",
    aliases: ['stalemate', 'no attackers', 'stuck fight', 'both 0 attack'],
    seeAlso: ['tie-fight', 'zero-attack-minions'],
  },
  {
    id: 'fight-length',
    topic: 'combat',
    q: 'How long can a fight last?',
    a: "Until one side runs out of minions. If a fight just keeps going way too long with both sides still standing, it's called a **draw**.",
    aliases: ['long fight', 'endless combat', 'infinite fight', 'time limit'],
    seeAlso: ['tie-fight', 'nobody-can-attack'],
  },
  {
    id: 'empty-board-fight',
    topic: 'combat',
    q: 'What if one side has no minions at all?',
    a: "The side with minions **wins** straight away and deals damage as usual. If both boards are empty, it's a draw.",
    aliases: ['no minions', 'empty board', 'fight with nothing'],
    seeAlso: ['how-much-damage', 'tie-fight'],
  },
  {
    id: 'damage-when-i-win',
    topic: 'combat',
    q: 'Does my opponent take damage when I win?',
    a: "Yes. It's the same formula in reverse: **your tavern tier** plus the tiers of **your surviving minions**, with the same early-round caps.",
    aliases: ['deal damage', 'winning damage', 'hurt opponent', 'win damage'],
    seeAlso: ['how-much-damage', 'health-and-armor'],
  },
  {
    id: 'attack-order-after-death',
    topic: 'combat',
    q: 'If one of my minions dies before its turn, who attacks next?',
    a: "Your side just carries on **left to right** with the next living minion after the one that attacked last. The dead one is skipped; nobody loses their place.",
    aliases: ['attack order death', 'skip dead minion', 'next attacker'],
    seeAlso: ['attack-order', 'summon-slot'],
  },
  {
    id: 'summon-slot',
    topic: 'combat',
    q: 'Where do minions summoned in combat go?',
    a: "Right **next to (to the right of)** whatever summoned them. An Echo's summons appear where the dying minion was. They join the attack order from that spot, so they can attack soon if they land just after your last attacker.",
    aliases: ['summon position', 'token placement', 'where do tokens go'],
    seeAlso: ['full-board-summon', 'tokens-after-fight', 'attack-order-after-death'],
  },
  {
    id: 'full-board-summon',
    topic: 'combat',
    q: 'What happens if I summon a minion when my board is full?',
    a: "Your board holds **7** minions max. A summon with no room simply **doesn't happen** (that's called an Overflow, and some cards reward it).",
    aliases: ['full board', 'board full', 'overflow', 'no room', 'seven minions'],
    seeAlso: ['board-and-hand-size', 'rise-full-board', 'summon-slot'],
    covers: [{ keyword: 'overflow', fp: '10809bad' }],
  },
  {
    id: 'attack-immediately',
    topic: 'combat',
    q: 'What does "attacks immediately" mean on a summon?',
    a: "That minion **cuts the line**: it attacks as soon as it's summoned, before the next normal attacker (even between the two attacks of a Flurry). It doesn't use up anyone's turn, and it still takes its own regular turn later.",
    aliases: ['charge', 'rush', 'attack right away', 'immediate attack'],
    seeAlso: ['flurry-interrupted', 'summon-slot'],
    covers: [{ rule: 'R-ORD-05', fp: '657ce940' }],
  },
  {
    id: 'ward-still-hits-back',
    topic: 'combat',
    q: 'Does a Warded minion still hit back when it gets attacked?',
    a: "Yes. The Ward blocks the damage it would take, but it still deals its Attack to the attacker as normal.",
    aliases: ['divine shield retaliation', 'shield hit back'],
    seeAlso: ['ward', 'simultaneous-damage'],
    covers: [{ keyword: 'ward', fp: '7855e365' }],
  },
];
