import type { WikiEntry } from './types';

// Checked against core/src/combat/simulate.ts (killOrReborn, the attack clash, placeSummon, bleed), core/src/effects/
// factories.ts (avengeCountFor), sim/src/recruit.ts (applyStartOfTurn, applyEndOfTurn, applyGoldSpent,
// destroyMinionInShop, chooseBothActive), sim/src/reducer.ts (play / Choose One / cancelChoice / sell / spendGold) and
// the approved rules cited in `covers` on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── Shout ─────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'shout',
    topic: 'keywords',
    q: 'What does Shout do?',
    a: "A Shout goes off **when you play the minion from your hand** onto your board.",
    aliases: ['battlecry', 'on play', 'when played', 'shout effect'],
    seeAlso: ['shout-only-from-hand', 'play-from-hand'],
    covers: [{ keyword: 'shout', fp: 'bbe6a0f3' }],
  },
  {
    id: 'shout-only-from-hand',
    topic: 'keywords',
    q: 'Does a Shout go off when I buy the minion or when something summons it?',
    a: "No. Buying just puts the card in your hand, and the Shout waits until you **play** it. A copy that gets summoned straight onto the board by another effect doesn't Shout either.",
    aliases: ['battlecry when bought', 'battlecry when summoned', 'shout on buy', 'shout on summon'],
    seeAlso: ['shout', 'buy-a-minion'],
    covers: [{ keyword: 'shout', fp: 'bbe6a0f3' }],
  },
  {
    id: 'shout-gilded',
    topic: 'keywords',
    q: 'What does a Gilded Shout do?',
    a: "Usually the **same Shout with double the numbers**. A few cards get something different instead (like hitting both neighbours instead of one), and when they do, the Gilded card's text says so. Read the Gilded version to be sure.",
    aliases: ['golden battlecry', 'gilded battlecry', 'golden shout', 'tripled shout'],
    seeAlso: ['triples', 'shout'],
    covers: [{ rule: 'R-GILD-01', fp: 'd0abe88d' }],
  },
  {
    id: 'shout-aura-first',
    topic: 'keywords',
    q: 'If something buffs every minion I play, does the new minion get the buff before its Shout goes off?',
    a: "Yep. The minion lands, **gets the on-play buffs first**, and only then does its own Shout go off. So anything its Shout makes can already benefit from a buff that just got bigger.",
    aliases: ['shout order', 'battlecry order', 'buff before battlecry'],
    seeAlso: ['shout'],
    covers: [{ rule: 'R-ORD-02', fp: 'f49cb500' }],
  },
  {
    id: 'shout-retrigger',
    topic: 'keywords',
    q: 'Can a Shout go off more than once?',
    a: "Yes. Some cards and runes **trigger your Shouts again**, in the shop, at End of Turn, or even during a fight. The re-fired Shout does its full effect again right away.",
    aliases: ['retrigger battlecry', 'battlecry twice', 'replay shout', 'shout again'],
    seeAlso: ['shout-refire-target', 'shout-in-combat-stats', 'trigger-twice-stacking'],
    covers: [{ rule: 'R-REALTIME-03', fp: 'c7ae3fde' }],
  },
  {
    id: 'shout-refire-target',
    topic: 'keywords',
    q: 'If a Shout that needs a target gets triggered again, who does it hit?',
    a: "When you play it, you aim it. When it gets **re-triggered** there's nobody to aim, so it picks a **random legal target** (never the minion itself). If there's no legal target, that re-fire just does nothing.",
    aliases: ['targeted battlecry retrigger', 'random target', 'aimed shout', 'targeted shout', 'retrigger target', 'who does it pick'],
    seeAlso: ['shout-retrigger'],
    covers: [{ rule: 'R-TARGET-06', fp: '57a4e762' }],
  },
  {
    id: 'shout-in-combat-stats',
    topic: 'keywords',
    q: 'If a Shout goes off during a fight, do the stats it gives stay after combat?',
    a: "No. Stats a Shout gives to minions **on your board during a fight** only last for that fight, like any other combat buff. Things that are permanent anyway (a buff to a card in your hand, or a card whose text says \"permanently\") still stick.",
    aliases: ['combat battlecry', 'shout in combat', 'temporary buff'],
    seeAlso: ['shout-retrigger'],
    covers: [{ rule: 'R-REALTIME-04', fp: '928aa562' }],
  },
  {
    id: 'shout-trigger-all-order',
    topic: 'keywords',
    q: 'When something triggers all my Shout minions, what order do they go in?',
    a: "**Left to right** across your board. Only minions that were there when it started get triggered, and a minion that leaves partway through is skipped. A Gilded version runs the whole lineup twice.",
    aliases: ['trigger your shouts', 'shout order', 'left to right'],
    seeAlso: ['board-order', 'shout-retrigger'],
    covers: [{ rule: 'R-SHOUT-02', fp: '1b547e9e' }],
  },
  {
    id: 'trigger-twice-stacking',
    topic: 'keywords',
    q: 'Do two "trigger twice" cards stack?',
    a: "Two copies of the **same** \"trigger twice\" card don't stack (still twice). **Different** \"trigger twice\" cards multiply each other. Cards that say \"trigger **1 additional time**\" always add up, every copy. So two different doublers make it 4 times, and two copies of a +1 card make it 3 times.",
    aliases: ['double trigger', 'stack multipliers', 'trigger twice', 'additional time', 'drakko', 'sylus', 'twice', 'extra trigger', 'stack', 'multiplier'],
    seeAlso: ['shout-retrigger', 'echo'],
    covers: [{ rule: 'R-MULT-01', fp: '2ec0f1a6' }],
  },

  // ── Echo ──────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'echo',
    topic: 'keywords',
    q: 'What does Echo do?',
    a: "An Echo goes off **when the minion dies**. It works in fights and also in the shop if something destroys the minion there.",
    aliases: ['deathrattle', 'on death', 'when it dies', 'last words'],
    seeAlso: ['echo-timing', 'echo-in-shop'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-timing',
    topic: 'keywords',
    q: 'When exactly does an Echo go off in a fight?',
    a: "**After every hit of that attack has landed.** An attack's damage all happens at once (the swing, any splash, and the hit back), and only then do the dead minions die and their Echoes fire. So an Echo sees the board after the whole exchange.",
    aliases: ['deathrattle timing', 'when does echo trigger'],
    seeAlso: ['echo-simultaneous-order', 'echo'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-simultaneous-order',
    topic: 'keywords',
    q: "If my minion and the enemy's minion kill each other, whose Echo goes first?",
    a: "Deaths are handled in the order the hits landed: **splash victims first, then the minion that got attacked, then the attacker.** So the defender's Echo goes before the attacker's.",
    aliases: ['deathrattle order', 'mutual kill', 'trade', 'who goes first echo'],
    seeAlso: ['echo-timing', 'attack-order'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-summon-position',
    topic: 'keywords',
    q: 'Where do minions summoned by an Echo show up?',
    a: "**Right where the minion died**, in its old slot. That's true in fights and in the shop.",
    aliases: ['deathrattle summon position', 'where do tokens go', 'summon slot'],
    seeAlso: ['echo', 'board-order'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-in-shop',
    topic: 'keywords',
    q: 'Does an Echo go off if my minion is destroyed in the shop?',
    a: "Yes. A minion destroyed in the shop by a card or effect **really dies**: its Echo fires, and anything that watches for deaths hears it.",
    aliases: ['deathrattle in shop', 'destroy in tavern', 'echo recruit phase'],
    seeAlso: ['echo', 'echo-sold'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-sold',
    topic: 'keywords',
    q: 'Does selling a minion trigger its Echo?',
    a: "No. **Selling isn't dying**, so no Echo. If you want something to happen when you sell it, that's what **Sell:** cards are for. Turning three copies into a Gilded one isn't a death either.",
    aliases: ['sell deathrattle', 'does selling count as death'],
    seeAlso: ['sell-trigger', 'sell-a-minion', 'triples'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-gilded',
    topic: 'keywords',
    q: 'Does a Gilded minion Echo twice?',
    a: "Usually not. It fires **once with doubled numbers**. A few Gilded cards do something different (like summoning a Gilded token instead of two), and their Gilded text tells you.",
    aliases: ['golden deathrattle', 'gilded deathrattle', 'golden echo'],
    seeAlso: ['echo', 'triples'],
    covers: [{ rule: 'R-GILD-01', fp: 'd0abe88d' }],
  },
  {
    id: 'echo-vs-rise',
    topic: 'keywords',
    q: 'If a minion has Echo and Rise, which happens first?',
    a: "**Echo first, then the Rise.** The minion dies and leaves its slot, its Echo fires (anything it summons takes that slot), and then the minion tries to come back to the right of what its Echo made. Same in the shop and in combat.",
    aliases: ['deathrattle reborn order', 'echo reborn', 'rise order', 'reborn deathrattle', 'rise echo order', 'rise deathrattle order'],
    seeAlso: ['echo-rise-full-board', 'overflow'],
    covers: [{ rule: 'R-RISE-05', fp: '08016ede' }],
  },
  {
    id: 'echo-rise-full-board',
    topic: 'keywords',
    q: "My minion with Rise and Echo didn't come back. Why?",
    a: "Your board was probably full. The Echo's summons got the free space first, so when the minion tried to Rise there was **no room**, and it stays dead. That counts as an **Overflow**. If its Echo summons nothing, it always has room to come back.",
    aliases: ['reborn did not work', 'rise failed', 'full board reborn'],
    seeAlso: ['echo-vs-rise', 'overflow'],
    covers: [{ rule: 'R-RISE-05', fp: '08016ede' }],
  },
  {
    id: 'echo-without-death',
    topic: 'keywords',
    q: 'Can an Echo go off without the minion dying?',
    a: "Yes. Some cards and runes **trigger a friendly Echo directly** (for example your left-most Echo minion). The minion stays alive and its Echo just happens.",
    aliases: ['trigger deathrattle', 'proc echo', 'echo without dying'],
    seeAlso: ['echo'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },
  {
    id: 'echo-extra-counts',
    topic: 'keywords',
    q: 'If my Echoes trigger twice, does that count as two Echoes for things that count Echoes?',
    a: "Yep. Every extra trigger **counts as another Echo triggered**. It's still only one minion dying, though, so death counters (like Avenge) only go up by one.",
    aliases: ['echoes triggered', 'deathrattle count', 'echo tally'],
    seeAlso: ['trigger-twice-stacking', 'avenge'],
    covers: [{ keyword: 'echo', fp: '4017d461' }],
  },

  // ── Start of Turn / End of Turn ───────────────────────────────────────────────────────────────────────────
  {
    id: 'start-of-turn',
    topic: 'keywords',
    q: 'What does "Start of Turn" do?',
    a: "It goes off **at the start of each of your shop turns**, right as you come back from a fight. Only minions **on your board** trigger it, not ones in your hand.",
    aliases: ['start of turn', 'beginning of turn', 'turn start', 'at the start of your turn'],
    seeAlso: ['start-of-turn-order', 'end-of-turn'],
    covers: [{ keyword: 'startofturn', fp: '0f361616' }],
  },
  {
    id: 'start-of-turn-order',
    topic: 'keywords',
    q: 'If several minions have Start of Turn, what order do they go in?',
    a: "**Left to right** across your board. Each one gets its own little moment so you can see what it did.",
    aliases: ['start of turn order', 'left to right'],
    seeAlso: ['start-of-turn', 'board-order'],
    covers: [{ rule: 'R-SOT-BEAT-01', fp: 'd38d5b2c' }],
  },
  {
    id: 'start-of-turn-timer',
    topic: 'keywords',
    q: 'Does my shop timer wait for Start of Turn effects to finish?',
    a: "No. The timer can start as soon as the shop is back on screen, and **you can shop while the Start of Turn effects play**. (In a lobby or Practice it waits for the **Gold Fuse**: no clock until you've spent 10 Gold in the turn.) Any pop-up they cause (like a Discover) still opens after they finish.",
    aliases: ['timer start of turn', 'shop timer', 'turn clock'],
    seeAlso: ['start-of-turn', 'timer-runs-out'],
    covers: [{ rule: 'R-SOT-TIMER-01', fp: '1c2bc9e9' }],
  },
  {
    id: 'end-of-turn',
    topic: 'keywords',
    q: 'What does "End of Turn" do?',
    a: "It goes off **when your shop turn ends**, right before you fight. That's when you hit End Turn, or when the timer runs out. Only minions **on your board** trigger it.",
    aliases: ['end of turn', 'eot', 'turn end', 'at the end of your turn'],
    seeAlso: ['end-of-turn-order', 'end-turn', 'timer-runs-out'],
    covers: [{ keyword: 'endofturn', fp: 'e71a0509' }],
  },
  {
    id: 'end-of-turn-order',
    topic: 'keywords',
    q: 'In what order do End of Turn effects go off?',
    a: "Your board's End of Turn minions go **left to right**. After them come End of Turn rewards from your runes. So if one End of Turn minion buffs another, where you put them matters.",
    aliases: ['end of turn order', 'eot order', 'left to right'],
    seeAlso: ['end-of-turn', 'board-order'],
    covers: [{ keyword: 'endofturn', fp: 'e71a0509' }],
  },
  {
    id: 'end-of-turn-repeat',
    topic: 'keywords',
    q: 'Some End of Turn cards say "Repeat for every..." How does that work?',
    a: "It does the effect **once, then once more for each** thing it counts this turn. With zero it still goes once. A Gilded one makes each repeat bigger, not more repeats. Long chains speed up so you're never stuck watching for ages.",
    aliases: ['repeat for every', 'end of turn repeat', 'ticks'],
    seeAlso: ['end-of-turn'],
    covers: [{ rule: 'R-REPEAT-01', fp: '88688c67' }, { rule: 'R-REPEAT-04', fp: 'ebd399a1' }],
  },
  {
    id: 'end-of-turn-multiple',
    topic: 'keywords',
    q: 'Can End of Turn effects go off more than once?',
    a: "Yes. Some cards make your **End of Turn effects trigger extra times**. They stack the same way other \"trigger twice\" and \"additional time\" cards do.",
    aliases: ['double end of turn', 'eot twice'],
    seeAlso: ['trigger-twice-stacking', 'end-of-turn'],
    covers: [{ rule: 'R-MULT-02', fp: '76497371' }],
  },

  // ── Avenge ────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'avenge',
    topic: 'keywords',
    q: 'What does Avenge do?',
    a: "**Avenge (N)** goes off **every time N of your minions have died** in the current fight. So Avenge (3) fires on the 3rd, 6th, 9th friendly death, and so on. The card shows how far along it is.",
    aliases: ['avenge', 'when friendly minions die', 'death counter'],
    seeAlso: ['avenge-what-counts', 'avenge-resets'],
    covers: [{ keyword: 'avenge', fp: 'c671d6fa' }, { rule: 'R-AVWIN-06', fp: '60d053aa' }],
  },
  {
    id: 'avenge-what-counts',
    topic: 'keywords',
    q: 'Do tokens and minions that Rise count toward Avenge?',
    a: "Yes to both. **Any friendly minion dying counts**, including tiny summoned tokens. A minion that dies and then Rises still counts as a death. Enemy deaths don't count.",
    aliases: ['avenge tokens', 'avenge reborn', 'does summoned count avenge'],
    seeAlso: ['avenge'],
    covers: [{ keyword: 'avenge', fp: 'c671d6fa' }],
  },
  {
    id: 'avenge-resets',
    topic: 'keywords',
    q: 'Does Avenge progress carry over to the next fight?',
    a: "No. Avenge counts deaths **in this fight only** and starts from zero every combat. Minions dying in the shop don't count toward it.",
    aliases: ['avenge reset', 'avenge carry over', 'avenge shop'],
    seeAlso: ['avenge'],
    covers: [{ keyword: 'avenge', fp: 'c671d6fa' }],
  },
  {
    id: 'avenge-late-arrival',
    topic: 'keywords',
    q: 'If an Avenge minion gets summoned mid-fight, does it count the deaths from before it showed up?',
    a: "No. It only counts deaths **after it arrives**, and its counter starts at 0. That includes the death that summoned it: if an Echo brings it in, that death doesn't count.",
    aliases: ['summoned avenge', 'avenge mid combat'],
    seeAlso: ['avenge'],
    covers: [{ rule: 'R-AVWIN-01', fp: '43ee2665' }, { rule: 'R-AVWIN-02', fp: '0503212e' }],
  },
  {
    id: 'avenge-dies-same-time',
    topic: 'keywords',
    q: 'If my Avenge minion dies at the same time as other minions, does it count them?',
    a: "No. A minion that's dying in the same exchange **counts none of those deaths**, so it can't fire on its way out.",
    aliases: ['avenge dies', 'avenge simultaneous'],
    seeAlso: ['avenge'],
    covers: [{ rule: 'R-AVWIN-10', fp: 'da141039' }],
  },
  {
    id: 'avenge-after-rise',
    topic: 'keywords',
    q: 'What happens to Avenge progress when the Avenge minion Rises?',
    a: "It **starts over at 0**. The returned minion only counts deaths from then on.",
    aliases: ['avenge reborn reset', 'avenge rise'],
    seeAlso: ['avenge', 'echo-vs-rise'],
    covers: [{ rule: 'R-AVWIN-09', fp: '6b12ce1a' }],
  },
  {
    id: 'avenge-twice',
    topic: 'keywords',
    q: 'If my Avenges "trigger twice", does each death count double?',
    a: "No. Deaths count normally. When the Avenge **reaches its number**, it just goes off twice.",
    aliases: ['avenge twice', 'double avenge'],
    seeAlso: ['avenge', 'trigger-twice-stacking'],
    covers: [{ rule: 'R-AVWIN-07', fp: 'c1675315' }],
  },

  // ── Pummel ────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'pummel',
    topic: 'keywords',
    q: 'What does Pummel do?',
    a: "**Pummel (X)** goes off **each time this minion has dealt another X damage**. The count **never resets**: it carries from fight to shop to the next fight. The card shows your progress toward the next payout.",
    aliases: ['pummel', 'damage dealt', 'damage counter'],
    seeAlso: ['pummel-what-counts', 'pummel-cap'],
    covers: [{ keyword: 'pummel', fp: '9832c410' }, { rule: 'R-PUMMEL-01', fp: '46dabaaa' }],
  },
  {
    id: 'pummel-what-counts',
    topic: 'keywords',
    q: 'What damage counts toward Pummel?',
    a: "Any hit it lands: **attacking, hitting back when attacked**, and damage from its effects. Overkill counts in full. A hit that gets **blocked by a Ward** (or deals 0) doesn't count.",
    aliases: ['pummel damage', 'pummel ward', 'overkill pummel'],
    seeAlso: ['pummel', 'ward'],
    covers: [{ rule: 'R-PUMMEL-01', fp: '46dabaaa' }],
  },
  {
    id: 'pummel-cap',
    topic: 'keywords',
    q: 'Can Pummel pay out more than once in a fight?',
    a: "Only up to the card's limit, which is **once per combat** unless the card says \"Max N per combat\". Crossings past the limit are **used up, not saved**. One huge hit can pay out several times if the limit allows.",
    aliases: ['pummel once per combat', 'pummel max', 'pummel limit'],
    seeAlso: ['pummel'],
    covers: [{ rule: 'R-PUMMEL-02', fp: 'cfa3809c' }],
  },
  {
    id: 'pummel-gilded',
    topic: 'keywords',
    q: 'Does a Gilded Pummel minion pay out more often?',
    a: "No. It needs the same damage and has the same limit, but **each payout is doubled**.",
    aliases: ['golden pummel', 'gilded pummel'],
    seeAlso: ['pummel'],
    covers: [{ keyword: 'pummel', fp: '9832c410' }],
  },

  // ── Rally ─────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'rally',
    topic: 'keywords',
    q: 'What does Rally do?',
    a: "A Rally goes off **each time this minion starts an attack** in combat, before its hit lands. If it buffs itself, that swing already hits harder.",
    aliases: ['rally', 'on attack', 'when this attacks', 'whenever this attacks'],
    seeAlso: ['rally-flurry', 'rally-watchers'],
    covers: [{ keyword: 'rally', fp: '98606ba2' }],
  },
  {
    id: 'rally-flurry',
    topic: 'keywords',
    q: 'Does a Flurry minion Rally twice?',
    a: "Yep. Flurry means two swings, and **each swing is its own attack**, so its Rally goes off on both (if it's still alive for the second).",
    aliases: ['windfury rally', 'flurry rally', 'rally twice', 'double rally'],
    seeAlso: ['rally'],
    covers: [{ keyword: 'rally', fp: '98606ba2' }],
  },
  {
    id: 'rally-watchers',
    topic: 'keywords',
    q: 'What\'s the difference between "Rally:" and "whenever you trigger a Rally"?',
    a: "A card that says **Rally:** only fires on **its own** attacks. A card that says **\"whenever you trigger a Rally\"** is a watcher: it fires on **every** friendly Rally, whoever it belongs to.",
    aliases: ['rally watcher', 'trigger a rally', 'rally synergy', 'watcher', 'whenever you trigger', 'own rally', 'reacts to others'],
    seeAlso: ['rally', 'watcher'],
    covers: [{ rule: 'R-RALLY-02', fp: '8bf8f9f8' }],
  },
  {
    id: 'rally-without-attack',
    topic: 'keywords',
    q: 'Can a Rally go off without the minion attacking?',
    a: "Yes. Some cards and runes **trigger a Rally directly** (for example at Start of Combat). No attack happens, but it still counts as a Rally triggered, so your Rally watchers fire too.",
    aliases: ['trigger rally', 'rally at start of combat', 'rally without attacking'],
    seeAlso: ['rally', 'rally-watchers'],
    covers: [{ rule: 'R-RALLY-01', fp: '4f5d9f16' }],
  },

  // ── Slaughter ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'slaughter',
    topic: 'keywords',
    q: 'What does Slaughter do?',
    a: "It goes off **whenever this minion kills an enemy by attacking** it. Kills from Cleave splash count too.",
    aliases: ['slaughter', 'on kill', 'overkill', 'when this kills'],
    seeAlso: ['slaughter-defending', 'slaughter-mutual-kill'],
    covers: [{ keyword: 'slaughter', fp: 'aa9a5c68' }],
  },
  {
    id: 'slaughter-defending',
    topic: 'keywords',
    q: 'Does Slaughter trigger if my minion kills its attacker by hitting back?',
    a: "No. Slaughter only counts kills **your minion makes on its own attack**. Killing an enemy that attacked it doesn't count.",
    aliases: ['slaughter retaliation', 'slaughter defend', 'slaughter counter attack'],
    seeAlso: ['slaughter'],
    covers: [{ keyword: 'slaughter', fp: 'aa9a5c68' }],
  },
  {
    id: 'slaughter-mutual-kill',
    topic: 'keywords',
    q: 'If my Slaughter minion kills its target but dies too, does Slaughter still trigger?',
    a: "Yep. A kill is a kill, even if both minions go down in the same exchange.",
    aliases: ['slaughter trade', 'slaughter dies', 'mutual kill'],
    seeAlso: ['slaughter'],
    covers: [{ keyword: 'slaughter', fp: 'aa9a5c68' }],
  },
  {
    id: 'slaughter-rise',
    topic: 'keywords',
    q: 'Does killing an enemy with Rise count for Slaughter?',
    a: "Yes. Knocking it down counts as a kill even though it comes back.",
    aliases: ['slaughter reborn', 'slaughter rise'],
    seeAlso: ['slaughter'],
    covers: [{ keyword: 'slaughter', fp: 'aa9a5c68' }],
  },
  {
    id: 'slaughter-effect-damage',
    topic: 'keywords',
    q: 'If my minion kills something with an effect instead of an attack, is that a Slaughter?',
    a: "No. Only **attack kills** count. Damage from an Echo, a Bleed or some other effect doesn't trigger Slaughter.",
    aliases: ['slaughter effect damage', 'slaughter deathrattle kill'],
    seeAlso: ['slaughter'],
    covers: [{ keyword: 'slaughter', fp: 'aa9a5c68' }],
  },

  // ── Overflow ──────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'overflow',
    topic: 'keywords',
    q: 'What does Overflow mean?',
    a: "It's what happens **when a minion gets summoned but your board has no space** (7 minions max). The summon is lost, but cards that say **Overflow:** get paid for it. Works in the shop and in combat.",
    aliases: ['overflow', 'full board', 'no room', 'board full summon'],
    seeAlso: ['board-and-hand-size', 'overflow-per-body'],
    covers: [{ keyword: 'overflow', fp: '10809bad' }],
  },
  {
    id: 'overflow-per-body',
    topic: 'keywords',
    q: "If an effect summons several minions and none fit, is that one Overflow or several?",
    a: "Several. **Each minion that doesn't fit** is its own Overflow.",
    aliases: ['multiple overflow', 'overflow count'],
    seeAlso: ['overflow'],
    covers: [{ keyword: 'overflow', fp: '10809bad' }],
  },
  {
    id: 'overflow-rise',
    topic: 'keywords',
    q: "Does a Rise that can't fit count as an Overflow?",
    a: "Yes. If a minion tries to Rise and there's no room, it stays dead, and that **counts as an Overflow**.",
    aliases: ['reborn overflow', 'rise no room'],
    seeAlso: ['overflow', 'echo-rise-full-board'],
    covers: [{ rule: 'R-RISE-05', fp: '08016ede' }],
  },

  // ── Bleed ─────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'bleed',
    topic: 'keywords',
    q: 'How does Bleed work?',
    a: "At Start of Combat the minion **marks random enemies**. Then every few attacks in the fight, each marked enemy that's still alive **takes damage equal to the Bleed minion's Attack**.",
    aliases: ['bleed', 'mark', 'marked enemies', 'damage over time'],
    seeAlso: ['bleed-details', 'start-of-combat'],
    covers: [{ keyword: 'bleed', fp: '2672aad8' }],
  },
  {
    id: 'bleed-details',
    topic: 'keywords',
    q: 'Whose attacks count for Bleed, and does it ever pick new targets?',
    a: "**Every attack in the fight counts, from both sides.** The marks are picked once at the start and **never change**, so once they're all dead the Bleed has nothing left to hit. It uses the minion's Attack at that moment, so buffing it makes the Bleed hurt more.",
    aliases: ['bleed attacks', 'bleed targets', 'bleed reroll'],
    seeAlso: ['bleed'],
    covers: [{ keyword: 'bleed', fp: '2672aad8' }],
  },
  {
    id: 'bleed-dies',
    topic: 'keywords',
    q: 'What happens to Bleed if the minion dies?',
    a: "It **stops**. The Bleed only works while its minion is alive. A Gilded one marks twice as many enemies.",
    aliases: ['bleed ends', 'bleed gilded', 'golden bleed'],
    seeAlso: ['bleed'],
    covers: [{ keyword: 'bleed', fp: '2672aad8' }],
  },

  // ── Choose One ────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'choose-one',
    topic: 'keywords',
    q: 'What does Choose One do?',
    a: "When you play the card, you **pick one of its two effects**. You choose first, and then aim if the effect needs a target.",
    aliases: ['choose one', 'pick one', 'option', 'modal', 'choice'],
    seeAlso: ['choose-one-cancel', 'choose-one-get-both'],
    covers: [{ keyword: 'chooseone', fp: 'bcefe663' }],
  },
  {
    id: 'choose-one-cancel',
    topic: 'keywords',
    q: 'Can I back out of a Choose One after I start playing it?',
    a: "Yes. Click away to **cancel** and nothing happens: the card stays in your hand and nothing is spent.",
    aliases: ['cancel choose one', 'undo choice', 'back out'],
    seeAlso: ['choose-one'],
    covers: [{ keyword: 'chooseone', fp: 'bcefe663' }],
  },
  {
    id: 'choose-one-cant-play',
    topic: 'keywords',
    q: "Why won't my Choose One card play?",
    a: "A Choose One **minion** needs a free board slot, so it won't play on a full board. A Choose One **spell** that needs a target won't play if there's no legal target, and it stays in your hand.",
    aliases: ['choose one full board', 'choose one no target'],
    seeAlso: ['choose-one', 'board-and-hand-size'],
    covers: [{ keyword: 'chooseone', fp: 'bcefe663' }],
  },
  {
    id: 'choose-one-get-both',
    topic: 'keywords',
    q: 'Can I ever get both Choose One effects?',
    a: "Sometimes. Some cards get **both effects when Gilded** (their Gilded text says so), and some cards and runes make your next Choose One (or a specific card) do both. When that's active, there's no prompt at all: you just get both.",
    aliases: ['choose both', 'both options', 'gilded choose one'],
    seeAlso: ['choose-one'],
    covers: [{ keyword: 'chooseone', fp: 'bcefe663' }],
  },

  // ── Watcher ───────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'watcher',
    topic: 'keywords',
    q: 'What is a Watcher?',
    a: "A **Watcher** is any card that **triggers off other minions** doing something: another minion dying, you triggering a Shout or a Rally, a friendly minion Rising, and so on. You'll see the name in the Compendium, not printed on cards.",
    aliases: ['watcher', 'whenever', 'reactive', 'after you'],
    seeAlso: ['rally-watchers', 'watcher-rise'],
    covers: [{ keyword: 'watcher', fp: 'ba7a7abe' }],
  },
  {
    id: 'watcher-rise',
    topic: 'keywords',
    q: 'Do "when a friendly minion Rises" cards work in the shop too?',
    a: "Yes. A Rise in the shop wakes them just like one in combat, and what they give in the shop is permanent. Only **your own** minions Rising count, not the enemy's.",
    aliases: ['rise watcher', 'when a minion rises', 'reborn watcher'],
    seeAlso: ['watcher', 'echo-vs-rise'],
    covers: [{ rule: 'R-RISE-03', fp: '99347468' }],
  },

  // ── Spend ─────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'spend',
    topic: 'keywords',
    q: 'How do "When you spend X Gold" cards work?',
    a: "The minion keeps a meter of the **Gold you spend while it's on your board**. Every time the meter fills to X, it goes off. Leftover Gold **carries over**, even into later turns, and the card shows how close it is.",
    aliases: ['spend', 'spend gold', 'gold spent', 'when you spend'],
    seeAlso: ['spend-what-counts', 'what-things-cost'],
    covers: [{ keyword: 'spend', fp: '750b1bee' }],
  },
  {
    id: 'spend-what-counts',
    topic: 'keywords',
    q: 'What counts as spending Gold?',
    a: "Pretty much anything that costs Gold: **buying, refreshing, leveling up your tavern, hero powers, runes and using Equipment**. Free refreshes don't count, since no Gold actually gets spent.",
    aliases: ['spend refresh', 'spend tier up', 'spend hero power', 'free refresh', 'gold spent', 'spend', 'spending', 'gold spent this turn', 'spent gold'],
    seeAlso: ['spend', 'refresh-and-freeze-buttons', 'tavern-up-button'],
    covers: [{ keyword: 'spend', fp: '750b1bee' }],
  },
  {
    id: 'spend-big',
    topic: 'keywords',
    q: 'If I spend a lot at once, can a Spend card go off twice?',
    a: "Yep. If one purchase fills the meter twice, it **fires twice**. A Gilded one fires just as often, but each payout is doubled.",
    aliases: ['spend twice', 'gilded spend', 'golden spend'],
    seeAlso: ['spend'],
    covers: [{ keyword: 'spend', fp: '750b1bee' }],
  },
];
