import type { WikiEntry } from './types';

// Checked against packages/sim/src/lobby/runLobby.ts (pairRunLobby, ghostFor, closeRunLobbyRound), rank.ts,
// lobbyStrength.ts, lobby/practiceBots.ts, reducer.ts (practice curtain), state.ts (PracticeConfig), and
// packages/ui/src LobbyPanel.tsx, Title.tsx, PracticeOptions.tsx, EscMenu.tsx, Recruit.tsx (drag/cast/timer),
// Career.tsx, Rankings.tsx, Leaderboard.tsx, RecentGames.tsx, EndScreen.tsx, replay/ReplayOverlay.tsx,
// touchInput.ts, bug-report/ and store.ts on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── Lobby: placements and how a game ends ─────────────────────────────────────────────────────────────
  {
    id: 'shared-placement',
    topic: 'lobby',
    q: 'What if two players get knocked out in the same round?',
    a: "They **share** a placement, and it's the lower one. Say 6 players are alive and 2 of them go out in the same round: both finish **6th**, and nobody gets 5th.",
    aliases: ['tie placement', 'same round elimination', 'double knockout', 'shared place', 'split placement'],
    seeAlso: ['placement-and-rating', 'everyone-dies-same-round'],
  },
  {
    id: 'everyone-dies-same-round',
    topic: 'lobby',
    q: 'What if everyone left dies in the same round?',
    a: "There's always a winner. If every player still standing would hit 0 in the same round, the one who went into that round with the **most Health plus Armor** survives and takes 1st. The others share the next placement down.",
    aliases: ['wipeout', 'nobody left', 'everyone dead', 'final round tie', 'who wins a tie'],
    seeAlso: ['shared-placement', 'goal-of-the-game'],
  },
  {
    id: 'game-over-for-me',
    topic: 'lobby',
    q: 'When is my game over?',
    a: "The moment your Health and Armor both hit 0, you're out and your placement is locked in. You go straight to the end screen, even though the other players keep fighting without you. Be the last one standing and you finish **1st**.",
    aliases: ['eliminated', 'knocked out', 'game over', 'end screen', 'dead', 'lost'],
    seeAlso: ['goal-of-the-game', 'health-and-armor'],
  },
  {
    id: 'very-long-game',
    topic: 'lobby',
    q: 'What happens if a game just goes on forever?',
    a: "There's a safety limit. If a game ever gets through **round 60** with more than one player still standing, it ends right there and everyone left alive shares **1st**. In practice, games end long before that.",
    aliases: ['stalemate', 'max rounds', 'round limit', 'infinite game', 'never ends', 'round 60'],
    seeAlso: ['game-over-for-me'],
  },
  // ── Lobby: pairing and ghosts ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ghost-fight',
    topic: 'lobby',
    q: 'What exactly is a ghost fight?',
    a: "When an odd number of players are left, one player fights a **ghost** instead of a live opponent. The ghost is the board of the **most recently knocked-out** player, exactly as it was the round they went out. You never get the ghost of someone you fought last round or knocked out yourself. Lose to it and you take damage as normal; beat it and nobody takes anything, since its owner is already out.",
    aliases: ['ghost', 'bye', 'odd player', 'dead player board', 'phantom'],
    seeAlso: ['who-do-i-fight', 'who-gets-the-ghost'],
    covers: [{ rule: 'R-LOBBY-01', fp: '3ca6048e' }],
  },
  {
    id: 'who-gets-the-ghost',
    topic: 'lobby',
    q: 'Who gets stuck with the ghost fight?',
    a: "Only the **three lowest players** (by Health plus Armor) can get the ghost, so the leaders never get the (usually easier) ghost round. It also rotates, so the same player doesn't keep getting it when there's a fair alternative.",
    aliases: ['ghost rotation', 'bye rotation', 'who fights the ghost', 'ghost pairing'],
    seeAlso: ['ghost-fight'],
  },
  {
    id: 'rematch-rule',
    topic: 'lobby',
    q: 'Can I fight the same player twice in a row?',
    a: "Not if it can be avoided. You won't face the same opponent again within **3 rounds**, and the game prefers whoever you've met the fewest times. Once only a few players are left there's no one else to fight, so repeats start happening then.",
    aliases: ['rematch', 'same opponent', 'fight again', 'repeat opponent', 'back to back'],
    seeAlso: ['who-do-i-fight'],
  },
  // ── Lobby: the player list ────────────────────────────────────────────────────────────────────────────
  {
    id: 'lobby-player-list',
    topic: 'lobby',
    q: 'What does the list of players on the side of the screen show?',
    a: "Every seat in your lobby: hero portrait, name, **Health** (heart) and **Armor** (shield), and a health bar. Players still alive are sorted strongest to weakest, and knocked-out players sit underneath showing the place they finished (like **#7**). The header shows the **round**, how many players are **left**, and the most Health you can lose this round.",
    aliases: ['lobby panel', 'player list', 'seats', 'rail', 'sidebar', 'other players'],
    seeAlso: ['next-opponent-glow', 'scout-a-player', 'max-loss-display'],
  },
  {
    id: 'next-opponent-glow',
    topic: 'lobby',
    q: "How do I know who I'm fighting next?",
    a: "Look at the player list: your next opponent's seat **glows**. You can hover it to scout their board before you end your turn.",
    aliases: ['next opponent', 'who am i facing', 'glowing seat', 'highlighted player'],
    seeAlso: ['scout-a-player', 'who-do-i-fight'],
  },
  {
    id: 'scout-a-player',
    topic: 'lobby',
    q: "How do I scout another player's board?",
    a: "**Hover** their seat in the player list. You'll see their hero, **shop tier**, how many **Gilded** minions they have, their main tribe, their **runes**, and their **last three fights** (who, win or loss, and the damage). It says \"No intel yet\" until they've fought. You can hover your own seat too.",
    aliases: ['scout', 'spy', 'check opponent', 'enemy board', 'intel', 'hover player'],
    seeAlso: ['pin-scout-card', 'next-opponent-glow'],
  },
  {
    id: 'pin-scout-card',
    topic: 'lobby',
    q: 'Can I keep a scout card open?',
    a: "Yep. **Click** (left or right) an opponent's seat to pin their card, so you can hover the rune icons on it for their text. Click a different seat to switch, and click anywhere else or press **Esc** to close it.",
    aliases: ['pin', 'keep open', 'lock scout', 'scout card closes'],
    seeAlso: ['scout-a-player'],
  },
  {
    id: 'last-damage-number',
    topic: 'lobby',
    q: "What's the minus number next to a player in the list?",
    a: "That's how much damage they **took last round**. It stays blank if they took nothing. And after you win a fight, the damage you dealt floats up over your opponent's seat once.",
    aliases: ['minus number', 'damage taken', 'last round damage', 'red number'],
    seeAlso: ['lobby-player-list'],
  },
  {
    id: 'max-loss-display',
    topic: 'lobby',
    q: 'What does the heart number at the top of the player list mean?',
    a: "It's the **most Health you can lose** if you lose this round's fight (like −5 early on). Once the early caps are over it just says **No cap**.",
    aliases: ['max damage', 'damage cap', 'max loss', 'no cap', 'heart number'],
    seeAlso: ['how-much-damage', 'lobby-player-list'],
  },
  // ── Lobby: leaving and saving ─────────────────────────────────────────────────────────────────────────
  {
    id: 'leave-mid-game',
    topic: 'lobby',
    q: 'Can I leave in the middle of a game?',
    a: "Yes. Press **Esc** and hit **Save & Quit**: it saves that exact moment and takes you to the main menu. Hit **Continue** on the main menu to pick up right where you left off. Your game is saved as you play, so even closing the window won't lose it.",
    aliases: ['save', 'quit', 'resume', 'continue', 'come back later', 'pause game', 'exit'],
    seeAlso: ['new-game-replaces-save', 'esc-menu'],
  },
  {
    id: 'new-game-replaces-save',
    topic: 'lobby',
    q: 'What happens to my saved game if I start a new one?',
    a: "You only get **one** saved game. Starting a new game replaces it (the Play button warns you first). You can also throw it away yourself with the **trash** button next to Continue; click it twice to confirm.",
    aliases: ['saved run', 'discard', 'delete save', 'two games', 'overwrite save'],
    seeAlso: ['leave-mid-game'],
  },
  // ── Lobby: Rating ─────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'rated-vs-unrated',
    topic: 'lobby',
    q: 'Which games count for my Rating?',
    a: "Only **Play** games are rated. **Practice**, the **Tutorial** and **Rift** never touch your Rating. Rated results are checked on the server, so your rank change can take a moment to show up on the end screen.",
    aliases: ['ranked', 'unrated', 'does practice count', 'mmr', 'rated game'],
    seeAlso: ['placement-and-rating', 'game-modes'],
  },
  {
    id: 'rank-medals',
    topic: 'lobby',
    q: 'What are the ranks?',
    a: "There are six medals: **Bronze, Silver, Gold, Platinum, Diamond** and **Ascendant**. Each has three divisions that go **I, II, III** from low to high, so you climb Bronze I, Bronze II, Bronze III, then Silver I. Each division is **100 points**, except **Ascendant III** at the very top, where points keep climbing with no cap.",
    aliases: ['medals', 'divisions', 'tiers', 'rank names', 'bronze', 'silver', 'gold', 'platinum', 'diamond', 'ascendant'],
    seeAlso: ['placement-and-rating', 'promotion-game'],
    covers: [{ rule: 'R-RANK-03', fp: '7f57de63' }],
  },
  {
    id: 'promotion-game',
    topic: 'lobby',
    q: 'What is a promotion game?',
    a: "Hitting **100 points** doesn't rank you up by itself. It makes your **next rated game** a promotion game. Win it and you move up, starting the new division at **10 points** (a little cushion). Finish 5th to 8th and you just lose points as normal, and you can try again once you're back at 100. Points past 100 are dropped, they don't carry over.",
    aliases: ['promo', 'rank up', 'promotion', 'level up rank', '100 points'],
    seeAlso: ['medal-promotion', 'placement-and-rating'],
    covers: [{ rule: 'R-RANK-01', fp: '739d650f' }],
  },
  {
    id: 'medal-promotion',
    topic: 'lobby',
    q: "Why didn't a top 4 promote me to the next medal?",
    a: "Moving up a division (like Gold I to Gold II) only needs a **top 4** in the promotion game. Moving up a whole **medal** (like Gold III to Platinum I) needs **1st place**. At a medal gate, 2nd to 4th keeps you parked at 100, still ready to try again. Only 5th to 8th drops you below 100.",
    aliases: ['medal gate', 'next medal', 'need first place', 'stuck at 100'],
    seeAlso: ['promotion-game'],
  },
  {
    id: 'demotion-game',
    topic: 'lobby',
    q: 'Can I drop down a rank?',
    a: "Never straight away. A loss that would take you below 0 **stops at 0** and makes your next rated game a **demotion game**. Finish **top 4** in it and you're safe (and gain points as normal). Finish **5th to 8th** and you drop one division, landing at 100 minus that game's loss (a 5th puts you at 94, an 8th at 60). Dropping out of a medal lands you in the medal below's III. Bronze I is the floor, so there's no demotion game there.",
    aliases: ['demote', 'derank', 'lose rank', 'drop division', 'zero points', 'demotion'],
    seeAlso: ['placement-and-rating'],
    covers: [{ rule: 'R-RANK-02', fp: '4ee5bf6c' }],
  },
  {
    id: 'lobby-strength',
    topic: 'lobby',
    q: 'What is lobby strength?',
    a: "It's how tough your **seven opponents** were: roughly their average win rate from all their fights, before your game. 50% is an even lobby. Bots count as weak (25%), and a player nobody has data on counts as 50%. It's **hidden for now** while we improve it, so you won't see it on your Career match history or Recent Games at the moment. It still counts toward the lobby strength bonus.",
    aliases: ['lobby strength', 'lobby difficulty', 'percent', 'how hard was my lobby'],
    seeAlso: ['lobby-strength-bonus', 'career-page'],
    covers: [{ rule: 'R-LOBBY-03', fp: 'c03915d5' }, { rule: 'R-LOBBY-04', fp: '4ab24a9f' }],
  },
  {
    id: 'lobby-strength-bonus',
    topic: 'lobby',
    q: 'Do I get extra Rating for beating a tough lobby?',
    a: "Yes, for a **top 4** finish in a lobby **above 50%**. The tougher the lobby and the higher you place, the bigger the bonus: up to **+15** for 1st in a 100% lobby (about +8 for 1st at 75%). An even or easier lobby pays no bonus, and a bad finish is never made worse by it. The end screen shows one total, bonus included.",
    aliases: ['strength bonus', 'bonus points', 'hard lobby bonus', 'extra mmr'],
    seeAlso: ['lobby-strength', 'placement-and-rating'],
    covers: [{ rule: 'R-RANK-04', fp: '74e1fca6' }],
  },
  // ── Modes ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'game-modes',
    topic: 'lobby',
    q: 'What game modes are there?',
    a: "Hit **Play** on the main menu to pick one. (**Patch Notes** on the main menu lists gameplay changes by date.) **Play** is the rated 8-player lobby. **Practice** is a sandbox with options and no Rating. **Learn** holds the **Tutorial**. Sometimes a limited-time **Rift** mode shows up too.",
    aliases: ['modes', 'mode select', 'ranked', 'practice', 'tutorial', 'learn', 'rift'],
    seeAlso: ['practice-mode', 'tutorial', 'rift-mode', 'rated-vs-unrated'],
  },
  {
    id: 'practice-mode',
    topic: 'lobby',
    q: 'What is Practice mode?',
    a: "A sandbox for trying things out. It's the same 8-player lobby, but **nothing is rated**, and you pick the rules first: which heroes, real players or bots, bot level, Health, timer speed and tribes. Your Practice games still show up on the Practice tabs of Recent Games and your Career.",
    aliases: ['practice', 'sandbox', 'casual', 'unranked', 'training'],
    seeAlso: ['practice-options', 'rated-vs-unrated'],
  },
  {
    id: 'practice-options',
    topic: 'lobby',
    q: 'What can I change in Practice?',
    a: "**Heroes** (Beginner or All), **Opponents** (real players' recorded boards, or simple Bots), **Bot difficulty** (1 to 10), **Health** (Unlimited or Normal), **Time** (1× to 4× the shop timer, or Unlimited) and **Tribes** (Normal, or pick the tribes you want).",
    aliases: ['practice settings', 'practice setup', 'custom game', 'options'],
    seeAlso: ['practice-bots', 'practice-unlimited-health', 'practice-timer', 'practice-heroes', 'practice-tribes'],
  },
  {
    id: 'practice-bots',
    topic: 'lobby',
    q: 'What do the Practice bot levels do?',
    a: "Bots are simple enemies that mostly just grow in stats. Level **1 is Easy, 3 is Medium, 5 is Hard**, and higher levels get stronger boards. From **level 6** up, bots also field some real utility minions. Heads up: losing to bots costs more Health than a normal fight (more at higher levels), so bot games don't drag on.",
    aliases: ['bot difficulty', 'bot level', 'ai', 'easy', 'medium', 'hard', 'computer opponents'],
    seeAlso: ['practice-options'],
  },
  {
    id: 'practice-unlimited-health',
    topic: 'lobby',
    q: 'How does a Practice game end if my Health is Unlimited?',
    a: "You can't be knocked out, so the game ends after **round 15** (or sooner if every opponent is out). Your placement is based on **how many fights you won** compared to the other players. Pick **Normal** Health instead for real damage and last-one-standing rules.",
    aliases: ['unlimited health', 'invulnerable', 'cant die', 'round 15', 'practice end'],
    seeAlso: ['practice-options'],
  },
  {
    id: 'practice-timer',
    topic: 'lobby',
    q: 'Can I turn off the turn timer?',
    a: "In **Practice**, yes. Set **Time** to **Unlimited** and the timer shows ∞ and never locks you out. 2×, 3× and 4× just give you that many times the normal time. You can also change it mid-game from the timer's dropdown. Rated games always use the normal timer.",
    aliases: ['no timer', 'more time', 'infinite time', 'slow down timer', 'unlimited time'],
    seeAlso: ['timer-runs-out', 'practice-options'],
    covers: [{ rule: 'R-PRACTICE-TIME-01', fp: 'a9b971d5' }],
  },
  {
    id: 'practice-heroes',
    topic: 'lobby',
    q: "What's the difference between Beginner and All heroes in Practice?",
    a: "**Beginner** (the default) always offers the same three starter heroes: **Indy, Warden and Keshi**. **All** lets you pick from every hero.",
    aliases: ['beginner heroes', 'all heroes', 'starter heroes', 'hero pick', 'choose any hero'],
    seeAlso: ['practice-options'],
    covers: [{ rule: 'R-PRACTICE-HEROES-01', fp: '0c849145' }],
  },
  {
    id: 'practice-tribes',
    topic: 'lobby',
    q: 'Can I choose which tribes show up in Practice?',
    a: "Yep. Pick as many tribes as you like, and your shop, Discovers and random cards will only be those tribes plus **neutral** cards. **Normal** plays the usual way. It only changes **your** cards: the enemies still use the full card pool.",
    aliases: ['tribe filter', 'pick tribes', 'only beasts', 'tribe select', 'surge'],
    seeAlso: ['practice-options'],
    covers: [{ rule: 'R-PRACTICE-SURGE-01', fp: '172e154b' }],
  },
  {
    id: 'tutorial',
    topic: 'lobby',
    q: 'Is there a tutorial?',
    a: "Yes, under **Learn**: a coached first game that walks you through every mechanic. If you've never played, hitting Play offers it first (you can **Skip and just play**). It's never rated, and finishing it the first time gives you **250 Account XP**.",
    aliases: ['learn', 'how to play', 'new player', 'guide', 'lessons', 'onboarding'],
    seeAlso: ['game-modes', 'account-xp'],
  },
  {
    id: 'rift-mode',
    topic: 'lobby',
    q: 'What is Rift mode?',
    a: "A **limited-time** mode that bends one rule for fun (like a free minion each turn), then goes away again. Its card only appears on the mode screen while a Rift is live, with a line saying what's different. Rift games don't count for Rating.",
    aliases: ['rift', 'event', 'weekend mode', 'special mode', 'limited time'],
    seeAlso: ['game-modes'],
  },
  // ── Pages ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'career-page',
    topic: 'lobby',
    q: "What's on my Career page?",
    a: "Open **Social** on the main menu. On the left: your favorite hero and stats like 1st place wins, top 4s and average placement. In the middle: **Match History** (your recent rated games with final team, runes and a Watch Replay button), **Heroes**, and **Practice**. On the right: your rank and **Performance Trends** over time. A top 4 counts as a win there.",
    aliases: ['career', 'profile', 'stats', 'match history', 'social', 'my games'],
    seeAlso: ['leaderboard', 'recent-games', 'lobby-strength'],
    covers: [{ rule: 'R-CAREER-PRACTICE-01', fp: '3be86986' }],
  },
  {
    id: 'leaderboard',
    topic: 'lobby',
    q: 'Where is the Leaderboard?',
    a: "Open **Social**, then **Leaderboard** in the side menu. It lists the top players by rank with their games played. Click a row to open their Career, or hit **Watch** to see their latest game. Your own row is highlighted.",
    aliases: ['rankings', 'top players', 'ladder', 'high scores', 'best players'],
    seeAlso: ['career-page', 'hall-of-champions'],
  },
  {
    id: 'hall-of-champions',
    topic: 'lobby',
    q: 'What is the Hall of Champions?',
    a: "It celebrates the best **boards**, not players. Every recorded game keeps fighting as an opponent in other people's lobbies, and the Hall shows the top 10 by win rate (boards need at least 10 fights, and more fights count for more). Sort by **Most recent** or **Win rate** to see their final team, runes and record.",
    aliases: ['hall', 'champions', 'best boards', 'top runs', 'hall of fame'],
    seeAlso: ['leaderboard', 'who-do-i-fight'],
    covers: [{ rule: 'R-HALL-01', fp: '6a762e2b' }],
  },
  {
    id: 'recent-games',
    topic: 'lobby',
    q: "Can I watch other people's games?",
    a: "Yep. **Recent Games** (in the Social side menu) lists the latest finished games from everyone, with **Ranked** and **Practice** tabs. Hit **Watch Replay** on a game (older Practice games may not have one), or click the banner to open that player's Career.",
    aliases: ['spectate', 'watch others', 'recent', 'replays', 'feed'],
    seeAlso: ['rewatch-a-game', 'replay-controls'],
  },
  // ── Progression ───────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'account-xp',
    topic: 'lobby',
    q: 'How do I earn Account XP?',
    a: "Finish games. A rated game gives **100 XP**, plus **40** for a top 4, plus **60** more for 1st, plus **25** for a comeback (winning a fight right after losing 4 or more in a row). Practice gives 60% of that (a flat 60 with Unlimited Health). Your first Tutorial finish is worth **250**. Quit games give nothing. It's separate from Rating and never goes down.",
    aliases: ['xp', 'experience', 'account level', 'level up', 'progression'],
    seeAlso: ['account-levels', 'crates'],
    covers: [{ rule: 'R-PROG-XP-01', fp: '014e0b65' }],
  },
  {
    id: 'account-levels',
    topic: 'lobby',
    q: 'How much XP does each Account Level take?',
    a: "Levels 1 to 10 need **250 XP** each, 11 to 25 need **400** each, and every level after that needs **500**. There's no max level, and one big game can take you up more than one level.",
    aliases: ['xp curve', 'level cap', 'max level', 'how many levels'],
    seeAlso: ['account-xp', 'crates'],
    covers: [{ rule: 'R-PROG-CURVE-01', fp: '3430d7ad' }],
  },
  {
    id: 'crates',
    topic: 'lobby',
    q: 'What are crates and how do I get them?',
    a: "You get **one crate per Account Level** (your first game gives a Welcome Crate). Open it right after the game or later from the **Collection**. It gives you a cosmetic you **don't already own**. The odds are fixed: **Common 50%, Rare 30%, Epic 15%, Legendary 5%** (if you already own everything of the rarity it rolls, you get the nearest rarity that still has something). No keys, no buying, just play.",
    aliases: ['crate', 'loot box', 'chest', 'rewards', 'unlock', 'open crate'],
    seeAlso: ['collection', 'account-levels'],
    covers: [{ rule: 'R-PROG-CRATE-01', fp: 'd438ab2c' }, { rule: 'R-PROG-CRATE-02', fp: 'f8a0ebcc' }],
  },
  {
    id: 'collection',
    topic: 'lobby',
    q: 'What is the Collection?',
    a: "Your cosmetics page, from the main menu. Open your crates there and equip what you've won: **titles** (shown under your name), hero and minion **skins**, and hero attack animations. Locked items show how to get them. Cosmetics are just looks and never change how anything plays.",
    aliases: ['cosmetics', 'skins', 'titles', 'hero attack', 'equip', 'wardrobe'],
    seeAlso: ['crates'],
  },
  {
    id: 'achievements',
    topic: 'lobby',
    q: 'Are there achievements?',
    a: "Yes. When they're switched on, your Career page gets an **Achievements** tab, sorted into categories with done and in-progress filters. Each one shows what it takes and the **XP** it pays, and new unlocks show up on the end screen.",
    aliases: ['achievement', 'feats', 'challenges', 'trophies'],
    seeAlso: ['career-page', 'account-xp'],
    covers: [{ rule: 'R-ACH-03', fp: 'bff1aca2' }],
  },
  // ── Controls: menus and settings ──────────────────────────────────────────────────────────────────────
  {
    id: 'esc-menu',
    topic: 'controls',
    q: "What's in the Esc menu?",
    a: "**Save & Quit** (mid-game), **Audio** (Master, Game sounds, Music and Announcer, each with a slider and mute), combat **speed** and **Auto-ramp**, **Show opponent cosmetics**, an effects frame cap, and sign in or out. The desktop app also has fullscreen and Quit game. Heads up: the Esc menu doesn't pause your shop timer.",
    aliases: ['settings', 'options', 'menu', 'volume', 'sound', 'music', 'announcer', 'escape'],
    seeAlso: ['auto-ramp', 'combat-speed', 'leave-mid-game'],
  },
  {
    id: 'auto-ramp',
    topic: 'controls',
    q: 'What does Auto-ramp speed do?',
    a: "It speeds up **long fights** as they go on, then eases back down so you still see the finish at a normal pace. Turn it on in the **Esc** menu. With it on, the speed slider sets the speed fights **start** at.",
    aliases: ['ramp', 'auto speed', 'faster fights', 'long combat'],
    seeAlso: ['combat-speed', 'esc-menu'],
  },
  {
    id: 'touch-controls',
    topic: 'controls',
    q: 'Can I play on a touchscreen?',
    a: "Yep. Drag cards with your finger just like a mouse. A quick **tap** works like hovering: it opens tooltips and scout cards, and they stay open until you tap somewhere else. **Tapping a card** opens its big inspect view; tap the backdrop to close it.",
    aliases: ['touch', 'phone', 'tablet', 'mobile', 'tap', 'finger'],
    seeAlso: ['inspect-a-card'],
  },
  // ── Controls: cards ───────────────────────────────────────────────────────────────────────────────────
  {
    id: 'cast-a-spell',
    topic: 'controls',
    q: 'How do I cast a spell?',
    a: "Drag it up out of your hand. A spell with no target casts as soon as you let go anywhere above your hand. A **targeted** spell has to be dropped right **on** the minion you want; let go anywhere else and it snaps back to your hand without being used.",
    aliases: ['use spell', 'play spell', 'target spell', 'buff spell', 'cast'],
    seeAlso: ['cancel-a-spell', 'choose-one-flow'],
  },
  {
    id: 'cancel-a-spell',
    topic: 'controls',
    q: "How do I cancel a spell I'm dragging?",
    a: "**Right-click** while you're still dragging it. It goes straight back to your hand, unused. Dropping it back down onto your hand works too.",
    aliases: ['cancel', 'undo spell', 'put spell back', 'right click'],
    seeAlso: ['cast-a-spell'],
  },
  {
    id: 'choose-one-flow',
    topic: 'controls',
    q: 'How do I play a Choose One card?',
    a: "Play it like normal (drag it up). A prompt pops up with its **two options**; click the one you want. If that option needs a target, you aim it next. Changed your mind? **Click away** from the prompt to cancel and the card stays in your hand, nothing spent.",
    aliases: ['choose one', 'pick an option', 'two effects', 'choice'],
    seeAlso: ['cast-a-spell', 'timer-pauses'],
    covers: [{ keyword: 'chooseone', fp: 'bcefe663' }],
  },
  {
    id: 'play-attachment',
    topic: 'controls',
    q: 'How do I play an Attachment minion onto another minion?',
    a: "Drag it from your hand and drop it **right on top of** a friendly minion that shares its type. It slides in and fuses its stats and keywords into that minion instead of taking its own spot.",
    aliases: ['attachment', 'magnetic', 'magnetize', 'attach', 'fuse', 'merge'],
    seeAlso: ['play-from-hand'],
    covers: [{ keyword: 'attachment', fp: '168ceb1c' }],
  },
  {
    id: 'reorder-hand',
    topic: 'controls',
    q: 'Can I rearrange the cards in my hand?',
    a: "Yep. Drag a card sideways and drop it **low**, down by your hand, where the gap opens. Lift it higher and you'll play or cast it instead.",
    aliases: ['sort hand', 'move card in hand', 'hand order'],
    seeAlso: ['board-order'],
  },
  {
    id: 'cant-drag-now',
    topic: 'controls',
    q: "Why can't I drag my cards right now?",
    a: "Probably one of these: a **fight** is playing (no dragging during combat), your turn is **ending**, or your **timer hit 0** (then only rearranging your board still works). A few cards also stay locked in your hand until you meet a condition (like reaching a certain tier).",
    aliases: ['cant move', 'stuck', 'drag not working', 'frozen cards', 'locked'],
    seeAlso: ['timer-runs-out', 'board-order'],
  },
  {
    id: 'timer-pauses',
    topic: 'controls',
    q: "Does the shop timer stop while I'm making a choice?",
    a: "Yes. It pauses while a **Discover**, a **Choose One** or any other pick is open, while you're **aiming** a targeted effect, and while the **Compendium** or the bug reporter is open. The Esc menu does **not** pause it.",
    aliases: ['timer paused', 'stop clock', 'discover timer', 'pause timer'],
    seeAlso: ['timer-runs-out', 'choose-one-flow'],
  },
  // ── Controls: replays, patch notes, bug reports ───────────────────────────────────────────────────────
  {
    id: 'rewatch-a-game',
    topic: 'controls',
    q: 'How do I rewatch a game I played?',
    a: "Right after a game, hit **Rewatch** on the end screen, or **Rewatch Last Game** on the main menu (that one only lasts until you close the game). For older games, open your **Career** Match History and hit **Watch Replay**.",
    aliases: ['replay', 'rewatch', 'watch my game', 'vod', 'recording'],
    seeAlso: ['replay-controls', 'recent-games'],
  },
  {
    id: 'replay-controls',
    topic: 'controls',
    q: 'What can I do while watching a replay?',
    a: "Pause and play, scrub through the round, and pick a speed (0.5× up to 5×). The round list lets you jump to any round's **shop** or **fight**. You can also toggle the shop sounds and the player's recorded cursor. Hit **✕** (or Esc, then Leave replay) to exit.",
    aliases: ['replay speed', 'skip round', 'scrub', 'pause replay', 'exit replay'],
    seeAlso: ['rewatch-a-game'],
  },
  {
    id: 'report-a-bug',
    topic: 'controls',
    q: 'How do I report a bug?',
    a: "Press **Ctrl+B** (almost any time), or click **Report a Problem** on the main menu. Describe what happened and what you expected. In a game, your current turn and latest fight are attached for you, and the timer pauses while you type. **Ctrl+Enter** sends it, **Esc** cancels.",
    aliases: ['bug', 'report', 'feedback', 'problem', 'broken', 'ctrl b', 'glitch'],
  },
];
