import type { WikiEntry } from './types';

// Checked against packages/sim/src/reducer.ts (buyRune / skipRuneforge / rerollRuneforge, the turn-6 / turn-9 forge
// schedule, runeforgePool, drawRuneOffer, the heroPower case), state.ts (handCap), config.ts (handMaxRuneTurn,
// QUESTS_ARCHIVED), heroes.ts (HeroPower, playableHeroes, practiceHeroChoiceIds), packages/content/src/runes.ts
// (RUNE_DUP_SWEETENER / RUNE_DUP_UNIQUE), and the UI: RuneforgeDialog.tsx, Recruit.tsx (forge overlay, turn clock,
// hero-power aim), QuestBadges.tsx (rune badges), LobbyPanel.tsx (scouting), StatusBar.tsx (power button),
// store.ts (rollHeroChoices) and MinionBook.tsx (Compendium tabs, quests hidden) on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── Runes ────────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'what-is-a-rune',
    topic: 'questsRunes',
    q: 'What is a rune?',
    a: "A rune is a permanent power-up for your whole game. You buy it at the **Runeforge** with Gold, and from then on it just works: some give you cards, some buff your minions, some change how the shop or combat plays out. Runes are never sold in the regular shop.",
    aliases: ['runes', 'run buff', 'trinket', 'anomaly', 'perk', 'relic'],
    seeAlso: ['what-is-the-runeforge', 'rune-lasts-whole-game', 'where-are-my-runes'],
  },
  {
    id: 'what-is-the-runeforge',
    topic: 'questsRunes',
    q: 'What is the Runeforge?',
    a: "It's a special shop that pops up at the start of certain turns. It lays out **4 runes**, you buy **one** with your Gold, and then it closes and your normal shop turn carries on.",
    aliases: ['forge', 'rune shop', 'rune forge', 'rune screen', 'rune offer'],
    seeAlso: ['when-does-the-runeforge-open', 'how-to-buy-a-rune', 'basic-vs-epic-runes'],
  },
  {
    id: 'when-does-the-runeforge-open',
    topic: 'questsRunes',
    q: 'When does the Runeforge open?',
    a: "Every hero gets two visits: the **Runeforge on turn 6** and the **Epic Runeforge on turn 9**. It opens right at the start of the turn, before you shop. A few runes can book you an extra visit or move the Epic one earlier.",
    aliases: ['rune turn', 'turn 6', 'turn 9', 'when runes', 'forge timing', 'rune schedule'],
    seeAlso: ['basic-vs-epic-runes', 'extra-runeforge-visits'],
  },
  {
    id: 'basic-vs-epic-runes',
    topic: 'questsRunes',
    q: "What's the difference between Basic and Epic runes?",
    a: "They come from two separate forges with two separate lists. The turn 6 **Runeforge** stocks Basic runes, and the turn 9 **Epic Runeforge** stocks Epic runes, which are the bigger, pricier ones. You can't get an Epic rune at the Basic forge or the other way around.",
    aliases: ['epic', 'epic forge', 'epic runeforge', 'basic rune', 'rarity', 'rare rune'],
    seeAlso: ['when-does-the-runeforge-open', 'rune-odds'],
  },
  {
    id: 'how-to-buy-a-rune',
    topic: 'questsRunes',
    q: 'How do I buy a rune?',
    a: "Click the rune tablet you want. Its price is on the coin, and your current Gold is shown at the top of the forge. A rune you can't afford is greyed out. As soon as you buy one, the forge closes.",
    aliases: ['pick a rune', 'choose rune', 'buy rune', 'rune cost', 'rune price'],
    seeAlso: ['rune-gold-is-shop-gold', 'can-i-skip-the-runeforge'],
  },
  {
    id: 'rune-gold-is-shop-gold',
    topic: 'questsRunes',
    q: 'Does buying a rune use my Gold for the turn?',
    a: "Yep. It's the same Gold you'd spend in the shop that turn, so a pricey rune means less to spend on minions right after. Plan your turn around it.",
    aliases: ['rune gold', 'rune cost gold', 'money for runes', 'spend gold runeforge'],
    seeAlso: ['how-to-buy-a-rune', 'gold-per-turn'],
  },
  {
    id: 'can-i-skip-the-runeforge',
    topic: 'questsRunes',
    q: 'Can I skip the Runeforge?',
    a: "No, there's no skip button. The forge stays open until you pick one of the runes, and you can't shop or end your turn until you do. If you don't like what's there, try the free **Re-roll** first.",
    aliases: ['skip', 'leave forge', 'close runeforge', 'pass', 'no rune', 'decline'],
    seeAlso: ['runeforge-reroll', 'runeforge-timer'],
  },
  {
    id: 'runeforge-reroll',
    topic: 'questsRunes',
    q: 'Can I re-roll the runes on offer?',
    a: "Once per game, for free. The **Re-roll** button swaps the offer for a fresh set, avoiding the runes you just saw when it can. Heads up: it's one re-roll for the **whole game**, shared by both forges, so using it on turn 6 means you won't have it on turn 9.",
    aliases: ['reroll', 'refresh runes', 'new runes', 'rune refresh', 'free reroll'],
    seeAlso: ['can-i-skip-the-runeforge', 'rune-discount'],
  },
  {
    id: 'runeforge-timer',
    topic: 'questsRunes',
    q: 'Does the turn timer run while the Runeforge is open?',
    a: "No. The clock waits while you choose, so take your time reading the runes. It starts ticking once the forge closes.",
    aliases: ['timer', 'clock', 'time', 'rush', 'hurry'],
    seeAlso: ['timer-runs-out', 'runeforge-inspect-board'],
  },
  {
    id: 'runeforge-inspect-board',
    topic: 'questsRunes',
    q: 'Can I look at my board while the Runeforge is open?',
    a: "Yes. Hit **Inspect the board** to tuck the forge away and look at your minions, then press the button again to return to the forge. Nothing is bought until you click a rune.",
    aliases: ['minimize', 'hide forge', 'see board', 'check board', 'peek'],
    seeAlso: ['rune-offer-fits-board'],
  },
  {
    id: 'how-many-runes',
    topic: 'questsRunes',
    q: 'How many runes can I have?',
    a: "You buy **one rune per forge visit**. Most games that's **two**: one Basic on turn 6 and one Epic on turn 9. Your rune row shows a third slot wrapped in chains; it unlocks only if something earns you an extra rune.",
    aliases: ['rune limit', 'max runes', 'number of runes', 'third rune', 'rune slots', 'chains'],
    seeAlso: ['extra-runeforge-visits', 'where-are-my-runes'],
  },
  {
    id: 'extra-runeforge-visits',
    topic: 'questsRunes',
    q: 'Can I get more than two Runeforge visits?',
    a: "Sometimes. A few runes book an extra forge visit, and one moves your Epic forge to an earlier turn instead (that's a move, not an extra visit). When a rune earns you a third rune, the chains on your third rune slot break so you know it's coming.",
    aliases: ['extra forge', 'bonus rune', 'third rune', 'another runeforge', 'more runes'],
    seeAlso: ['how-many-runes', 'two-forges-one-turn'],
  },
  {
    id: 'two-forges-one-turn',
    topic: 'questsRunes',
    q: 'What if two forges open on the same turn?',
    a: "You get both, one after the other. Epic forges open first, then the Basic one. Each works like a normal visit: buy one rune and the next forge opens.",
    aliases: ['double forge', 'two runeforges', 'back to back'],
    seeAlso: ['extra-runeforge-visits'],
    covers: [{ rule: 'R-RUNE-02', fp: 'a4f4fdce' }],
  },
  {
    id: 'rune-lasts-whole-game',
    topic: 'questsRunes',
    q: 'Do runes last the whole game?',
    a: "Yes. Once you buy a rune it stays active until the game ends. You can't sell it, lose it or swap it out.",
    aliases: ['permanent', 'expire', 'wear off', 'sell rune', 'remove rune', 'duration'],
    seeAlso: ['what-is-a-rune', 'when-does-a-rune-start-working'],
  },
  {
    id: 'when-does-a-rune-start-working',
    topic: 'questsRunes',
    q: 'When does a rune start working?',
    a: "Right away. A rune that says **Get something, repeat every Start of Turn** hands you the first one the moment you buy it, then one more each turn after. A rune that works in combat is already on for that turn's fight.",
    aliases: ['kick in', 'activate', 'first payout', 'immediately', 'next turn'],
    seeAlso: ['rune-lasts-whole-game', 'rune-counters'],
    covers: [{ rule: 'R-RUNE-08', fp: '069cd4aa' }], // re-checked 2026-10-07 (the Deep moved to the every-2-turns cadence; the answer still holds)
  },
  {
    id: 'where-are-my-runes',
    topic: 'questsRunes',
    q: 'Where can I see the runes I own?',
    a: "They sit as round badges in a row just above your hero. Hover one to read exactly what it does. The badge bounces and flashes whenever the rune goes off, in the shop or in a fight.",
    aliases: ['rune badges', 'my runes', 'owned runes', 'rune icons', 'rune row'],
    seeAlso: ['rune-counters', 'how-many-runes'],
  },
  {
    id: 'rune-counters',
    topic: 'questsRunes',
    q: 'What do the numbers on my rune badges mean?',
    a: "That's the rune's progress, like **3/5**. Runes that pay out every so often (every few Gold spent, every few kills, and so on) count up so you can see how close the next payout is. Runes that just always work show no number.",
    aliases: ['counter', 'meter', 'x/5', 'progress', 'tally', 'rune number'],
    seeAlso: ['where-are-my-runes'],
  },
  {
    id: 'rune-hand-size',
    topic: 'questsRunes',
    q: 'What happens if my hand is full when I buy a rune?',
    a: "No problem. While the Runeforge is open your hand can hold up to **20 cards** instead of 10, so everything a rune gives you still lands. You keep the extras afterwards, you just can't add more cards until you're back under 10.",
    aliases: ['full hand', 'hand limit', '20 cards', 'hand size', 'overflow', 'lost cards'],
    seeAlso: ['board-and-hand-size'],
  },
  {
    id: 'tribe-runes',
    topic: 'questsRunes',
    q: "Why don't I ever see runes for some tribes?",
    a: "A rune that's built around a tribe only shows up in games where that tribe is in the shop. No Dragons in this game means no Dragon runes. Runes that don't care about tribes can show up in any game.",
    aliases: ['tribe rune', 'missing runes', 'dragon rune', 'beast rune', 'which runes', 'tribes'],
    seeAlso: ['rune-offer-fits-board'],
    covers: [{ rule: 'R-RUNE-04', fp: '40f81b56' }],
  },
  {
    id: 'rune-offer-fits-board',
    topic: 'questsRunes',
    q: 'Will the Runeforge offer runes that fit my board?',
    a: "It tries to. If none of the 4 runes fits what you're building but a fitting one exists, one slot gets swapped for one that does. So you'll almost always see at least one rune that matches your board.",
    aliases: ['synergy', 'matching rune', 'guaranteed', 'fits my build', 'good rune'],
    seeAlso: ['what-fits-my-board', 'rune-discount'],
    covers: [{ rule: 'R-RUNE-03', fp: '3cb30fb5' }],
  },
  {
    id: 'what-fits-my-board',
    topic: 'questsRunes',
    q: 'What counts as a rune that "fits" my board?',
    a: "For a tribe rune, you need at least **2 of that tribe** on your board at the Runeforge, or **3** at the Epic Runeforge. Only your 7 board slots count, not your hand. An **All types** minion counts as one of every tribe. For a mechanic rune (Rally, Echo, Shout and so on), one minion that uses it is enough.",
    aliases: ['fit', 'match', 'synergy rules', 'tribe count', 'build'],
    seeAlso: ['rune-offer-fits-board', 'rune-discount'],
    covers: [{ rule: 'R-RUNE-03', fp: '3cb30fb5' }],
  },
  {
    id: 'rune-discount',
    topic: 'questsRunes',
    q: 'Why is one of the runes cheaper than usual?',
    a: "Runes that **don't** fit your board sometimes come with a discount, as a nudge to try something new: **1 to 2 Gold** off at the Runeforge, **2 to 4 Gold** off at the Epic Runeforge. A rune that already fits your board never gets one. The re-roll rolls new discounts too.",
    aliases: ['discount', 'cheaper', 'sale', 'pivot', 'lower price', 'price drop'],
    seeAlso: ['what-fits-my-board', 'runeforge-reroll'],
    covers: [{ rule: 'R-RUNE-03', fp: '3cb30fb5' }],
  },
  {
    id: 'rune-odds',
    topic: 'questsRunes',
    q: 'Are some runes rarer than others?',
    a: "No. Within a forge, every rune that's allowed to show up in your game has the same chance. The only nudge is the one that makes sure you see a rune that fits your board.",
    aliases: ['rarity', 'odds', 'chance', 'rare', 'pity', 'weights'],
    seeAlso: ['rune-offer-fits-board', 'basic-vs-epic-runes'],
  },
  {
    id: 'same-rune-twice',
    topic: 'questsRunes',
    q: 'Can I get the same rune twice? Does it stack?',
    a: "Yes, most runes can show up again, and a second copy stacks: it fires one more time, pays out double, or repeats one more time, depending on the rune. A handful of runes can't stack, and the forge stops offering those once you own one.",
    aliases: ['duplicate', 'double rune', 'two copies', 'stack', 'same rune'],
    seeAlso: ['rune-duplicate-no-stack'],
    covers: [{ rule: 'R-RUNEDUP-01', fp: 'd88a3cc8' }, { rule: 'R-RUNEDUP-07', fp: '64443a7f' }],
  },
  {
    id: 'rune-duplicate-no-stack',
    topic: 'questsRunes',
    q: "What if I end up with a second copy of a rune that can't stack?",
    a: "It's never a wasted buy. Instead of stacking you get **Gold back** (half the rune's price, rounded up) plus a **free refresh**.",
    aliases: ['duplicate refund', 'wasted rune', 'consolation', 'sweetener'],
    seeAlso: ['same-rune-twice'],
    covers: [{ rule: 'R-RUNEDUP-06', fp: '998c334d' }],
  },
  {
    id: 'opponents-have-runes',
    topic: 'questsRunes',
    q: 'Do my opponents get runes too?',
    a: "Yep. Every seat in the lobby visits the Runeforge, and their runes work in their fight against you, just like yours work for you.",
    aliases: ['enemy runes', 'bot runes', 'other players runes', 'opponent rune'],
    seeAlso: ['scout-opponent-runes'],
  },
  {
    id: 'scout-opponent-runes',
    topic: 'questsRunes',
    q: 'Can I see what runes an opponent has?',
    a: "Yes. Hover a seat in the lobby list to see their scouting card (click it to pin it open). It shows their hero, shop tier, build and recent fights, plus a **Runes** row. Hover a rune there to read it.",
    aliases: ['scout', 'scouting', 'enemy runes', 'spy', 'opponent info', 'check opponent'],
    seeAlso: ['opponents-have-runes', 'who-do-i-fight', 'see-opponent-hero'],
  },
  {
    id: 'runes-in-compendium',
    topic: 'questsRunes',
    q: 'Where can I read every rune?',
    a: "Open the Compendium and pick the **Runes** tab. The **Rune Rewards** tab shows the specific cards runes can hand you, and **Gifts** lists the Gift spells.",
    aliases: ['rune list', 'all runes', 'browse runes', 'rune rewards', 'library'],
    seeAlso: ['open-compendium', 'gift'],
  },
  {
    id: 'gift-not-shop-spell',
    topic: 'questsRunes',
    q: 'Do Gifts count for "when you cast a Shop spell" effects?',
    a: "No. A Gift isn't a Shop spell, so anything that says **Shop spell** ignores it. Only spells from the shop's own spell list count as Shop spells.",
    aliases: ['shop spell', 'gift trigger', 'gift counts', 'spell trigger'],
    seeAlso: ['gift'],
    covers: [{ keyword: 'gift', fp: '7eb2076b' }, { rule: 'R-SHOPSPELL-01', fp: 'fcac2a2e' }],
  },
  {
    id: 'are-there-quests',
    topic: 'questsRunes',
    q: 'Are there quests?',
    a: "Not right now. Quests are switched off while the game focuses on runes, so you won't be offered any. If they come back, this page will say so.",
    aliases: ['quest', 'quests', 'objective', 'mission', 'quest reward'],
    seeAlso: ['what-is-a-rune'],
  },

  // ── Heroes ───────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'pick-a-hero',
    topic: 'basics',
    q: 'How do I pick a hero?',
    a: "At the start of each game you're shown **3 random heroes**. Pick one and you're in. There's no re-roll, so it's a nice nudge to try heroes you might not pick yourself.",
    aliases: ['hero select', 'choose hero', 'hero choice', 'three heroes', 'reroll heroes', 'character'],
    seeAlso: ['missing-hero', 'practice-hero-choice', 'what-is-a-hero-power'],
  },
  {
    id: 'missing-hero',
    topic: 'basics',
    q: "Why haven't I seen a certain hero in a while?",
    a: "Two reasons. First, the 3 offered are random. Second, a hero whose power only works with a certain tribe is only offered in games where that tribe is in the shop. Some older heroes are also retired for now and won't show up at all.",
    aliases: ['missing hero', 'hero not showing', 'where is hero', 'tribe hero', 'retired hero'],
    seeAlso: ['pick-a-hero'],
  },
  {
    id: 'practice-hero-choice',
    topic: 'basics',
    q: 'Can I choose any hero in Practice?',
    a: "Yes. Practice has a **Heroes** setting. **Beginner** (the default) gives you the usual 3-hero pick, always **Indy, Warden and Keshi**, which are friendly starters. **All** lets you pick from every hero.",
    aliases: ['practice', 'choose any hero', 'beginner', 'starter heroes', 'all heroes'],
    seeAlso: ['pick-a-hero'],
    covers: [{ rule: 'R-PRACTICE-HEROES-01', fp: '0c849145' }],
  },
  {
    id: 'change-hero',
    topic: 'basics',
    q: 'Can I change my hero during a game?',
    a: "No, your hero is locked in for the game. There is a Tier 5 Shop spell that lets you **Discover a new hero power** to replace yours, though. Your hero stays the same, only the power changes.",
    aliases: ['swap hero', 'switch hero', 'new hero power', 'power shifter', 'replace power'],
    seeAlso: ['what-is-a-hero-power', 'discover'],
  },
  {
    id: 'hero-health',
    topic: 'basics',
    q: 'Do all heroes have the same Health?',
    a: "Yes, every hero starts at **30 Health**. What differs is **Armor**, which each hero brings on top of that.",
    aliases: ['hp', 'life', 'starting health', 'max health', 'resolve'],
    seeAlso: ['health-and-armor', 'hero-armor-differs'],
  },
  {
    id: 'hero-armor-differs',
    topic: 'basics',
    q: 'Why do heroes have different Armor?',
    a: "Armor is part of how each hero is balanced, so it changes from hero to hero (roughly 4 to 18 right now). It sits on top of your 30 Health and soaks up damage first. You can see a hero's Armor on the pick screen.",
    aliases: ['armor', 'armour', 'shield', 'extra health', 'tanky hero'],
    seeAlso: ['health-and-armor', 'hero-health'],
  },
  {
    id: 'what-is-a-hero-power',
    topic: 'basics',
    q: 'What is a hero power?',
    a: "Every hero has one special ability, shown on the button next to your hero. Some you press to use (**active**), and some just work on their own all game (**passive**). Hover the button to read what yours does.",
    aliases: ['hero power', 'ability', 'power', 'special', 'hp button', 'skill', 'hero ability', 'passive'],
    seeAlso: ['use-hero-power', 'passive-hero-power', 'hero-power-cost'],
  },
  {
    id: 'use-hero-power',
    topic: 'basics',
    q: 'How do I use my hero power?',
    a: "Press the hero power button during your shop turn. If it doesn't need a target, it fires right away. If it does, drag the glowing line onto a minion and let go (or click the button, then click the minion). Let go on nothing to cancel; it costs you nothing.",
    aliases: ['activate power', 'use power', 'target power', 'aim power', 'click hero', 'cancel power'],
    seeAlso: ['hero-power-cost', 'hero-power-greyed-out', 'hero-power-shop-targets'],
  },
  {
    id: 'hero-power-shop-targets',
    topic: 'basics',
    q: 'Can my hero power target minions in the Shop?',
    a: "Some can. Most targeted powers only work on your own board, but a few can also (or only) aim at a minion in the Shop. While you're aiming, the minions you're allowed to pick light up.",
    aliases: ['target shop', 'tavern target', 'aim at shop', 'which minions'],
    seeAlso: ['use-hero-power'],
  },
  {
    id: 'hero-power-cost',
    topic: 'basics',
    q: 'Does my hero power cost Gold?',
    a: "Depends on the hero. Lots of powers are free, others cost Gold, and a few get cheaper or pricier as the game goes on. The coin on the button always shows what it costs **right now**.",
    aliases: ['power cost', 'hero power price', 'free power', 'gold cost'],
    seeAlso: ['use-hero-power', 'hero-power-greyed-out'],
  },
  {
    id: 'hero-power-once-per-turn',
    topic: 'basics',
    q: 'How often can I use my hero power?',
    a: "Usually **once per turn**, and it refreshes at the start of every turn. It doesn't save up, so an unused power is just gone for that turn. Some powers work differently: **once per game**, a set number of uses per game, or more than once a turn. The button tells you which.",
    aliases: ['once per turn', 'cooldown', 'recharge', 'uses', 'once per game', 'save power'],
    seeAlso: ['hero-power-greyed-out', 'use-hero-power'],
  },
  {
    id: 'passive-hero-power',
    topic: 'basics',
    q: 'What does "passive" mean on a hero power?',
    a: "A passive power is always on. There's nothing to press: it does its thing automatically whenever its text says so. Many show a little counter so you can track their progress.",
    aliases: ['passive', 'always on', 'automatic', "can't click power", 'no button'],
    seeAlso: ['what-is-a-hero-power', 'hero-power-numbers'],
  },
  {
    id: 'hero-power-numbers',
    topic: 'basics',
    q: 'What are the numbers on my hero power?',
    a: "It's live info about your power, like progress toward its next payout, a countdown, or how big it is right now. Hover the power to read the full, up-to-date text.",
    aliases: ['power counter', 'tally', 'progress', 'countdown'],
    seeAlso: ['passive-hero-power'],
  },
  {
    id: 'hero-power-greyed-out',
    topic: 'basics',
    q: "Why can't I use my hero power?",
    a: "Hover the button and the line under it tells you why. The usual reasons: you already **used** it this turn, you **need more Gold**, it's a once-per-game power that's **spent**, it's **locked** for a few turns, or it's a **passive** power with nothing to press.",
    aliases: ['greyed out', 'disabled', 'not working', 'power locked', 'cant use', 'need gold'],
    seeAlso: ['hero-power-once-per-turn', 'hero-power-cost', 'passive-hero-power'],
  },
  {
    id: 'hero-power-in-combat',
    topic: 'basics',
    q: 'Can I use my hero power during a fight?',
    a: "No. You press your hero power in the shop. Fights play out on their own, though some powers (passive ones especially) can still affect what happens in combat.",
    aliases: ['combat power', 'use in fight', 'battle', 'during combat'],
    seeAlso: ['use-hero-power', 'passive-hero-power'],
  },
  {
    id: 'see-opponent-hero',
    topic: 'basics',
    q: 'Can I see which hero an opponent is playing?',
    a: "Yes. Hover a seat in the lobby list and the scouting card shows their hero, along with their tier, build, recent fights and runes.",
    aliases: ['enemy hero', 'opponent hero', 'scout hero', 'who are they'],
    seeAlso: ['scout-opponent-runes', 'who-do-i-fight'],
  },
];
