import type { WikiEntry } from './types';

// Checked against packages/sim/src/shop.ts (tierSlots, stockPool, rollShop, topUpTavern, drawOfferId, spell slot),
// config.ts (economy, POOL_QUANTITIES, tier ceiling), reducer.ts (buy / sell / roll / freeze / upgrade, turn start,
// checkTriples / pullCopies / combineIntoGolden, grantGoldenDiscover, discover), recruit.ts (sellValueOf,
// offerDiscover, conjureToHand), state.ts (selectRunTribes, handCap), spellPool.ts, heroes.ts (HeroPower),
// packages/content/src/sets.ts, cards/set1/tokens.ts (Triple Reward) and packages/ui/src/Recruit.tsx (turn timer)
// + store.ts (Practice timer) on 2026-09-28.
export const ENTRIES: readonly WikiEntry[] = [
  // ── The shop row ─────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'shop-size-by-tier',
    topic: 'shop',
    q: 'How many minions does the shop show?',
    a: "It depends on your tavern tier: **3** at Tier 1, **4** at Tiers 2 and 3, **5** at Tiers 4 and 5, and **6** at Tier 6. On top of that there's one **spell** slot on the right.",
    aliases: ['shop slots', 'how many cards', 'offers', 'tavern size', 'more slots'],
    seeAlso: ['tavern-tier-cost', 'shop-spell-slot', 'upgrade-does-not-refresh'],
    covers: [{ rule: 'R-SHOP-01', fp: '340af593' }],
  },
  {
    id: 'shop-tiers-offered',
    topic: 'shop',
    q: 'Which tiers of minions can show up in my shop?',
    a: "Anything **at or below** your tavern tier. At Tier 4 you can see Tier 1, 2, 3 and 4 minions all mixed together. You never see a minion from a tier above yours in the shop.",
    aliases: ['higher tier', 'low tier minions', 'what tier', 'shop odds', 'only my tier'],
    seeAlso: ['minion-tier', 'card-pool-copies'],
  },
  {
    id: 'shop-spell-slot',
    topic: 'shop',
    q: 'Does the shop sell spells?',
    a: "Yep, **one** at a time, in the slot on the far right. It only offers spells **at or below** your tavern tier, and only ones that fit your game's tribes (or Neutral ones). Once you buy it, that slot stays empty until the shop refreshes.",
    aliases: ['spell', 'buy spell', 'spell shop', 'spell slot', 'right slot'],
    seeAlso: ['what-things-cost', 'use-a-bought-spell', 'spells-never-run-out'],
    covers: [{ keyword: 'shopspell', fp: '29456d92' }],
  },
  {
    id: 'spells-never-run-out',
    topic: 'shop',
    q: 'Can spells run out like minions do?',
    a: "No. Spells aren't part of the limited minion supply, so the same spell can keep showing up as many times as it likes.",
    aliases: ['spell copies', 'spell pool', 'limited spells'],
    seeAlso: ['card-pool-copies', 'shop-spell-slot'],
  },
  {
    id: 'card-pool-copies',
    topic: 'shop',
    q: 'Is there a limited number of each minion?',
    a: "Yes. Each minion has a set number of copies: **10** for Tier 1, **9** for Tier 2, **8** for Tier 3, **7** for Tier 4, and **6** for Tiers 5 and 6. Copies you own, and copies sitting in your shop right now, are taken out. A minion with no copies left stops appearing until one comes back.",
    aliases: ['pool', 'copies', 'supply', 'run out', 'how many copies', 'deck'],
    seeAlso: ['pool-odds', 'selling-returns-to-pool', 'pool-not-shared'],
  },
  {
    id: 'pool-odds',
    topic: 'shop',
    q: 'If I already own copies of a minion, is it harder to find more?',
    a: "A little, yes. Every copy still left is like one raffle ticket, so the more copies of a minion you've taken out, the rarer it gets. The odds slide gradually, not all at once.",
    aliases: ['odds', 'chance', 'find triples', 'rarer', 'weighted', 'probability'],
    seeAlso: ['card-pool-copies', 'triples'],
    covers: [{ rule: 'R-SHOP-02', fp: '3b3f4662' }],
  },
  {
    id: 'pool-not-shared',
    topic: 'shop',
    q: 'Do other players buy from the same supply of minions as me?',
    a: "No. Your supply of minions is **yours alone**. Nobody else in the lobby can take the copies you're hunting for, so it's only your own buys, sells and refreshes that change it.",
    aliases: ['shared pool', 'contested', 'other players', 'steal cards', 'hate buy'],
    seeAlso: ['card-pool-copies'],
  },
  {
    id: 'selling-returns-to-pool',
    topic: 'shop',
    q: 'When I sell a minion, does it go back into the shop?',
    a: "Its copy goes back into your supply, so it can show up in your shop again later. Selling a **Gilded** minion puts all **three** copies back. Tokens don't go back anywhere, they just vanish.",
    aliases: ['sell back', 'return to pool', 'resell'],
    seeAlso: ['card-pool-copies', 'sell-a-minion', 'what-is-a-token'],
  },
  {
    id: 'refresh-returns-offers',
    topic: 'shop',
    q: 'What happens to the minions I refresh away?',
    a: "They go back into your supply, so you can still find them later. Refreshing just reshuffles which copies are sitting in front of you.",
    aliases: ['reroll', 'refresh', 'lost cards', 'where did it go'],
    seeAlso: ['refresh-and-freeze-buttons', 'card-pool-copies'],
  },
  {
    id: 'shop-auto-refresh',
    topic: 'shop',
    q: 'Does the shop refresh by itself each turn?',
    a: "Yep. Every new turn starts with a **free** fresh shop, spell slot included. The only exception is if you **froze** it, then you get the same cards back (with any empty slots filled in).",
    aliases: ['new shop', 'free refresh', 'turn start', 'restock'],
    seeAlso: ['freeze', 'shop-after-combat'],
  },
  {
    id: 'shop-after-combat',
    topic: 'shop',
    q: 'What happens to my shop while I fight?',
    a: "Nothing, it just waits. When you come back from combat the next turn begins, and you get a brand new shop (or your frozen one).",
    aliases: ['after combat', 'after fight', 'leftover shop'],
    seeAlso: ['shop-auto-refresh', 'freeze'],
  },
  {
    id: 'upgrade-does-not-refresh',
    topic: 'shop',
    q: 'Does upgrading my tavern refresh the shop?',
    a: "No. Your current shop stays exactly as it is. The new tier's minions (and the extra slot, if you get one) show up the next time the shop refreshes, either when you pay to refresh or at the start of next turn.",
    aliases: ['tavern up refresh', 'level up shop', 'upgrade reroll', 'new slot'],
    seeAlso: ['tavern-tier-cost', 'shop-size-by-tier'],
  },
  {
    id: 'freeze-then-tier-up',
    topic: 'shop',
    q: 'If I freeze and then tier up, do I still get the extra shop slot?',
    a: "Yes. Next turn your frozen cards stay put, and any empty slots, including a new one from tiering up, get filled in with fresh cards from your new tier range.",
    aliases: ['freeze upgrade', 'frozen tier up', 'extra slot'],
    seeAlso: ['freeze', 'shop-size-by-tier'],
  },
  {
    id: 'freeze-keeps-spell',
    topic: 'shop',
    q: 'Does Freeze keep the spell too?',
    a: "Yep, the spell slot freezes along with the minions. If you already bought the spell, a new one fills that slot next turn.",
    aliases: ['freeze spell', 'frozen spell'],
    seeAlso: ['freeze', 'shop-spell-slot'],
  },

  // ── Buying, Gold and your hand ───────────────────────────────────────────────────────────────────────────
  {
    id: 'buy-with-full-hand',
    topic: 'shop',
    q: 'Can I buy something when my hand is full?',
    a: "No. Everything you buy goes to your hand first, so with **10 cards** in hand the shop won't let you buy. Heads up: that's true even if the minion would be your third copy. Play something first to make room.",
    aliases: ['full hand', 'hand full', "can't buy", '10 cards', 'buy blocked'],
    seeAlso: ['board-and-hand-size', 'buy-with-full-board'],
  },
  {
    id: 'buy-with-full-board',
    topic: 'shop',
    q: 'Can I buy a minion when my board is full?',
    a: "Yep. Bought minions go to your **hand**, not the board, so a full board doesn't stop you buying. You just can't play it until you free up a spot.",
    aliases: ['full board', '7 minions', 'board full buy'],
    seeAlso: ['board-and-hand-size', 'play-from-hand'],
  },
  {
    id: 'unspent-gold',
    topic: 'shop',
    q: "What happens to Gold I don't spend?",
    a: "It's gone. Your Gold refills to your turn's amount at the start of every turn, and leftovers don't carry over. So it's almost always worth spending it (even on a refresh).",
    aliases: ['save gold', 'bank gold', 'leftover gold', 'carry over', 'interest'],
    seeAlso: ['gold-per-turn', 'gold-above-ten'],
  },
  {
    id: 'gold-above-ten',
    topic: 'shop',
    q: 'Can I ever have more than 10 Gold?',
    a: "Yes. 10 is where your normal income stops growing, but some cards, heroes and runes give you bonus Gold on top, either for one turn or every turn. That bonus isn't capped at 10.",
    aliases: ['max gold', 'gold cap', 'over 10', 'extra gold'],
    seeAlso: ['gold-per-turn', 'unspent-gold'],
  },
  {
    id: 'minion-tier',
    topic: 'shop',
    q: 'What does the tier on a minion mean?',
    a: "It's how strong the minion is and when you can find it. A Tier 3 minion only shows up in your shop once your tavern is **Tier 3 or higher**. Higher tier minions are generally stronger, but they cost the same to buy.",
    aliases: ['tier', 'stars', 'level', 'minion level', 'card tier'],
    seeAlso: ['shop-tiers-offered', 'tavern-tier-cost', 'max-tavern-tier'],
  },
  {
    id: 'max-tavern-tier',
    topic: 'shop',
    q: "What's the highest tavern tier?",
    a: "**Tier 6.** Once you're there, the Tavern Up button is done. A few special effects can reach beyond it, but they'll say so on the card.",
    aliases: ['max tier', 'tier 6', 'tier 7', 'top tier'],
    seeAlso: ['tavern-tier-cost', 'minion-tier'],
  },

  // ── Tribes, tokens, sets ─────────────────────────────────────────────────────────────────────────────────
  {
    id: 'tribes-in-a-game',
    topic: 'shop',
    q: 'Which tribes are in my game?',
    a: "Each game uses the tribes of the current card set, plus **Neutral** minions, which are always in. Right now that's all five of the set's tribes every game: **Kobolds, Dragons, Beasts, Demons and Dwarves**. In Practice you can pick which tribes you want instead.",
    aliases: ['tribes', 'types', 'races', 'minion types', 'kobold', 'dwarf', 'beast', 'demon', 'dragon', 'tribe list', 'kobolds', 'dwarves', 'dragons', 'beasts', 'demons', 'mech', 'undead', 'murloc', 'pirate', 'set tribes'],
    seeAlso: ['tribes-not-in-game', 'neutral-minions', 'card-sets'],
  },
  {
    id: 'tribes-not-in-game',
    topic: 'shop',
    q: "Can I get cards from a tribe that isn't in my game?",
    a: "No. Your shop, your spells and your Discovers only ever offer cards from your game's tribes plus Neutral. The Compendium in a run shows only the cards you can actually find, so you can check there.",
    aliases: ['missing tribe', 'other tribes', 'banned tribe', 'tribe not in game'],
    seeAlso: ['tribes-in-a-game', 'open-compendium'],
  },
  {
    id: 'neutral-minions',
    topic: 'shop',
    q: 'What are Neutral minions?',
    a: "Minions with no tribe. They're in **every** game no matter which tribes are picked, and they fit into any build.",
    aliases: ['neutral', 'no tribe', 'tribeless', 'colorless'],
    seeAlso: ['tribes-in-a-game'],
  },
  {
    id: 'two-tribes',
    topic: 'shop',
    q: 'What about a minion with two tribes?',
    a: "It counts as **both**. It shows up whenever either of its tribes is in the game, and effects that care about either tribe will count it.",
    aliases: ['dual tribe', 'two types', 'both tribes', 'hybrid'],
    seeAlso: ['tribes-in-a-game'],
  },
  {
    id: 'card-to-full-hand',
    topic: 'shop',
    q: 'What happens if an effect gives me a card but my hand is full?',
    a: "Usually the card is just **lost**. A few rewards (like some rune payouts) squeeze in anyway, and a Discover you're in the middle of choosing always keeps its spot, so a random card can't steal it. Keep a slot free if you know cards are coming.",
    aliases: ['hand full', 'lost card', 'overflow hand', 'burned', '10 cards'],
    seeAlso: ['board-and-hand-size', 'discover-full-hand'],
  },
  {
    id: 'card-sets',
    topic: 'basics',
    q: "What's a card set?",
    a: "A set is the whole collection of minions, spells and tribes a game draws from. Everyone plays the same live set, and every so often a new one comes out. A game keeps the set it started with, even if a new set goes live while you're playing.",
    aliases: ['set', 'expansion', 'season', 'which cards', 'set 2', 'set 3'],
    seeAlso: ['tribes-in-a-game'],
  },

  // ── Discover ─────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'discover-tier',
    topic: 'shop',
    q: 'What tier are the cards I Discover?',
    a: "Normally anything **at or below your tavern tier**, all equally likely, and only from your game's tribes plus Neutral. The three choices are always different cards. Some cards say otherwise (like \"Discover a Tier 3\" or \"a Beast\"), and the **Triple Reward** looks **one tier above** yours.",
    aliases: ['discover tier', 'discover odds', 'what can i discover'],
    seeAlso: ['discover', 'triple-reward-timing'],
  },
  {
    id: 'discover-completes-triple',
    topic: 'shop',
    q: 'Can a Discover give me my third copy?',
    a: "Yep! If the card you pick is your third copy, it combines into the Gilded version right away, just like if you'd bought it.",
    aliases: ['discover triple', 'discover golden'],
    seeAlso: ['discover', 'triple-any-route'],
  },
  {
    id: 'discover-full-hand',
    topic: 'shop',
    q: 'What if I Discover with a full hand?',
    a: "The pick is lost, since the card has nowhere to go. Make room before you play a card that Discovers.",
    aliases: ['discover hand full', 'lost discover'],
    seeAlso: ['card-to-full-hand', 'discover'],
  },

  // ── Triples / Gilded ─────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'triple-reward-timing',
    topic: 'shop',
    q: 'Should I tier up before playing my Gilded minion?',
    a: "Often, yes! You get the **Triple Reward** when you **play** the Gilded minion, and it's locked to one tier above whatever your tavern tier is at that moment. Tiering up afterwards won't improve it. So if you're about to tier up anyway, do that first.",
    aliases: ['triple reward', 'discover spell', 'golden discover', 'when to play golden'],
    seeAlso: ['triples', 'discover-tier'],
  },
  {
    id: 'triple-reward-at-max-tier',
    topic: 'shop',
    q: 'What does a Triple Reward give me at Tier 6?',
    a: "It can't go higher than the top, so it offers **Tier 6** minions (and fills in with lower tiers only if there aren't enough to choose from).",
    aliases: ['triple reward tier 6', 'max tier discover'],
    seeAlso: ['triple-reward-timing', 'max-tavern-tier'],
  },
  {
    id: 'triple-reward-no-triple',
    topic: 'shop',
    q: 'Do three Triple Rewards combine into something?',
    a: "No. Triple Reward cards never combine, so you can hold as many as you like and use each one.",
    aliases: ['triple reward stack', 'three discovers'],
    seeAlso: ['triple-reward-timing'],
  },
  {
    id: 'triple-across-hand-and-board',
    topic: 'shop',
    q: 'Do all three copies need to be on my board for a triple?',
    a: "No. Copies on your **board and in your hand** both count, in any mix. Three in hand works too. The moment you hold the third copy, they combine.",
    aliases: ['triple in hand', 'copies in hand', 'where do copies need to be'],
    seeAlso: ['triples', 'triple-uses-board-first'],
  },
  {
    id: 'triple-uses-board-first',
    topic: 'shop',
    q: 'If I have extra copies, which ones get used for the triple?',
    a: "Copies on your **board** get used first (left-most first), and only then copies from your hand (the newest one first). Any spare copy stays where it was. The Gilded minion keeps the stats of the best two copies used, plus their buffs.",
    aliases: ['which copies', 'extra copy', 'fourth copy', 'triple order'],
    seeAlso: ['triple-across-hand-and-board', 'triples'],
    covers: [{ rule: 'R-GILD-03', fp: '2840b201' }],
  },
  {
    id: 'gilded-where-it-goes',
    topic: 'shop',
    q: 'Where does my Gilded minion go after a triple?',
    a: "Into your **hand**, ready to play (that's when you get your Triple Reward). If your hand is full, it goes straight onto your board instead, so it's never lost.",
    aliases: ['golden hand', 'where is my golden'],
    seeAlso: ['triples', 'triple-reward-timing'],
  },
  {
    id: 'gilded-no-second-triple',
    topic: 'shop',
    q: 'Does a Gilded minion count toward another triple?',
    a: "No. Only regular copies count. A Gilded minion plus two more regular copies won't combine. You'd need three fresh regular copies to make a second Gilded one.",
    aliases: ['golden triple', 'second golden', 'double golden', 'gilded copy'],
    seeAlso: ['triples', 'gilded-sell-value'],
  },
  {
    id: 'gilded-sell-value',
    topic: 'shop',
    q: 'Can I sell a Gilded minion, and how much do I get?',
    a: "Yep, it sells like any other minion, usually for **1 Gold**. All three of its copies go back into your supply.",
    aliases: ['sell golden', 'sell gilded', 'golden sell price'],
    seeAlso: ['what-things-cost', 'selling-returns-to-pool'],
  },
  {
    id: 'triple-any-route',
    topic: 'shop',
    q: "Does a triple still happen if the third copy wasn't bought?",
    a: "Yes. However the copy reaches you (bought, Discovered, copied, summoned, or handed to you when you sell something), if it's your third it combines on the spot and pays out the Triple Reward like normal.",
    aliases: ['copy triple', 'summon triple', 'free triple', 'sell triple'],
    seeAlso: ['discover-completes-triple', 'triples'],
    covers: [{ rule: 'R-SHOP-03', fp: '43378226' }],
  },
  {
    id: 'spells-never-gilded',
    topic: 'shop',
    q: 'Can I triple a spell?',
    a: "No. Spells never combine and there's no such thing as a Gilded spell. Three copies of a spell are just three spells to cast.",
    aliases: ['golden spell', 'triple spell', 'gilded spell'],
    seeAlso: ['triples', 'use-a-bought-spell'],
    covers: [{ rule: 'R-GILD-02', fp: '4cf9aa2f' }],
  },

  // ── Spells ───────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'use-a-bought-spell',
    topic: 'shop',
    q: 'How do I use a spell I bought?',
    a: "It goes to your hand. Drag it up out of your hand to cast it; you already paid when you bought it, so casting is free. If it targets a minion, drop it on one. Some spells can even buff a minion still sitting in the shop, and it keeps that buff when you buy it. If there's no valid target, the spell just stays in your hand.",
    aliases: ['cast', 'use spell', 'play spell', 'target spell', 'spell fizzle'],
    seeAlso: ['shop-spell-slot', 'sell-spells'],
  },
  {
    id: 'sell-spells',
    topic: 'shop',
    q: 'Can I sell a spell?',
    a: "No, spells can't be sold. They're only for casting. So think before you buy one you might not use.",
    aliases: ['sell spell', 'refund spell', 'get rid of spell'],
    seeAlso: ['what-things-cost', 'use-a-bought-spell'],
    covers: [{ keyword: 'shopspell', fp: '29456d92' }],
  },

  // ── Turn timer ───────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'turn-timer-length',
    topic: 'shop',
    q: 'How long is my shop turn?',
    a: "About **21 seconds** on turn 1, then roughly **4 seconds more** each turn, with bigger jumps on turns **6** and **12**. It tops out at about a **minute and a half**. In a lobby or Practice the clock only starts once you've spent **10 Gold** in the turn (the **Gold Fuse**), and it never starts before the screen comes back from combat.",
    aliases: ['timer', 'turn length', 'how much time', 'seconds', 'clock'],
    seeAlso: ['timer-runs-out', 'more-time-to-think', 'bronze-timer'],
    covers: [{ rule: 'R-SOT-TIMER-01', fp: '1c2bc9e9' }],
  },
  {
    id: 'more-time-to-think',
    topic: 'shop',
    q: 'Can I get more time to think?',
    a: "In **Practice**, yes. You can stretch the turn timer up to 4 times longer, or switch it off completely. The timer in ranked games can't be changed, but it only starts once you've spent 10 Gold in a turn (the **Gold Fuse**).",
    aliases: ['more time', 'no timer', 'unlimited time', 'slow timer', 'practice mode'],
    seeAlso: ['turn-timer-length', 'timer-runs-out', 'bronze-timer'],
  },

  // ── Basics ───────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'turn-and-round',
    topic: 'basics',
    q: "What's a turn? Is a round the same thing?",
    a: "Yep, same thing. A turn is one **shop phase** (buy, sell, set up your board) plus the **fight** that follows it. Then the next turn starts with more Gold and a fresh shop.",
    aliases: ['turn', 'round', 'wave', 'phase', 'shop phase', 'combat phase'],
    seeAlso: ['this-turn-meaning', 'goal-of-the-game'],
  },
  {
    id: 'this-turn-meaning',
    topic: 'basics',
    q: 'When a card says "this turn", when does that end?',
    a: "At the start of your **next** shop turn. \"This turn\" covers your shop phase **and** the fight right after it, so something you set up in the shop can still pay off in that fight.",
    aliases: ['this turn', 'until end of turn', 'expires', 'per turn'],
    seeAlso: ['turn-and-round'],
    covers: [{ rule: 'R-TURN-01', fp: '61026a27' }],
  },
  {
    id: 'attack-and-health',
    topic: 'basics',
    q: 'What do the two numbers on a minion mean?',
    a: "**Attack** is how much damage it deals when it fights. **Health** is how much damage it can take before it dies. When two minions fight, each one hits the other for its Attack.",
    aliases: ['stats', 'attack', 'health', 'numbers', 'hp', 'damage', 'atk'],
    seeAlso: ['what-is-a-buff', 'minions-after-combat'],
  },
  {
    id: 'minions-after-combat',
    topic: 'basics',
    q: 'Do my minions stay damaged or dead after a fight?',
    a: "No. Fights happen on a copy of your board. Once it's over, every minion is back, at full Health, ready for next turn. Only things a card says are permanent stick around.",
    aliases: ['dead minions', 'heal', 'damage stays', 'lost minions', 'respawn'],
    seeAlso: ['are-buffs-permanent', 'attack-and-health'],
  },
  {
    id: 'what-is-a-buff',
    topic: 'basics',
    q: "What's a buff?",
    a: "Any bonus to a minion's Attack or Health (like **+2/+1**, meaning +2 Attack and +1 Health), or a keyword it gains. Buffed numbers change colour on the card, and right-clicking a minion lists every buff and where it came from.",
    aliases: ['buff', 'stats up', '+1/+1', 'green numbers', 'bonus stats'],
    seeAlso: ['are-buffs-permanent', 'inspect-a-card'],
  },
  {
    id: 'are-buffs-permanent',
    topic: 'basics',
    q: 'Are buffs permanent?',
    a: "Buffs a minion gets in the **shop** stay for the rest of the game. Buffs it gets **during a fight** usually only last for that fight, unless the minion has **Engraved** or the card says it's permanent. Buffs on a card **in your hand** always stick, even if they land mid-fight.",
    aliases: ['permanent', 'temporary', 'keep buffs', 'combat buffs', 'lose stats', 'engraved'],
    seeAlso: ['what-is-a-buff', 'minions-after-combat'],
    covers: [{ keyword: 'permanent', fp: '32993c18' }, { keyword: 'engraved', fp: '5c0422d8' }, { rule: 'R-HAND-02', fp: 'd7ad0466' }],
  },
];
