/**
 * @game/rules — the ASCENT rulebook registry (the owner's Complete Rulebook blueprint, first increment).
 *
 * Three tiers, one API:
 *  · APPROVED_RULES  — hand-authored, each on an explicit owner ruling, evidence cited.
 *  · PENDING_RULES   — generated by `npm run rules:seed` from Doc Bot's live queues (274 verified-reachable
 *                      questions at seed time; regenerate any time, decisions survive).
 *  · MANUAL_PENDING  — hand-authored pending questions (registry/pendingManual.ts) that no scan can generate
 *                      (family-policy proposals, cross-boundary judgement calls); NEVER touched by the seeder,
 *                      decided through the same board and decisions.json.
 *  · DECISIONS       — the owner's clicks from the DEV MENU → Rulebook triage board (decisions.json, written
 *                      by the dev-server endpoint), or hand entries from chat rulings.
 *
 * `allRules()` folds decisions in; a pending item the owner approved reads as `approved` everywhere, and Doc
 * Bot lanes can begin citing rule ids instead of pinned comments.
 */
import decisionsJson from './registry/decisions.json';
import { APPROVED_RULES } from './registry/approved';
import { PENDING_RULES } from './registry/pending.generated';
import { MANUAL_PENDING } from './registry/pendingManual';
import { CONVENTION_PENDING } from './registry/pendingConventions.generated';
import { WORDING_PENDING } from './registry/pendingWording.generated';
import { INTERACTION_PENDING } from './registry/pendingInteractions.generated';
import { effectiveStatus, type DecisionMap, type GameRule, type RuleDecision, type RuleStatus } from './schema';
import { enforcementOf } from './enforcement';

export * from './schema';
export { APPROVED_RULES } from './registry/approved';
export { PENDING_RULES } from './registry/pending.generated';
export { MANUAL_PENDING } from './registry/pendingManual';
export { CONVENTION_PENDING } from './registry/pendingConventions.generated';
export { WORDING_PENDING } from './registry/pendingWording.generated';
export { LANGUAGE_GUIDE, LANGUAGE_GUIDE_INDEX, LANGUAGE_GUIDE_VERSION, type LanguageGuideEntry, type LanguageGuideTopic, type LanguageGuidePredicate } from './languageGuide';
export { INTERACTION_PENDING } from './registry/pendingInteractions.generated';
export { RETIRED_RULES, RETIRED_IDS, type RetiredRule } from './registry/retired';
export { AUTO_RETIRED_RULES, AUTO_RETIRED_IDS } from './registry/retired.generated';
export {
  ENFORCEMENT_LANES, RULE_ENFORCEMENT, enforcementOf, enforcementErrors, unenforcedApproved,
  type EnforcementLane, type EnforcementCheckEnv,
} from './enforcement';
export { applySeedHygiene, type SeedHygieneInput, type SeedHygieneResult } from './seedSupport';
export {
  PARKED_CLASSES, PARKED_CLASS_IDS, PARKED_REASON, PARKED_RETIRED_RULE_IDS, isParked, parkedClassForFamily,
  parkedClassForFlag, parkedClassForTribe, parkedClassForTrigger, parkedClassOf, parkedSkipReason,
  type ParkedClass, type ParkedReason, type ParkedSubject,
} from './parked';
export { ruleImpact, enforcementFiles, type RuleImpactInput, type RuleImpactReport, type TouchedRule } from './ruleImpact';
export { rulesRevision } from './registryHash';

export const DECISIONS: DecisionMap = decisionsJson as DecisionMap;

export interface ResolvedRule extends GameRule {
  effective: RuleStatus;
  decision?: RuleDecision;
}

export function allRules(): ResolvedRule[] {
  return [...APPROVED_RULES, ...PENDING_RULES, ...MANUAL_PENDING, ...CONVENTION_PENDING, ...WORDING_PENDING, ...INTERACTION_PENDING].map((r) => {
    const enforcement = enforcementOf(r);
    return {
      ...r,
      effective: effectiveStatus(r, DECISIONS),
      ...(DECISIONS[r.id] ? { decision: DECISIONS[r.id] } : {}),
      ...(enforcement ? { enforcement } : {}),
    };
  });
}

/** The board's worklist: still-undecided pending rules. */
export function undecided(): ResolvedRule[] {
  return allRules().filter((r) => r.effective === 'needs-ruling');
}
