/**
 * @game/rules — the ASCENT rulebook registry (the owner's Complete Rulebook blueprint, first increment).
 *
 * Three tiers, one API:
 *  · APPROVED_RULES  — hand-authored, each on an explicit owner ruling, evidence cited.
 *  · PENDING_RULES   — generated by `npm run rules:seed` from Doc Bot's live queues (274 verified-reachable
 *                      questions at seed time; regenerate any time, decisions survive).
 *  · DECISIONS       — the owner's clicks from the DEV MENU → Rulebook triage board (decisions.json, written
 *                      by the dev-server endpoint), or hand entries from chat rulings.
 *
 * `allRules()` folds decisions in; a pending item the owner approved reads as `approved` everywhere, and Doc
 * Bot lanes can begin citing rule ids instead of pinned comments.
 */
import decisionsJson from './registry/decisions.json';
import { APPROVED_RULES } from './registry/approved';
import { PENDING_RULES } from './registry/pending.generated';
import { effectiveStatus, type DecisionMap, type GameRule, type RuleDecision, type RuleStatus } from './schema';

export * from './schema';
export { APPROVED_RULES } from './registry/approved';
export { PENDING_RULES } from './registry/pending.generated';

export const DECISIONS: DecisionMap = decisionsJson as DecisionMap;

export interface ResolvedRule extends GameRule {
  effective: RuleStatus;
  decision?: RuleDecision;
}

export function allRules(): ResolvedRule[] {
  return [...APPROVED_RULES, ...PENDING_RULES].map((r) => ({
    ...r,
    effective: effectiveStatus(r, DECISIONS),
    ...(DECISIONS[r.id] ? { decision: DECISIONS[r.id] } : {}),
  }));
}

/** The board's worklist: still-undecided pending rules. */
export function undecided(): ResolvedRule[] {
  return allRules().filter((r) => r.effective === 'needs-ruling');
}
