/**
 * LANGUAGE GUIDE — the versioned style registry for printed card/rune/power text (Doc Bot 2.0 WP E;
 * blueprint §11.3). How things are WORDED, as distinct from what they DO (that is the rulebook +
 * contracts).
 *
 * WP E grew the v0 seed (LG-TWICE-01 / LG-COPY-01) into the full §11.3 topic set. Every rule is SEEDED
 * from measured evidence — the 2026-08-27 corpus survey (1059 printed texts: cards + gilded texts +
 * runes + hero powers) whose counts each entry quotes — or from a standing owner ruling. Doctrine,
 * mirrored from the rulebook:
 *
 *  · 'seeded' entries are Claude-recorded readings of majority usage / owner statements, cited in
 *    evidence; 'approved' requires an explicit owner decision on the guide entry itself. The Sitting-3
 *    wording deck (pendingWording.generated.ts, regenerated by `npm run docbot:text`) asks exactly the
 *    rules whose corpus usage is INCONSISTENT — the owner picks the canon; the deck self-retires as the
 *    text becomes consistent.
 *  · Ids are stable (`LG-<TOPIC>-<NN>`) and never recycled.
 *  · `predicate` makes a rule machine-checkable: the WP E rewrite advisor flags texts matching
 *    `deprecated` and proposes `canonical` — recommendations ONLY, never applied (§23). Predicates are
 *    given only where the canon is settled (an owner ruling or a shipped vocabulary decision), never on
 *    a rule the Sitting-3 deck is still asking about.
 *  · RESERVED: the Rise/Reborn split is the owner's own in-flight Rebirth rename — recorded, never
 *    advised on, never asked about (WP E brief).
 */
import type { RuleEvidence } from './schema';

export const LANGUAGE_GUIDE_VERSION = 1;

export type LanguageGuideTopic =
  | 'multiplier-wording' // how extra fires are printed
  | 'copy-wording' // plain vs exact copies
  | 'counter-wording' // live values + countdowns (the CLAUDE.md live-text rule's wording half)
  | 'keyword-wording' // keyword display names + phrasing
  | 'trigger-wording' // trigger display names + punctuation
  | 'zone-terms' // Shop / hand / board vocabulary
  | 'verb-usage' // get / play / cast / summon / buy / sell / trigger
  | 'gain-give' // gain for self vs give for another
  | 'duration-wording' // permanently / this turn / this run
  | 'scope-wording' // wherever-they-are reach
  | 'numerals' // digits vs spelled counts, units
  | 'positional-wording' // left-most / right-most / adjacent / opposite
  | 'clause-order' // trigger → target → action → amount → duration/limit
  | 'limits-wording' // once per X, (N max), up to N
  | 'improvement-wording' // Improve this by +X/+X per N
  | 'plural-agreement' // counts agree with their nouns
  | 'pronouns' // this / it scope
  | 'aura-wording' // while-on-your-board effects
  | 'combat-only-wording' // combat-gated phrasing
  | 'gilding-wording' // Gilded terminology
  | 'general';

/** A machine-checkable predicate: text matching `deprecated` (a regex source) violates the rule; the
 *  advisor's proposed replacement swaps the match for `canonical` (mechanics preserved — pure renames). */
export interface LanguageGuidePredicate {
  deprecated: string;
  canonical: string;
  /** Extra applicability gate: 'non-stacking-multiplier' consults CardDef.triggerMultiplier. */
  appliesTo?: 'all' | 'non-stacking-multiplier';
}

export interface LanguageGuideEntry {
  /** Stable, never recycled: `LG-<TOPIC>-<NN>`. */
  id: string;
  topic: LanguageGuideTopic;
  /** The style rule, stated so a parser can test text against it and an advisor can cite it. */
  rule: string;
  /** One concrete compliant example (and, where useful, the non-compliant shape it replaces). */
  example?: string;
  evidence: RuleEvidence[];
  status: 'seeded' | 'approved';
  /** Present only where the canon is settled — the rewrite advisor's lever. */
  predicate?: LanguageGuidePredicate;
  /** Both spellings are live and the owner has NOT picked — the Sitting-3 deck asks; the advisor waits. */
  contested?: boolean;
  /** The owner's own rename is in flight — record only; no question, no advice. */
  reserved?: boolean;
}

const survey = (quote: string): RuleEvidence =>
  ({ kind: 'docbot-scan', ref: 'textParse corpus survey 2026-08-27 (1059 printed texts)', quote });

export const LANGUAGE_GUIDE: LanguageGuideEntry[] = [
  // ── v0 seeds, carried forward unchanged ──────────────────────────────────────────────────────────────
  {
    id: 'LG-TWICE-01',
    topic: 'multiplier-wording',
    rule: 'A NON-STACKING effect that fires something one extra time prints "Twice" / "twice" — never "an additional time", which reads as if copies stack. Stacking multipliers may print "+1 more time" per copy.',
    example: 'Rune of Fury: "Your Avenge effects trigger twice." (compliant). Zyff: "Your Battlecries and Deathrattles trigger an additional time." (the flagged non-stacker shape — the wording-recommendation exemplar).',
    evidence: [
      { kind: 'owner-chat', ref: 'docs/docbot2/vertical-slice-report.md', quote: 'owner flag: non-stackers should say "Twice"' },
      { kind: 'docbot-scan', ref: 'verticalSlice wording-recommendation finding (zyff)' },
    ],
    status: 'seeded',
    predicate: { deprecated: '\\ban additional time\\b', canonical: 'twice', appliesTo: 'non-stacking-multiplier' },
  },
  {
    id: 'LG-COPY-01',
    topic: 'copy-wording',
    rule: 'An unmarked "copy" means a PLAIN copy (base card: no buffs, counters, or gilding — R-COPY-01). Text for an effect that copies the full instance (stats, buffs, gilding, accrued counters — R-COPY-02) must say "exact copy". A copy effect whose printed text says only "a copy" while behaving exact is a text defect.',
    example: 'Bellringer: "get a plain copy of the minion to the left" (compliant). Xerox\'s "Summon a copy of a friendly minion" while the ruled behaviour is exact — the slice\'s verified-text-defect exemplar.',
    evidence: [
      { kind: 'owner-handoff', ref: 'R-COPY-01 / R-COPY-02 (registry/approved.ts)' },
      { kind: 'docbot-scan', ref: 'verticalSlice verified-text-defect finding (hero:xerox)' },
    ],
    status: 'seeded',
  },

  // ── WP E — trigger display names (contested: the Sitting-3 deck asks) ────────────────────────────────
  {
    id: 'LG-TRIGGER-01',
    topic: 'trigger-wording',
    rule: 'The on-play trigger prints as "Shout" (the shipped vocabulary), never "Battlecry". Both are live today — the canon is a Sitting-3 pick.',
    example: 'Cinder: "Shout: give your Shop spells +1 Health." vs Joker: "Battlecry: Discover a Tier 5 minion." — one name must win.',
    evidence: [survey('Shout ×112 texts vs Battlecry ×44 texts — both live')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-TRIGGER-02',
    topic: 'trigger-wording',
    rule: 'The on-death trigger prints as "Echo", never "Deathrattle". Both are live today — the canon is a Sitting-3 pick.',
    example: 'Grim: "Echo: give your Beasts +8/+8 wherever they are." vs Pack: "Deathrattle: summon two 1/1 Pups."',
    evidence: [survey('Echo ×94 texts vs Deathrattle ×55 texts — both live')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-TRIGGER-03',
    topic: 'trigger-wording',
    rule: 'A named trigger is bold, capitalized, and ends with a colon before its effect clause: "**Shout:** …", "**Avenge (3):** …". Conditional triggers read "When/Whenever/After …," with a comma.',
    example: '"**Avenge (3):** get a random Shop spell." · "When you buy a minion, give your minions +1/+1."',
    evidence: [survey('the colon-prefix and comma-conditional shapes are near-universal across the corpus')],
    status: 'seeded',
  },

  // ── keyword display names ────────────────────────────────────────────────────────────────────────────
  {
    id: 'LG-KEYWORD-01',
    topic: 'keyword-wording',
    rule: 'The shield keyword prints as "Ward" (vocab rework, PR #505). "Divine Shield" is deprecated.',
    example: 'Karwind: "Ward. Whenever a Shout triggers, …" (compliant). Selfless: "give a friend a Divine Shield" (deprecated).',
    evidence: [
      { kind: 'owner-handoff', ref: 'vocab rework PR #505 (2026-07-17) — display renames shipped' },
      survey('Ward ×44 texts vs Divine Shield ×2 texts (selfless plain+gilded)'),
    ],
    status: 'seeded',
    predicate: { deprecated: '\\bDivine Shield\\b', canonical: 'Ward' },
  },
  {
    id: 'LG-KEYWORD-02',
    topic: 'keyword-wording',
    rule: 'RESERVED — the Rise/Reborn split (Rise ×13, Reborn ×4) is the owner\'s own in-flight Rebirth rename. Recorded here so the split is visible; no advice, no Sitting question, no rename by any agent.',
    example: 'Mumi: "give a friendly Undead Rise." · Anubis: "Give your minions Reborn." — left exactly as printed until the owner\'s rename lands.',
    evidence: [survey('Rise ×13 texts vs Reborn ×4 texts — both live; rename reserved to the owner')],
    status: 'seeded',
    reserved: true,
  },
  {
    id: 'LG-KEYWORD-03',
    topic: 'keyword-wording',
    rule: 'Keyword names are capitalized wherever they appear ("Taunt", "Ward", "Flurry", "Consume") and bold on their granting clause. The double-attack keyword prints as "Flurry" (Windfury ×0 in text).',
    example: '"summon two 1/1 Gemheart Golems with Taunt" · Impala: "Flurry. Ward. Critical Strike (50%)."',
    evidence: [survey('capitalized keyword names are universal; Flurry ×8 vs Windfury ×0')],
    status: 'seeded',
  },

  // ── zones, gilding, durations, scope (contested pairs feed the deck) ─────────────────────────────────
  {
    id: 'LG-ZONE-01',
    topic: 'zone-terms',
    rule: 'The buy row is "the Shop" ("Shop spell", "Shop tier", "in the Shop"). "tavern" is legacy vocabulary — nine texts still print it.',
    example: '"Refresh the Shop" (majority) vs Lasso: "Steal a random minion from the tavern." (legacy).',
    evidence: [survey('Shop ×204 texts vs tavern ×9 texts')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-GILD-01',
    topic: 'gilding-wording',
    rule: 'The upgraded state is "Gilded" in printed text; "Golden"/"golden" is the legacy name. Both are live — a Sitting-3 pick (the internal flag and summon-badge convention stay untouched either way).',
    example: 'Second Draft: "Return a friendly non-Gilded minion to your hand." vs Goldcrafter: "Make a friendly minion golden."',
    evidence: [survey('Gilded ×8 texts vs Golden/golden ×7 texts')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-DURATION-01',
    topic: 'duration-wording',
    rule: 'Run-long effects say "this run" / "for the rest of the run" — the product\'s own noun — never "this game". Both are live today.',
    example: 'Bane: "give your Imps +3/+3 this run." vs Impoverseer: "Your Imps gain +2/+1 this game."',
    evidence: [survey('run-wording ×10 texts vs game-wording ×14 texts — both live')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-DURATION-02',
    topic: 'duration-wording',
    rule: 'Shop-phase stat grants are permanent by default and say nothing; a grant that outlives its default scope says so explicitly ("permanently" for combat-time grants that stick, "this turn"/"next combat only" for shorter ones).',
    example: 'Sandbag: "When this takes damage, it gains +1 Attack permanently." · Fleeting Vigor: "give your minions +2/+1 (next combat only)."',
    evidence: [survey('permanently ×40 · this turn ×33 · next combat ×13 — each marks a departure from the default')],
    status: 'seeded',
  },
  {
    id: 'LG-SCOPE-01',
    topic: 'scope-wording',
    rule: 'A grant that reaches copies beyond the board says "wherever they are" (majority); "everywhere" is the minority variant. One phrase should win.',
    example: 'Deathswarmer: "Give your Undead +1 Attack wherever they are." vs Lantern of Souls: "Your Undead get +3 Attack everywhere."',
    evidence: [survey('wherever-they-are ×15 texts vs everywhere ×3 texts')],
    status: 'seeded',
    contested: true,
  },

  // ── verbs ────────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'LG-VERB-01',
    topic: 'verb-usage',
    rule: 'Effects "trigger" — the near-universal verb. "fire" and "proc" are stragglers (three cards).',
    example: 'Chronos: "Your End of Turn effects trigger 1 more time." vs Drummer: "Your Battlecries fire 1 more time." vs Sylus: "your Deathrattles proc 1 more time."',
    evidence: [survey('trigger(s) ×98 texts vs fire(s) ×2 (drummer) + proc(s) ×4 (sylus, graverobber)')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-VERB-02',
    topic: 'verb-usage',
    rule: 'Verb roles: "buy"/"sell" are Shop transactions; "play" moves a card from hand; "cast" is for spells only; "summon" puts a minion into play without playing it; "get"/"add" acquire cards ("add … to your hand" when the destination matters).',
    example: '"When you buy a minion, …" · "Cast Lasso." · "Summon a Footman." · "get a random Tier 1 minion."',
    evidence: [survey('the five verb roles are consistent across the corpus (get ×143, cast/play/summon/buy/sell each in role)')],
    status: 'seeded',
  },
  {
    id: 'LG-VERB-03',
    topic: 'gain-give',
    rule: '"gain" is for SELF ("this gains", "you gain Gold"); "give" is for ANOTHER target ("give your Beasts", "give a friendly minion"). A grant clause never mixes them.',
    example: 'Sandbag: "it gains +1 Attack" (self) · Broker: "give your minions +1/+1" (others).',
    evidence: [survey('gain ×110 (self/resource) vs give ×231 (another target) — roles consistent')],
    status: 'seeded',
  },
  {
    id: 'LG-VERB-04',
    topic: 'verb-usage',
    rule: 'The eat mechanic is the keyword verb "Consume" (capitalized). Lower-case "devour" appears twice as flavor — mechanic clauses use Consume.',
    example: 'Abyssal Feeder: "adjacent minions each Consume a Fodder." vs the Devour spell\'s "Devour a friendly minion…".',
    evidence: [survey('Consume ×23 texts vs devour ×2 (fred flavor, the devour spell)')],
    status: 'seeded',
    contested: true,
  },

  // ── numerals + units ─────────────────────────────────────────────────────────────────────────────────
  {
    id: 'LG-NUMERAL-01',
    topic: 'numerals',
    rule: 'Money prints as "N Gold" — never the "Ng" abbreviation (two texts).',
    example: 'Hoard Whelp: "Sell: get 6 Gold." vs Trail Forager: "Sells for 3g, plus 1g for every Beast you play."',
    evidence: [survey('"N Gold" ×87 texts vs "Ng" ×2 (trailforager plain+gilded)')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-NUMERAL-02',
    topic: 'numerals',
    rule: 'Stats, Gold, tiers and thresholds are digits ("+2/+3", "Avenge (3)", "6 Gold"). Small counts of summoned/granted things may be spelled ("two 1/1 Pups") — but a card and its gilded text keep ONE style.',
    example: 'Pack: "summon two 1/1 Pups" → gilded "summon four 1/1 Pups" (consistent). Broodmother: "summon 2 Violet Whelps" (digits — also fine).',
    evidence: [survey('spelled small counts ×34 texts beside digit counts — mixed, style-per-card is the seeded floor')],
    status: 'seeded',
  },

  // ── positions, order, limits, improvement, plural, pronouns, aura, combat-only ───────────────────────
  {
    id: 'LG-POSITION-01',
    topic: 'positional-wording',
    rule: 'Positional words are hyphenated: "left-most" / "right-most" (majority 81); "leftmost"/"rightmost" appear in three texts. "adjacent" and "opposite" are bare.',
    example: 'Foreman: "your left-most minion…" vs Deathsayer: "trigger your leftmost Deathrattle."',
    evidence: [survey('left-/right-most ×81 texts vs leftmost ×3 (deathsayer, gravebody); rightmost ×0')],
    status: 'seeded',
    contested: true,
  },
  {
    id: 'LG-ORDER-01',
    topic: 'clause-order',
    rule: 'Standard clause order: trigger, then target, then action + amount, then duration/limit tail. ("**Shout:** give your Dragons +2/+2 this turn (2 max).")',
    example: 'Emissary: "Taunt. Battlecry: give a friendly Dragon +2/+2." — trigger → target → action+amount.',
    evidence: [survey('the dominant clause shape across all parsed sentences')],
    status: 'seeded',
  },
  {
    id: 'LG-LIMIT-01',
    topic: 'limits-wording',
    rule: 'Trigger limits print explicitly, at the clause tail: "once per turn/combat", "(N max)", "up to N … a combat", "the first N …". An undisplayed limit is a text defect, not a style choice.',
    example: 'Ropewrangler: "Casts an additional time per 6 Gold spent this turn (5 max)." · Gryphon: "— up to 4 hits a combat."',
    evidence: [survey('once per ×8 · (N max) / up to N shapes across the corpus')],
    status: 'seeded',
  },
  {
    id: 'LG-IMPROVE-01',
    topic: 'improvement-wording',
    rule: 'Escalating effects print "Improve(s) (this) by +X/+X per/every N <events>" — and the printed magnitude is the LIVE value (the CLAUDE.md live-text law), with the countdown where one exists.',
    example: 'Mama Bear: "give it +2/+2 — and improve this by +2/+2." · Guel: "improving by +1/+1 per 4 Shop spells cast".',
    evidence: [
      { kind: 'owner-handoff', ref: 'CLAUDE.md live-text rule (2026-07-02, reaffirmed 2026-07-08)' },
      survey('the Improve-by shape is the standing escalation wording'),
    ],
    status: 'seeded',
  },
  {
    id: 'LG-PLURAL-01',
    topic: 'plural-agreement',
    rule: 'Counts agree with their nouns, including in gilded text: "summon two 1/1 Strays", not "two 1/1 Stray". A gilded count that doubles pluralizes its noun.',
    example: 'Alley: "summon a 1/1 Stray" → gilded "summon two 1/1 Strays". Deathless Hand: "Summon a Footman" → "Summon 2 Footmen".',
    evidence: [survey('plural agreement holds across the summon corpus')],
    status: 'seeded',
  },
  {
    id: 'LG-PRONOUN-01',
    topic: 'pronouns',
    rule: '"this" (or "this minion") is the printed card itself; "it" is the clause\'s most recent target. "they" only for an unambiguous plural target already named in the sentence.',
    example: 'Raptor: "When a friendly Beast attacks, give it +3/+1." — "it" is the attacker just named.',
    evidence: [survey('the this/it split is consistent across the corpus')],
    status: 'seeded',
  },
  {
    id: 'LG-AURA-01',
    topic: 'aura-wording',
    rule: 'A continuous while-present effect opens "While on your board, …" (the Aura shape). Passive statements without the prefix are reserved for combat-passives on the body itself.',
    example: 'Lazarus: "While on your board, shop spells cost 1 less." · Heckbinder: "While on your board, your Fodder gets +3/+3."',
    evidence: [survey('While-on-your-board is the aura prefix across lazarus/moneybot/heckbinder')],
    status: 'seeded',
  },
  {
    id: 'LG-COMBAT-01',
    topic: 'combat-only-wording',
    rule: 'A combat-gated effect says so up front: a combat trigger word (Start of Combat, Rally, Slaughter, Avenge, Echo) or the "In combat," prefix. Shop-only clauses say "in the Shop".',
    example: 'Sylus: "In combat, your Deathrattles proc 1 more time." · Pack Leader: "… for each Beast played in the Shop …".',
    evidence: [survey('In-combat prefix ×37 texts; in-the-Shop gate on shop-only clauses')],
    status: 'seeded',
  },
];

export const LANGUAGE_GUIDE_INDEX: Readonly<Record<string, LanguageGuideEntry>> =
  Object.fromEntries(LANGUAGE_GUIDE.map((e) => [e.id, e]));
