/* AUTO-GENERATED by `npm run bot:learn` — do not edit by hand.
 * STUB: no rollout data has been fit yet. Empty tables make every lookup fall back gracefully. */
export interface WaveStats { mean: number[]; scale: number[] }
export const RUN_VALUE: { waves: Record<string, WaveStats>; w: number[]; b: number; testR: number } =
  { waves: {}, w: [], b: 0, testR: 0 };
export const QUEST_VALUE: Record<string, number> = {};
export const RUNE_VALUE: Record<string, number> = {};
export const RUN_MODEL_EXTRA_FEATURES = ['gold', 'maxGold', 'tier', 'effectiveHp', 'handSize'];
