/**
 * `npm run contracts:extract` — Doc Bot 2.0 WP B: regenerate the extracted ContentContract registry, run
 * the triangle screening, and reseed the convention-question deck for the owner's Sitting 1.
 *
 * Writes (all committed, all regenerable, none ever touching curated space — §4.6):
 *  · packages/rules/src/contracts/extracted.generated.ts   — one draft contract per active content object
 *    (curated ids excluded at the source; `allContracts()` additionally merges curated-wins).
 *  · packages/rules/src/registry/pendingConventions.generated.ts — the convention question cards, run
 *    through the SAME seed hygiene as rules:seed (decisions survive; rejects tombstone; stale retires).
 *  · packages/rules/src/registry/retired.generated.ts      — tombstones appended, never dropped.
 *
 * Prints the Sitting-1 report: inventory, per-aspect corroboration totals, the disagreement queue, and the
 * question count. Deterministic output (no dates in generated files; hygiene tombstones carry today's date
 * exactly like rules:seed).
 */
import { writeFileSync } from 'node:fs';
import { CARD_INDEX, QUEST_DEFS, RUNE_INDEX } from '@game/content';
import {
  AUTO_RETIRED_RULES, CONVENTION_PENDING, DECISIONS, RETIRED_IDS, applySeedHygiene, type RetiredRule,
} from '@game/rules';
import { CURATED_CONTRACTS } from '@game/rules/contracts/curated';
import { PARKED_CLASSES } from '@game/rules/parked';
import { buildConventionQuestions, conventionClusters, corroborateContracts, extractAllContracts } from '@game/sim';

// ── 1. extraction ────────────────────────────────────────────────────────────────────────────────────────
const extraction = extractAllContracts();
const header = `/**
 * GENERATED by \`npm run contracts:extract\` — do not hand-edit. ${extraction.contracts.length} DRAFT contracts,
 * one per active content object (cards incl. tokens/gifts/henchmen — archive skipped; runes basic+epic —
 * archived skipped; quests; hero powers in the hero:<id> namespace). Every entry is visibly
 * reviewStatus 'extracted' with extraction provenance (§4.2); anything unparsed is listed, never silently
 * complete (§4.3). Ids owned by contracts/curated/ are never emitted (§4.6)${extraction.curatedSkipped.length ? ` — ${extraction.curatedSkipped.length} skipped: ${extraction.curatedSkipped.join(', ')}` : ''}.
 * Corroboration ('corroborated') is DERIVED per run by the screening lane, never stored (friction item 10).
 */
import type { ContentContract } from './schema';

export const EXTRACTED_CONTRACTS: ContentContract[] = `;
writeFileSync(
  'packages/rules/src/contracts/extracted.generated.ts',
  `${header}${JSON.stringify(extraction.contracts, null, 2)} as ContentContract[];\n`,
);

// ── 2. triangle screening (curated + freshly extracted) ─────────────────────────────────────────────────
const screened = corroborateContracts([...CURATED_CONTRACTS, ...extraction.contracts]);

// ── 3. convention questions through seed hygiene ────────────────────────────────────────────────────────
const fresh = buildConventionQuestions();
const questIds = new Set(QUEST_DEFS.map((q) => q.id));
const priorAutoIds = new Set(AUTO_RETIRED_RULES.map((t) => t.id));
const hygiene = applySeedHygiene({
  fresh,
  previous: CONVENTION_PENDING,
  decisions: DECISIONS,
  retiredIds: new Set([...RETIRED_IDS, ...priorAutoIds]),
  contentResolves: (id) => !!CARD_INDEX[id] || !!RUNE_INDEX[id] || questIds.has(id),
  today: new Date().toISOString().slice(0, 10),
});
const convHeader = `/**
 * GENERATED by \`npm run contracts:extract\` — do not hand-edit. ${hygiene.pending.length} convention questions
 * for the owner's Sitting 1 (Doc Bot 2.0 WP B; owner-review-pipeline.md §3/§5): one card per FAMILY —
 * presentation timing families, keyword contracts, hero-power activation families, quest reward shapes,
 * and the global conventions owner specs established but no R- rule yet pins. Every card is self-contained
 * (verbatim exemplar text, one concrete example, explicit ✓/✎/✕ click semantics, the member list) and
 * decided through the SAME board + decisions.json as every other pending rule. Decisions survive
 * regeneration; rejects tombstone into retired.generated.ts via the shared seed-hygiene pass.
 */
import type { GameRule } from '../schema';

export const CONVENTION_PENDING: GameRule[] = `;
writeFileSync(
  'packages/rules/src/registry/pendingConventions.generated.ts',
  `${convHeader}${JSON.stringify(hygiene.pending, null, 2)} as GameRule[];\n`,
);

// ── 4. tombstones (append-only, shared with rules:seed) ─────────────────────────────────────────────────
if (hygiene.newTombstones.length) {
  const allTombstones: RetiredRule[] = [...AUTO_RETIRED_RULES, ...hygiene.newTombstones];
  const retiredHeader = `/**
 * GENERATED by \`npm run rules:seed\` — do not hand-edit. AUTO-retired tombstones: pending questions that
 * left the board mechanically (owner REJECTED the recommendation, or the question's content ids vanished),
 * each with an audit record. Entries are append-only — the seeder merges, never drops. Ids here are never
 * recycled as new pending ids (tested in rules.test.ts).
 */
import type { RetiredRule } from './retired';

export const AUTO_RETIRED_RULES: RetiredRule[] = `;
  writeFileSync(
    'packages/rules/src/registry/retired.generated.ts',
    `${retiredHeader}${JSON.stringify(allTombstones, null, 2)} as RetiredRule[];\n\n`
    + 'export const AUTO_RETIRED_IDS: ReadonlySet<string> = new Set(AUTO_RETIRED_RULES.map((r) => r.id));\n',
  );
}

// ── 5. the Sitting-1 report ─────────────────────────────────────────────────────────────────────────────
const inv = Object.entries(extraction.inventory).sort().map(([k, v]) => `${k} ${v}`).join(' · ');
console.log(`EXTRACTED ${extraction.contracts.length} draft contracts (${inv}); curated skipped: ${extraction.curatedSkipped.length}`);
const confidences: Record<string, number> = {};
for (const c of extraction.contracts) confidences[c.extraction?.confidence ?? '?'] = (confidences[c.extraction?.confidence ?? '?'] ?? 0) + 1;
console.log(`  extraction confidence: ${Object.entries(confidences).sort().map(([k, v]) => `${k} ${v}`).join(' · ')}`);
console.log('TRIANGLE SCREENING (per-aspect honesty — corroboration is derived, never stored):');
for (const [aspect, t] of Object.entries(screened.aspectTotals)) {
  console.log(`  ${aspect}: agree ${t.agree} · disagree ${t.disagree} · uncovered ${t.uncovered}`);
}
console.log(`  derived status: ${Object.entries(screened.statusTotals).sort().map(([k, v]) => `${k} ${v}`).join(' · ')}`);
console.log(`DISAGREEMENT QUEUE (${screened.disagreements.length}):`);
for (const d of screened.disagreements) console.log(`  · ${d.contractId} [${d.aspect}] ${d.detail}`);
console.log(`CONVENTION QUESTIONS: ${hygiene.pending.length} pending (Sitting 1)`
  + (hygiene.newTombstones.length ? `; auto-retired ${hygiene.newTombstones.map((t) => t.id).join(', ')}` : ''));

// PARKED WIP surfaces (owner triage 2026-08-28) — always printed, even at zero: a parked class must be
// visible in the counts, never silently dropped. Un-parking is one edit in packages/rules/src/parked.ts.
const suppressed = conventionClusters().parked;
console.log(`PARKED (owner-declared WIP — no questions, no rules, contracts stamped '${'parked-wip'}'):`);
for (const p of PARKED_CLASSES) {
  const contracts = extraction.parked[p.id] ?? 0;
  const sup = suppressed.find((s) => s.classId === p.id);
  console.log(`  · ${p.id} (${p.label}, since ${p.since}): ${contracts} contracts stamped`
    + `; ${sup ? sup.families.length : 0} family question(s) suppressed`
    + `; ${sup ? sup.membersStripped : 0} member(s) stripped from the deck`);
}
console.log(`  corroboration: ${Object.values(screened.parked.byClass).reduce((a, b) => a + b, 0)} parked rows still measured`
  + `; ${screened.parked.downgraded} intent claim(s) withheld`);
