/**
 * `npm run docbot:text` — Doc Bot 2.0 WP E: the full text-intelligence sweep + the Sitting-3 deck.
 *
 * Prints the §18-E classification report — every active object in exactly one of the four buckets
 * (parsed-equivalent / verified-mismatch / approved-exception / unresolved-parse), per-type totals, the
 * unresolved queue, every mismatch with its registry pin, and the rewrite advisor's recommendations —
 * then regenerates the Sitting-3 wording deck through the SAME seed hygiene as rules:seed /
 * contracts:extract (decisions survive; rejects tombstone; stale questions self-retire).
 *
 * Writes (committed, regenerable, never touching curated space):
 *  · packages/rules/src/registry/pendingWording.generated.ts — the wording question cards.
 *  · packages/rules/src/registry/retired.generated.ts        — tombstones appended, never dropped.
 *
 * The deck ships DORMANT — cards land as needs-ruling on the standard board; nothing here schedules the
 * sitting. WP E never edits content files (§23): defects and recommendations are REPORT output only.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CARD_INDEX, QUEST_DEFS, RUNE_INDEX } from '@game/content';
import {
  AUTO_RETIRED_RULES, DECISIONS, LANGUAGE_GUIDE, RETIRED_IDS, WORDING_PENDING, applySeedHygiene, type RetiredRule,
} from '@game/rules';
import { allContracts } from '@game/rules/contracts';
import {
  buildWordingQuestions, emitFindingsJson, estimatedSittingMinutes, runRewriteAdvisor, runTextSweep, textObjectOf,
} from '@game/sim';

// WP G (§15.6): the text review queue needs the sweep's verdicts ON DISK for the QA Workbench to read. The
// flag is additive — without `--out` this CLI behaves exactly as it did.
const OUT = ((): string | undefined => {
  const i = process.argv.indexOf('--out');
  return i >= 0 && process.argv[i + 1] && !process.argv[i + 1]!.startsWith('--') ? process.argv[i + 1] : undefined;
})();

// ── 1. the classification sweep (full — the PR-gate lane samples nothing either; parsing is cheap) ──────
const contracts = allContracts();
const sweep = runTextSweep({ contracts });

console.log(`TEXT SWEEP — ${sweep.total} active objects classified (§18-E buckets):`);
for (const [bucket, n] of Object.entries(sweep.buckets)) console.log(`  ${bucket}: ${n}`);
console.log(`  (textless objects — quests + vanilla bodies — counted inside parsed-equivalent: ${sweep.textless})`);
console.log('per type:');
for (const [type, b] of Object.entries(sweep.byType).sort()) {
  console.log(`  ${type}: ${Object.entries(b).filter(([, n]) => n > 0).map(([k, n]) => `${k} ${n}`).join(' · ')}`);
}

const unresolvedRows = sweep.rows.filter((r) => r.bucket === 'unresolved-parse');
console.log(`\nUNRESOLVED-PARSE QUEUE (${unresolvedRows.length} objects — a visible queue, never a clean pass):`);
for (const r of unresolvedRows.slice(0, 25)) {
  console.log(`  · ${r.contentId} [${r.contentType}] — ${r.unresolved.map((u) => `"${u}"`).join(' · ')}`);
}
if (unresolvedRows.length > 25) console.log(`  … and ${unresolvedRows.length - 25} more`);

console.log(`\nMISMATCHES (${sweep.mismatches.length}):`);
for (const m of sweep.mismatches) {
  const pin = sweep.rows.find((r) => r.contentId === m.contentId)?.pinned;
  console.log(`  · ${m.contentId} [${m.taxonomy}] expected ${m.expected} · observed ${m.observed}${pin ? ` — PINNED ${pin}` : ' — UNPINNED (investigate before it may stand)'}`);
}
if (sweep.unpinnedMismatchIds.length) console.log(`  UNPINNED mismatch ids: ${sweep.unpinnedMismatchIds.join(', ')}`);
if (sweep.staleKnownIds.length) console.log(`  STALE registry pins (no longer mismatching): ${sweep.staleKnownIds.join(', ')}`);

// ── 2. the rewrite advisor ──────────────────────────────────────────────────────────────────────────────
const objects = contracts.map(textObjectOf);
const recs = runRewriteAdvisor({ objects, guide: LANGUAGE_GUIDE });
console.log(`\nWORDING RECOMMENDATIONS (${recs.length}) — suggestions only, never applied (§23):`);
for (const f of recs) console.log(`  · ${f.contentIds.join(',')} — ${f.title}${f.suggestedText ? `\n      → ${f.suggestedText}` : ''}`);

// ── 3. the Sitting-3 deck through seed hygiene ──────────────────────────────────────────────────────────
const fresh = buildWordingQuestions();
const questIds = new Set(QUEST_DEFS.map((q) => q.id));
const priorAutoIds = new Set(AUTO_RETIRED_RULES.map((t) => t.id));
const hygiene = applySeedHygiene({
  fresh,
  previous: WORDING_PENDING,
  decisions: DECISIONS,
  retiredIds: new Set([...RETIRED_IDS, ...priorAutoIds]),
  contentResolves: (id) => !!CARD_INDEX[id] || !!RUNE_INDEX[id] || questIds.has(id),
  today: new Date().toISOString().slice(0, 10),
});
const header = `/**
 * GENERATED by \`npm run docbot:text\` — do not hand-edit. ${hygiene.pending.length} wording questions for the
 * owner's Sitting 3 (Doc Bot 2.0 WP E; blueprint §11.3): one card per language-guide rule whose printed
 * usage is measured INCONSISTENT — both spellings live in the corpus, the owner picks the canon. Cards
 * are self-contained (verbatim exemplars from BOTH sides, one concrete example, ✓/✕/✎ click semantics)
 * and decided through the SAME board + decisions.json as every other pending rule. Decisions survive
 * regeneration; rejects tombstone; a pair whose text becomes consistent self-retires on the next run.
 */
import type { GameRule } from '../schema';

export const WORDING_PENDING: GameRule[] = `;
writeFileSync(
  'packages/rules/src/registry/pendingWording.generated.ts',
  `${header}${JSON.stringify(hygiene.pending, null, 2)} as GameRule[];\n`,
);

if (hygiene.newTombstones.length) {
  const allTombstones: RetiredRule[] = [...AUTO_RETIRED_RULES, ...hygiene.newTombstones];
  const retiredHeader = `/**
 * GENERATED by \`npm run rules:seed\` — do not hand-edit. AUTO-retired tombstones: pending questions that
 * left the board mechanically (owner REJECTED the recommendation, or the question's content ids vanished),
 * each with an audit record. Entries are append-only — the seeder merges, never drops. Ids here are never
 * recycled as new pending ids (tested in rules.test.ts).
 */
import type { RetiredRule } from './retired';

export const AUTO_RETIRED_RULES: RetiredRule[] = `;
  writeFileSync(
    'packages/rules/src/registry/retired.generated.ts',
    `${retiredHeader}${JSON.stringify(allTombstones, null, 2)} as RetiredRule[];\n\n`
    + 'export const AUTO_RETIRED_IDS: ReadonlySet<string> = new Set(AUTO_RETIRED_RULES.map((r) => r.id));\n',
  );
}

console.log(`\nSITTING-3 DECK: ${hygiene.pending.length} wording questions pending (≈ ${estimatedSittingMinutes(hygiene.pending.length)} min at the fly-through bar)`
  + (hygiene.newTombstones.length ? `; auto-retired ${hygiene.newTombstones.map((t) => t.id).join(', ')}` : ''));
console.log('The deck is DORMANT — the main session schedules the sitting.');

// ── 4. WP G artifacts (§15.6 text review queue) ─────────────────────────────────────────────────────────
if (OUT) {
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, 'findings.json'), emitFindingsJson([...sweep.findings, ...recs]));
  writeFileSync(join(OUT, 'text-review.json'), JSON.stringify({
    total: sweep.total,
    buckets: sweep.buckets,
    byType: sweep.byType,
    textless: sweep.textless,
    mismatches: sweep.mismatches,
    unpinnedMismatchIds: sweep.unpinnedMismatchIds,
    staleKnownIds: sweep.staleKnownIds,
    unresolved: unresolvedRows.map((r) => ({ contentId: r.contentId, contentType: r.contentType, unresolved: r.unresolved })),
    recommendations: recs.map((f) => ({
      fingerprint: f.fingerprint, contentIds: f.contentIds, ruleIds: f.ruleIds,
      title: f.title, summary: f.summary, suggestedText: f.suggestedText ?? null,
    })),
  }, null, 2));
  console.log(`
  artifacts → ${OUT}`);
}
