/**
 * The pure half of `npm run assets:manifest` — list every shipped image/SVG under `apps/web/public/`.
 *
 * Shared by the generator and by `packages/ui/src/publicAssets.test.ts`, which re-lists the folder and fails
 * when the committed `publicAssets.generated.ts` is stale. That test is the whole point: the boot preloader
 * warms exactly this list, so an asset that is dropped into `public/` without regenerating would be the one
 * that pops in — and the test says so before it ships.
 */
import { readdirSync } from 'node:fs';
import { join, relative } from 'node:path';

/** Extensions the preloader can warm with an `<img>` (`decode()` handles svg too). */
export const PUBLIC_ASSET_EXT = /\.(webp|png|jpg|jpeg|svg)$/i;

/** Public-root-relative, forward-slash paths of every warmable file, sorted. Preview HTML pages, README,
 *  the PWA manifest and the like are not images and are skipped by the extension filter. */
export function listPublicAssets(publicDir: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (PUBLIC_ASSET_EXT.test(e.name)) out.push(relative(publicDir, p).split('\\').join('/'));
    }
  };
  walk(publicDir);
  return out.sort();
}

/** Render the committed TypeScript module. */
export function renderPublicManifest(paths: readonly string[]): string {
  const rows = paths.map((p) => `  ${JSON.stringify(p)},`).join('\n');
  return [
    '// GENERATED by `npm run assets:manifest` (packages/tools/src/public-manifest.ts) — DO NOT EDIT.',
    '// Every image/SVG under apps/web/public/, public-root-relative. The boot preloader warms all of them',
    '// (see art.ts ALL_IMAGE_URLS); publicAssets.test.ts fails when this file is stale.',
    'export const PUBLIC_ASSETS: readonly string[] = [',
    rows,
    '];',
    '',
  ].join('\n');
}
