/**
 * DOC BOT 2.0 VERTICAL SLICE — the hand-authored contracts for the §19 interaction-heavy content set.
 *
 * Every amount below was read from the PRINTED TEXT and the owner rulings in @game/rules — never from the
 * factory params the oracle executes (§4.2: intent stays independent of implementation). Where an owner
 * ruling directly covers a claim, the contract cites it in `relatedRuleIds` and — only when the ruling
 * covers the load-bearing claims — carries `reviewStatus: 'approved'`; everything else ships visibly
 * 'extracted'. Corroboration ('corroborated') is computed by the slice lane, never hand-stamped (§23).
 *
 * The §19 roster: Echo source (wolvesden) · Echo multipliers (sylus stacking / zyff non-stacking) ·
 * forced Echo (deathsayer) · Avenge under simultaneous deaths (stuntdrake) · Avenge counter + copy subject
 * (kennel) · Rise (anubis) · plain-copy summoner (n2_bellringer) · exact-copy active hero power
 * (hero:xerox) · Shout with gilded delta (dm_butcher) · Shop Consume Demon (dm_agent) · Shop spell copier
 * (d2_recaller) · behavior-altering rune (rune_fury).
 */
import type { ContentContract } from './contentContract';

export const SLICE_CONTRACTS: readonly ContentContract[] = [
  {
    contentId: 'wolvesden',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tribes: ['undead', 'beast'],
    tags: ['trigger:echo', 'effect:summon'],
    triggers: [{ event: 'onDeath', phase: 'combat', note: 'Echo (Deathrattle); also shop-firable through forced-Echo effects' }],
    effects: [{ kind: 'summon', summons: { cardId: 'cryptwolf', count: { plain: 3, gilded: 6 } } }],
    gildedDelta: { kind: 'multiply', factor: 2, description: 'gilded summons 6 Crypt Wolves instead of 3' },
    textContract: { text: '**Deathrattle:** Summon 3 **Crypt Wolves**.', goldenText: '**Deathrattle:** Summon 6 **Crypt Wolves**.' },
  },
  {
    contentId: 'sylus',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tags: ['multiplier:echo', 'stacking'],
    multiplier: { families: ['deathrattle'], extra: 1, stacks: true, resolutionOnly: true },
    relatedRuleIds: ['R-MULT-01'],
    textContract: { text: '**In combat,** your Deathrattles proc **1 more** time.', goldenText: '**In combat,** your Deathrattles proc **2 more** times.' },
    notes: 'STACKING per R-MULT-01 ("stacking multipliers (Sylus) sum"). The stacks:true half is UNPROBED in the slice (board-cap ceilings make a two-Sylus wolf count ambiguous) — an honest coverage gap, reported by the lane.',
  },
  {
    contentId: 'zyff',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tags: ['multiplier:echo', 'multiplier:shout', 'non-stacking'],
    multiplier: { families: ['battlecry', 'deathrattle'], extra: 1, stacks: false, resolutionOnly: true },
    relatedRuleIds: ['R-MULT-01'],
    textContract: { text: 'Your **Battlecries** and **Deathrattles** trigger an additional time.', goldenText: 'Your **Battlecries** and **Deathrattles** trigger **2** additional times.' },
    notes: 'Non-stacking (best-of across the family, R-MULT-01). Its "an additional time" phrasing is the owner-flagged non-stacker terminology — see the wording-recommendation finding.',
  },
  {
    contentId: 'deathsayer',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tribes: ['undead'],
    keywords: ['RL'],
    tags: ['trigger:rally', 'effect:trigger-other', 'forced-echo'],
    triggers: [{ event: 'onAttack', phase: 'combat', note: 'Rally — before this attacks' }],
    effects: [{ kind: 'trigger-other-echo', targets: { count: 1, scope: 'leftmost-friendly-echo' }, note: 'fires the target\'s Echo WITHOUT a death; folds the side\'s Echo multipliers like every forced trigger (owner ruling q-interact-forced-echo, 2026-08-27)' }],
    gildedDelta: { kind: 'multiply', factor: 2, description: 'gilded triggers the leftmost Echo twice per Rally' },
    textContract: { text: '**Rally:** before this attacks, trigger your leftmost Deathrattle.', goldenText: '**Rally:** before this attacks, trigger your leftmost Deathrattle **twice**.' },
  },
  {
    contentId: 'stuntdrake',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tribes: ['dragon'],
    tags: ['trigger:avenge', 'effect:grant-attack'],
    triggers: [{ event: 'avenge', phase: 'combat', threshold: 3 }],
    effects: [{ kind: 'give-own-attack', targets: { count: 2, scope: '2-other-friendly' } }],
    gildedDelta: { kind: 'multiply', factor: 2, description: 'gilded resolves the grant twice per threshold' },
    persistence: ['combat-only'],
    relatedRuleIds: ['R-AVWIN-01', 'R-AVWIN-06', 'R-AVWIN-07', 'R-AVWIN-10'],
    textContract: { text: "**Avenge (3):** give this minion's Attack to 2 other friendly minions.", goldenText: "**Avenge (3):** give this minion's Attack to 2 other friendly minions **twice**." },
    notes: 'The simultaneous-death subject: R-AVWIN-10 (a source dying in a batch observes none of it) is APPROVED and currently VIOLATED by the engine — the slice\'s verified-mechanical-bug finding.',
  },
  {
    contentId: 'kennel',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tribes: ['beast'],
    keywords: ['SC'],
    tags: ['trigger:avenge', 'counter:improving', 'copy-subject'],
    triggers: [{ event: 'avenge', phase: 'combat', threshold: 4 }],
    effects: [{ kind: 'improve-own-aura', note: 'permanent per-instance accrual (summonBonus channel) — the copy-semantics subject of both copy fixtures' }],
    persistence: ['permanent'],
    relatedRuleIds: ['R-AVWIN-01', 'R-AVWIN-03', 'R-AVWIN-04', 'R-AVWIN-05'],
    textContract: { text: '**Start of Combat:** give your **Beast Aura** **+1 Attack**. **Avenge (4):** Improve this.', goldenText: '**Start of Combat:** give your **Beast Aura** **+2 Attack**. **Avenge (4):** Improve this (twice as much).' },
  },
  {
    contentId: 'anubis',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set1'],
    tribes: ['undead'],
    keywords: ['R'],
    tags: ['keyword:rise', 'trigger:echo', 'effect:grant-keyword', 'effect:cast-spell'],
    triggers: [{ event: 'onDeath', phase: 'combat' }],
    effects: [
      { kind: 'grant-rise-all', targets: { count: -1, scope: 'all-other-friendly-without-rise' } },
      { kind: 'cast-spell', note: 'casts Lantern of Souls (permanent run-wide Undead Attack)' },
    ],
    persistence: ['permanent'],
    relatedRuleIds: ['R-AVWIN-09', 'R-AVWIN-11'],
    textContract: { text: '**Deathrattle:** Give your minions **Reborn**. Cast **Lantern of Souls**.', goldenText: '**Deathrattle:** Give your minions **Reborn**. Cast **Lantern of Souls** twice.' },
    notes: 'Rise + Echo on one body. Neither the text nor any rule states whether the Echo fires on BOTH the rise-death and the final death — the slice\'s questionable-interaction finding.',
  },
  {
    contentId: 'n2_bellringer',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set2'],
    tags: ['effect:copy', 'copy:plain', 'cadence:every-2-turns'],
    triggers: [{ event: 'endOfTurn', phase: 'shop', note: 'every 2 turns' }],
    effects: [{ kind: 'copy-neighbour', targets: { count: 1, scope: 'left-neighbour' } }],
    copyPolicy: { mode: 'plain', note: 'fresh base copy: no buffs, counters, gilding (R-COPY-01)' },
    relatedRuleIds: ['R-COPY-01', 'R-AVWIN-04'],
    textContract: { text: '**Every 2 turns:** get a plain copy of the minion to the **left**.', goldenText: '**Every 2 turns:** get a plain copy of **adjacent** minions.' },
  },
  {
    // Owner rulings 2026-08-14 (board summon) + 2026-08-15 (exact copy) cover the load-bearing claims,
    // and R-AVWIN-03's currentBehaviour records the conforming behaviour — hence 'approved' (a citation
    // of real owner rulings, not an auto-promotion).
    contentId: 'hero:xerox',
    contentType: 'hero-power',
    revision: 1,
    reviewStatus: 'approved',
    tags: ['hero-power:active', 'effect:copy', 'copy:exact', 'once-per-game'],
    triggers: [{ event: 'heroPower', phase: 'shop' }],
    effects: [{ kind: 'summon-copy', targets: { count: 1, scope: 'friendly-board-minion' }, note: 'board summon beside the target; needs a free slot; once per game' }],
    copyPolicy: { mode: 'exact', note: 'full instance spread — stats, buffs, granted keywords, GILDING, accrued counters (summonBonus etc.) all ride along (owner ruling 2026-08-15; R-COPY-02)' },
    relatedRuleIds: ['R-COPY-02', 'R-AVWIN-03'],
    textContract: { text: 'Summon a copy of a friendly minion. Needs a free board slot. Once per game.' },
    notes: 'The displayed text says only "a copy" — under R-COPY-01 an unmarked copy reads plain. The slice\'s verified-text-defect finding.',
  },
  {
    contentId: 'dm_butcher',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set2'],
    tribes: ['demon'],
    tags: ['trigger:shout', 'effect:shop-buff'],
    triggers: [{ event: 'onPlay', phase: 'shop' }],
    effects: [{ kind: 'buff-shop', amount: { plain: [2, 1], gilded: [4, 2] }, targets: { count: -1, scope: 'all-shop-minions' } }],
    gildedDelta: { kind: 'multiply', factor: 2, description: 'gilded grants +4/+2 instead of +2/+1' },
    persistence: ['run-wide'],
    textContract: { text: '**Shout:** give minions in the Shop **+2/+1**.', goldenText: '**Shout:** give minions in the Shop **+4/+2**.' },
    notes: '"Minions in the Shop" is the ruled run-wide vocabulary (owner ruling 2026-07-25): a lasting buff on everything bought from here on, not one roll.',
  },
  {
    contentId: 'dm_agent',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set2'],
    tribes: ['demon'],
    tags: ['trigger:shout', 'effect:consume-shop', 'targeted'],
    triggers: [{ event: 'onPlay', phase: 'shop' }],
    effects: [{ kind: 'target-consumes-shop', amount: { plain: 1, gilded: 2 }, targets: { count: 1, scope: 'friendly-demon' }, note: 'the TARGET eats the right-most Shop minion, gaining its bought stats' }],
    gildedDelta: { kind: 'multiply', factor: 2, description: 'gilded: the target Consumes 2 Shop minions' },
    textContract: { text: '**Shout:** target a friendly **Demon**. It Consumes a minion in the Shop.', goldenText: '**Shout:** target a friendly **Demon**. It Consumes **2** minions in the Shop.' },
  },
  {
    contentId: 'd2_recaller',
    contentType: 'minion',
    revision: 1,
    reviewStatus: 'extracted',
    setIds: ['set2'],
    tribes: ['dragon'],
    tags: ['trigger:shout', 'effect:copy-spell'],
    triggers: [{ event: 'onPlay', phase: 'shop' }],
    effects: [{ kind: 'copy-cast-spell', amount: { plain: 1, gilded: 2 }, note: 'copies the LAST Shop spell cast THIS TURN (turn-scoped, not run-lifetime)' }],
    gildedDelta: { kind: 'multiply', factor: 2, description: 'gilded grants 2 copies' },
    textContract: { text: '**Shout:** get a copy of the last **Shop spell** you cast this turn.', goldenText: '**Shout:** get **2** copies of the last **Shop spell** you cast this turn.' },
  },
  {
    contentId: 'rune_fury',
    contentType: 'rune',
    revision: 1,
    reviewStatus: 'extracted',
    tags: ['multiplier:avenge', 'behavior-altering-rune'],
    multiplier: { families: ['avenge'], extra: 1, stacks: true, resolutionOnly: true },
    relatedRuleIds: ['R-AVWIN-07'],
    textContract: { text: 'Your **Avenge** effects trigger twice.' },
    notes: 'resolutionOnly restates R-AVWIN-07: the rune re-resolves at the threshold; each death still counts once toward it. stacks per R-RUNEDUP-05 (flagCopies), unprobed here.',
  },
];

export const SLICE_CONTRACT_INDEX: Readonly<Record<string, ContentContract>> =
  Object.fromEntries(SLICE_CONTRACTS.map((c) => [c.contentId, c]));
